<?php
/**
 * Access Swedish lexicon topic
 *
 * @language sv
 * @package modx
 * @subpackage lexicon
 */
$_lang['access_category_management_msg'] = 'Hantera användargruppsmedlemmars tillgång till element via kategorier och lägg på åtkomstpolicyer om så önskas.';
$_lang['access_category_err_ae'] = 'Det finns redan en ACL för den kategorin!';
$_lang['access_category_err_nf'] = 'Kategorins ACL kunde inte hittas.';
$_lang['access_category_err_ns'] = 'Ingen ACL för kategorin angiven.';
$_lang['access_category_err_remove'] = 'Ett fel inträffade när kategorins ACL skulle tas bort.';
$_lang['access_category_remove'] = 'Ta bort kategoriåtkomst';
$_lang['access_category_update'] = 'Uppdatera kategoriåtkomst';
$_lang['access_confirm_remove'] = 'Är du säker på att du vill ta bort denna ACL-post?';
$_lang['access_context_management_msg'] = 'Hantera användargruppsmedlemmars tillgång till kontexter och, om så önskas, ange åtkomstpolicyer.';
$_lang['access_context_err_ae'] = 'Det finns redan en ACL för den kontexten!';
$_lang['access_context_err_nf'] = 'Kunde inte hitta kontext-ACL.';
$_lang['access_context_err_ns'] = 'Ingen kontext-ACL angiven.';
$_lang['access_context_err_remove'] = 'Ett fel inträffade när kontextens ACL skulle tas bort.';
$_lang['access_context_remove'] = 'Ta bort tillgång till kontext';
$_lang['access_context_update'] = 'Uppdatera tillgång till kontext';
$_lang['access_err_ae'] = 'ACL:en finns redan!';
$_lang['access_err_create_md'] = 'Kan inte skapa ACL - data saknas!';
$_lang['access_err_nf'] = 'Kan inte hitta angiven ACL!';
$_lang['access_err_remove'] = 'Ett fel inträffade när ACL:en skulle tas bort!';
$_lang['access_err_save'] = 'Ett fel inträffade när ACL:en skulle sparas!';
$_lang['access_grid_empty'] = 'Det finns inga ACL:er att visa'; // ACL = Access Control List = åtkomstkontrollista/behörighetslista(?)
$_lang['access_grid_paginate'] = 'Visar ACL:erna {0} - {1} av {2}';
$_lang['access_permissions'] = 'Åtkomstinställningar';
$_lang['access_permissions_add_document_group'] = 'Skapa en ny dokumentgrupp';
$_lang['access_permissions_add_user_group'] = 'Skapa en ny användargrupp';
$_lang['access_permissions_documents_in_group'] = '<strong>Dokument i gruppen:</strong> ';
$_lang['access_permissions_documents_tab'] = 'Här kan du se vilka dokumentgrupper som har blivit konfigurereade. Du kan även skapa nya och byta namn på grupper samt se vilka dokument som tillhör en specifik grupp (håll musen över dokumentets ID för att se dess namn). För att lägga till eller ta bort ett dokument från en grupp, redigera dokumentet direkt.';
$_lang['access_permissions_document_groups'] = 'Dokumentgrupper';
$_lang['access_permissions_introtext'] = 'Här kan du hantera de användargrupper och dokumentgrupper som används för åtkomstkontroll. Högerklicka i det vänstra trädet för att lägga till användargrupper eller användare i grupper. För att länka användargrupper till dokumentgrupper drar du helt enkelt användargrupper från det vänstra trädet till dokumentgrupper i det högra trädet.';
$_lang['access_permissions_links'] = 'Användar/dokumentgruppslänkar';
$_lang['access_permissions_links_tab'] = 'Här specificerar du vilka användargrupper som har behörighet för de olika dokumentgrupperna (dvs kan redigera eller skapa underdokument). För att länka en dokumentgrupp till en användargrupp, välj gruppen från menyn och klicka på "Länka". För att ta bort länken för en grupp, klicka på "Ta bort ->". Detta tar genast bort länken.';
$_lang['access_permissions_no_documents_in_group'] = 'Inga.';
$_lang['access_permissions_no_users_in_group'] = 'Inga.';
$_lang['access_permissions_off'] = '<span class="warning">Åtkomstinställningar är inte aktiverade.</span> Detta betyder att förändringar som görs här inte kommer att ha någon effekt förrän åtkomstinställningarna är aktiverade.';
$_lang['access_permissions_users_in_group'] = '<strong>Användare i gruppen:</strong> ';
$_lang['access_permissions_users_tab'] = 'Här kan du se vilka användargrupper som har blivit konfigurerade. Du kan också skapa nya, byta namn på och ta bort grupper samt se vilka användare som är medlemmar i en specifik grupp. För att lägga till eller ta bort en användare från en grupp, redigera användaren direkt.';
$_lang['access_permissions_user_group'] = 'Användargrupp:';
$_lang['access_permissions_user_groups'] = 'Användargrupper';
$_lang['access_permissions_user_group_access'] = 'Dokumentgrupper som denna användargrupp har behörighet för:';
$_lang['access_permissions_user_message'] = 'Här kan du välja vilka användargrupper denna anvädare ska tillhöra:';
$_lang['access_permission_denied'] = 'Du har inte behörighet för detta dokument.';
$_lang['access_permission_parent_denied'] = 'Du har inte behörighet att skapa ett dokument här eller att flytta ett hit! Välj en annan plats.';
$_lang['access_policy_err_nf'] = 'Kan inte hitta åtkomstpolicyn.';
$_lang['access_policy_err_ns'] = 'Ingen åtkomstpolicy angiven.';
$_lang['access_policy_grid_empty'] = 'Det finns inga policyer att visa';
$_lang['access_policy_grid_paginate'] = 'Visar policyerna {0} - {1} av {2}';
$_lang['access_resourcegroup_management_msg'] = 'Hantera användargruppers medlemmars tillgång till resursgrupper och, om så önskas, ange åtkomstpolicyer.';
$_lang['access_rgroup_err_ae'] = 'Det finns redan en ACL för den resursgruppen!';
$_lang['access_rgroup_err_nf'] = 'Resursgruppens ACL kunde inte hittas.';
$_lang['access_rgroup_err_ns'] = 'Ingen ACL för resursgruppen angiven.';
$_lang['access_rgroup_err_remove'] = 'Ett fel inträffade när resursgruppens ACL skulle tas bort.';
$_lang['access_rgroup_remove'] = 'Ta bort tillgång till resursgrupp';
$_lang['access_rgroup_update'] = 'Uppdatera tillgång till resursgrupp';
$_lang['access_to_contexts'] = 'Tillgång till kontexter';
$_lang['access_to_resource_groups'] = 'Tillgång till resursgrupper';
$_lang['access_type_err_ns'] = 'Målets typ eller id har inte angivits!';
$_lang['acl_add'] = 'Lägg till åtkomstkontroll';
$_lang['authority'] = 'Auktoritet';
$_lang['authority_err_ns'] = 'Ange en minimal roll.';
$_lang['category'] = 'Kategori';
$_lang['category_add'] = 'Lägg till kategori';
$_lang['filter_by_context'] = 'Filtrera efter kontext...';
$_lang['filter_by_policy'] = 'Filtrera efter policy...';
$_lang['filter_by_resource_group'] = 'Filtrera efter resursgrupp...';
$_lang['filter_by_category'] = 'Filtrera efter kategori...';
$_lang['resource_group'] = 'Resursgrupp';
$_lang['resource_group_add'] = 'Lägg till resursgrupp';
$_lang['resource_group_access_remove'] = 'Ta bort resurs från grupp';
$_lang['resource_group_access_remove_confirm'] = 'Är du säker på att du vill ta bort denna resurs från resursgruppen?';
$_lang['resource_group_create'] = 'Skapa resursgrupp';
$_lang['resource_group_err_ae'] = 'Det finns redan en resursgrupp med det namnet.';
$_lang['resource_group_err_create'] = 'Ett fel inträffade när resursgruppen skulle skapas.';
$_lang['resource_group_err_nf'] = 'Resursgruppen kunde inte hittas.';
$_lang['resource_group_err_ns'] = 'Ingen resursgrupp angiven.';
$_lang['resource_group_err_remove'] = 'Ett fel inträffade när resursgruppen skulle tas bort.';
$_lang['resource_group_remove'] = 'Ta bort resursgrupp';
$_lang['resource_group_remove_confirm'] = 'Är du säker på att du vill ta bort denna resursgrupp?';
$_lang['resource_group_resource_err_ae'] = 'Resursen är redan med i den resursgruppen.';
$_lang['resource_group_resource_err_create'] = 'Ett fel inträffade när resursen skulle läggas till i resursgruppen.';
$_lang['resource_group_resource_err_nf'] = 'Resursen är inte med i den resursgruppen.';
$_lang['resource_group_resource_err_remove'] = 'Ett fel inträffade när resursen skulle tas bort från resursgruppen.';
$_lang['resource_group_untitled'] = 'Namnlös resursgrupp';
$_lang['roles_msg'] = 'En roll är, per definition, den position eller status man har i en viss situation. Den kan användas för att gruppera användare till en position eller status inom en användargrupp. Roller i MODx har också vad som kallas "Befogenhet". Detta är ett nummer som kan vara vilket giltigt heltal som helst. Befogenhetsnivåer "ärvs neråt" i den mening att en roll med befogenhetsnivå 1 ärver alla gruppolicyer tilldelade till sig själv och till alla roller med högre befogenhetsnivå än 1.';
$_lang['user_group_category_access'] = 'Elementkategoriåtkomst';
$_lang['user_group_category_access_msg'] = 'Här kan du ange vilka element denna användargrupp kan komma åt genom de kategorier elementen ingår i.';
$_lang['user_group_category_err_ae'] = 'Användargruppen har redan tillgång till den kategorin.';
$_lang['user_group_category_remove_confirm'] = 'Är du säker på att du vill ta bort denna kategori från denna användargrupp?';
$_lang['user_group_context_access'] = 'Kontextåtkomst';
$_lang['user_group_context_access_msg'] = 'Här kan du ange vilka kontexter denna användargrupp kan komma åt.';
$_lang['user_group_context_err_ae'] = 'Användargruppen har redan tillgång till den kontexten.';
$_lang['user_group_context_remove_confirm'] = 'Är du säker på att du vill ta bort denna kontext från denna användargrupp?';
$_lang['user_group_resourcegroup_access'] = 'Resursgruppsåtkomst';
$_lang['user_group_resourcegroup_access_msg'] = 'Här kan du ange vilka resursgrupper denna användargrupp kan komma åt.';
$_lang['user_group_resourcegroup_err_ae'] = 'Användargruppen har redan tillgång till den resursgruppen.';
$_lang['user_group_resourcegroup_remove_confirm'] = 'Är du säker på att du vill ta bort denna resursgrupp från denna användargrupp?';
$_lang['user_group_user_access_msg'] = 'Välj vilka användare du vill ha i denna användargrupp.';