<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Snippet';
$_lang['snippets_available'] = 'Snippets som är tillgängliga för dig att inkludera i dina sidor';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Är du säker på att du vill ta bort denna snippet?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Är du säker på att du vill duplicera denna snippet?';
$_lang['snippet_duplicate_error'] = 'Ett fel inträffade när snippeten skulle dupliceras.';
$_lang['snippet_err_create'] = 'Ett fel inträffade när snippeten skulle skapas.';
$_lang['snippet_err_delete'] = 'Ett fel inträffade när snippeten skulle tas bort.';
$_lang['snippet_err_duplicate'] = 'Ett fel inträffade när snippeten skulle dupliceras.';
$_lang['snippet_err_ae'] = 'Det finns redan en snippet med namnet "[[+name]]".';
$_lang['snippet_err_invalid_name'] = 'Snippetens namn är ogiltigt.';
$_lang['snippet_err_locked'] = 'Denna snippet är låst för redigering.';
$_lang['snippet_err_nf'] = 'Snippeten kunde inte hittas!';
$_lang['snippet_err_ns'] = 'Ingen snippet angiven.';
$_lang['snippet_err_ns_name'] = 'Ange ett namn på snippeten.';
$_lang['snippet_err_remove'] = 'Ett fel inträffade när snippeten skulle tas bort.';
$_lang['snippet_err_save'] = 'Ett fel inträffade när snippeten skulle sparas.';
$_lang['snippet_execonsave'] = 'Kör snippeten efter att den sparats.';
$_lang['snippet_lock'] = 'Lås snippet för redigering';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Här kan du skapa nya snippets eller välja en redan befintlig för redigering.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Skapa snippet';
$_lang['snippet_properties'] = 'Standardegenskaper';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippet_title'] = 'Create/Edit Snippet';
$_lang['snippet_untitled'] = 'Namnlös snippet';
$_lang['snippets'] = 'Snippets';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
