<?php
/**
 * TV English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_tvname'] = 'NameOfTV';
$_lang['has_access'] = 'Har tillgång?';
$_lang['filter_by_category'] = 'Filtrera efter kategori...';
$_lang['rank'] = 'Rang';
$_lang['rendering_options'] = 'Visningsalternativ';
$_lang['tv'] = 'Mallvariabel';
$_lang['tvs'] = 'Mallvariabler';
$_lang['tv_binding_msg'] = 'Detta fält tillåter bindning av datakällor med @-kommandon';
$_lang['tv_caption'] = 'Rubrik';
$_lang['tv_caption_desc'] = 'The label shown for this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_category_desc'] = 'Use to group TVs in Resource editing pages and within the Elements tree.';
$_lang['tv_change_template_msg'] = 'Ändrar du denna mall, kommer sidan att ladda om alla mallvariabler. Alla icke sparade ändringar kommer att förloras.<br /><br />Är du säker på att du vill ändra denna mall?';
$_lang['tv_delete_confirm'] = 'Är du säker på att du vill ta bort denna TV?';
$_lang['tv_description'] = 'Beskrivning';
$_lang['tv_description_desc'] = 'Usage information for this TV shown next its caption in Resource editing pages and as a tooltip in the Elements tree.';
$_lang['tv_err_delete'] = 'Ett fel inträffade när mallvariabeln skulle tas bort.';
$_lang['tv_err_duplicate'] = 'Ett fel inträffade när mallvariabeln skulle dupliceras.';
$_lang['tv_err_duplicate_templates'] = 'Ett fel inträffade när mallvariabelns mallar skulle dupliceras.';
$_lang['tv_err_duplicate_documents'] = 'Ett fel inträffade när mallvariabelns dokument skulle dupliceras.';
$_lang['tv_err_duplicate_documentgroups'] = 'Ett fel inträffade när dokumentgrupper för mallvariabeln skulle dupliceras.';
$_lang['tv_err_ae'] = 'Det finns redan en mallvariabel med namnet "[[+name]]".';
$_lang['tv_err_invalid_name'] = 'Mallvariabelns namn är ogiltigt.';
$_lang['tv_err_invalid_id_attr'] = 'HTML ids must not begin with a number or contain any white space.';
$_lang['tv_err_locked'] = 'Mallvariabeln är låst!';
$_lang['tv_err_nf'] = 'Mallvariabeln kunde inte hittas.';
$_lang['tv_err_nfs'] = 'Kunde inte hitta mallvariabeln med nyckel: [[+id]]';
$_lang['tv_err_ns'] = 'Ingen mallvariabel angiven.';
$_lang['tv_err_reserved_name'] = 'En mallvariabel kan inte ha samma namn som ett resursfält.';
$_lang['tv_err_save_access_permissions'] = 'Ett fel inträffade när mallvariabelns åtkomstinställningar skulle sparas.';
$_lang['tv_err_save'] = 'Ett fel inträffade när mallvariabeln skulle sparas.';
$_lang['tv_inuse'] = 'Följande dokument använder för närvarande denna mallvariabel. För att fortsätta med denna borttagningsoperation, klicka på knappen "Ta bort". Klicka på knappen "Avbryt" för att avbryta.';
$_lang['tv_inuse_template'] = 'Följande mallar använder för närvarande denna TV: [[+templates]].<br /><br />Koppla bort TV:n från mallarna innan den kan raderas.';
$_lang['tv_lock'] = 'Restrict Editing';
$_lang['tv_lock_desc'] = 'Only users with “edit_locked” permissions can edit this TV.';
$_lang['tv_management_msg'] = 'Hantera ytterligare anpassade mallvariabler för dina dokument.';
$_lang['tv_name'] = 'Mallvariabelns namn';
$_lang['tv_name_desc'] = 'Place the content generated by this TV in a Resource, Template, or Chunk using the following MODX tag: <span class="copy-this">[[*<span class="example-replace-name">'.$_lang['example_tag_tvname'].'</span>]]</span>';
$_lang['tv_new'] = 'Skapa mallvariabel';
$_lang['tv_novars'] = 'Hittade inga mallvariabler';
$_lang['tv_properties'] = 'Standardegenskaper';
$_lang['tv_rank'] = 'Sorteringsordning';
$_lang['tv_rank_desc'] = 'Use to control the positioning of this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_reset_params'] = 'Återställ parametrar';
$_lang['tv_tab_access_desc'] = 'Select the Resource Groups that this TV belongs to. Only users with access to the Groups selected will be able to modify this TV. If no Groups are selected, all users with access to the Manager will be able to modify the TV.';
$_lang['tv_tab_general_desc'] = 'Here you can create/edit a <dfn>Template Variable</dfn> (TV). TVs must be assigned to templates in order to access them from snippets and documents.';
$_lang['tv_tab_input_options'] = 'Inmatningsalternativ';
$_lang['tv_tab_input_options_desc'] = '<p>Here you can edit the input options for the TV, specific to the type of input render that you select.</p>';
$_lang['tv_tab_output_options'] = 'Utdataalternativ';
$_lang['tv_tab_output_options_desc'] = '<p>Here you can edit the output options for the TV, specific to the type of output render that you select.</p>';
$_lang['tv_tab_sources_desc'] = 'Här kan du ange de mediakällor som ska användas av denna mallvariabel i varje angiven kontext. Dubbelklicka på källans namn i rutnätet för att ändra det.';
$_lang['tv_tab_tmpl_access'] = 'Mallåtkomst';
$_lang['tv_tab_tmpl_access_desc'] = 'Select the templates that are allowed to access this TV.';
$_lang['tv_tag_copied'] = 'TV tag copied!';
$_lang['tv_widget'] = 'Widget';
$_lang['tv_widget_prop'] = 'Widget-inställningar';
$_lang['tvd_err_remove'] = 'Ett fel inträffade när mallvariabeln skulle tas bort från dokumentet.';
$_lang['tvdg_err_remove'] = 'Ett fel inträffade när mallvariabeln skulle tas bort från dokumentgruppen.';
$_lang['tvdg_err_save'] = 'Ett fel inträffade när mallvariabeln skulle knytas till dokumentgruppen.';
$_lang['tvt_err_nf'] = 'Mallvariabeln har inte tillgång till den angivna mallen.';
$_lang['tvt_err_remove'] = 'Ett fel inträffade när mallvariabeln skulle tas bort från mallen.';
$_lang['tvt_err_save'] = 'Ett fel inträffade när mallvariabeln skulle knytas till mallen.';

// Temporarily match old keys to new ones to ensure compatibility
// -- fields
$_lang['tv_desc_caption'] = $_lang['tv_caption_desc'];
$_lang['tv_desc_category'] = $_lang['tv_category_desc'];
$_lang['tv_desc_description'] = $_lang['tv_description_desc'];
$_lang['tv_desc_name'] = $_lang['tv_name_desc'];
$_lang['tv_lock_msg'] = $_lang['tv_lock_desc'];
$_lang['tv_rank_msg'] = $_lang['tv_rank_desc'];

// -- tabs
$_lang['tv_access_msg'] = $_lang['tv_tab_access_desc'];
$_lang['tv_input_options'] = $_lang['tv_tab_input_options'];
$_lang['tv_input_options_msg'] = $_lang['tv_tab_input_options_desc'];
$_lang['tv_msg'] = $_lang['tv_tab_general_desc'];
$_lang['tv_output_options'] = $_lang['tv_tab_output_options'];
$_lang['tv_output_options_msg'] = $_lang['tv_tab_output_options_desc'];
$_lang['tv_sources.intro_msg'] = $_lang['tv_tab_sources_desc'];
$_lang['tv_tmpl_access'] = $_lang['tv_tab_tmpl_access'];
$_lang['tv_tmpl_access_msg'] = $_lang['tv_tab_tmpl_access_desc'];
