<?php
/**
 * @package modx
 * @subpackage lexicon

 * @language de
 * @namespace core
 * @topic access
 */
$_lang['access_category_management_msg'] = 'Verwalten Sie die Zugriffsrechte von Benutzergruppen-Mitgliedern auf Elemente über Kategorien und weisen Sie optional Zugriffsrichtlinien zu.';
$_lang['access_category_err_ae'] = 'Eine ACL für diese Kategorie existiert bereits!';
$_lang['access_category_err_nf'] = 'Kategorie-ACL nicht gefunden.';
$_lang['access_category_err_ns'] = 'Kategorie-ACL nicht angegeben.';
$_lang['access_category_err_remove'] = 'Ein Fehler trat auf beim Versuch, die Kategorie-ACL zu löschen.';
$_lang['access_category_remove'] = 'Zugriff auf diese Kategorie löschen';
$_lang['access_category_update'] = 'Zugriff auf diese Kategorie bearbeiten';
$_lang['access_confirm_remove'] = 'Sind Sie sicher, dass Sie diesen Zugriffskontrollen-Eintrag löschen möchten?';
$_lang['access_context_management_msg'] = 'Verwalten Sie die Zugriffsrechte von Benutzergruppen-Mitgliedern auf Kontexte und weisen Sie optional Zugriffsrichtlinien zu.';
$_lang['access_context_err_ae'] = 'Eine ACL für diesen Kontext existiert bereits!';
$_lang['access_context_err_nf'] = 'Kontext-ACL nicht gefunden.';
$_lang['access_context_err_ns'] = 'Kontext-ACL nicht angegeben.';
$_lang['access_context_err_remove'] = 'Ein Fehler trat auf beim Versuch, die Kontext-ACL zu löschen.';
$_lang['access_context_remove'] = 'Zugriff auf diesen Kontext löschen';
$_lang['access_context_update'] = 'Zugriff auf diesen Kontext bearbeiten';
$_lang['access_err_ae'] = 'ACL existiert bereits!';
$_lang['access_err_create_md'] = 'Die ACL kann nicht erstellt werden; es fehlen Daten!';
$_lang['access_err_nf'] = 'Konnte die angegebene ACL nicht finden!';
$_lang['access_err_remove'] = 'Fehler beim Löschen der ACL!';
$_lang['access_err_save'] = 'Fehler beim Speichern der ACL!';
$_lang['access_grid_empty'] = 'Keine ACLs vorhanden';
$_lang['access_grid_paginate'] = 'ACLs {0} - {1} von {2}';
$_lang['access_permissions'] = 'Zugriffsrechte';
$_lang['access_permissions_add_document_group'] = 'Neue Dokumentgruppe anlegen';
$_lang['access_permissions_add_user_group'] = 'Neue Benutzergruppe erstellen';
$_lang['access_permissions_documents_in_group'] = '<strong>Dokumente in der Gruppe:</strong> ';
$_lang['access_permissions_documents_tab'] = 'Hier können Sie sehen, welche Dokumentgruppen angelegt wurden. Sie können auch neue Gruppen einrichten, Gruppen löschen und sehen, welche Dokumente den verschiedenen Gruppen zugeordnet sind (fahren Sie mit dem Mauscursor über die ID eines Dokuments, um seinen Namen zu sehen). Um ein Dokument einer Gruppe hinzuzufügen oder ein Dokument aus einer Gruppe zu entfernen, bearbeiten Sie bitte das Dokument selbst.';
$_lang['access_permissions_document_groups'] = 'Dokumentgruppen';
$_lang['access_permissions_introtext'] = 'Hier können Sie die Benutzergruppen und Dokumentgruppen verwalten, die für Zugriffsberechtigungen verwendet werden. Um Benutzergruppen hinzuzufügen oder Benutzer Benutzergruppen zuzuordnen, führen Sie im Baum auf der linken Seite einen Rechtsklick durch. Um Benutzergruppen mit Dokumentgruppen zu verbinden, ziehen Sie einfach Benutzergruppen aus dem linken Baum auf Dokumentgruppen im rechten Baum.';
$_lang['access_permissions_links'] = 'Benutzer-/Dokumentgruppen-Verknüpfung';
$_lang['access_permissions_links_tab'] = 'Hier legen Sie fest, welche Benutzergruppen auf die Ressourcen-Gruppen Zugriff haben (d.h. Ressourcen bearbeiten oder anlegen können). Um eine Ressourcen-Gruppe mit einer Benutzergruppe zu verknüpfen, wählen Sie die entsprechende Gruppe aus dem Dropdown-Menü und klicken Sie anschließend auf "Absenden". Um eine Verknüpfung für eine bestimmte Gruppe zu entfernen, klicken Sie auf "Entfernen". Die Verknüpfung wird sofort gelöscht.';
$_lang['access_permissions_no_documents_in_group'] = 'Keine.';
$_lang['access_permissions_no_users_in_group'] = 'Keine.';
$_lang['access_permissions_off'] = '<span class="warning">Zugriffsberechtigungen sind nicht aktiviert.</span> Dies bedeutet, dass hier durchgeführte Änderungen keine Auswirkungen haben, bis Zugriffsberechtigungen aktiviert werden.';
$_lang['access_permissions_users_in_group'] = '<strong>Benutzer in der Gruppe:</strong> ';
$_lang['access_permissions_users_tab'] = 'Hier können Sie sehen, welche Benutzergruppen angelegt wurden. Sie können auch neue Gruppen einrichten, Gruppen umbenennen oder löschen und sehen, welche Benutzer Mitglieder der verschiedenen Gruppen sind. Um einen Benutzer einer Gruppe hinzuzufügen oder einen Benutzer aus einer Gruppe zu entfernen, bearbeiten Sie bitte den Benutzer selbst.';
$_lang['access_permissions_user_group'] = 'Benutzergruppe:';
$_lang['access_permissions_user_groups'] = 'Benutzergruppen';
$_lang['access_permissions_user_group_access'] = 'Dokumentgruppen, auf die diese Benutzergruppe Zugriff hat:';
$_lang['access_permissions_user_message'] = 'Hier können Sie festlegen, welchen Benutzergruppen dieser Benutzer angehört:';
$_lang['access_permission_denied'] = 'Sie haben nicht die richtigen Befugnisse für dieses Dokument.';
$_lang['access_permission_parent_denied'] = 'Sie haben keine Berechtigung, hier ein Dokument anzulegen oder eines hierher zu verschieben! Bitte wählen Sie einen anderen Ort.';
$_lang['access_policy_err_nf'] = 'Zugriffsrichtlinie nicht gefunden.';
$_lang['access_policy_err_ns'] = 'Zugriffsrichtlinie nicht angegeben.';
$_lang['access_policy_grid_empty'] = 'Keine Richtlinien vorhanden';
$_lang['access_policy_grid_paginate'] = 'Richtlinien {0} - {1} von {2}';
$_lang['access_resourcegroup_management_msg'] = 'Verwalten Sie die Zugriffsrechte von Benutzergruppen-Mitgliedern auf Ressourcen-Gruppen und weisen Sie optional Zugriffsrichtlinien zu.';
$_lang['access_rgroup_err_ae'] = 'Eine ACL für diese Ressourcen-Gruppe existiert bereits!';
$_lang['access_rgroup_err_nf'] = 'Ressourcen-Gruppen-ACL nicht gefunden.';
$_lang['access_rgroup_err_ns'] = 'Ressourcen-Gruppen-ACL nicht angegeben.';
$_lang['access_rgroup_err_remove'] = 'Ein Fehler trat auf beim Versuch, die Ressourcen-Gruppen-ACL zu löschen.';
$_lang['access_rgroup_remove'] = 'Zugriff auf diese Ressourcen-Gruppe löschen';
$_lang['access_rgroup_update'] = 'Zugriff auf diese Ressourcen-Gruppe bearbeiten';
$_lang['access_to_contexts'] = 'Zugriff auf Kontexte';
$_lang['access_to_resource_groups'] = 'Zugriff auf Ressourcen-Gruppen';
$_lang['access_type_err_ns'] = 'Zieltyp oder ID nicht angegeben!';
$_lang['acl_add'] = 'Zugriffskontrolle hinzufügen';
$_lang['authority'] = 'Autorität';
$_lang['authority_err_ns'] = 'Bitte geben Sie einen Mindestwert für die Rolle an.';
$_lang['category'] = 'Kategorie';
$_lang['category_add'] = 'Kategorie hinzufügen';
$_lang['filter_by_context'] = 'Nach Kontext filtern...';
$_lang['filter_by_policy'] = 'Nach Zugriffs-Richtlinie filtern...';
$_lang['filter_by_resource_group'] = 'Nach Ressourcen-Gruppe filtern...';
$_lang['filter_by_category'] = 'Nach Kategorie filtern...';
$_lang['resource_group'] = 'Ressourcen-Gruppe';
$_lang['resource_group_add'] = 'Ressourcen-Gruppe hinzufügen';
$_lang['resource_group_access_remove'] = 'Ressource aus der Gruppe entfernen';
$_lang['resource_group_access_remove_confirm'] = 'Sind Sie sicher, dass Sie diese Ressource aus der Ressourcen-Gruppe entfernen möchten?';
$_lang['resource_group_create'] = 'Ressourcen-Gruppe erstellen';
$_lang['resource_group_err_ae'] = 'Eine Ressourcen-Gruppe mit diesem Namen existiert bereits.';
$_lang['resource_group_err_create'] = 'Ein Fehler trat auf beim Versuch, die Ressourcen-Gruppe zu erstellen.';
$_lang['resource_group_err_nf'] = 'Ressourcen-Gruppe nicht gefunden.';
$_lang['resource_group_err_ns'] = 'Ressourcen-Gruppe nicht angegeben.';
$_lang['resource_group_err_remove'] = 'Ein Fehler trat auf beim Versuch, die Ressourcen-Gruppe zu löschen.';
$_lang['resource_group_remove'] = 'Ressourcen-Gruppe löschen';
$_lang['resource_group_remove_confirm'] = 'Sind Sie sicher, dass Sie diese Ressourcen-Gruppe löschen möchten?';
$_lang['resource_group_resource_err_ae'] = 'Die Ressource ist bereits Teil dieser Ressourcen-Gruppe.';
$_lang['resource_group_resource_err_create'] = 'Ein Fehler trat auf beim Versuch, die Ressource der Ressourcen-Gruppe hinzuzufügen.';
$_lang['resource_group_resource_err_nf'] = 'Die Ressource ist nicht Teil dieser Ressourcen-Gruppe.';
$_lang['resource_group_resource_err_remove'] = 'Ein Fehler trat auf beim Versuch, die Ressource aus der Ressourcen-Gruppe zu entfernen.';
$_lang['resource_group_untitled'] = 'Unbenannte Ressourcen-Gruppe';
$_lang['roles_msg'] = 'Eine Rolle ist per Definition eine Position oder ein Status, den man in einer bestimmten Situation hat. Rollen können verwendet werden, um Benutzer innerhalb einer Benutzergruppe nach Position oder Status zu gruppieren. Rollen haben in MODx zudem das, was wir "Autorität" nennen. Dies ist ein Zahlenwert, genauer gesagt eine beliebige ganze Zahl >= 0. Autoritäts-Level sind "abwärts vererbbar" in dem Sinne, dass eine Rolle mit Autorität 1 alle Gruppenrichtlinien erbt, die ihr selbst und allen Rollen mit einem höheren Autoritäts-Wert als 1 zugeordnet sind.';
$_lang['user_group_category_access'] = 'Zugriff auf Elemente über Kategorien';
$_lang['user_group_category_access_msg'] = 'Hier können Sie festlegen, auf welche Elemente diese Benutzergruppe über die Kategorien, in denen sich die Elemente befinden, zugreifen kann.';
$_lang['user_group_category_err_ae'] = 'Die Benutzergruppe hat bereits Zugriff auf diese Kategorie.';
$_lang['user_group_category_remove_confirm'] = 'Sind Sie sicher, dass Sie diese Kategorie aus dieser Benutzergruppe entfernen möchten?';
$_lang['user_group_context_access'] = 'Kontext-Zugriff';
$_lang['user_group_context_access_msg'] = 'Hier legen Sie fest, auf welche Kontexte diese Benutzergruppe zugreifen kann.';
$_lang['user_group_context_err_ae'] = 'Die Benutzergruppe hat bereits Zugriff auf diesen Kontext.';
$_lang['user_group_context_remove_confirm'] = 'Sind Sie sicher, dass Sie dieser Benutzergruppe den Zugriff auf diesen Kontext entziehen möchten?';
$_lang['user_group_resourcegroup_access'] = 'Ressourcen-Gruppen-Zugriff';
$_lang['user_group_resourcegroup_access_msg'] = 'Hier können Sie festlegen, auf welche Ressourcen-Gruppen diese Benutzergruppe zugreifen kann.';
$_lang['user_group_resourcegroup_err_ae'] = 'Die Benutzergruppe hat bereits Zugriff auf diese Ressourcen-Gruppe.';
$_lang['user_group_resourcegroup_remove_confirm'] = 'Sind Sie sicher, dass Sie dieser Benutzergruppe den Zugriff auf diese Ressourcen-Gruppe entziehen möchten?';
$_lang['user_group_user_access_msg'] = 'Bitte wählen Sie, welche Benutzer sie in diese Benutzergruppe aufnehmen möchten.';
