<?php
/**
 * @package modx
 * @subpackage lexicon

 * @language de
 * @namespace core
 * @topic permissions
 */
$_lang['perm.about_desc'] = 'Die Seite "Über MODx" anzeigen.';
$_lang['perm.access_permissions_desc'] = 'Mit Zugriffsrechten zusammenhängende Seiten und Aktionen anzeigen und bearbeiten/benutzen.';
$_lang['perm.actions_desc'] = 'Die Aktionen-Seite anzeigen und benutzen.';
$_lang['perm.add_children_desc'] = 'Der angegebenen Ressource Kind-Ressourcen hinzufügen.';
$_lang['perm.change_password_desc'] = 'Benutzer kann sein Benutzer-Passwort ändern.';
$_lang['perm.change_profile_desc'] = 'Benutzer kann sein Profil ändern.';
$_lang['perm.charsets_desc'] = 'Eine Liste von Zeichencodierungen anzeigen.';  // charsets = Zeichensätze?
$_lang['perm.content_types_desc'] = 'Die Inhaltstypen-Seite anzeigen und benutzen.';
$_lang['perm.countries_desc'] = 'Eine Liste von Ländern anzeigen.';
$_lang['perm.create_desc'] = 'Elementarer "Erstellen"-Zugriff auf neue Objekte.';
$_lang['perm.credits_desc'] = 'Die Seite mit den Danksagungen anzeigen.';
$_lang['perm.customize_forms_desc'] = 'Formular-Anpassungs-Seite anzeigen und verwalten.';
$_lang['perm.database_desc'] = 'Die Systeminformationen-Seite anzeigen.';
$_lang['perm.database_truncate_desc'] = 'Datenbank-Tabellen leeren.';
$_lang['perm.delete_desc'] = 'Elementarer "Löschen"-Zugriff auf Objekte.';  // basic = grundlegend? elementar? eingeschränkt???
$_lang['perm.delete_category_desc'] = 'Kategorien löschen oder entfernen.';  // any: beliebige? (auch bei den anderen so aufgebauten Begriffen)
$_lang['perm.delete_chunk_desc'] = 'Chunks löschen oder entfernen.';
$_lang['perm.delete_context_desc'] = 'Kontexte löschen oder entfernen.';
$_lang['perm.delete_document_desc'] = 'Ressourcen löschen oder entfernen.';
$_lang['perm.delete_eventlog_desc'] = 'Das Ereignisprotokoll leeren.';  // Manager-Aktivitäten?
$_lang['perm.delete_plugin_desc'] = 'Plugins löschen oder entfernen.';
$_lang['perm.delete_propertyset_desc'] = 'Eigenschaften-Gruppen löschen oder entfernen.';
$_lang['perm.delete_role_desc'] = 'Rollen löschen oder entfernen.';
$_lang['perm.delete_snippet_desc'] = 'Snippets löschen oder entfernen.';
$_lang['perm.delete_template_desc'] = 'Templates löschen oder entfernen.';
$_lang['perm.delete_tv_desc'] = 'Template-Variablen löschen oder entfernen.';
$_lang['perm.delete_user_desc'] = 'Benutzer löschen oder entfernen.';
$_lang['perm.directory_chmod_desc'] = 'Verzeichnisrechte eines Verzeichnisses ändern (CHMOD).';
$_lang['perm.directory_create_desc'] = 'Verzeichnisse anlegen.';
$_lang['perm.directory_list_desc'] = 'Liste der Unterverzeichnisse eines Verzeichnisses anzeigen.';
$_lang['perm.directory_remove_desc'] = 'Verzeichnisse löschen.';
$_lang['perm.directory_update_desc'] = 'Verzeichnisse umbenennen.';
$_lang['perm.edit_category_desc'] = 'Kategorien bearbeiten.';  // any: beliebige? (auch bei den anderen so aufgebauten Begriffen)
$_lang['perm.edit_chunk_desc'] = 'Chunks bearbeiten.';
$_lang['perm.edit_context_desc'] = 'Kontexte bearbeiten.';
$_lang['perm.edit_document_desc'] = 'Ressourcen bearbeiten.';
$_lang['perm.edit_locked_desc'] = 'Erlaubt einem Benutzer, eine Sperre zu umgehen und eine gesperrte Ressource zu bearbeiten.';
$_lang['perm.edit_plugin_desc'] = 'Plugins bearbeiten.';
$_lang['perm.edit_propertyset_desc'] = 'Eigenschaften-Gruppen bearbeiten.';
$_lang['perm.edit_role_desc'] = 'Rollen bearbeiten.';
$_lang['perm.edit_snippet_desc'] = 'Snippets bearbeiten.';
$_lang['perm.edit_template_desc'] = 'Templates bearbeiten.';
$_lang['perm.edit_tv_desc'] = 'Template-Variablen bearbeiten.';
$_lang['perm.edit_user_desc'] = 'Benutzer bearbeiten.';
$_lang['perm.element_tree_desc'] = 'Den Elemente-Baum im linken Navigations-Bereich anzeigen.';
$_lang['perm.empty_cache_desc'] = 'Den Site-Cache leeren.';
$_lang['perm.error_log_erase_desc'] = 'Das Fehlerprotokoll löschen.';  // leeren?
$_lang['perm.error_log_view_desc'] = 'Das Fehlerprotokoll anzeigen.';  // ansehen? (auch bei den anderen so aufgebauten Begriffen)
$_lang['perm.export_static_desc'] = 'Die Site in statische HTML-Dateien exportieren.';
$_lang['perm.file_list_desc'] = 'Liste der in einem angegebenen Verzeichnis liegenden Dateien anzeigen.';
$_lang['perm.file_manager_desc'] = 'Den Dateimanager benutzen.';
$_lang['perm.file_remove_desc'] = 'Dateien löschen.';
$_lang['perm.file_tree_desc'] = 'Den Dateibaum im linken Navigations-Bereich anzeigen.';
$_lang['perm.file_update_desc'] = 'Den Inhalt von Dateien ändern.';
$_lang['perm.file_upload_desc'] = 'Dateien in ein Verzeichnis hochladen.';
$_lang['perm.file_view_desc'] = 'Inhalte von Dateien anzeigen.';
$_lang['perm.flush_sessions_desc'] = 'Sessions Site-übergreifend zurücksetzen.';
$_lang['perm.frames_desc'] = 'Die MODx-Manager-Oberfläche benutzen.';
$_lang['perm.help_desc'] = 'Die Hilfe-Seite anzeigen.';
$_lang['perm.home_desc'] = 'Die Manager-Startseite anzeigen.';
$_lang['perm.import_static_desc'] = 'Import-Seiten anzeigen oder benutzen.';
$_lang['perm.languages_desc'] = 'Lexikon-Sprachen bearbeiten oder anzeigen.';
$_lang['perm.lexicons_desc'] = 'Lexika bearbeiten oder anzeigen.';
$_lang['perm.list_desc'] = 'Elementare Berechtigung, Objekte "aufzulisten". Auflisten bedeutet, eine Sammlung von Objekten zu erhalten.';
$_lang['perm.load_desc'] = 'Elementare Berechtigung, Objekte zu "laden" oder überhaupt in der Lage zu sein, sie als Instanzen zurückzugeben.';
$_lang['perm.logout_desc'] = 'Als Benutzer ausloggen.';
$_lang['perm.logs_desc'] = 'Protokolle wie das Fehlerprotokoll und das Protokoll der Manager-Aktivitäten anzeigen.';
$_lang['perm.menus_desc'] = 'Menüpunkte des Hauptmenüs bearbeiten oder speichern.';
$_lang['perm.messages_desc'] = 'Persönliche Nachrichten senden oder anzeigen.';
$_lang['perm.move_desc'] = 'Elementarer "Verschieben"-Zugriff auf Objekte.';
$_lang['perm.namespaces_desc'] = 'Namespaces bearbeiten oder anzeigen.';
$_lang['perm.new_category_desc'] = 'Neue Kategorien anlegen.';
$_lang['perm.new_chunk_desc'] = 'Neue Chunks anlegen.';
$_lang['perm.new_context_desc'] = 'Neue Kontexte anlegen.';
$_lang['perm.new_document_desc'] = 'Neue Ressourcen anlegen.';
$_lang['perm.new_document_in_root_desc'] = 'Eine Ressource in der obersten Ebene (Root) anlegen.';
$_lang['perm.new_plugin_desc'] = 'Neue Plugins anlegen.';
$_lang['perm.new_propertyset_desc'] = 'Neue Eigenschaften-Gruppen anlegen.';
$_lang['perm.new_role_desc'] = 'Neue Rollen anlegen.';
$_lang['perm.new_snippet_desc'] = 'Neue Snippets anlegen.';
$_lang['perm.new_template_desc'] = 'Neue Templates anlegen.';
$_lang['perm.new_tv_desc'] = 'Neue Template-Variablen anlegen.';
$_lang['perm.new_user_desc'] = 'Neue Benutzer anlegen.';
$_lang['perm.packages_desc'] = 'Transport-Packages in der Package-Verwaltung benutzen.';
$_lang['perm.property_sets_desc'] = 'Eigenschaften und Eigenschaften-Gruppen anzeigen und bearbeiten.';
$_lang['perm.providers_desc'] = 'Anbieter anzeigen und bearbeiten.';
$_lang['perm.publish_desc'] = 'Elementarer "Veröffentlichen"-Zugriff auf Objekte.';
$_lang['perm.publish_document_desc'] = 'Ressourcen veröffentlichen und zurückziehen.';
$_lang['perm.purge_deleted_desc'] = 'Mülleimer leeren (gelöschte Ressourcen endgültig entfernen).';
$_lang['perm.remove_desc'] = 'Elementare Berechtigung, Objekte zu entfernen.';  // löschen
$_lang['perm.remove_locks_desc'] = 'Alle existierenden Sperren der Site aufheben.';
$_lang['perm.resource_tree_desc'] = 'Den Ressourcen-Baum im linken Navigations-Bereich anzeigen.';
$_lang['perm.save_desc'] = 'Elementare Berechtigung, Objekte zu speichern.';
$_lang['perm.save_category_desc'] = 'Kategorien speichern.';  // any: beliebige? (auch bei den anderen so aufgebauten Begriffen)
$_lang['perm.save_chunk_desc'] = 'Chunks speichern.';
$_lang['perm.save_context_desc'] = 'Kontexte speichern.';
$_lang['perm.save_document_desc'] = 'Ressourcen speichern.';
$_lang['perm.save_plugin_desc'] = 'Plugins speichern.';
$_lang['perm.save_propertyset_desc'] = 'Eigenschaften-Gruppen speichern.';
$_lang['perm.save_role_desc'] = 'Rollen speichern.';
$_lang['perm.save_snippet_desc'] = 'Snippets speichern.';
$_lang['perm.save_template_desc'] = 'Templates speichern.';
$_lang['perm.save_tv_desc'] = 'Template-Variablen speichern.';
$_lang['perm.save_user_desc'] = 'Benutzer speichern.';
$_lang['perm.search_desc'] = 'Die Suchfunktion des MODx-Managers benutzen.';  // Such-Seite
$_lang['perm.settings_desc'] = 'Systemeinstellungen anzeigen und bearbeiten.';
$_lang['perm.steal_lock_desc'] = 'Eine Sperre einer Ressource "stehlen" oder entfernen.';
$_lang['perm.steal_locks_desc'] = 'Sperren "stehlen", indem man eine bestehende Sperre einer Ressource umgeht.';
$_lang['perm.undelete_desc'] = 'Elementare Berechtigung, Objekte "wiederherzustellen".';
$_lang['perm.undelete_document_desc'] = 'Ressourcen wiederherstellen.';
$_lang['perm.unlock_element_properties_desc'] = 'Standard-Eigenschaften von Elementen bearbeiten.';
$_lang['perm.unpublish_desc'] = 'Ressourcen zurückziehen.';  // Unterschied?
$_lang['perm.unpublish_document_desc'] = 'Ressourcen zurückziehen.';  // Unterschied?
$_lang['perm.view_desc'] = 'Elementare Berechtigung, Objekte "anzuzeigen".';
$_lang['perm.view_category_desc'] = 'Kategorien anzeigen.';  // any: beliebige? (auch bei den anderen so aufgebauten Begriffen)
$_lang['perm.view_chunk_desc'] = 'Chunks anzeigen.';
$_lang['perm.view_context_desc'] = 'Kontexte anzeigen.';
$_lang['perm.view_document_desc'] = 'Ressourcen anzeigen.';
$_lang['perm.view_element_desc'] = 'Eine Liste von Elementen oder Element-Klassen anzeigen.';
$_lang['perm.view_eventlog_desc'] = 'Das Ereignisprotokoll anzeigen.';
$_lang['perm.view_offline_desc'] = 'Die Site anzeigen, wenn sie offline geschaltet ist.';
$_lang['perm.view_plugin_desc'] = 'Plugins anzeigen.';
$_lang['perm.view_propertyset_desc'] = 'Eigenschaften-Gruppen anzeigen.';
$_lang['perm.view_role_desc'] = 'Rollen anzeigen.';
$_lang['perm.view_snippet_desc'] = 'Snippets anzeigen.';
$_lang['perm.view_sysinfo_desc'] = 'Die Systeminformationen-Seite anzeigen.';
$_lang['perm.view_template_desc'] = 'Templates anzeigen.';
$_lang['perm.view_tv_desc'] = 'Template-Variablen anzeigen.';
$_lang['perm.view_unpublished_desc'] = 'Nicht veröffentlichte bzw. zurückgezogene Ressourcen anzeigen.';
$_lang['perm.view_user_desc'] = 'Benutzer anzeigen.';
$_lang['perm.workspaces_desc'] = 'Package-Verwaltung benutzen.';