<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameDesSnippet';
$_lang['snippet'] = 'Snippet';
$_lang['snippets_available'] = 'Snippets, die Sie in Ihre Seite einbinden können';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Sind Sie sicher, dass Sie dieses Snippet löschen möchten?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Sind Sie sicher, dass Sie dieses Snippet duplizieren möchten?';
$_lang['snippet_duplicate_error'] = 'Beim Duplizieren des Snippets ist ein Fehler aufgetreten.';
$_lang['snippet_err_create'] = 'Beim Erstellen des Snippets ist ein Fehler aufgetreten.';
$_lang['snippet_err_delete'] = 'Beim Versuch, das Snippet zu löschen, ist ein Fehler aufgetreten.';
$_lang['snippet_err_duplicate'] = 'Beim Versuch, das Snippet zu duplizieren, ist ein Fehler aufgetreten.';
$_lang['snippet_err_ae'] = 'Ein Snippet mit dem Namen "[[+name]]" existiert bereits.';
$_lang['snippet_err_invalid_name'] = 'Der Snippet-Name ist ungültig.';
$_lang['snippet_err_locked'] = 'Dieses Snippet ist für die Bearbeitung gesperrt.';
$_lang['snippet_err_nf'] = 'Snippet nicht gefunden!';
$_lang['snippet_err_ns'] = 'Snippet nicht angegeben.';
$_lang['snippet_err_ns_name'] = 'Bitte geben Sie einen Namen für das Snippet an.';
$_lang['snippet_err_remove'] = 'Beim Versuch, das Snippet zu löschen, ist ein Fehler aufgetreten.';
$_lang['snippet_err_save'] = 'Beim Speichern des Snippets ist ein Fehler aufgetreten.';
$_lang['snippet_execonsave'] = 'Snippet nach dem Speichern ausführen.';
$_lang['snippet_lock'] = 'Snippet für die Bearbeitung sperren';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Hier können Sie auswählen, welches Snippet Sie bearbeiten möchten.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: <span class="copy-this">[[<span class="example-replace-name">'.$_lang['example_tag_snippet_name'].'</span>]]</span>';
$_lang['snippet_new'] = 'Snippet erstellen';
$_lang['snippet_properties'] = 'Standardeigenschaften';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippet_title'] = 'Create/Edit Snippet';
$_lang['snippet_untitled'] = 'Unbenanntes Snippet';
$_lang['snippets'] = 'Snippets';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
