<?php
/**
 * TV English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_tvname'] = 'NameOfTV';
$_lang['has_access'] = 'Hat Zugriff?';
$_lang['filter_by_category'] = 'Nach Kategorie filtern …';
$_lang['rank'] = 'Rang';
$_lang['rendering_options'] = 'Darstellungsoptionen';
$_lang['tv'] = 'TV';
$_lang['tvs'] = 'Template-Variablen';
$_lang['tv_binding_msg'] = 'Dieses Feld unterstützt Datenquellen-Bindung mittels der @-Befehle.';
$_lang['tv_caption'] = 'Bezeichnung';
$_lang['tv_caption_desc'] = 'The label shown for this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_category_desc'] = 'Use to group TVs in Resource editing pages and within the Elements tree.';
$_lang['tv_change_template_msg'] = 'Das Wechseln des Templates führt dazu, dass die TVs neu geladen werden, wobei alle nicht gespeicherten Änderungen verloren gehen.<br /><br />Sind Sie sicher, dass Sie das Template wechseln möchten?';
$_lang['tv_delete_confirm'] = 'Sind Sie sicher, dass Sie diese TV löschen möchten?';
$_lang['tv_description'] = 'Beschreibung';
$_lang['tv_description_desc'] = 'Usage information for this TV shown next its caption in Resource editing pages and as a tooltip in the Elements tree.';
$_lang['tv_err_delete'] = 'Beim Versuch, die TV zu löschen, ist ein Fehler aufgetreten.';
$_lang['tv_err_duplicate'] = 'Beim Versuch, die TV zu duplizieren, ist ein Fehler aufgetreten.';
$_lang['tv_err_duplicate_templates'] = 'Beim Duplizieren der TV-Templates ist ein Fehler aufgetreten.';
$_lang['tv_err_duplicate_documents'] = 'Beim Duplizieren von TV-Dokumenten ist ein Fehler aufgetreten.';
$_lang['tv_err_duplicate_documentgroups'] = 'Beim Duplizieren von TV-Dokumentgruppen ist ein Fehler aufgetreten.';
$_lang['tv_err_ae'] = 'Eine TV mit dem Namen "[[+name]]" existiert bereits.';
$_lang['tv_err_invalid_name'] = 'Der TV-Name ist ungültig.';
$_lang['tv_err_invalid_id_attr'] = 'HTML ids must not begin with a number or contain any white space.';
$_lang['tv_err_locked'] = 'TV gesperrt!';
$_lang['tv_err_nf'] = 'TV nicht gefunden.';
$_lang['tv_err_nfs'] = 'TV mit dem Schlüssel [[+key]] nicht gefunden';
$_lang['tv_err_ns'] = 'TV nicht angegeben.';
$_lang['tv_err_reserved_name'] = 'Eine TV kann nicht den gleichen Namen wie ein Ressourcen-Feld haben.';
$_lang['tv_err_save_access_permissions'] = 'Beim Versuch, die Zugriffsrechte der TV zu speichern, ist ein Fehler aufgetreten.';
$_lang['tv_err_save'] = 'Beim Speichern der TV ist ein Fehler aufgetreten.';
$_lang['tv_inuse'] = 'Die unten aufgeführten Dokumente verwenden momentan diese TV. Um mit dem Löschen fortzufahren, klicken Sie bitte auf den Löschen-Button, anderenfalls klicken Sie auf den Abbrechen-Button.';
$_lang['tv_inuse_template'] = 'Die folgenden Templates nutzen derzeit diese TV: [[+templates]].<br /><br />Bitte löschen Sie die TV aus den Templates, bevor Sie sie löschen.';
$_lang['tv_lock'] = 'Restrict Editing';
$_lang['tv_lock_desc'] = 'Only users with “edit_locked” permissions can edit this TV.';
$_lang['tv_management_msg'] = 'Verwalten Sie zusätzliche benutzerdefinierte TVs für Ihre Ressourcen.';
$_lang['tv_name'] = 'TV-Name';
$_lang['tv_name_desc'] = 'Place the content generated by this TV in a Resource, Template, or Chunk using the following MODX tag: <span class="copy-this">[[*<span class="example-replace-name">'.$_lang['example_tag_tvname'].'</span>]]</span>';
$_lang['tv_new'] = 'TV erstellen';
$_lang['tv_novars'] = 'Keine TVs gefunden';
$_lang['tv_properties'] = 'Standardeigenschaften';
$_lang['tv_rank'] = 'Sortierreihenfolge';
$_lang['tv_rank_desc'] = 'Use to control the positioning of this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_reset_params'] = 'Parameter zurücksetzen';
$_lang['tv_tab_access_desc'] = 'Select the Resource Groups that this TV belongs to. Only users with access to the Groups selected will be able to modify this TV. If no Groups are selected, all users with access to the Manager will be able to modify the TV.';
$_lang['tv_tab_general_desc'] = 'Here you can create/edit a <dfn>Template Variable</dfn> (TV). TVs must be assigned to templates in order to access them from snippets and documents.';
$_lang['tv_tab_input_options'] = 'Eingabe-Optionen';
$_lang['tv_tab_input_options_desc'] = '<p>Here you can edit the input options for the TV, specific to the type of input render that you select.</p>';
$_lang['tv_tab_output_options'] = 'Ausgabe-Optionen';
$_lang['tv_tab_output_options_desc'] = '<p>Here you can edit the output options for the TV, specific to the type of output render that you select.</p>';
$_lang['tv_tab_sources_desc'] = 'Hier können Sie die Medienquellen, die für diese TV genutzt werden sollen, für den jeweils angegebenen Kontext zuordnen. Klicken Sie in der Übersicht doppelt auf den Quellen-Namen, um die Zuordnung zu ändern.';
$_lang['tv_tab_tmpl_access'] = 'Template-Zugriff';
$_lang['tv_tab_tmpl_access_desc'] = 'Select the templates that are allowed to access this TV.';
$_lang['tv_tag_copied'] = 'TV tag copied!';
$_lang['tv_widget'] = 'Widget';
$_lang['tv_widget_prop'] = 'Widget-Eigenschaften';
$_lang['tvd_err_remove'] = 'Beim Versuch, die TV von der Ressource zu entfernen, ist ein Fehler aufgetreten.';
$_lang['tvdg_err_remove'] = 'Beim Versuch, die TV aus der Ressourcen-Gruppe zu entfernen, ist ein Fehler aufgetreten.';
$_lang['tvdg_err_save'] = 'Beim Versuch, die TV der Ressourcen-Gruppe zuzuordnen, ist ein Fehler aufgetreten.';
$_lang['tvt_err_nf'] = 'Die TV hat keinen Zugriff auf das angegebene Template.';
$_lang['tvt_err_remove'] = 'Beim Versuch, die TV vom Template zu entfernen, ist ein Fehler aufgetreten.';
$_lang['tvt_err_save'] = 'Beim Versuch, die TV dem Template zuzuordnen, ist ein Fehler aufgetreten.';

// Temporarily match old keys to new ones to ensure compatibility
// -- fields
$_lang['tv_desc_caption'] = $_lang['tv_caption_desc'];
$_lang['tv_desc_category'] = $_lang['tv_category_desc'];
$_lang['tv_desc_description'] = $_lang['tv_description_desc'];
$_lang['tv_desc_name'] = $_lang['tv_name_desc'];
$_lang['tv_lock_msg'] = $_lang['tv_lock_desc'];
$_lang['tv_rank_msg'] = $_lang['tv_rank_desc'];

// -- tabs
$_lang['tv_access_msg'] = $_lang['tv_tab_access_desc'];
$_lang['tv_input_options'] = $_lang['tv_tab_input_options'];
$_lang['tv_input_options_msg'] = $_lang['tv_tab_input_options_desc'];
$_lang['tv_msg'] = $_lang['tv_tab_general_desc'];
$_lang['tv_output_options'] = $_lang['tv_tab_output_options'];
$_lang['tv_output_options_msg'] = $_lang['tv_tab_output_options_desc'];
$_lang['tv_sources.intro_msg'] = $_lang['tv_tab_sources_desc'];
$_lang['tv_tmpl_access'] = $_lang['tv_tab_tmpl_access'];
$_lang['tv_tmpl_access_msg'] = $_lang['tv_tab_tmpl_access_desc'];
