<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'اسنیپت';
$_lang['snippets_available'] = 'اسنیپت‌های موجود';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'آیا مایل به حذف این اسنیپت هستید؟';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'آیا مایل به تکرار این اسنیپت هستید؟';
$_lang['snippet_duplicate_error'] = 'خطایی هنگام تکرار اسنیپت رخ داده است.';
$_lang['snippet_err_create'] = 'خطایی هنگام ایجاد اسنیپت رخ داده است.';
$_lang['snippet_err_delete'] = 'خطایی هنگام حذف اسنیپت رخ داده است.';
$_lang['snippet_err_duplicate'] = 'خطایی هنگام تکرار اسنیپت رخ داده است.';
$_lang['snippet_err_ae'] = 'یک اسنیپت با نام "[[+name]]" وجود دارد.';
$_lang['snippet_err_invalid_name'] = 'نام اسنیپت درست نیست.';
$_lang['snippet_err_locked'] = 'این اسنیپت برای ویرایش قفل شده است.';
$_lang['snippet_err_nf'] = 'اسنیپت پیدا نشد!';
$_lang['snippet_err_ns'] = 'اسنیپت مشخص نشده است.';
$_lang['snippet_err_ns_name'] = 'لطفا نامی برای اسنیپت مشخص کنید.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'خطایی هنگام ذخیره اسنیپت رخ داده است.';
$_lang['snippet_execonsave'] = 'اجرا اسنیپت بعد از دخیره‌سازی.';
$_lang['snippet_lock'] = 'قفل کردن ویرایش اسنیپت';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'اینجا می‌توانید اسنیپت را برای ویرایش انتخاب کنید.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'ویژگی‌های پیش‌فرض';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'Snippets';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
