<?php
/**
 * Chunk English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */

// Entry out of alpha order because it must come before the entry it's used in below
$_lang['example_tag_chunk_name'] = 'NameOfChunk';

$_lang['chunk'] = 'Chunk';
$_lang['chunk_category_desc'] = 'Use to group Chunks within the Elements tree.';
$_lang['chunk_code'] = 'Chunk Code (HTML)';
$_lang['chunk_description_desc'] = 'Usage information for this Chunk shown in search results and as a tooltip in the Elements tree.';
$_lang['chunk_delete_confirm'] = 'Voulez-vous vraiment supprimer ce chunk?';
$_lang['chunk_duplicate_confirm'] = 'Voulez-vous vraiment dupliquer ce chunk?';
$_lang['chunk_err_create'] = 'Une erreur est survenue lors de la création du chunk.';
$_lang['chunk_err_duplicate'] = 'Erreur dans la duplication du chunk';
$_lang['chunk_err_ae'] = 'Un chunk ayant pour nom "[[+name]]" existe déjà.';
$_lang['chunk_err_invalid_name'] = 'Nom de chunk invalide.';
$_lang['chunk_err_locked'] = 'Le chunk est verrouillé.';
$_lang['chunk_err_remove'] = 'Une erreur est survenue lors de la suppression du chunk.';
$_lang['chunk_err_save'] = 'Une erreur s\'est produite pendant l\'enregistrement du chunk.';
$_lang['chunk_err_nf'] = 'Chunk introuvable!';
$_lang['chunk_err_nfs'] = 'Chunk introuvable avec l\'id: [[+id]]';
$_lang['chunk_err_ns'] = 'Chunk non spécifié.';
$_lang['chunk_err_ns_name'] = 'Veuillez préciser un nom.';
$_lang['chunk_lock'] = 'Verrouiller le chunk pour l\'édition';
$_lang['chunk_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Chunk.';
$_lang['chunk_name_desc'] = 'Place the content generated by this Chunk in a Resource, Template, or other Chunk using the following MODX tag: [[+tag]]';
$_lang['chunk_new'] = 'Créer un Chunk';
$_lang['chunk_properties'] = 'Propriétés par défaut';
$_lang['chunk_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Chunk</em> as well as its content. The content must be HTML, either placed in the <em>Chunk Code</em> field below or in a static external file, and may include MODX tags. Note, however, that PHP code will not run in this element.';
$_lang['chunk_tag_copied'] = 'Chunk tag copied!';
$_lang['chunk_title'] = 'Créer/modifier le chunk';
$_lang['chunk_untitled'] = 'Chunk sans nom';
$_lang['chunks'] = 'Chunks';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['chunk_desc_category'] = $_lang['chunk_category_desc'];
$_lang['chunk_desc_description'] = $_lang['chunk_description_desc'];
$_lang['chunk_desc_name'] = $_lang['chunk_name_desc'];
$_lang['chunk_lock_msg'] = $_lang['chunk_lock_desc'];

// --tabs
$_lang['chunk_msg'] = $_lang['chunk_tab_general_desc'];
