<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Snippet';
$_lang['snippets_available'] = 'Snippets disponibles, à ajouter dans votre page';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Voulez-vous vraiment supprimer ce snippet?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Voulez-vous vraiment dupliquer ce snippet?';
$_lang['snippet_duplicate_error'] = 'Une erreur s\'est produite pendant la copie du snippet.';
$_lang['snippet_err_create'] = 'Une erreur s\'est produite lors de la création du snippet.';
$_lang['snippet_err_delete'] = 'Une erreur s\'est produite lors de la suppression du snippet .';
$_lang['snippet_err_duplicate'] = 'Une erreur s\'est produite lors de la duplication du snippet.';
$_lang['snippet_err_ae'] = 'Un snippet ayant pour nom "[[+name]]" existe déjà.';
$_lang['snippet_err_invalid_name'] = 'Nom de snippet invalide.';
$_lang['snippet_err_locked'] = 'Ce snippet est verrouillé contre les modifications.';
$_lang['snippet_err_nf'] = 'Snippet introuvable!';
$_lang['snippet_err_ns'] = 'Snippet non spécifié.';
$_lang['snippet_err_ns_name'] = 'Veuillez spécifier un nom pour le snippet.';
$_lang['snippet_err_remove'] = 'Une erreur s\'est produite lors de la suppression du snippet .';
$_lang['snippet_err_save'] = 'Une erreur s\'est produite lors de l\'enregistrement du snippet.';
$_lang['snippet_execonsave'] = 'Exécuter le snippet après son enregistrement.';
$_lang['snippet_lock'] = 'Verrouiller le snippet contre les modifications';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Choisissez ici le snippet que vous souhaitez modifier.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Créer un snippet de code';
$_lang['snippet_properties'] = 'Propriétés par défaut';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippet_title'] = 'Create/Edit Snippet';
$_lang['snippet_untitled'] = 'Snippet sans nom';
$_lang['snippets'] = 'Snippets';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
