<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'كتلة كود';
$_lang['snippets_available'] = 'كتل الكود متاحة لك لتضمينها في الصفحة';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'هل أنت متأكد من أنك تريد حذف كتلة الكود هذه؟';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'هل أنت متأكد من أنك تريد تكرار كتلة الكود هذه؟';
$_lang['snippet_duplicate_error'] = 'حدث خطأ أثناء تكرار كتل الكود.';
$_lang['snippet_err_create'] = 'حدث خطأ أثناء إنشاء كتلة الكود.';
$_lang['snippet_err_delete'] = 'حدث خطأ أثناء محاولة حذف كتلة الكود.';
$_lang['snippet_err_duplicate'] = 'حدث خطأ أثناء محاولة تكرار كتلة الكود.';
$_lang['snippet_err_ae'] = 'يوجد كتلة كود مسبقاً بهذا الاسم "[[+name]]".';
$_lang['snippet_err_invalid_name'] = 'اسم كتلة الكود غير صالح.';
$_lang['snippet_err_locked'] = 'كتلة الكود مقفلة عن التعديل.';
$_lang['snippet_err_nf'] = 'لم يتم العثور على كتلة الكود!';
$_lang['snippet_err_ns'] = 'كتلة الكود غير محددة.';
$_lang['snippet_err_ns_name'] = 'الرجاء تحديد اسم لكتلة الكود.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'حدث خطأ أثناء حفظ كتلة الكود.';
$_lang['snippet_execonsave'] = 'تنفيذ كتلة الكود بعد الحفظ.';
$_lang['snippet_lock'] = 'قفل كتلة الكود عن التعديل';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'هنا تستطيع أي كتلة كود تريد تعديلها.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'الخصائص الافتراضية';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'كتل كود';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
