<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Снiпет';
$_lang['snippets_available'] = 'Сніпеты даступны для таго, каб дадаць іх да вашай старонкі';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Вы сапраўды жадаеце выдаліць гэты сніпет?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Вы сапраўды жадаеце дубляваць гэты сніпет?';
$_lang['snippet_duplicate_error'] = 'Адбылася памылка пры дубляванні сніпета.';
$_lang['snippet_err_create'] = 'Адбылася памылка пры стварэнні сніпета.';
$_lang['snippet_err_delete'] = 'Адбылася памылка пры спробе выдаліць сніпет.';
$_lang['snippet_err_duplicate'] = 'Адбылася памылка пры спробе дубляваць сніпет.';
$_lang['snippet_err_ae'] = 'Сніпет ужо існуе з назвай "[[+name]]".';
$_lang['snippet_err_invalid_name'] = 'Такое імя сніпета недапушчальна.';
$_lang['snippet_err_locked'] = 'Гэты сніпет заблакаваны для рэдагавання.';
$_lang['snippet_err_nf'] = 'Сніпет не знойдзены!';
$_lang['snippet_err_ns'] = 'Сніпет не пазначаны.';
$_lang['snippet_err_ns_name'] = 'Калі ласка, пазначце назву для сніпета.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'Адбылася памылка пры захаванні сніпета.';
$_lang['snippet_execonsave'] = 'Выканаць сніпет пасля захавання.';
$_lang['snippet_lock'] = 'Заблакаваць сніпет для рэдагавання';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Тут вы можаце выбраць які сніпет вы жадаеце рэдагаваць.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'Параметры па змаўчанні';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippet_title'] = 'Create/Edit Snippet';
$_lang['snippet_untitled'] = 'Сніпет без назвы';
$_lang['snippets'] = 'Снiпеты';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
