<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'أفغانستان'; // Afghanistan
$_country_lang["2"] = 'ألبانيا'; // Albania
$_country_lang["3"] = 'الجزائر'; // Algeria
$_country_lang["4"] = 'ساموا الأمريكية'; // American Samoa
$_country_lang["5"] = 'أندورا'; // Andorra
$_country_lang["6"] = 'أنغولا'; // Angola
$_country_lang["7"] = 'أنجويلا'; // Anguilla
$_country_lang["8"] = 'أنتركتيكا'; // Antarctica
$_country_lang["9"] = 'أنتيغوا وبربودا'; // Antigua and Barbuda
$_country_lang["10"] = 'الأرجنتين'; // Argentina
$_country_lang["11"] = 'أرمينيا'; // Armenia
$_country_lang["12"] = 'أروبا'; // Aruba
$_country_lang["13"] = 'أُستراليا'; // Australia
$_country_lang["14"] = 'النمسا'; // Austria
$_country_lang["15"] = 'أذربيجان'; // Azerbaijan
$_country_lang["16"] = 'البهاما'; // Bahamas
$_country_lang["17"] = 'البحرين'; // Bahrain
$_country_lang["18"] = 'بانغلادش'; // Bangladesh
$_country_lang["19"] = 'باربادوس'; // Barbados
$_country_lang["20"] = 'بيلاروسيا'; // Belarus
$_country_lang["21"] = 'بلجيكا'; // Belgium
$_country_lang["22"] = 'بيلز'; // Belize
$_country_lang["23"] = 'بنن'; // Benin
$_country_lang["24"] = 'برمودا'; // Bermuda
$_country_lang["25"] = 'بوتان'; // Bhutan
$_country_lang["26"] = 'بوليفيا'; // Bolivia
$_country_lang["27"] = 'البوسنة والهرسك'; // Bosnia and Herzegowina
$_country_lang["28"] = 'بوتسوانا'; // Botswana
$_country_lang["29"] = 'جزيرة بوفيت'; // Bouvet Island
$_country_lang["30"] = 'البرازيل'; // Brazil
$_country_lang["31"] = 'إقليم المحيط الهندي البريطاني'; // British Indian Ocean Territory
$_country_lang["32"] = 'بروناي دار السلام'; // Brunei Darussalam
$_country_lang["33"] = 'بلغاريا'; // Bulgaria
$_country_lang["34"] = 'بوركينا فاسو'; // Burkina Faso
$_country_lang["35"] = 'بوروندي'; // Burundi
$_country_lang["36"] = 'كامبوديا'; // Cambodia
$_country_lang["37"] = 'الكاميرون'; // Cameroon
$_country_lang["38"] = 'كندا'; // Canada
$_country_lang["39"] = 'الرأس الأخضر'; // Cape Verde
$_country_lang["40"] = 'جزر كايمان'; // Cayman Islands
$_country_lang["41"] = 'جمهورية أفريقيا الوسطى'; // Central African Republic
$_country_lang["42"] = 'تشاد'; // Chad
$_country_lang["43"] = 'شيلي'; // Chile
$_country_lang["44"] = 'الصين'; // China
$_country_lang["45"] = 'جزيرة عيد الميلاد'; // Christmas Island
$_country_lang["46"] = 'جزر كوكوس (كيلينغ)'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'كولومبيا'; // Colombia
$_country_lang["48"] = 'جزر القمر'; // Comoros
$_country_lang["49"] = 'جمهورية الكونغو'; // Congo
$_country_lang["50"] = 'جزر كوك'; // Cook Islands
$_country_lang["51"] = 'كوستاريكا'; // Costa Rica
$_country_lang["52"] = 'ساحل العاج'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'كرواتيا'; // Croatia
$_country_lang["54"] = 'كوبا'; // Cuba
$_country_lang["55"] = 'قبرص'; // Cyprus
$_country_lang["56"] = 'جمهورية التشيك'; // Czech Republic
$_country_lang["57"] = 'الدانمارك'; // Denmark
$_country_lang["58"] = 'جيبوتي'; // Djibouti
$_country_lang["59"] = 'دومينيكا'; // Dominica
$_country_lang["60"] = 'جمهورية الدومينيكان'; // Dominican Republic
$_country_lang["61"] = 'تيمور الشرقية'; // East Timor
$_country_lang["62"] = 'الإكوادور'; // Ecuador
$_country_lang["63"] = 'مصر'; // Egypt
$_country_lang["64"] = 'السلفادور'; // El Salvador
$_country_lang["65"] = 'غينيا الاستوائية'; // Equatorial Guinea
$_country_lang["66"] = 'إريتريا'; // Eritrea
$_country_lang["67"] = 'إستونيا'; // Estonia
$_country_lang["68"] = 'إثيوبيا'; // Ethiopia
$_country_lang["69"] = 'جزر فوكلاند (مالفيناس)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'جزر الفارو'; // Faroe Islands
$_country_lang["71"] = 'فيجي'; // Fiji
$_country_lang["72"] = 'فنلندا'; // Finland
$_country_lang["73"] = 'فرنسا'; // France
$_country_lang["74"] = 'فرنسا'; // France, Metropolitan
$_country_lang["75"] = 'غويانا الفرنسية'; // French Guiana
$_country_lang["76"] = 'بولينيزيا الفرنسية'; // French Polynesia
$_country_lang["77"] = 'الأراضي الجنوبية الفرنسية'; // French Southern Territories
$_country_lang["78"] = 'غابون'; // Gabon
$_country_lang["79"] = 'غامبيا'; // Gambia
$_country_lang["80"] = 'جورجيا'; // Georgia
$_country_lang["81"] = 'ألمانيا'; // Germany
$_country_lang["82"] = 'غانا'; // Ghana
$_country_lang["83"] = 'جبل طارق'; // Gibraltar
$_country_lang["84"] = 'اليونان'; // Greece
$_country_lang["85"] = 'جرينلاند'; // Greenland
$_country_lang["86"] = 'غرينادا'; // Grenada
$_country_lang["87"] = 'غواديلوب'; // Guadeloupe
$_country_lang["88"] = 'غوام'; // Guam
$_country_lang["89"] = 'جواتيمالا'; // Guatemala
$_country_lang["90"] = 'غينيا'; // Guinea
$_country_lang["91"] = 'غينيا-بيساو'; // Guinea-bissau
$_country_lang["92"] = 'غيانا'; // Guyana
$_country_lang["93"] = 'هايتي'; // Haiti
$_country_lang["94"] = 'واستمع جزر ماك دونالد'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'هندوراس'; // Honduras
$_country_lang["96"] = 'هونغ كونغ'; // Hong Kong
$_country_lang["97"] = 'هنغاريا'; // Hungary
$_country_lang["98"] = 'أيسلندا'; // Iceland
$_country_lang["99"] = 'الهند'; // India
$_country_lang["100"] = 'إندونيسيا'; // Indonesia
$_country_lang["101"] = 'إيران'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'العراق'; // Iraq
$_country_lang["103"] = 'ايرلندا'; // Ireland
$_country_lang["104"] = 'إسرائيل'; // Israel
$_country_lang["105"] = 'إيطاليا'; // Italy
$_country_lang["106"] = 'جامايكا'; // Jamaica
$_country_lang["107"] = 'اليابان'; // Japan
$_country_lang["108"] = 'الأردن'; // Jordan
$_country_lang["109"] = 'كازاخستان'; // Kazakhstan
$_country_lang["110"] = 'كينيا'; // Kenya
$_country_lang["111"] = 'كيريباتي'; // Kiribati
$_country_lang["112"] = 'جمهورية كوريا الشعبية الديمقراطية'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'جمهورية كوريا'; // Korea, Republic of
$_country_lang["114"] = 'الكويت'; // Kuwait
$_country_lang["115"] = 'قيرغيزستان'; // Kyrgyzstan
$_country_lang["116"] = 'لاوس'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'لاتفيا'; // Latvia
$_country_lang["118"] = 'لبنان'; // Lebanon
$_country_lang["119"] = 'ليسوتو'; // Lesotho
$_country_lang["120"] = 'ليبريا'; // Liberia
$_country_lang["121"] = 'الجماهيرية العربية الليبية'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'ليشتنشتاين'; // Liechtenstein
$_country_lang["123"] = 'لتوانيا'; // Lithuania
$_country_lang["124"] = 'لوكسمبورج'; // Luxembourg
$_country_lang["125"] = 'ماكاو'; // Macau
$_country_lang["126"] = 'مقدونيا'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'مدغشقر'; // Madagascar
$_country_lang["128"] = 'ملاوي'; // Malawi
$_country_lang["129"] = 'ماليزيا'; // Malaysia
$_country_lang["130"] = 'جزر المالديف'; // Maldives
$_country_lang["131"] = 'مالي'; // Mali
$_country_lang["132"] = 'مالطا'; // Malta
$_country_lang["133"] = 'جزر مارشال'; // Marshall Islands
$_country_lang["134"] = 'جزر المارتينيك'; // Martinique
$_country_lang["135"] = 'موريتانيا'; // Mauritania
$_country_lang["136"] = 'موريشيوس'; // Mauritius
$_country_lang["137"] = 'جزيرة مايوت'; // Mayotte
$_country_lang["138"] = 'المكسيك'; // Mexico
$_country_lang["139"] = 'ولايات مقدونيا المتحدة'; // Micronesia, Federated States of
$_country_lang["140"] = 'جمهورية مولدوفا'; // Moldova, Republic of
$_country_lang["141"] = 'موناكو'; // Monaco
$_country_lang["142"] = 'منغوليا'; // Mongolia
$_country_lang["241"] = 'الجبل الأسود'; //Montenegro
$_country_lang["143"] = 'مونتسيرات'; // Montserrat
$_country_lang["144"] = 'المغرب'; // Morocco
$_country_lang["145"] = 'موزامبيق'; // Mozambique
$_country_lang["146"] = 'ميانمار'; // Myanmar
$_country_lang["147"] = 'ناميبيا'; // Namibia
$_country_lang["148"] = 'ناورو'; // Nauru
$_country_lang["149"] = 'نيبال'; // Nepal
$_country_lang["150"] = 'هولندا'; // Netherlands
$_country_lang["151"] = 'جزر اﻷنتيل الهولندية'; // Netherlands Antilles
$_country_lang["152"] = 'كاليدونيا الجديدة'; // New Caledonia
$_country_lang["153"] = 'نيوزيلندا'; // New Zealand
$_country_lang["154"] = 'نيكاراجوا'; // Nicaragua
$_country_lang["155"] = 'النيجر'; // Niger
$_country_lang["156"] = 'نيجيريا'; // Nigeria
$_country_lang["157"] = 'نيوي'; // Niue
$_country_lang["158"] = 'جزيرة نورفولك'; // Norfolk Island
$_country_lang["159"] = 'جزر ماريانا الشمالية'; // Northern Mariana Islands
$_country_lang["160"] = 'النرويج'; // Norway
$_country_lang["161"] = 'عُمان'; // Oman
$_country_lang["162"] = 'باكستان'; // Pakistan
$_country_lang["163"] = 'باﻻو'; // Palau
$_country_lang["164"] = 'بنما'; // Panama
$_country_lang["165"] = 'بابوا غينيا الجديدة'; // Papua New Guinea
$_country_lang["166"] = 'باراجواي'; // Paraguay
$_country_lang["167"] = 'بيرو'; // Peru
$_country_lang["168"] = 'الفلبين'; // Philippines
$_country_lang["169"] = 'بيتكيرن'; // Pitcairn
$_country_lang["170"] = 'بولندا'; // Poland
$_country_lang["171"] = 'البرتغال'; // Portugal
$_country_lang["172"] = 'بويرتوريكو'; // Puerto Rico
$_country_lang["173"] = 'قطر'; // Qatar
$_country_lang["174"] = 'ريونيون'; // Reunion
$_country_lang["175"] = 'رومانيا'; // Romania
$_country_lang["176"] = 'روسيا الاتحادية'; // Russian Federation
$_country_lang["177"] = 'رواندا'; // Rwanda
$_country_lang["178"] = 'سانت كيتس ونيفيس'; // Saint Kitts and Nevis
$_country_lang["179"] = 'سانت لوسيا'; // Saint Lucia
$_country_lang["180"] = 'سانت فنسنت وجزر غرينادين'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'ساموا'; // Samoa
$_country_lang["182"] = 'سان مارينو'; // San Marino
$_country_lang["183"] = 'ساو تومي وبرينسيبي'; // Sao Tome and Principe
$_country_lang["184"] = 'المملكة العربية السعودية'; // Saudi Arabia
$_country_lang["185"] = 'السنغال'; // Senegal
$_country_lang["240"] = 'صربيا'; //Serbia
$_country_lang["186"] = 'سيشيل'; // Seychelles
$_country_lang["187"] = 'سيراليون'; // Sierra Leone
$_country_lang["188"] = 'سنغافورة'; // Singapore
$_country_lang["189"] = 'سلوفاكيا'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'سلوفينيا'; // Slovenia
$_country_lang["191"] = 'جزر سليمان'; // Solomon Islands
$_country_lang["192"] = 'الصومال'; // Somalia
$_country_lang["193"] = 'جنوب أفريقيا'; // South Africa
$_country_lang["194"] = 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'إسبانيا'; // Spain
$_country_lang["196"] = 'سري لانكا'; // Sri Lanka
$_country_lang["197"] = 'سانت هيلينا'; // St. Helena
$_country_lang["198"] = 'سانت بيير'; // St. Pierre and Miquelon
$_country_lang["199"] = 'السودان'; // Sudan
$_country_lang["200"] = 'سورينام'; // Suriname
$_country_lang["201"] = 'سفالبارد وجان مايان'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'سويسرا'; // Swaziland
$_country_lang["203"] = 'السويد'; // Sweden
$_country_lang["204"] = 'سويسرا'; // Switzerland
$_country_lang["205"] = 'الجمهورية العربية السورية'; // Syrian Arab Republic
$_country_lang["206"] = 'تايوان'; // Taiwan
$_country_lang["207"] = 'طاجيكستان'; // Tajikistan
$_country_lang["208"] = 'جمهورية تنزانيا المتحدة'; // Tanzania, United Republic of
$_country_lang["209"] = 'تايلاند'; // Thailand
$_country_lang["210"] = 'توغو'; // Togo
$_country_lang["211"] = 'توكيلاو'; // Tokelau
$_country_lang["212"] = 'تونغا'; // Tonga
$_country_lang["213"] = 'ترنداد وتوباجو'; // Trinidad and Tobago
$_country_lang["214"] = 'تونس'; // Tunisia
$_country_lang["215"] = 'تركيا'; // Turkey
$_country_lang["216"] = 'تركمانستان'; // Turkmenistan
$_country_lang["217"] = 'جزر تركس وكايكوس'; // Turks and Caicos Islands
$_country_lang["218"] = 'توفالو'; // Tuvalu
$_country_lang["219"] = 'أوغندا'; // Uganda
$_country_lang["220"] = 'أوكرانيا'; // Ukraine
$_country_lang["221"] = 'الإمارات العربية المتحدة'; // United Arab Emirates
$_country_lang["222"] = 'المملكة المتحدة'; // United Kingdom
$_country_lang["223"] = 'الولايات المتحدة الأمريكية'; // United States
$_country_lang["224"] = 'جزر الولايات المتحدة البعيدة الصغرى'; // United States Minor Outlying Islands
$_country_lang["225"] = 'الأورغواي'; // Uruguay
$_country_lang["226"] = 'أوزباكستان'; // Uzbekistan
$_country_lang["227"] = 'فانواتو'; // Vanuatu
$_country_lang["228"] = 'الفاتيكان'; // Vatican City State (Holy See)
$_country_lang["229"] = 'فنزويلا'; // Venezuela
$_country_lang["230"] = 'فيتنام'; // Viet Nam
$_country_lang["231"] = 'جزر العذراء (البريطانية)'; // Virgin Islands (British)
$_country_lang["232"] = 'الجزر العذراء (الولايات المتحدة)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'جزر والس وفوتونا'; // Wallis and Futuna Islands
$_country_lang["234"] = 'الصحاري الغربية'; // Western Sahara
$_country_lang["235"] = 'اليمن'; // Yemen
$_country_lang["236"] = 'صربيا والجبل الأسود'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'جمهورية الكونغو الديمقراطية'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'زامبيا'; // Zambia
$_country_lang["239"] = 'زمبابواي'; // Zimbabwe
?>