<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Афганістан'; // Afghanistan
$_country_lang["2"] = 'Албанія'; // Albania
$_country_lang["3"] = 'Алжыр'; // Algeria
$_country_lang["4"] = 'Амерыканскае Самоа'; // American Samoa
$_country_lang["5"] = 'Андора'; // Andorra
$_country_lang["6"] = 'Ангола'; // Angola
$_country_lang["7"] = 'Ангілья'; // Anguilla
$_country_lang["8"] = 'Антарктыда'; // Antarctica
$_country_lang["9"] = 'Антыгуа і Барбуда'; // Antigua and Barbuda
$_country_lang["10"] = 'Аргенціна'; // Argentina
$_country_lang["11"] = 'Арменія'; // Armenia
$_country_lang["12"] = 'Аруба'; // Aruba
$_country_lang["13"] = 'Аўстралія'; // Australia
$_country_lang["14"] = 'Аўстрыя'; // Austria
$_country_lang["15"] = 'Азербайджан'; // Azerbaijan
$_country_lang["16"] = 'Багамы'; // Bahamas
$_country_lang["17"] = 'Бахрэйн'; // Bahrain
$_country_lang["18"] = 'Бангладэш'; // Bangladesh
$_country_lang["19"] = 'Барбадас'; // Barbados
$_country_lang["20"] = 'Беларусь'; // Belarus
$_country_lang["21"] = 'Бельгія'; // Belgium
$_country_lang["22"] = 'Беліз'; // Belize
$_country_lang["23"] = 'Бенін'; // Benin
$_country_lang["24"] = 'Бярмуды'; // Bermuda
$_country_lang["25"] = 'Бутан'; // Bhutan
$_country_lang["26"] = 'Балівія'; // Bolivia
$_country_lang["27"] = 'Боснія і Герцагавіна'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Батсвана'; // Botswana
$_country_lang["29"] = 'Востраў Буве'; // Bouvet Island
$_country_lang["30"] = 'Бразілія'; // Brazil
$_country_lang["31"] = 'Брытанская тэрыторыя Індыйскага акіяна'; // British Indian Ocean Territory
$_country_lang["32"] = 'Бруней-Даруссалам'; // Brunei Darussalam
$_country_lang["33"] = 'Балгарыя'; // Bulgaria
$_country_lang["34"] = 'Буркіна Фасо'; // Burkina Faso
$_country_lang["35"] = 'Бурундзі'; // Burundi
$_country_lang["36"] = 'Камбоджа'; // Cambodia
$_country_lang["37"] = 'Камерун'; // Cameroon
$_country_lang["38"] = 'Канада'; // Canada
$_country_lang["39"] = 'Каба-Вэрдэ'; // Cape Verde
$_country_lang["40"] = 'Кайманавы астравы'; // Cayman Islands
$_country_lang["41"] = 'ЦАР'; // Central African Republic
$_country_lang["42"] = 'Чад'; // Chad
$_country_lang["43"] = 'Чылі'; // Chile
$_country_lang["44"] = 'Кітай'; // China
$_country_lang["45"] = 'Востраў Раства'; // Christmas Island
$_country_lang["46"] = 'Какосавыя астравы'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Калумбія'; // Colombia
$_country_lang["48"] = 'Каморскія астравы'; // Comoros
$_country_lang["49"] = 'Конга'; // Congo
$_country_lang["50"] = 'Астравы Кука'; // Cook Islands
$_country_lang["51"] = 'Коста-Рыка'; // Costa Rica
$_country_lang["52"] = 'Кот д\\\'Івуар'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Харватыя'; // Croatia
$_country_lang["54"] = 'Куба'; // Cuba
$_country_lang["55"] = 'Кіпр'; // Cyprus
$_country_lang["56"] = 'Чэхія'; // Czech Republic
$_country_lang["57"] = 'Данія'; // Denmark
$_country_lang["58"] = 'Джыбуці'; // Djibouti
$_country_lang["59"] = 'Дамініка'; // Dominica
$_country_lang["60"] = 'Дамініканская Рэспубліка'; // Dominican Republic
$_country_lang["61"] = 'Усходні Тымор'; // East Timor
$_country_lang["62"] = 'Эквадор'; // Ecuador
$_country_lang["63"] = 'Егіпет'; // Egypt
$_country_lang["64"] = 'Сальвадор'; // El Salvador
$_country_lang["65"] = 'Экватарыяльная Гвінея'; // Equatorial Guinea
$_country_lang["66"] = 'Эрытрэя'; // Eritrea
$_country_lang["67"] = 'Эстонія'; // Estonia
$_country_lang["68"] = 'Эфіопія'; // Ethiopia
$_country_lang["69"] = 'Фалклендскія астравы'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Фарэрскія астравы'; // Faroe Islands
$_country_lang["71"] = 'Фіджы'; // Fiji
$_country_lang["72"] = 'Фінляндыя'; // Finland
$_country_lang["73"] = 'Францыя'; // France
$_country_lang["74"] = 'Метраполія Францыі'; // France, Metropolitan
$_country_lang["75"] = 'Французская Гвіяна'; // French Guiana
$_country_lang["76"] = 'Французская Палінезія'; // French Polynesia
$_country_lang["77"] = 'Французскія паўднёвыя тэрыторыі'; // French Southern Territories
$_country_lang["78"] = 'Габон'; // Gabon
$_country_lang["79"] = 'Гамбія'; // Gambia
$_country_lang["80"] = 'Грузія'; // Georgia
$_country_lang["81"] = 'Германія'; // Germany
$_country_lang["82"] = 'Гана'; // Ghana
$_country_lang["83"] = 'Гібралтар'; // Gibraltar
$_country_lang["84"] = 'Грэцыя'; // Greece
$_country_lang["85"] = 'Грэнландыя'; // Greenland
$_country_lang["86"] = 'Грэнада'; // Grenada
$_country_lang["87"] = 'Гвадэлупа'; // Guadeloupe
$_country_lang["88"] = 'Гуам'; // Guam
$_country_lang["89"] = 'Гватэмала'; // Guatemala
$_country_lang["90"] = 'Гвінея'; // Guinea
$_country_lang["91"] = 'Гвінея-Бісаў'; // Guinea-bissau
$_country_lang["92"] = 'Гаяна'; // Guyana
$_country_lang["93"] = 'Гаіці'; // Haiti
$_country_lang["94"] = 'Астравы Херд і Макдональд'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Гандурас'; // Honduras
$_country_lang["96"] = 'Ганконг'; // Hong Kong
$_country_lang["97"] = 'Венгрыя'; // Hungary
$_country_lang["98"] = 'Ісландыя'; // Iceland
$_country_lang["99"] = 'Індыя'; // India
$_country_lang["100"] = 'Інданезія'; // Indonesia
$_country_lang["101"] = 'Іран'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Ірак'; // Iraq
$_country_lang["103"] = 'Ірландыя'; // Ireland
$_country_lang["104"] = 'Ізраіль'; // Israel
$_country_lang["105"] = 'Італія'; // Italy
$_country_lang["106"] = 'Ямайка'; // Jamaica
$_country_lang["107"] = 'Японія'; // Japan
$_country_lang["108"] = 'Іарданія'; // Jordan
$_country_lang["109"] = 'Казахстан'; // Kazakhstan
$_country_lang["110"] = 'Кенія'; // Kenya
$_country_lang["111"] = 'Кірыбаці'; // Kiribati
$_country_lang["112"] = 'КНДР'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Карэя'; // Korea, Republic of
$_country_lang["114"] = 'Кувейт'; // Kuwait
$_country_lang["115"] = 'Кіргізстан'; // Kyrgyzstan
$_country_lang["116"] = 'Лаос'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Латвія'; // Latvia
$_country_lang["118"] = 'Ліван'; // Lebanon
$_country_lang["119"] = 'Лесота'; // Lesotho
$_country_lang["120"] = 'Ліберыя'; // Liberia
$_country_lang["121"] = 'Лівія'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Ліхтэнштэйн'; // Liechtenstein
$_country_lang["123"] = 'Літва'; // Lithuania
$_country_lang["124"] = 'Люксембург'; // Luxembourg
$_country_lang["125"] = 'Макао'; // Macau
$_country_lang["126"] = 'Македонія'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Мадагаскар'; // Madagascar
$_country_lang["128"] = 'Малаві'; // Malawi
$_country_lang["129"] = 'Малайзія'; // Malaysia
$_country_lang["130"] = 'Мальдывы'; // Maldives
$_country_lang["131"] = 'Малі'; // Mali
$_country_lang["132"] = 'Мальта'; // Malta
$_country_lang["133"] = 'Маршалавы астравы'; // Marshall Islands
$_country_lang["134"] = 'Марцініка'; // Martinique
$_country_lang["135"] = 'Маўрытанія'; // Mauritania
$_country_lang["136"] = 'Маўрыкій'; // Mauritius
$_country_lang["137"] = 'Майотта'; // Mayotte
$_country_lang["138"] = 'Мексіка'; // Mexico
$_country_lang["139"] = 'Мікранезія'; // Micronesia, Federated States of
$_country_lang["140"] = 'Малдова'; // Moldova, Republic of
$_country_lang["141"] = 'Манака'; // Monaco
$_country_lang["142"] = 'Манголія'; // Mongolia
$_country_lang["241"] = 'Чарнагорыя'; //Montenegro
$_country_lang["143"] = 'Монтсеррат'; // Montserrat
$_country_lang["144"] = 'Марока'; // Morocco
$_country_lang["145"] = 'Мазамбік'; // Mozambique
$_country_lang["146"] = 'М\\\'янма'; // Myanmar
$_country_lang["147"] = 'Намібія'; // Namibia
$_country_lang["148"] = 'Науру'; // Nauru
$_country_lang["149"] = 'Непал'; // Nepal
$_country_lang["150"] = 'Нідэрланды'; // Netherlands
$_country_lang["151"] = 'Нідэрландскія Антыльскія астравы'; // Netherlands Antilles
$_country_lang["152"] = 'Новая Каледонія'; // New Caledonia
$_country_lang["153"] = 'Новая Зеландыя'; // New Zealand
$_country_lang["154"] = 'Нікарагуа'; // Nicaragua
$_country_lang["155"] = 'Нігер'; // Niger
$_country_lang["156"] = 'Нігерыя'; // Nigeria
$_country_lang["157"] = 'Ніуе'; // Niue
$_country_lang["158"] = 'Востраў Норфолк'; // Norfolk Island
$_country_lang["159"] = 'Паўночныя Марыянскія астравы'; // Northern Mariana Islands
$_country_lang["160"] = 'Нарвегія'; // Norway
$_country_lang["161"] = 'Аман'; // Oman
$_country_lang["162"] = 'Пакістан'; // Pakistan
$_country_lang["163"] = 'Палаў'; // Palau
$_country_lang["164"] = 'Панама'; // Panama
$_country_lang["165"] = 'Папуа-Новая Гвінея'; // Papua New Guinea
$_country_lang["166"] = 'Парагвай'; // Paraguay
$_country_lang["167"] = 'Перу'; // Peru
$_country_lang["168"] = 'Філіпіны'; // Philippines
$_country_lang["169"] = 'Піткэрн'; // Pitcairn
$_country_lang["170"] = 'Польшча'; // Poland
$_country_lang["171"] = 'Партугалія'; // Portugal
$_country_lang["172"] = 'Пуэрта-Рыка'; // Puerto Rico
$_country_lang["173"] = 'Катар'; // Qatar
$_country_lang["174"] = 'Рэюньён'; // Reunion
$_country_lang["175"] = 'Румынія'; // Romania
$_country_lang["176"] = 'Расія'; // Russian Federation
$_country_lang["177"] = 'Руанда'; // Rwanda
$_country_lang["178"] = 'Сэнт-Кітс і Нэвіс'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Сэнт-Люсія'; // Saint Lucia
$_country_lang["180"] = 'Сэнт-Вінсэнт і Грэнадыны'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Самоа'; // Samoa
$_country_lang["182"] = 'Сан-Марына'; // San Marino
$_country_lang["183"] = 'Сан-Томе і Прынсэп'; // Sao Tome and Principe
$_country_lang["184"] = 'Саудаўская Аравія'; // Saudi Arabia
$_country_lang["185"] = 'Сенегал'; // Senegal
$_country_lang["240"] = 'Сербія'; //Serbia
$_country_lang["186"] = 'Сейшэльскія астравы'; // Seychelles
$_country_lang["187"] = 'Сьера-Леонэ'; // Sierra Leone
$_country_lang["188"] = 'Сінгапур'; // Singapore
$_country_lang["189"] = 'Славакія'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Славенія'; // Slovenia
$_country_lang["191"] = 'Саламонавы астравы'; // Solomon Islands
$_country_lang["192"] = 'Самалі'; // Somalia
$_country_lang["193"] = 'ПАР'; // South Africa
$_country_lang["194"] = 'Паўднёвая Джорджыя і Паўднёвыя Сандвічавы астравы'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Іспанія'; // Spain
$_country_lang["196"] = 'Шры-Ланка'; // Sri Lanka
$_country_lang["197"] = 'Востраў Святой Алены'; // St. Helena
$_country_lang["198"] = 'Сен-П\\\'ер і Міквэлон'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Судан'; // Sudan
$_country_lang["200"] = 'Сурынам'; // Suriname
$_country_lang["201"] = 'Шпіцбэрген і Ян-Майен'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Свазіленд'; // Swaziland
$_country_lang["203"] = 'Швецыя'; // Sweden
$_country_lang["204"] = 'Швейцарыя'; // Switzerland
$_country_lang["205"] = 'Сірыя'; // Syrian Arab Republic
$_country_lang["206"] = 'Тайвань'; // Taiwan
$_country_lang["207"] = 'Таджыкістан'; // Tajikistan
$_country_lang["208"] = 'Танзанія'; // Tanzania, United Republic of
$_country_lang["209"] = 'Тайланд'; // Thailand
$_country_lang["210"] = 'Таго'; // Togo
$_country_lang["211"] = 'Такелаў'; // Tokelau
$_country_lang["212"] = 'Тонга'; // Tonga
$_country_lang["213"] = 'Трынідад і Табага'; // Trinidad and Tobago
$_country_lang["214"] = 'Туніс'; // Tunisia
$_country_lang["215"] = 'Турцыя'; // Turkey
$_country_lang["216"] = 'Туркменістан'; // Turkmenistan
$_country_lang["217"] = 'Астравы Тэркс і Кайкас'; // Turks and Caicos Islands
$_country_lang["218"] = 'Тувалу'; // Tuvalu
$_country_lang["219"] = 'Уганда'; // Uganda
$_country_lang["220"] = 'Украіна'; // Ukraine
$_country_lang["221"] = 'ААЭ'; // United Arab Emirates
$_country_lang["222"] = 'Вялікабрытанія'; // United Kingdom
$_country_lang["223"] = 'ЗША'; // United States
$_country_lang["224"] = 'Знешнія малыя астравы (ЗША)'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Уругвай'; // Uruguay
$_country_lang["226"] = 'Узбекістан'; // Uzbekistan
$_country_lang["227"] = 'Вануату'; // Vanuatu
$_country_lang["228"] = 'Ватыкан'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Венесуэла'; // Venezuela
$_country_lang["230"] = 'В\\\'етнам'; // Viet Nam
$_country_lang["231"] = 'Віргінскія астравы (Брытанскія)'; // Virgin Islands (British)
$_country_lang["232"] = 'Віргінскія астравы (ЗША)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Астравы Уоліс і Футуна'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Заходняя Сахара'; // Western Sahara
$_country_lang["235"] = 'Емен'; // Yemen
$_country_lang["236"] = 'Сербія і Чарнагорыя'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Конга'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Замбія'; // Zambia
$_country_lang["239"] = 'Зімбабвэ'; // Zimbabwe
?>