<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afghánistán'; // Afghanistan
$_country_lang["2"] = 'Albánie'; // Albania
$_country_lang["3"] = 'Alžírsko'; // Algeria
$_country_lang["4"] = 'Americká Samoa'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antarktida'; // Antarctica
$_country_lang["9"] = 'Antigua a Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentina'; // Argentina
$_country_lang["11"] = 'Arménie'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Austrálie'; // Australia
$_country_lang["14"] = 'Rakousko'; // Austria
$_country_lang["15"] = 'Ázerbájdžán'; // Azerbaijan
$_country_lang["16"] = 'Bahamy'; // Bahamas
$_country_lang["17"] = 'Bahrajn'; // Bahrain
$_country_lang["18"] = 'Bangladéš'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Bělorusko'; // Belarus
$_country_lang["21"] = 'Belgie'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermudy'; // Bermuda
$_country_lang["25"] = 'Bhútán'; // Bhutan
$_country_lang["26"] = 'Bolívie'; // Bolivia
$_country_lang["27"] = 'Bosna a Hercegovina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Bouvetův ostrov'; // Bouvet Island
$_country_lang["30"] = 'Brazílie'; // Brazil
$_country_lang["31"] = 'Britské indickooceánské území'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunej'; // Brunei Darussalam
$_country_lang["33"] = 'Bulharsko'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Kambodža'; // Cambodia
$_country_lang["37"] = 'Kamerun'; // Cameroon
$_country_lang["38"] = 'Kanada'; // Canada
$_country_lang["39"] = 'Kapverdy'; // Cape Verde
$_country_lang["40"] = 'Kajmanské ostrovy'; // Cayman Islands
$_country_lang["41"] = 'Středoafrická republika'; // Central African Republic
$_country_lang["42"] = 'Čad'; // Chad
$_country_lang["43"] = 'Chile'; // Chile
$_country_lang["44"] = 'Čína'; // China
$_country_lang["45"] = 'Vánoční ostrov'; // Christmas Island
$_country_lang["46"] = 'Kokosové (Keelingovy) ostrovy'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Kolumbie'; // Colombia
$_country_lang["48"] = 'Komory'; // Comoros
$_country_lang["49"] = 'Kongo (Brazzaville) '; // Congo
$_country_lang["50"] = 'Cookovy ostrovy'; // Cook Islands
$_country_lang["51"] = 'Kostarika'; // Costa Rica
$_country_lang["52"] = 'Pobřeží slonoviny'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Chorvatsko'; // Croatia
$_country_lang["54"] = 'Kuba'; // Cuba
$_country_lang["55"] = 'Kypr'; // Cyprus
$_country_lang["56"] = 'Česká republika'; // Czech Republic
$_country_lang["57"] = 'Dánsko'; // Denmark
$_country_lang["58"] = 'Džibuti'; // Djibouti
$_country_lang["59"] = 'Dominika'; // Dominica
$_country_lang["60"] = 'Dominikánská republika'; // Dominican Republic
$_country_lang["61"] = 'Východní Timor'; // East Timor
$_country_lang["62"] = 'Ekvádor'; // Ecuador
$_country_lang["63"] = 'Egypt'; // Egypt
$_country_lang["64"] = 'Salvador'; // El Salvador
$_country_lang["65"] = 'Rovníková Guinea'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Estonsko'; // Estonia
$_country_lang["68"] = 'Etiopie'; // Ethiopia
$_country_lang["69"] = 'Falklandské ostrovy (Malvíny)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Faerské ostrovy'; // Faroe Islands
$_country_lang["71"] = 'Fidži'; // Fiji
$_country_lang["72"] = 'Finsko'; // Finland
$_country_lang["73"] = 'Francie'; // France
$_country_lang["74"] = 'Metropolitní Francie'; // France, Metropolitan
$_country_lang["75"] = 'Francouzská Guyana'; // French Guiana
$_country_lang["76"] = 'Francouzská Polynésie'; // French Polynesia
$_country_lang["77"] = 'Francouzská jižní území'; // French Southern Territories
$_country_lang["78"] = 'Gabonu'; // Gabon
$_country_lang["79"] = 'Gambie'; // Gambia
$_country_lang["80"] = 'Gruzie'; // Georgia
$_country_lang["81"] = 'Německo'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Řecko'; // Greece
$_country_lang["85"] = 'Grónsko'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Guinea-Bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Heardův ostrov a McDonaldovy ostrovy'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Maďarsko'; // Hungary
$_country_lang["98"] = 'Island'; // Iceland
$_country_lang["99"] = 'Indie'; // India
$_country_lang["100"] = 'Indonésie'; // Indonesia
$_country_lang["101"] = 'Írán'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irák'; // Iraq
$_country_lang["103"] = 'Irsko'; // Ireland
$_country_lang["104"] = 'Izrael'; // Israel
$_country_lang["105"] = 'Itálie'; // Italy
$_country_lang["106"] = 'Jamajka'; // Jamaica
$_country_lang["107"] = 'Japonsko'; // Japan
$_country_lang["108"] = 'Jordánsko'; // Jordan
$_country_lang["109"] = 'Kazachstán'; // Kazakhstan
$_country_lang["110"] = 'Keňa'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Severní Korea (KLDR)'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Korea'; // Korea, Republic of
$_country_lang["114"] = 'Kuvajt'; // Kuwait
$_country_lang["115"] = 'Kyrgyzstán'; // Kyrgyzstan
$_country_lang["116"] = 'Laos'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Lotyšsko'; // Latvia
$_country_lang["118"] = 'Libanonu'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Libérie'; // Liberia
$_country_lang["121"] = 'Libyjská arabská džamáhírije'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Lichtenštejnsko'; // Liechtenstein
$_country_lang["123"] = 'Litva'; // Lithuania
$_country_lang["124"] = 'Lucembursko'; // Luxembourg
$_country_lang["125"] = 'Macao'; // Macau
$_country_lang["126"] = 'Makedonie'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaskar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malajsie'; // Malaysia
$_country_lang["130"] = 'Maledivy'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Marshallovy ostrovy'; // Marshall Islands
$_country_lang["134"] = 'Martinik'; // Martinique
$_country_lang["135"] = 'Mauritánie'; // Mauritania
$_country_lang["136"] = 'Mauricius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Mexiko'; // Mexico
$_country_lang["139"] = 'Mikronésie'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldavská republika'; // Moldova, Republic of
$_country_lang["141"] = 'Monako'; // Monaco
$_country_lang["142"] = 'Mongolsko'; // Mongolia
$_country_lang["241"] = 'Černá Hora'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Maroko'; // Morocco
$_country_lang["145"] = 'Mosambik'; // Mozambique
$_country_lang["146"] = 'Myanmar'; // Myanmar
$_country_lang["147"] = 'Namibie'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepál'; // Nepal
$_country_lang["150"] = 'Nizozemí'; // Netherlands
$_country_lang["151"] = 'Nizozemské Antily'; // Netherlands Antilles
$_country_lang["152"] = 'Nová Kaledonie'; // New Caledonia
$_country_lang["153"] = 'Nový Zéland'; // New Zealand
$_country_lang["154"] = 'Nikaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigérie'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolk'; // Norfolk Island
$_country_lang["159"] = 'Severní Mariany'; // Northern Mariana Islands
$_country_lang["160"] = 'Norsko'; // Norway
$_country_lang["161"] = 'Omán'; // Oman
$_country_lang["162"] = 'Pákistán'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papua-Nová Guinea'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Peru'; // Peru
$_country_lang["168"] = 'Filipíny'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Polsko'; // Poland
$_country_lang["171"] = 'Portugalsko'; // Portugal
$_country_lang["172"] = 'Portoriko'; // Puerto Rico
$_country_lang["173"] = 'Katar'; // Qatar
$_country_lang["174"] = 'Réunion'; // Reunion
$_country_lang["175"] = 'Rumunsko'; // Romania
$_country_lang["176"] = 'Rusko'; // Russian Federation
$_country_lang["177"] = 'Rwanda'; // Rwanda
$_country_lang["178"] = 'Svatý Kryštof a Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Svatá Lucie'; // Saint Lucia
$_country_lang["180"] = 'Svatý Vincent a Grenadiny'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'Svatý Tomáš a Princův ostrov'; // Sao Tome and Principe
$_country_lang["184"] = 'Saúdská Arábie'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'Srbsko'; //Serbia
$_country_lang["186"] = 'Seychely'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapur'; // Singapore
$_country_lang["189"] = 'Slovensko'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Slovinsko'; // Slovenia
$_country_lang["191"] = 'Šalamounovy ostrovy'; // Solomon Islands
$_country_lang["192"] = 'Somálsko'; // Somalia
$_country_lang["193"] = 'Jižní Afrika'; // South Africa
$_country_lang["194"] = 'Jižní Georgie a Jižní Sandwichovy ostrovy'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Španělsko'; // Spain
$_country_lang["196"] = 'Srí Lanka'; // Sri Lanka
$_country_lang["197"] = 'Svatá Helena'; // St. Helena
$_country_lang["198"] = 'Saint-Pierre a Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Súdán'; // Sudan
$_country_lang["200"] = 'Surinam'; // Suriname
$_country_lang["201"] = 'Svalbard a ostrovy Jan Mayen'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Svazijsko'; // Swaziland
$_country_lang["203"] = 'Švédsko'; // Sweden
$_country_lang["204"] = 'Švýcarsko'; // Switzerland
$_country_lang["205"] = 'Sjednocená arabská republika'; // Syrian Arab Republic
$_country_lang["206"] = 'Tchaj-wan'; // Taiwan
$_country_lang["207"] = 'Tádžikistán'; // Tajikistan
$_country_lang["208"] = 'Tanzánie'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thajsko'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad a Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunisko'; // Tunisia
$_country_lang["215"] = 'Turecko'; // Turkey
$_country_lang["216"] = 'Turkmenistán'; // Turkmenistan
$_country_lang["217"] = 'Turks a Caicos'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukrajina'; // Ukraine
$_country_lang["221"] = 'Spojené arabské emiráty'; // United Arab Emirates
$_country_lang["222"] = 'Spojené království'; // United Kingdom
$_country_lang["223"] = 'USA'; // United States
$_country_lang["224"] = 'Menší odlehlé ostrovy USA'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Uzbekistán'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vatikán'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Vietnam'; // Viet Nam
$_country_lang["231"] = 'Panenské ostrovy (Britské)'; // Virgin Islands (British)
$_country_lang["232"] = 'Panenské ostrovy (USA)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis a Futuna ostrovy'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Západní Sahara'; // Western Sahara
$_country_lang["235"] = 'Jemen'; // Yemen
$_country_lang["236"] = 'Srbsko a Černá Hora'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Konžská demokratická republika'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambie'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>