<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afghanistan'; // Afghanistan
$_country_lang["2"] = 'Albanien'; // Albania
$_country_lang["3"] = 'Algeriet'; // Algeria
$_country_lang["4"] = 'Amerikanske Samoa'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antarktis'; // Antarctica
$_country_lang["9"] = 'Antigua og Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentina'; // Argentina
$_country_lang["11"] = 'Armenien'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Australien'; // Australia
$_country_lang["14"] = 'Østrig'; // Austria
$_country_lang["15"] = 'Azerbajdzjan'; // Azerbaijan
$_country_lang["16"] = 'Bahamas'; // Bahamas
$_country_lang["17"] = 'Bahrain'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Hviderusland'; // Belarus
$_country_lang["21"] = 'Belgien'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Bhutan'; // Bhutan
$_country_lang["26"] = 'Bolivia'; // Bolivia
$_country_lang["27"] = 'Bosnien-Hercegovina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Bouvet øen'; // Bouvet Island
$_country_lang["30"] = 'Brasilien'; // Brazil
$_country_lang["31"] = 'Britiske territorie i Indiske Ocean'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgarien'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Cambodia'; // Cambodia
$_country_lang["37"] = 'Cameroon'; // Cameroon
$_country_lang["38"] = 'Canada'; // Canada
$_country_lang["39"] = 'Cap Verde'; // Cape Verde
$_country_lang["40"] = 'Caymanøerne'; // Cayman Islands
$_country_lang["41"] = 'Centralafrikanske republik'; // Central African Republic
$_country_lang["42"] = 'Chad'; // Chad
$_country_lang["43"] = 'Chile'; // Chile
$_country_lang["44"] = 'Kina'; // China
$_country_lang["45"] = 'Jule øen'; // Christmas Island
$_country_lang["46"] = 'Cocos øerne'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Colombia'; // Colombia
$_country_lang["48"] = 'Comoros'; // Comoros
$_country_lang["49"] = 'Congo, Republiken'; // Congo, Republic of the
$_country_lang["50"] = 'Cook øerne'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Elfenbenskysten'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Kroatien'; // Croatia
$_country_lang["54"] = 'Cuba'; // Cuba
$_country_lang["55"] = 'Cypern'; // Cyprus
$_country_lang["56"] = 'Tjekkiet'; // Czech Republic
$_country_lang["57"] = 'Danmark'; // Denmark
$_country_lang["58"] = 'Djibouti'; // Djibouti
$_country_lang["59"] = 'Dominica'; // Dominica
$_country_lang["60"] = 'Dominikanske republik'; // Dominican Republic
$_country_lang["61"] = 'Østtimor'; // East Timor
$_country_lang["62"] = 'Ecuador'; // Ecuador
$_country_lang["63"] = 'Egypten'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Ækvatorialguinea'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Estland'; // Estonia
$_country_lang["68"] = 'Etiopien'; // Ethiopia
$_country_lang["69"] = 'Falklandsøerne'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Færøerne'; // Faroe Islands
$_country_lang["71"] = 'Fiji'; // Fiji
$_country_lang["72"] = 'Finland'; // Finland
$_country_lang["73"] = 'Frankrig'; // France
$_country_lang["74"] = 'France, Metropolitan'; // France, Metropolitan
$_country_lang["75"] = 'Franske Guyana'; // French Guiana
$_country_lang["76"] = 'Franske Polynesien'; // French Polynesia
$_country_lang["77"] = 'French Southern Territories'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Georgien'; // Georgia
$_country_lang["81"] = 'Tyskland'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Grækenland'; // Greece
$_country_lang["85"] = 'Grønland'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Guinea-Bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Heardøen og McDonaldsøerne'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Ungarn'; // Hungary
$_country_lang["98"] = 'Island'; // Iceland
$_country_lang["99"] = 'Indien'; // India
$_country_lang["100"] = 'Indonesien'; // Indonesia
$_country_lang["101"] = 'Iran'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irak'; // Iraq
$_country_lang["103"] = 'Irland'; // Ireland
$_country_lang["104"] = 'Israel'; // Israel
$_country_lang["105"] = 'Italien'; // Italy
$_country_lang["106"] = 'Jamaica'; // Jamaica
$_country_lang["107"] = 'Japan'; // Japan
$_country_lang["108"] = 'Jordan'; // Jordan
$_country_lang["109"] = 'Kazakhstan'; // Kazakhstan
$_country_lang["110"] = 'Kenya'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Nordkorea'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Sydkorea'; // Korea, Republic of
$_country_lang["114"] = 'Kuwait'; // Kuwait
$_country_lang["115"] = 'Kirgistan'; // Kyrgyzstan
$_country_lang["116"] = 'Laos'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Letland'; // Latvia
$_country_lang["118"] = 'Libanon'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Liberia'; // Liberia
$_country_lang["121"] = 'Libyen'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Litauen'; // Lithuania
$_country_lang["124"] = 'Luxembourg'; // Luxembourg
$_country_lang["125"] = 'Macau'; // Macau
$_country_lang["126"] = 'Makedonien'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaskar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malaysia'; // Malaysia
$_country_lang["130"] = 'Maldiverne'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Marshalløerne'; // Marshall Islands
$_country_lang["134"] = 'Martinique'; // Martinique
$_country_lang["135"] = 'Mauretanien'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Mexico'; // Mexico
$_country_lang["139"] = 'Micronesien'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldavien'; // Moldova, Republic of
$_country_lang["141"] = 'Monaco'; // Monaco
$_country_lang["142"] = 'Mongoliet'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Marocco'; // Morocco
$_country_lang["145"] = 'Mocambique'; // Mozambique
$_country_lang["146"] = 'Myanmar'; // Myanmar
$_country_lang["147"] = 'Namibia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Holland'; // Netherlands
$_country_lang["151"] = 'Nederlandske Antillerne'; // Netherlands Antilles
$_country_lang["152"] = 'Ny Caledonien'; // New Caledonia
$_country_lang["153"] = 'New Zeeland'; // New Zealand
$_country_lang["154"] = 'Nicaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolk Island'; // Norfolk Island
$_country_lang["159"] = 'Nord mariana øerne'; // Northern Mariana Islands
$_country_lang["160"] = 'Norge'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papua Ny Guinea'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Peru'; // Peru
$_country_lang["168"] = 'Filippinerne'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Polen'; // Poland
$_country_lang["171"] = 'Portugal'; // Portugal
$_country_lang["172"] = 'Puerto Rico'; // Puerto Rico
$_country_lang["173"] = 'Qatar'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Rumænien'; // Romania
$_country_lang["176"] = 'Rusiske federation'; // Russian Federation
$_country_lang["177"] = 'Rwanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts og Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Saint Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent og Grenadinerne'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'Sao Tome og Principe'; // Sao Tome and Principe
$_country_lang["184"] = 'Saudiarabien'; // Saudi Arabia
$_country_lang["240"] = 'Serbien'; //Serbia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["186"] = 'Seychellerne'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapore'; // Singapore
$_country_lang["189"] = 'Slovakien'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Slovenien'; // Slovenia
$_country_lang["191"] = 'Salomonøerne'; // Solomon Islands
$_country_lang["192"] = 'Somalia'; // Somalia
$_country_lang["193"] = 'Sydafrika'; // South Africa
$_country_lang["194"] = 'Sydgeorgia og Syd sandwich øerne'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Spanien'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'Sankt Helena'; // St. Helena
$_country_lang["198"] = 'Saint-Pierre og Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sudan'; // Sudan
$_country_lang["200"] = 'Surinam'; // Suriname
$_country_lang["201"] = 'Svalbard og Jan Mayen øerne'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Swaziland'; // Swaziland
$_country_lang["203"] = 'Sverige'; // Sweden
$_country_lang["204"] = 'Schweiz'; // Switzerland
$_country_lang["205"] = 'Syrien'; // Syrian Arab Republic
$_country_lang["206"] = 'Taiwan'; // Taiwan
$_country_lang["207"] = 'Tajikistan'; // Tajikistan
$_country_lang["208"] = 'Tanzania'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thailand'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad og Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunesien'; // Tunisia
$_country_lang["215"] = 'Tyrkiet'; // Turkey
$_country_lang["216"] = 'Turkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Turks- og Caicos øerne'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukraine'; // Ukraine
$_country_lang["221"] = 'De Forenede arabiske emirater'; // United Arab Emirates
$_country_lang["222"] = 'England'; // United Kingdom
$_country_lang["223"] = 'USA'; // United States
$_country_lang["224"] = 'United States Minor Outlying Islands'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Uzbekistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vatikanstaten'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Vietnam'; // Viet Nam
$_country_lang["231"] = 'Britiske Jomfruøerne'; // Virgin Islands (British)
$_country_lang["232"] = 'Amerikanske Jomfruøerne'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis- og Futunaøerne'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Vestsahara'; // Western Sahara
$_country_lang["235"] = 'Yemen'; // Yemen
$_country_lang["236"] = 'Serbien og Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Demokratiske Congo'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe

?>