<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afganistan'; // Afghanistan
$_country_lang["2"] = 'Albaania'; // Albania
$_country_lang["3"] = 'Alžeeria'; // Algeria
$_country_lang["4"] = 'Ameerika Samoa'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antartika'; // Antarctica
$_country_lang["9"] = 'Antigua ja Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentina'; // Argentina
$_country_lang["11"] = 'Armeenia'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Austraalia'; // Australia
$_country_lang["14"] = 'Austria'; // Austria
$_country_lang["15"] = 'Aserbaidžaan'; // Azerbaijan
$_country_lang["16"] = 'Bahama'; // Bahamas
$_country_lang["17"] = 'Bahrein'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Valgevene'; // Belarus
$_country_lang["21"] = 'Belgia'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Bhutan'; // Bhutan
$_country_lang["26"] = 'Boliivia'; // Bolivia
$_country_lang["27"] = 'Bosnia ja Hertsegoviina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Bouvet saar'; // Bouvet Island
$_country_lang["30"] = 'Brasiilia'; // Brazil
$_country_lang["31"] = 'Briti India ookeani ala'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgaaria'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Kambodža'; // Cambodia
$_country_lang["37"] = 'Kamerun'; // Cameroon
$_country_lang["38"] = 'Kanada'; // Canada
$_country_lang["39"] = 'Roheneemesaared'; // Cape Verde
$_country_lang["40"] = 'Kaimanisaared'; // Cayman Islands
$_country_lang["41"] = 'Kesk-Aafrika Vabariik'; // Central African Republic
$_country_lang["42"] = 'Tšaad'; // Chad
$_country_lang["43"] = 'Tšiili'; // Chile
$_country_lang["44"] = 'Hiina'; // China
$_country_lang["45"] = 'Jõulusaar'; // Christmas Island
$_country_lang["46"] = 'Kookossaared'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Kolumbia'; // Colombia
$_country_lang["48"] = 'Komoorid'; // Comoros
$_country_lang["49"] = 'Kongo Vabariik'; // Congo
$_country_lang["50"] = 'Cooki saared'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Elevandiluurannik'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Horvaatia'; // Croatia
$_country_lang["54"] = 'Kuuba'; // Cuba
$_country_lang["55"] = 'Küpros'; // Cyprus
$_country_lang["56"] = 'Tšehhi'; // Czech Republic
$_country_lang["57"] = 'Taani'; // Denmark
$_country_lang["58"] = 'Djibouti'; // Djibouti
$_country_lang["59"] = 'Dominikaani'; // Dominica
$_country_lang["60"] = 'Dominikaani Vabariik'; // Dominican Republic
$_country_lang["61"] = 'Ida-Timor'; // East Timor
$_country_lang["62"] = 'Ecuador'; // Ecuador
$_country_lang["63"] = 'Egiptus'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Ekvatoriaal-Guinea'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Eesti'; // Estonia
$_country_lang["68"] = 'Etioopia'; // Ethiopia
$_country_lang["69"] = 'Falklandi (Malviini) saared'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Fääri saared'; // Faroe Islands
$_country_lang["71"] = 'Fidži'; // Fiji
$_country_lang["72"] = 'Soome'; // Finland
$_country_lang["73"] = 'Prantsusmaa'; // France
$_country_lang["74"] = 'Prantsusmaa, Metropolitan'; // France, Metropolitan
$_country_lang["75"] = 'Prantsuse Guajaana'; // French Guiana
$_country_lang["76"] = 'Prantsuse Polüneesia'; // French Polynesia
$_country_lang["77"] = 'Prantsuse Lõunaalad'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Gruusia'; // Georgia
$_country_lang["81"] = 'Saksamaa'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Kreeka'; // Greece
$_country_lang["85"] = 'Gröönimaa'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Guinea-bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Heard ja McDonald'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Ungari'; // Hungary
$_country_lang["98"] = 'Island'; // Iceland
$_country_lang["99"] = 'India'; // India
$_country_lang["100"] = 'Indoneesia'; // Indonesia
$_country_lang["101"] = 'Iraan (Iraani Islamivabariik)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Iraak'; // Iraq
$_country_lang["103"] = 'Iirimaa'; // Ireland
$_country_lang["104"] = 'Iisrael'; // Israel
$_country_lang["105"] = 'Itaalia'; // Italy
$_country_lang["106"] = 'Jamaica'; // Jamaica
$_country_lang["107"] = 'Jaapan'; // Japan
$_country_lang["108"] = 'Jordaania'; // Jordan
$_country_lang["109"] = 'Kasahstan'; // Kazakhstan
$_country_lang["110"] = 'Keenia'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Põhja-Korea, Korea Rahvademokraatlik Vabarii'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Lõuna-Korea, Korea Vabariik'; // Korea, Republic of
$_country_lang["114"] = 'Kuveit'; // Kuwait
$_country_lang["115"] = 'Kõrgõzstan'; // Kyrgyzstan
$_country_lang["116"] = 'Laose Demokraatlik Rahvavabariik'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Läti'; // Latvia
$_country_lang["118"] = 'Liibanon'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Libeeria'; // Liberia
$_country_lang["121"] = 'Liibüa Araabia Sotsialistlik Rahvadžamahirija'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Leedu'; // Lithuania
$_country_lang["124"] = 'Luksemburg'; // Luxembourg
$_country_lang["125"] = 'Macau'; // Macau
$_country_lang["126"] = 'Makedoonia Vabariik'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaskar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malaisia'; // Malaysia
$_country_lang["130"] = 'Maldiivid'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Marshalli Saared'; // Marshall Islands
$_country_lang["134"] = 'Martinique'; // Martinique
$_country_lang["135"] = 'Mauritaania'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Mehhiko'; // Mexico
$_country_lang["139"] = 'Mikroneesia Liiduriigid'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldova Vabariik'; // Moldova, Republic of
$_country_lang["141"] = 'Monaco'; // Monaco
$_country_lang["142"] = 'Mongoolia'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Maroko'; // Morocco
$_country_lang["145"] = 'Mosambiik'; // Mozambique
$_country_lang["146"] = 'Birma'; // Myanmar
$_country_lang["147"] = 'Namiibia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Holland'; // Netherlands
$_country_lang["151"] = 'Hollandi Antillid'; // Netherlands Antilles
$_country_lang["152"] = 'Uus-Kaledoonia'; // New Caledonia
$_country_lang["153"] = 'Uus-Meremaa'; // New Zealand
$_country_lang["154"] = 'Nicaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolki saare ala'; // Norfolk Island
$_country_lang["159"] = 'Põhja-Mariaani Ühendus'; // Northern Mariana Islands
$_country_lang["160"] = 'Norra'; // Norway
$_country_lang["161"] = 'Omaan'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'Belau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Paapua Uus-Guinea'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Peruu'; // Peru
$_country_lang["168"] = 'Filipiinid'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Poola'; // Poland
$_country_lang["171"] = 'Portugal'; // Portugal
$_country_lang["172"] = 'Puerto Rico'; // Puerto Rico
$_country_lang["173"] = 'Katar'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Rumeenia'; // Romania
$_country_lang["176"] = 'Venemaa Föderatsioon'; // Russian Federation
$_country_lang["177"] = 'Rwanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts ja Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Saint Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent ja Grenadiinid'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'São Tomé ja Príncipe'; // Sao Tome and Principe
$_country_lang["184"] = 'Saudi Araabia'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'Serbia'; //Serbia
$_country_lang["186"] = 'Seišellid'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapur'; // Singapore
$_country_lang["189"] = 'Slovaki Vabariik'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Sloveenia'; // Slovenia
$_country_lang["191"] = 'Saalomoni Saared'; // Solomon Islands
$_country_lang["192"] = 'Somaalia'; // Somalia
$_country_lang["193"] = 'Lõuna-Aafrika Vabariik'; // South Africa
$_country_lang["194"] = 'South Georgia and the South Sandwich Islands'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Hispaania'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'Saint Helena'; // St. Helena
$_country_lang["198"] = 'Saint-Pierre ja Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sudaan'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Svalbard ja Jan Mayeni Saared'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Svaasimaa'; // Swaziland
$_country_lang["203"] = 'Rootsi'; // Sweden
$_country_lang["204"] = 'Šveits'; // Switzerland
$_country_lang["205"] = 'Süüria Araabia Vabariik'; // Syrian Arab Republic
$_country_lang["206"] = 'Taiwan'; // Taiwan
$_country_lang["207"] = 'Tadžikistan'; // Tajikistan
$_country_lang["208"] = 'Tansaania Ühendvabariik'; // Tanzania, United Republic of
$_country_lang["209"] = 'Tai'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad ja Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tuneesia'; // Tunisia
$_country_lang["215"] = 'Türgi'; // Turkey
$_country_lang["216"] = 'Türkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Turks ja Caico'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukraina'; // Ukraine
$_country_lang["221"] = 'Araabia Ühendemiraadid'; // United Arab Emirates
$_country_lang["222"] = 'Suurbritannia'; // United Kingdom
$_country_lang["223"] = 'Ameerika Ühendriigid'; // United States
$_country_lang["224"] = 'Ühendriikide väikesed hajasaared'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Usbekistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vatikani Linnriik'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Vietnam'; // Viet Nam
$_country_lang["231"] = 'Briti Neitsisaared'; // Virgin Islands (British)
$_country_lang["232"] = 'Neitsisaared, USA'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis ja Futuna'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Lääne-Sahar'; // Western Sahara
$_country_lang["235"] = 'Jeemen'; // Yemen
$_country_lang["236"] = 'Serbia ja Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Kongo Demokraatlik Vabariik'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Sambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>
