<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'افغانستان'; // Afghanistan
$_country_lang["2"] = 'آلبانی'; // Albania
$_country_lang["3"] = 'الجزایر'; // Algeria
$_country_lang["4"] = 'ساموآی آمریکا'; // American Samoa
$_country_lang["5"] = 'آندورا'; // Andorra
$_country_lang["6"] = 'آنگولا'; // Angola
$_country_lang["7"] = 'آنگوییلا'; // Anguilla
$_country_lang["8"] = 'جنوبگان'; // Antarctica
$_country_lang["9"] = 'آنتیگوا و باربودا'; // Antigua and Barbuda
$_country_lang["10"] = 'آرژانتین'; // Argentina
$_country_lang["11"] = 'ارمنستان'; // Armenia
$_country_lang["12"] = 'آروبا'; // Aruba
$_country_lang["13"] = 'استرالیا'; // Australia
$_country_lang["14"] = 'اتریش'; // Austria
$_country_lang["15"] = 'آذربایجان'; // Azerbaijan
$_country_lang["16"] = 'باهاما'; // Bahamas
$_country_lang["17"] = 'بحرین'; // Bahrain
$_country_lang["18"] = 'بنگلادش'; // Bangladesh
$_country_lang["19"] = 'باربادوس'; // Barbados
$_country_lang["20"] = 'بلاروس'; // Belarus
$_country_lang["21"] = 'بلژیک'; // Belgium
$_country_lang["22"] = 'بلیز'; // Belize
$_country_lang["23"] = 'بنین'; // Benin
$_country_lang["24"] = 'برمودا'; // Bermuda
$_country_lang["25"] = 'بوتان'; // Bhutan
$_country_lang["26"] = 'بولیوی'; // Bolivia
$_country_lang["27"] = 'بوسنی و هرزگووین'; // Bosnia and Herzegowina
$_country_lang["28"] = 'بوتسوآنا'; // Botswana
$_country_lang["29"] = 'جزیره بووه'; // Bouvet Island
$_country_lang["30"] = 'برزیل'; // Brazil
$_country_lang["31"] = 'قلمرو بریتانیا در اقیانوس هند'; // British Indian Ocean Territory
$_country_lang["32"] = 'برونئی'; // Brunei Darussalam
$_country_lang["33"] = 'بلغارستان'; // Bulgaria
$_country_lang["34"] = 'بورکینا فاسو'; // Burkina Faso
$_country_lang["35"] = 'بوروندی'; // Burundi
$_country_lang["36"] = 'کامبوج'; // Cambodia
$_country_lang["37"] = 'کامرون'; // Cameroon
$_country_lang["38"] = 'کانادا'; // Canada
$_country_lang["39"] = 'کیپ ورد'; // Cape Verde
$_country_lang["40"] = 'جزایر کیمن'; // Cayman Islands
$_country_lang["41"] = 'جمهوری آفریقای مرکزی'; // Central African Republic
$_country_lang["42"] = 'چاد'; // Chad
$_country_lang["43"] = 'شیلی'; // Chile
$_country_lang["44"] = 'چین'; // China
$_country_lang["45"] = 'جزیره کریسمس'; // Christmas Island
$_country_lang["46"] = 'جزایر کوکوس'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'کلمبیا'; // Colombia
$_country_lang["48"] = 'کومور'; // Comoros
$_country_lang["49"] = 'کنگو'; // Congo
$_country_lang["50"] = 'جزایر کوک'; // Cook Islands
$_country_lang["51"] = 'کاستاریکا'; // Costa Rica
$_country_lang["52"] = 'ساحل عاج'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'کرواسی'; // Croatia
$_country_lang["54"] = 'کوبا'; // Cuba
$_country_lang["55"] = 'قبرس'; // Cyprus
$_country_lang["56"] = 'جمهوری چک'; // Czech Republic
$_country_lang["57"] = 'دانمارک'; // Denmark
$_country_lang["58"] = 'جیبوتی'; // Djibouti
$_country_lang["59"] = 'دومینیکا'; // Dominica
$_country_lang["60"] = 'جمهوری دومینیکن'; // Dominican Republic
$_country_lang["61"] = 'تیمور شرقی'; // East Timor
$_country_lang["62"] = 'اکوادور'; // Ecuador
$_country_lang["63"] = 'مصر'; // Egypt
$_country_lang["64"] = 'السالوادور'; // El Salvador
$_country_lang["65"] = 'گینه استوایی'; // Equatorial Guinea
$_country_lang["66"] = 'اریتره'; // Eritrea
$_country_lang["67"] = 'استونی'; // Estonia
$_country_lang["68"] = 'اتیوپی'; // Ethiopia
$_country_lang["69"] = 'جزایر فالکلند (مالویناس)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'جزایر فارو'; // Faroe Islands
$_country_lang["71"] = 'فیجی'; // Fiji
$_country_lang["72"] = 'فنلاند'; // Finland
$_country_lang["73"] = 'فرانسه'; // France
$_country_lang["74"] = 'فرانسه، متروپولیتن'; // France, Metropolitan
$_country_lang["75"] = 'گویان فرانسه'; // French Guiana
$_country_lang["76"] = 'پلینزی فرانسه'; // French Polynesia
$_country_lang["77"] = 'قلمرو جنوبی فرانسه'; // French Southern Territories
$_country_lang["78"] = 'گابن'; // Gabon
$_country_lang["79"] = 'گامبیا'; // Gambia
$_country_lang["80"] = 'گرجستان'; // Georgia
$_country_lang["81"] = 'آلمان'; // Germany
$_country_lang["82"] = 'غنا'; // Ghana
$_country_lang["83"] = 'جبل الطارق'; // Gibraltar
$_country_lang["84"] = 'یونان'; // Greece
$_country_lang["85"] = 'گرینلند'; // Greenland
$_country_lang["86"] = 'گراندا'; // Grenada
$_country_lang["87"] = 'گوادلوپ'; // Guadeloupe
$_country_lang["88"] = 'گوام'; // Guam
$_country_lang["89"] = 'گواتمالا'; // Guatemala
$_country_lang["90"] = 'گینه'; // Guinea
$_country_lang["91"] = 'گینه بیسائو'; // Guinea-bissau
$_country_lang["92"] = 'گویان'; // Guyana
$_country_lang["93"] = 'هائیتی'; // Haiti
$_country_lang["94"] = 'جزایر هرد و مک‌دونالد'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'هندوراس'; // Honduras
$_country_lang["96"] = 'هنگ کنگ'; // Hong Kong
$_country_lang["97"] = 'مجارستان'; // Hungary
$_country_lang["98"] = 'آیسلند'; // Iceland
$_country_lang["99"] = 'هند'; // India
$_country_lang["100"] = 'اندونزی'; // Indonesia
$_country_lang["101"] = 'ايران (جمهوری اسلامی)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'عراق'; // Iraq
$_country_lang["103"] = 'ایرلند'; // Ireland
$_country_lang["104"] = 'اسرائیل'; // Israel
$_country_lang["105"] = 'ایتالیا'; // Italy
$_country_lang["106"] = 'جامائیکا'; // Jamaica
$_country_lang["107"] = 'ژاپن'; // Japan
$_country_lang["108"] = 'اردن'; // Jordan
$_country_lang["109"] = 'قزاقستان'; // Kazakhstan
$_country_lang["110"] = 'کنیا'; // Kenya
$_country_lang["111"] = 'کیریباتی'; // Kiribati
$_country_lang["112"] = 'کره‌ی شمالی'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'کره جنوبی'; // Korea, Republic of
$_country_lang["114"] = 'کویت'; // Kuwait
$_country_lang["115"] = 'قرقیزستان'; // Kyrgyzstan
$_country_lang["116"] = 'لائوس'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'لتونی'; // Latvia
$_country_lang["118"] = 'لبنان'; // Lebanon
$_country_lang["119"] = 'لسوتو'; // Lesotho
$_country_lang["120"] = 'لیبریا'; // Liberia
$_country_lang["121"] = 'لیبی'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'لیختن اشتاین'; // Liechtenstein
$_country_lang["123"] = 'لیتوانی'; // Lithuania
$_country_lang["124"] = 'لوکزامبورگ'; // Luxembourg
$_country_lang["125"] = 'ماکائو'; // Macau
$_country_lang["126"] = 'مقدونیه'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'ماداگاسکار'; // Madagascar
$_country_lang["128"] = 'مالاوی'; // Malawi
$_country_lang["129"] = 'مالزی'; // Malaysia
$_country_lang["130"] = 'مالدیو'; // Maldives
$_country_lang["131"] = 'مالی'; // Mali
$_country_lang["132"] = 'مالت'; // Malta
$_country_lang["133"] = 'جزایر مارشال'; // Marshall Islands
$_country_lang["134"] = 'مارتینیک'; // Martinique
$_country_lang["135"] = 'موریتانی'; // Mauritania
$_country_lang["136"] = 'موریس'; // Mauritius
$_country_lang["137"] = 'مایوت'; // Mayotte
$_country_lang["138"] = 'مکزیک'; // Mexico
$_country_lang["139"] = 'ایالات فدرال میکرونزی'; // Micronesia, Federated States of
$_country_lang["140"] = 'مولداوی'; // Moldova, Republic of
$_country_lang["141"] = 'موناکو'; // Monaco
$_country_lang["142"] = 'مغولستان'; // Mongolia
$_country_lang["241"] = 'مونته نگرو'; //Montenegro
$_country_lang["143"] = 'مونتسرات'; // Montserrat
$_country_lang["144"] = 'مراکش'; // Morocco
$_country_lang["145"] = 'موزامبیک'; // Mozambique
$_country_lang["146"] = 'میانمار'; // Myanmar
$_country_lang["147"] = 'نامیبیا'; // Namibia
$_country_lang["148"] = 'نائورو'; // Nauru
$_country_lang["149"] = 'نپال'; // Nepal
$_country_lang["150"] = 'هلند'; // Netherlands
$_country_lang["151"] = 'آنتیل هلند'; // Netherlands Antilles
$_country_lang["152"] = 'کالدونیای جدید'; // New Caledonia
$_country_lang["153"] = 'نيوزلند'; // New Zealand
$_country_lang["154"] = 'نیکاراگوئه'; // Nicaragua
$_country_lang["155"] = 'نیجر'; // Niger
$_country_lang["156"] = 'نیجریه'; // Nigeria
$_country_lang["157"] = 'نیوئه'; // Niue
$_country_lang["158"] = 'جزیره نورفولک'; // Norfolk Island
$_country_lang["159"] = 'جزایر ماریانای شمالی'; // Northern Mariana Islands
$_country_lang["160"] = 'نروژ'; // Norway
$_country_lang["161"] = 'عمان'; // Oman
$_country_lang["162"] = 'پاکستان'; // Pakistan
$_country_lang["163"] = 'پالائو'; // Palau
$_country_lang["164"] = 'پاناما'; // Panama
$_country_lang["165"] = 'پاپوآ گینه نو'; // Papua New Guinea
$_country_lang["166"] = 'پاراگوئه'; // Paraguay
$_country_lang["167"] = 'پرو'; // Peru
$_country_lang["168"] = 'فیلیپین'; // Philippines
$_country_lang["169"] = 'پیتکرن'; // Pitcairn
$_country_lang["170"] = 'لهستان'; // Poland
$_country_lang["171"] = 'پرتغال'; // Portugal
$_country_lang["172"] = 'پورتوریکو'; // Puerto Rico
$_country_lang["173"] = 'قطر'; // Qatar
$_country_lang["174"] = 'رئونیون'; // Reunion
$_country_lang["175"] = 'رومانی'; // Romania
$_country_lang["176"] = 'روسیه'; // Russian Federation
$_country_lang["177"] = 'رواندا'; // Rwanda
$_country_lang["178"] = 'سنت کیتس و نویس'; // Saint Kitts and Nevis
$_country_lang["179"] = 'سنت لوسیا'; // Saint Lucia
$_country_lang["180"] = 'سنت وینسنت و گرنادین'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'ساموآ'; // Samoa
$_country_lang["182"] = 'سان مارینو'; // San Marino
$_country_lang["183"] = 'سائو تومه و پرنسیپ'; // Sao Tome and Principe
$_country_lang["184"] = 'عربستان سعودی'; // Saudi Arabia
$_country_lang["185"] = 'سنگال'; // Senegal
$_country_lang["240"] = 'صربستان'; //Serbia
$_country_lang["186"] = 'سیشل'; // Seychelles
$_country_lang["187"] = 'سیرالئون'; // Sierra Leone
$_country_lang["188"] = 'سنگاپور'; // Singapore
$_country_lang["189"] = 'اسلواکی'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'اسلوونی'; // Slovenia
$_country_lang["191"] = 'جزایر سلیمان'; // Solomon Islands
$_country_lang["192"] = 'سومالی'; // Somalia
$_country_lang["193"] = 'آفریقای جنوبی'; // South Africa
$_country_lang["194"] = 'گرجستان جنوبی و جزایر ساندویچ جنوبی'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'اسپانیا'; // Spain
$_country_lang["196"] = 'سریلانکا'; // Sri Lanka
$_country_lang["197"] = 'سنت هلن'; // St. Helena
$_country_lang["198"] = 'سن پیِر و میکلُن'; // St. Pierre and Miquelon
$_country_lang["199"] = 'سودان'; // Sudan
$_country_lang["200"] = 'سورینام'; // Suriname
$_country_lang["201"] = 'سوالبارد و جان ماین جزیره'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'سوازیلند'; // Swaziland
$_country_lang["203"] = 'سوئد'; // Sweden
$_country_lang["204"] = 'سوئیس'; // Switzerland
$_country_lang["205"] = 'سوریه'; // Syrian Arab Republic
$_country_lang["206"] = 'تایوان'; // Taiwan
$_country_lang["207"] = 'تاجیکستان'; // Tajikistan
$_country_lang["208"] = 'تانزانیا'; // Tanzania, United Republic of
$_country_lang["209"] = 'تایلند'; // Thailand
$_country_lang["210"] = 'توگو'; // Togo
$_country_lang["211"] = 'توکلائو'; // Tokelau
$_country_lang["212"] = 'تونگا'; // Tonga
$_country_lang["213"] = 'ترینیداد و توباگو'; // Trinidad and Tobago
$_country_lang["214"] = 'تونس'; // Tunisia
$_country_lang["215"] = 'ترکیه'; // Turkey
$_country_lang["216"] = 'ترکمنستان'; // Turkmenistan
$_country_lang["217"] = 'جزایر تورکس و کایکوس'; // Turks and Caicos Islands
$_country_lang["218"] = 'تووالو'; // Tuvalu
$_country_lang["219"] = 'اوگاندا'; // Uganda
$_country_lang["220"] = 'اوکراین'; // Ukraine
$_country_lang["221"] = 'امارات متحده عربی'; // United Arab Emirates
$_country_lang["222"] = 'بریتانیا'; // United Kingdom
$_country_lang["223"] = 'ایالات متحده آمریکا'; // United States
$_country_lang["224"] = 'جزایر کوچک حاشیه ای ایالات متحده'; // United States Minor Outlying Islands
$_country_lang["225"] = 'اوروگوئه'; // Uruguay
$_country_lang["226"] = 'ازبکستان'; // Uzbekistan
$_country_lang["227"] = 'وانواتو'; // Vanuatu
$_country_lang["228"] = 'واتیکان'; // Vatican City State (Holy See)
$_country_lang["229"] = 'ونزوئلا'; // Venezuela
$_country_lang["230"] = 'ویتنام'; // Viet Nam
$_country_lang["231"] = 'جزایر ویرجین (بریتانیا)'; // Virgin Islands (British)
$_country_lang["232"] = 'جزایر ویرجین (ایالات متحده)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'جزایر والیس و فوتونا'; // Wallis and Futuna Islands
$_country_lang["234"] = 'صحرای غربی'; // Western Sahara
$_country_lang["235"] = 'یمن'; // Yemen
$_country_lang["236"] = 'صربستان و مونته نگرو'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'کنگو'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'زامبیا'; // Zambia
$_country_lang["239"] = 'زیمباوه'; // Zimbabwe
?>