<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afganistan'; // Afghanistan
$_country_lang["2"] = 'Albania'; // Albania
$_country_lang["3"] = 'Algeria'; // Algeria
$_country_lang["4"] = 'Amerikan Samoa'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Etelämanner'; // Antarctica
$_country_lang["9"] = 'Antigua ja Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentiina'; // Argentina
$_country_lang["11"] = 'Armenia'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Australia'; // Australia
$_country_lang["14"] = 'Itävalta'; // Austria
$_country_lang["15"] = 'Azerbaidžan'; // Azerbaijan
$_country_lang["16"] = 'Bahama'; // Bahamas
$_country_lang["17"] = 'Bahrain'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Valko-Venäjä'; // Belarus
$_country_lang["21"] = 'Belgia'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Bhutan'; // Bhutan
$_country_lang["26"] = 'Bolivia'; // Bolivia
$_country_lang["27"] = 'Bosnia ja Hertsegovina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Bouvet\'nsaari'; // Bouvet Island
$_country_lang["30"] = 'Brasilia'; // Brazil
$_country_lang["31"] = 'Brittiläinen Intian valtameren alue'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei Darussalam'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgaria'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Kambodža'; // Cambodia
$_country_lang["37"] = 'Kamerun'; // Cameroon
$_country_lang["38"] = 'Kanada'; // Canada
$_country_lang["39"] = 'Kap Verde'; // Cape Verde
$_country_lang["40"] = 'Caymansaaret'; // Cayman Islands
$_country_lang["41"] = 'Keski-Afrikan tasavalta'; // Central African Republic
$_country_lang["42"] = 'Tšad'; // Chad
$_country_lang["43"] = 'Chile'; // Chile
$_country_lang["44"] = 'Kiina'; // China
$_country_lang["45"] = 'Joulusaari'; // Christmas Island
$_country_lang["46"] = 'Kookossaaret'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Kolumbia'; // Colombia
$_country_lang["48"] = 'Komorit'; // Comoros
$_country_lang["49"] = 'Kongon tasavalta'; // Congo
$_country_lang["50"] = 'Cookinsaaret'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Norsunluurannikko'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Kroatia'; // Croatia
$_country_lang["54"] = 'Kuuba'; // Cuba
$_country_lang["55"] = 'Kypros'; // Cyprus
$_country_lang["56"] = 'Tšekin tasavalta'; // Czech Republic
$_country_lang["57"] = 'Tanska'; // Denmark
$_country_lang["58"] = 'Djibouti'; // Djibouti
$_country_lang["59"] = 'Dominica'; // Dominica
$_country_lang["60"] = 'Dominikaaninen tasavalta'; // Dominican Republic
$_country_lang["61"] = 'Itä-Timor'; // East Timor
$_country_lang["62"] = 'Ecuador'; // Ecuador
$_country_lang["63"] = 'Egypti'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Päiväntasaajan Guinea'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Viro'; // Estonia
$_country_lang["68"] = 'Etiopia'; // Ethiopia
$_country_lang["69"] = 'Falklandin saaret (Malvinas)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Färsaaret'; // Faroe Islands
$_country_lang["71"] = 'Fidži'; // Fiji
$_country_lang["72"] = 'Suomi'; // Finland
$_country_lang["73"] = 'Ranska'; // France
$_country_lang["74"] = 'Ranska, Pääkaupunkiseutu'; // France, Metropolitan
$_country_lang["75"] = 'Ranskan Guayana'; // French Guiana
$_country_lang["76"] = 'Ranskan Polynesia'; // French Polynesia
$_country_lang["77"] = 'Ranskan eteläiset alueet'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Georgia'; // Georgia
$_country_lang["81"] = 'Saksa'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Kreikka'; // Greece
$_country_lang["85"] = 'Grönlanti'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Guinea-Bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Heard ja McDonaldinsaaret'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Unkari'; // Hungary
$_country_lang["98"] = 'Islanti'; // Iceland
$_country_lang["99"] = 'Intia'; // India
$_country_lang["100"] = 'Indonesia'; // Indonesia
$_country_lang["101"] = 'Iran (islamilainen tasavalta)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irak'; // Iraq
$_country_lang["103"] = 'Irlanti'; // Ireland
$_country_lang["104"] = 'Israel'; // Israel
$_country_lang["105"] = 'Italia'; // Italy
$_country_lang["106"] = 'Jamaika'; // Jamaica
$_country_lang["107"] = 'Japani'; // Japan
$_country_lang["108"] = 'Jordania'; // Jordan
$_country_lang["109"] = 'Kazakstan'; // Kazakhstan
$_country_lang["110"] = 'Kenia'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Korea, demokraattisen tasavalta'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Etelä-Korea'; // Korea, Republic of
$_country_lang["114"] = 'Kuwait'; // Kuwait
$_country_lang["115"] = 'Kirgisistan'; // Kyrgyzstan
$_country_lang["116"] = 'Laos'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Latvia'; // Latvia
$_country_lang["118"] = 'Libanon'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Liberia'; // Liberia
$_country_lang["121"] = 'Libya'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Liettua'; // Lithuania
$_country_lang["124"] = 'Luxemburg'; // Luxembourg
$_country_lang["125"] = 'Macao'; // Macau
$_country_lang["126"] = 'Makedonia'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaskar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malesia'; // Malaysia
$_country_lang["130"] = 'Malediivit'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Marshallinsaaret'; // Marshall Islands
$_country_lang["134"] = 'Martinique'; // Martinique
$_country_lang["135"] = 'Mauritania'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Meksiko'; // Mexico
$_country_lang["139"] = 'Mikronesia'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldovan tasavalta'; // Moldova, Republic of
$_country_lang["141"] = 'Monaco'; // Monaco
$_country_lang["142"] = 'Mongolia'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Marokko'; // Morocco
$_country_lang["145"] = 'Mosambik'; // Mozambique
$_country_lang["146"] = 'Myanmar'; // Myanmar
$_country_lang["147"] = 'Namibia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Alankomaat'; // Netherlands
$_country_lang["151"] = 'Alankomaiden Antillit'; // Netherlands Antilles
$_country_lang["152"] = 'Uusi-Kaledonia'; // New Caledonia
$_country_lang["153"] = 'Uusi-Seelanti'; // New Zealand
$_country_lang["154"] = 'Nicaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolkinsaari'; // Norfolk Island
$_country_lang["159"] = 'Pohjois-Mariaanit'; // Northern Mariana Islands
$_country_lang["160"] = 'Norja'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papua-Uusi-Guinea'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Peru'; // Peru
$_country_lang["168"] = 'Filippiinit'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Puola'; // Poland
$_country_lang["171"] = 'Portugali'; // Portugal
$_country_lang["172"] = 'Puerto Rico'; // Puerto Rico
$_country_lang["173"] = 'Qatar'; // Qatar
$_country_lang["174"] = 'Réunion'; // Reunion
$_country_lang["175"] = 'Romania'; // Romania
$_country_lang["176"] = 'Venäjä'; // Russian Federation
$_country_lang["177"] = 'Ruanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts ja Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Saint Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent ja Grenadiinit'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'Salomonsaaret'; // Sao Tome and Principe
$_country_lang["184"] = 'Saudi-Arabia'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'Serbia'; //Serbia
$_country_lang["186"] = 'Seychellit'; // Seychelles
$_country_lang["187"] = 'Sierra Leonen'; // Sierra Leone
$_country_lang["188"] = 'Singapore'; // Singapore
$_country_lang["189"] = 'Slovakia'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Slovenia'; // Slovenia
$_country_lang["191"] = 'Salomonsaaret'; // Solomon Islands
$_country_lang["192"] = 'Somalia'; // Somalia
$_country_lang["193"] = 'Etelä-Afrikka'; // South Africa
$_country_lang["194"] = 'Etelä-Georgia ja Eteläiset Sandwichsaaret'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Espanja'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'St. Helena'; // St. Helena
$_country_lang["198"] = 'Saint-Pierre ja Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sudan'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Huippuvuoret ja Jan Mayen'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Swazimaa'; // Swaziland
$_country_lang["203"] = 'Ruotsi'; // Sweden
$_country_lang["204"] = 'Sveitsi'; // Switzerland
$_country_lang["205"] = 'Syyria'; // Syrian Arab Republic
$_country_lang["206"] = 'Taiwan'; // Taiwan
$_country_lang["207"] = 'Tadžikistanin'; // Tajikistan
$_country_lang["208"] = 'Tansania'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thaimaa'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad ja Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunisia'; // Tunisia
$_country_lang["215"] = 'Turkki'; // Turkey
$_country_lang["216"] = 'Turkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Turks- ja Caicossaaret'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukraina'; // Ukraine
$_country_lang["221"] = 'Yhdistyneet arabiemiirikunnat'; // United Arab Emirates
$_country_lang["222"] = 'Iso-Britannia'; // United Kingdom
$_country_lang["223"] = 'Yhdysvallat'; // United States
$_country_lang["224"] = 'Yhdysvaltain pienet erillissaaret'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Uzbekistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vatikaanivaltio'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Vietnam'; // Viet Nam
$_country_lang["231"] = 'Neitsytsaaret (UK)'; // Virgin Islands (British)
$_country_lang["232"] = 'Neitsytsaaret (US)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis ja Futuna'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Länsi-Sahara'; // Western Sahara
$_country_lang["235"] = 'Jemen'; // Yemen
$_country_lang["236"] = 'Serbia ja Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Kongon demokraattinen tasavalta'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Sambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>