<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afghanistan'; // Afghanistan
$_country_lang["2"] = 'Albanie'; // Albania
$_country_lang["3"] = 'Algérie'; // Algeria
$_country_lang["4"] = 'Samoa Américaines'; // American Samoa
$_country_lang["5"] = 'Andorre'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antarctique'; // Antarctica
$_country_lang["9"] = 'Antigua et Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentine'; // Argentina
$_country_lang["11"] = 'Arménie'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Australie'; // Australia
$_country_lang["14"] = 'Austriche'; // Austria
$_country_lang["15"] = 'Azerbaïdjan'; // Azerbaijan
$_country_lang["16"] = 'Bahamas'; // Bahamas
$_country_lang["17"] = 'Bahreïn'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbades'; // Barbados
$_country_lang["20"] = 'Biélorussie'; // Belarus
$_country_lang["21"] = 'Belgique'; // Belgium
$_country_lang["22"] = 'Bélize'; // Belize
$_country_lang["23"] = 'Bénin'; // Benin
$_country_lang["24"] = 'Bermudes'; // Bermuda
$_country_lang["25"] = 'Bhoutan'; // Bhutan
$_country_lang["26"] = 'Bolivie'; // Bolivia
$_country_lang["27"] = 'Bosnie Herzegovine'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Île Bouvet'; // Bouvet Island
$_country_lang["30"] = 'Brésil'; // Brazil
$_country_lang["31"] = 'Territoire Britannique de l\'Océan Indien'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgarie'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Cambodge'; // Cambodia
$_country_lang["37"] = 'Cameroun'; // Cameroon
$_country_lang["38"] = 'Canada'; // Canada
$_country_lang["39"] = 'Cap-Vert'; // Cape Verde
$_country_lang["40"] = 'Îles Caïman'; // Cayman Islands
$_country_lang["41"] = 'République d\'Afrique Centrale'; // Central African Republic
$_country_lang["42"] = 'TChad'; // Chad
$_country_lang["43"] = 'Chili'; // Chile
$_country_lang["44"] = 'Chine'; // China
$_country_lang["45"] = 'Île Christmas'; // Christmas Island
$_country_lang["46"] = 'Îles Cocos'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Colombie'; // Colombia
$_country_lang["48"] = 'Comores'; // Comoros
$_country_lang["49"] = 'Congo, République Démocratique du'; // Congo
$_country_lang["50"] = 'Îles Cook'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Côte d\'Ivoire'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Croatie'; // Croatia
$_country_lang["54"] = 'Cuba'; // Cuba
$_country_lang["55"] = 'Chypre'; // Cyprus
$_country_lang["56"] = 'Republique Tchèque'; // Czech Republic
$_country_lang["57"] = 'Danemark'; // Denmark
$_country_lang["58"] = 'Djibouti'; // Djibouti
$_country_lang["59"] = 'Dominique'; // Dominica
$_country_lang["60"] = 'République Dominicaine'; // Dominican Republic
$_country_lang["61"] = 'Timor Oriental'; // East Timor
$_country_lang["62"] = 'Equateur'; // Ecuador
$_country_lang["63"] = 'Egypte'; // Egypt
$_country_lang["64"] = 'Salvador'; // El Salvador
$_country_lang["65"] = 'Guinée Equatoriale'; // Equatorial Guinea
$_country_lang["66"] = 'Erythrée'; // Eritrea
$_country_lang["67"] = 'Estonie'; // Estonia
$_country_lang["68"] = 'Ethiopie'; // Ethiopia
$_country_lang["69"] = 'Îles Falkland (Malouines)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Îles Féroe'; // Faroe Islands
$_country_lang["71"] = 'Fidji'; // Fiji
$_country_lang["72"] = 'Finlande'; // Finland
$_country_lang["73"] = 'France'; // France
$_country_lang["74"] = 'France Metropolitaine'; // France, Metropolitan
$_country_lang["75"] = 'Guyane Française'; // French Guiana
$_country_lang["76"] = 'Polynésie Française'; // French Polynesia
$_country_lang["77"] = 'Terres Australes Françaises'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambie'; // Gambia
$_country_lang["80"] = 'Georgie'; // Georgia
$_country_lang["81"] = 'Allemagne'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Grèce'; // Greece
$_country_lang["85"] = 'Groënland'; // Greenland
$_country_lang["86"] = 'Grenade'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinée'; // Guinea
$_country_lang["91"] = 'Guinée-Bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyane'; // Guyana
$_country_lang["93"] = 'Haïti'; // Haiti
$_country_lang["94"] = 'Îles Heard et Mc Donald'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Hongrie'; // Hungary
$_country_lang["98"] = 'Islande'; // Iceland
$_country_lang["99"] = 'Inde'; // India
$_country_lang["100"] = 'Indonésie'; // Indonesia
$_country_lang["101"] = 'Iran (République Islamique d\')'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irak'; // Iraq
$_country_lang["103"] = 'Irlande'; // Ireland
$_country_lang["104"] = 'Israël'; // Israel
$_country_lang["105"] = 'Italie'; // Italy
$_country_lang["106"] = 'Jamaïque'; // Jamaica
$_country_lang["107"] = 'Japon'; // Japan
$_country_lang["108"] = 'Jordanie'; // Jordan
$_country_lang["109"] = 'Kazakhstan'; // Kazakhstan
$_country_lang["110"] = 'Kenya'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Corée du Nord, (République Démocratique Populaire de)'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Corée du Sud, (République de)'; // Korea, Republic of
$_country_lang["114"] = 'Koweit'; // Kuwait
$_country_lang["115"] = 'Kirghizstan'; // Kyrgyzstan
$_country_lang["116"] = 'Laos (République Démocratique du)'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Lettonie'; // Latvia
$_country_lang["118"] = 'Liban'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Liberia'; // Liberia
$_country_lang["121"] = 'Libye'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Lithuanie'; // Lithuania
$_country_lang["124"] = 'Luxembourg'; // Luxembourg
$_country_lang["125"] = 'Macao'; // Macau
$_country_lang["126"] = 'Macédoine, (Ex Yougoslavie)'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagascar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malaisie'; // Malaysia
$_country_lang["130"] = 'Maldives'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malte'; // Malta
$_country_lang["133"] = 'Îles Marshall'; // Marshall Islands
$_country_lang["134"] = 'Martinique'; // Martinique
$_country_lang["135"] = 'Mauritanie'; // Mauritania
$_country_lang["136"] = 'Île Maurice'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Mexique'; // Mexico
$_country_lang["139"] = 'Micronésie, (Fédération de)'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldavie, (République de)'; // Moldova, Republic of
$_country_lang["141"] = 'Monaco'; // Monaco
$_country_lang["142"] = 'Mongolie'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Maroc'; // Morocco
$_country_lang["145"] = 'Mozambique'; // Mozambique
$_country_lang["146"] = 'Birmanie'; // Myanmar
$_country_lang["147"] = 'Namibie'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Pays-bas'; // Netherlands
$_country_lang["151"] = 'Antilles Néerlandaises'; // Netherlands Antilles
$_country_lang["152"] = 'Nouvelle Calédonie'; // New Caledonia
$_country_lang["153"] = 'Nouvelle Zélande'; // New Zealand
$_country_lang["154"] = 'Nicaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Île Norfolk'; // Norfolk Island
$_country_lang["159"] = 'Îles Mariannes du Nord'; // Northern Mariana Islands
$_country_lang["160"] = 'Norvège'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'République des Palaos'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papouasie Nouvelle Guinée'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Perou'; // Peru
$_country_lang["168"] = 'Philippines'; // Philippines
$_country_lang["169"] = 'Îles Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Pologne'; // Poland
$_country_lang["171"] = 'Portugal'; // Portugal
$_country_lang["172"] = 'Porto Rico'; // Puerto Rico
$_country_lang["173"] = 'Qatar'; // Qatar
$_country_lang["174"] = 'Réunion'; // Reunion
$_country_lang["175"] = 'Roumanie'; // Romania
$_country_lang["176"] = 'Russie (Fédération de)'; // Russian Federation
$_country_lang["177"] = 'Rwanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts et Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Sainte Lucie'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent et Les Grenadines'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marin'; // San Marino
$_country_lang["183"] = 'Sao Tome et Principe'; // Sao Tome and Principe
$_country_lang["184"] = 'Arabie Saoudite'; // Saudi Arabia
$_country_lang["185"] = 'Sénégal'; // Senegal
$_country_lang["240"] = 'Serbie'; //Serbia
$_country_lang["186"] = 'Seychelles'; // Seychelles
$_country_lang["187"] = 'Sierra Léone'; // Sierra Leone
$_country_lang["188"] = 'Singapour'; // Singapore
$_country_lang["189"] = 'Slovaquie (République Slovaque)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Slovenie'; // Slovenia
$_country_lang["191"] = 'Îles Salomon'; // Solomon Islands
$_country_lang["192"] = 'Somalie'; // Somalia
$_country_lang["193"] = 'Afrique du Sud'; // South Africa
$_country_lang["194"] = 'Georgie du Sud et Îles Sandwich du Sud'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Espagne'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'St. Hélène'; // St. Helena
$_country_lang["198"] = 'St. Pierre et Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Soudan'; // Sudan
$_country_lang["200"] = 'Surinam'; // Suriname
$_country_lang["201"] = 'Iles de Svalbard et Jan Mayen'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Swaziland'; // Swaziland
$_country_lang["203"] = 'Suède'; // Sweden
$_country_lang["204"] = 'Suisse'; // Switzerland
$_country_lang["205"] = 'Syrie'; // Syrian Arab Republic
$_country_lang["206"] = 'Taïwan'; // Taiwan
$_country_lang["207"] = 'Tadjikistan'; // Tajikistan
$_country_lang["208"] = 'Tanzanie, (République Unie de)'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thaïlande'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad et Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunisie'; // Tunisia
$_country_lang["215"] = 'Turquie'; // Turkey
$_country_lang["216"] = 'Turkménistan'; // Turkmenistan
$_country_lang["217"] = 'Îles Turks et Caiques'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Ouganda'; // Uganda
$_country_lang["220"] = 'Ukraine'; // Ukraine
$_country_lang["221"] = 'Emirats Arabes Unis'; // United Arab Emirates
$_country_lang["222"] = 'Royaume Uni'; // United Kingdom
$_country_lang["223"] = 'États-Unis d\'Amérique'; // United States
$_country_lang["224"] = 'Parc Sauvage des Iles du Pacifique des États-Unis'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Ouzbékistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Cité du Vatican (Saint Siège)'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Vénézuela'; // Venezuela
$_country_lang["230"] = 'Viêt Nam'; // Viet Nam
$_country_lang["231"] = 'Îles Vierges Britanniques'; // Virgin Islands (British)
$_country_lang["232"] = 'Îles Vierges Américaines'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis et Futuna'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Sahara Occidental'; // Western Sahara
$_country_lang["235"] = 'Yémen'; // Yemen
$_country_lang["236"] = 'Serbie and Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Congo, (République Démocratique du)'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambie'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>