<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'אפגניסטן'; // Afghanistan
$_country_lang["2"] = 'אלבניה'; // Albania
$_country_lang["3"] = 'אלג\'יריה'; // Algeria
$_country_lang["4"] = 'סמואה האמריקנית'; // American Samoa
$_country_lang["5"] = 'אנדורה'; // Andorra
$_country_lang["6"] = 'אנגולה'; // Angola
$_country_lang["7"] = 'אנגווילה'; // Anguilla
$_country_lang["8"] = 'אנטארקטיקה'; // Antarctica
$_country_lang["9"] = 'אנטיגואה וברבודה'; // Antigua and Barbuda
$_country_lang["10"] = 'ארגנטינה'; // Argentina
$_country_lang["11"] = 'ארמניה'; // Armenia
$_country_lang["12"] = 'ארובה'; // Aruba
$_country_lang["13"] = 'אוסטרליה'; // Australia
$_country_lang["14"] = 'אוסטריה'; // Austria
$_country_lang["15"] = 'אזרבייג\'ן'; // Azerbaijan
$_country_lang["16"] = 'איי הבהאמה'; // Bahamas
$_country_lang["17"] = 'בחריין'; // Bahrain
$_country_lang["18"] = 'בנגלדש'; // Bangladesh
$_country_lang["19"] = 'ברבדוס'; // Barbados
$_country_lang["20"] = 'בלארוס'; // Belarus
$_country_lang["21"] = 'בלגיה'; // Belgium
$_country_lang["22"] = 'בליז'; // Belize
$_country_lang["23"] = 'בנין'; // Benin
$_country_lang["24"] = 'ברמודה'; // Bermuda
$_country_lang["25"] = 'בהוטן'; // Bhutan
$_country_lang["26"] = 'בוליביה'; // Bolivia
$_country_lang["27"] = 'בוסניה והרצגובינה'; // Bosnia and Herzegowina
$_country_lang["28"] = 'בוטסואנה'; // Botswana
$_country_lang["29"] = 'האי בובה'; // Bouvet Island
$_country_lang["30"] = 'ברזיל'; // Brazil
$_country_lang["31"] = 'הטריטוריה הבריטית באוקיינוס ההודי'; // British Indian Ocean Territory
$_country_lang["32"] = 'ברוניי דרוסלאם'; // Brunei Darussalam
$_country_lang["33"] = 'בולגריה'; // Bulgaria
$_country_lang["34"] = 'בורקינה פאסו'; // Burkina Faso
$_country_lang["35"] = 'בורונדי'; // Burundi
$_country_lang["36"] = 'קמבודיה'; // Cambodia
$_country_lang["37"] = 'קמרון'; // Cameroon
$_country_lang["38"] = 'קנדה'; // Canada
$_country_lang["39"] = 'קייפ ורדה'; // Cape Verde
$_country_lang["40"] = 'איי קיימן'; // Cayman Islands
$_country_lang["41"] = 'הרפובליקה המרכז אפריקאית'; // Central African Republic
$_country_lang["42"] = 'צ\'אד'; // Chad
$_country_lang["43"] = 'צ\'ילה'; // Chile
$_country_lang["44"] = 'סין'; // China
$_country_lang["45"] = 'אי חג המולד'; // Christmas Island
$_country_lang["46"] = 'איי קוקוס (קילינג)'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'קולומביה'; // Colombia
$_country_lang["48"] = 'איי קומורו'; // Comoros
$_country_lang["49"] = 'הרפובליקה של קונגו'; // Congo
$_country_lang["50"] = 'איי קוק'; // Cook Islands
$_country_lang["51"] = 'קוסטה ריקה'; // Costa Rica
$_country_lang["52"] = 'חוף השנהב'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'קרואטיה'; // Croatia
$_country_lang["54"] = 'קובה'; // Cuba
$_country_lang["55"] = 'קפריסין'; // Cyprus
$_country_lang["56"] = 'הרפובליקה הצ\'כית'; // Czech Republic
$_country_lang["57"] = 'דנמרק'; // Denmark
$_country_lang["58"] = 'ג\'יבוטי'; // Djibouti
$_country_lang["59"] = 'דומיניקה'; // Dominica
$_country_lang["60"] = 'הרפובליקה הדומיניקנית'; // Dominican Republic
$_country_lang["61"] = 'מזרח טימור'; // East Timor
$_country_lang["62"] = 'אקוודור'; // Ecuador
$_country_lang["63"] = 'מצרים'; // Egypt
$_country_lang["64"] = 'אל סלבדור'; // El Salvador
$_country_lang["65"] = 'גינאה המשוונית'; // Equatorial Guinea
$_country_lang["66"] = 'אריתריאה'; // Eritrea
$_country_lang["67"] = 'אסטוניה'; // Estonia
$_country_lang["68"] = 'אתיופיה'; // Ethiopia
$_country_lang["69"] = 'איי פוקלנד (מלבינס)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'איי פארו'; // Faroe Islands
$_country_lang["71"] = 'פיג\'י'; // Fiji
$_country_lang["72"] = 'פינלנד'; // Finland
$_country_lang["73"] = 'צרפת'; // France
$_country_lang["74"] = 'צרפת, מטרופוליטן'; // France, Metropolitan
$_country_lang["75"] = 'גיאנה הצרפתית'; // French Guiana
$_country_lang["76"] = 'פולינזיה הצרפתית'; // French Polynesia
$_country_lang["77"] = 'הטריטוריות הדרומיות של צרפת'; // French Southern Territories
$_country_lang["78"] = 'גבון'; // Gabon
$_country_lang["79"] = 'גמביה'; // Gambia
$_country_lang["80"] = 'גיאורגיה'; // Georgia
$_country_lang["81"] = 'גרמניה'; // Germany
$_country_lang["82"] = 'גאנה'; // Ghana
$_country_lang["83"] = 'גיברלטר'; // Gibraltar
$_country_lang["84"] = 'יוון'; // Greece
$_country_lang["85"] = 'גרינלנד'; // Greenland
$_country_lang["86"] = 'גרנדה'; // Grenada
$_country_lang["87"] = 'גוואדלופ'; // Guadeloupe
$_country_lang["88"] = 'גואם'; // Guam
$_country_lang["89"] = 'גואטמלה'; // Guatemala
$_country_lang["90"] = 'גינאה'; // Guinea
$_country_lang["91"] = 'גינאה ביסאו'; // Guinea-bissau
$_country_lang["92"] = 'גיאנה'; // Guyana
$_country_lang["93"] = 'האיטי'; // Haiti
$_country_lang["94"] = 'האי הרד ואיי מקדונלד'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'הונדורס'; // Honduras
$_country_lang["96"] = 'הונג קונג'; // Hong Kong
$_country_lang["97"] = 'הונגריה'; // Hungary
$_country_lang["98"] = 'איסלנד'; // Iceland
$_country_lang["99"] = 'הודו'; // India
$_country_lang["100"] = 'אינדונזיה'; // Indonesia
$_country_lang["101"] = 'אירן (הרפובליקה האיסלמית של)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'עיראק'; // Iraq
$_country_lang["103"] = 'אירלנד'; // Ireland
$_country_lang["104"] = 'ישראל'; // Israel
$_country_lang["105"] = 'איטליה'; // Italy
$_country_lang["106"] = 'ג\'מייקה'; // Jamaica
$_country_lang["107"] = 'יפן'; // Japan
$_country_lang["108"] = 'ירדן'; // Jordan
$_country_lang["109"] = 'קזחסטן'; // Kazakhstan
$_country_lang["110"] = 'קניה'; // Kenya
$_country_lang["111"] = 'קיריבטי'; // Kiribati
$_country_lang["112"] = 'קוריאה הצפונית'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'קוריאה הדרומית'; // Korea, Republic of
$_country_lang["114"] = 'כוויית'; // Kuwait
$_country_lang["115"] = 'קירגיזסטן'; // Kyrgyzstan
$_country_lang["116"] = 'לאוס'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'לטביה'; // Latvia
$_country_lang["118"] = 'לבנון'; // Lebanon
$_country_lang["119"] = 'לסוטו'; // Lesotho
$_country_lang["120"] = 'ליבריה'; // Liberia
$_country_lang["121"] = 'לוב'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'ליכטנשטיין'; // Liechtenstein
$_country_lang["123"] = 'ליטא'; // Lithuania
$_country_lang["124"] = 'לוקסמבורג'; // Luxembourg
$_country_lang["125"] = 'מקאו'; // Macau
$_country_lang["126"] = 'מקדוניה'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'מדגסקר'; // Madagascar
$_country_lang["128"] = 'מלאווי'; // Malawi
$_country_lang["129"] = 'מלזיה'; // Malaysia
$_country_lang["130"] = 'האיים המלדיביים'; // Maldives
$_country_lang["131"] = 'מאלי'; // Mali
$_country_lang["132"] = 'מלטה'; // Malta
$_country_lang["133"] = 'איי מרשל'; // Marshall Islands
$_country_lang["134"] = 'מרטיניק'; // Martinique
$_country_lang["135"] = 'מאוריטניה'; // Mauritania
$_country_lang["136"] = 'מאוריציוס'; // Mauritius
$_country_lang["137"] = 'מיוט'; // Mayotte
$_country_lang["138"] = 'מקסיקו'; // Mexico
$_country_lang["139"] = 'המדינות המאוחדות של מיקרונזיה'; // Micronesia, Federated States of
$_country_lang["140"] = 'הרפובליקה של מולדובה'; // Moldova, Republic of
$_country_lang["141"] = 'מונאקו'; // Monaco
$_country_lang["142"] = 'מונגוליה'; // Mongolia
$_country_lang["241"] = 'מונטנגרו'; //Montenegro
$_country_lang["143"] = 'מונטסראט'; // Montserrat
$_country_lang["144"] = 'מרוקו'; // Morocco
$_country_lang["145"] = 'מוזמביק'; // Mozambique
$_country_lang["146"] = 'מיאנמר'; // Myanmar
$_country_lang["147"] = 'נמיביה'; // Namibia
$_country_lang["148"] = 'נאורו'; // Nauru
$_country_lang["149"] = 'נפאל'; // Nepal
$_country_lang["150"] = 'הולנד'; // Netherlands
$_country_lang["151"] = 'האנטילים ההולנדיים'; // Netherlands Antilles
$_country_lang["152"] = 'קלדוניה החדשה'; // New Caledonia
$_country_lang["153"] = 'ניו זילנד'; // New Zealand
$_country_lang["154"] = 'ניקרגואה'; // Nicaragua
$_country_lang["155"] = 'ניז\'ר'; // Niger
$_country_lang["156"] = 'ניגריה'; // Nigeria
$_country_lang["157"] = 'ניואה'; // Niue
$_country_lang["158"] = 'האי נורפוק'; // Norfolk Island
$_country_lang["159"] = 'איי מריאנה הצפוניים'; // Northern Mariana Islands
$_country_lang["160"] = 'נורווגיה'; // Norway
$_country_lang["161"] = 'עומאן'; // Oman
$_country_lang["162"] = 'פקיסטן'; // Pakistan
$_country_lang["163"] = 'פלאו'; // Palau
$_country_lang["164"] = 'פנמה'; // Panama
$_country_lang["165"] = 'פפואה גינאה החדשה'; // Papua New Guinea
$_country_lang["166"] = 'פרגוואי'; // Paraguay
$_country_lang["167"] = 'פרו'; // Peru
$_country_lang["168"] = 'פיליפינים'; // Philippines
$_country_lang["169"] = 'פיטקרן'; // Pitcairn
$_country_lang["170"] = 'פולין'; // Poland
$_country_lang["171"] = 'פורטוגל'; // Portugal
$_country_lang["172"] = 'פורטו ריקו'; // Puerto Rico
$_country_lang["173"] = 'קטאר'; // Qatar
$_country_lang["174"] = 'ראוניון'; // Reunion
$_country_lang["175"] = 'רומניה'; // Romania
$_country_lang["176"] = 'הפדרציה הרוסית'; // Russian Federation
$_country_lang["177"] = 'רואנדה'; // Rwanda
$_country_lang["178"] = 'סנט קיטס ונוויס'; // Saint Kitts and Nevis
$_country_lang["179"] = 'סנט לוסיה'; // Saint Lucia
$_country_lang["180"] = 'סנט וינסנט והגרנדינים'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'סמואה'; // Samoa
$_country_lang["182"] = 'סן מרינו'; // San Marino
$_country_lang["183"] = 'סאו טומה ופרינסיפה'; // Sao Tome and Principe
$_country_lang["184"] = 'ערב הסעודית'; // Saudi Arabia
$_country_lang["185"] = 'סנגל'; // Senegal
$_country_lang["240"] = 'סרביה'; //Serbia
$_country_lang["186"] = 'איי סיישל'; // Seychelles
$_country_lang["187"] = 'סיירה לאונה'; // Sierra Leone
$_country_lang["188"] = 'סינגפור'; // Singapore
$_country_lang["189"] = 'סלובקיה (הרפובליקה הסלובקית)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'סלובניה'; // Slovenia
$_country_lang["191"] = 'איי שלמה'; // Solomon Islands
$_country_lang["192"] = 'סומליה'; // Somalia
$_country_lang["193"] = 'דרום אפריקה'; // South Africa
$_country_lang["194"] = 'איי ג\'ורג\'יה הדרומית ואיי סנדוויץ'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'ספרד'; // Spain
$_country_lang["196"] = 'סרי לנקה'; // Sri Lanka
$_country_lang["197"] = 'סנט הלנה'; // St. Helena
$_country_lang["198"] = 'סן פייר ומיקלון'; // St. Pierre and Miquelon
$_country_lang["199"] = 'סודאן'; // Sudan
$_country_lang["200"] = 'סורינאם'; // Suriname
$_country_lang["201"] = 'איי סוולברד ויאן מאיין'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'סווזילנד'; // Swaziland
$_country_lang["203"] = 'שוודיה'; // Sweden
$_country_lang["204"] = 'שוויץ'; // Switzerland
$_country_lang["205"] = 'הרפובליקה הערבית הסורית'; // Syrian Arab Republic
$_country_lang["206"] = 'טיוואן'; // Taiwan
$_country_lang["207"] = 'טג\'יקיסטן'; // Tajikistan
$_country_lang["208"] = 'טנזניה, הרפובליקה המאוחדת'; // Tanzania, United Republic of
$_country_lang["209"] = 'תאילנד'; // Thailand
$_country_lang["210"] = 'טוגו'; // Togo
$_country_lang["211"] = 'טוקלאו'; // Tokelau
$_country_lang["212"] = 'טונגה'; // Tonga
$_country_lang["213"] = 'טרינידד וטובגו'; // Trinidad and Tobago
$_country_lang["214"] = 'טוניסיה'; // Tunisia
$_country_lang["215"] = 'טורקיה'; // Turkey
$_country_lang["216"] = 'טורקמניסטן'; // Turkmenistan
$_country_lang["217"] = 'איי טרקס וקייקוס'; // Turks and Caicos Islands
$_country_lang["218"] = 'טובאלו'; // Tuvalu
$_country_lang["219"] = 'אוגנדה'; // Uganda
$_country_lang["220"] = 'אוקראינה'; // Ukraine
$_country_lang["221"] = 'איחוד האמירויות הערביות'; // United Arab Emirates
$_country_lang["222"] = 'בריטניה'; // United Kingdom
$_country_lang["223"] = 'ארצות הברית'; // United States
$_country_lang["224"] = 'האיים המינוריים של ארצות הברית'; // United States Minor Outlying Islands
$_country_lang["225"] = 'אורוגוואי'; // Uruguay
$_country_lang["226"] = 'אוזבקיסטן'; // Uzbekistan
$_country_lang["227"] = 'ונואטו'; // Vanuatu
$_country_lang["228"] = 'מדינת הוותיקאן (הכס הקדוש)'; // Vatican City State (Holy See)
$_country_lang["229"] = 'ונצואלה'; // Venezuela
$_country_lang["230"] = 'וייטנאם'; // Viet Nam
$_country_lang["231"] = 'איי הבתולה (בריטניה)'; // Virgin Islands (British)
$_country_lang["232"] = 'איי הבתולה (ארה"ב)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'איי ווליס ופוטונה'; // Wallis and Futuna Islands
$_country_lang["234"] = 'סהרה המערבית'; // Western Sahara
$_country_lang["235"] = 'תימן'; // Yemen
$_country_lang["236"] = 'סרביה ומונטנגרו'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'קונגו, הרפובליקה הדמוקרטית של'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'זמביה'; // Zambia
$_country_lang["239"] = 'זימבבואה'; // Zimbabwe
?>