<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'अफ़गानिस्तान'; // Afghanistan
$_country_lang["2"] = 'अल्बानिया'; // Albania
$_country_lang["3"] = 'अल्जीरिया'; // Algeria
$_country_lang["4"] = 'अमेरिकन समोआ'; // American Samoa
$_country_lang["5"] = 'अंडोरा'; // Andorra
$_country_lang["6"] = 'अंगोला'; // Angola
$_country_lang["7"] = 'एंगुइला'; // Anguilla
$_country_lang["8"] = 'अंटार्कटिका'; // Antarctica
$_country_lang["9"] = 'एंटिगुआ और बरबुडा'; // Antigua and Barbuda
$_country_lang["10"] = 'अर्जेंटीना'; // Argentina
$_country_lang["11"] = 'आर्मीनिया'; // Armenia
$_country_lang["12"] = 'अरूबा'; // Aruba
$_country_lang["13"] = 'ऑस्ट्रेलिया'; // Australia
$_country_lang["14"] = 'ऑस्ट्रिया'; // Austria
$_country_lang["15"] = 'अज़रबैजान'; // Azerbaijan
$_country_lang["16"] = 'बहामा'; // Bahamas
$_country_lang["17"] = 'बहरीन'; // Bahrain
$_country_lang["18"] = 'बांग्लादेश'; // Bangladesh
$_country_lang["19"] = 'बारबाडोस'; // Barbados
$_country_lang["20"] = 'बेलारूस'; // Belarus
$_country_lang["21"] = 'बेल्जियम'; // Belgium
$_country_lang["22"] = 'बेलीज़'; // Belize
$_country_lang["23"] = 'बेनिन'; // Benin
$_country_lang["24"] = 'बरमूडा'; // Bermuda
$_country_lang["25"] = 'भूटान'; // Bhutan
$_country_lang["26"] = 'बोलीविया'; // Bolivia
$_country_lang["27"] = 'बोस्निया और हर्जेगोविना'; // Bosnia and Herzegowina
$_country_lang["28"] = 'बोत्सवाना'; // Botswana
$_country_lang["29"] = 'बुवेत आइलैंड'; // Bouvet Island
$_country_lang["30"] = 'ब्राज़ील'; // Brazil
$_country_lang["31"] = 'ब्रिटिश हिंद महासागरीय क्षेत्र'; // British Indian Ocean Territory
$_country_lang["32"] = 'ब्रुनेई दारुस्सलाम'; // Brunei Darussalam
$_country_lang["33"] = 'बल्गारिया'; // Bulgaria
$_country_lang["34"] = 'बुर्किना फासो'; // Burkina Faso
$_country_lang["35"] = 'बुरुंडी'; // Burundi
$_country_lang["36"] = 'कंबोडिया'; // Cambodia
$_country_lang["37"] = 'कैमरून'; // Cameroon
$_country_lang["38"] = 'कनाडा'; // Canada
$_country_lang["39"] = 'केप वर्दे'; // Cape Verde
$_country_lang["40"] = 'केमैन द्वीप'; // Cayman Islands
$_country_lang["41"] = 'मध्य अफ्रीकी गणराज्य'; // Central African Republic
$_country_lang["42"] = 'चाड'; // Chad
$_country_lang["43"] = 'चिली'; // Chile
$_country_lang["44"] = 'चीन'; // China
$_country_lang["45"] = 'क्रिसमस द्वीप'; // Christmas Island
$_country_lang["46"] = 'कोकोस (कीलिंग) द्वीप समूह'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'कोलंबिया'; // Colombia
$_country_lang["48"] = 'कोमोरोस'; // Comoros
$_country_lang["49"] = 'कांगो, गणराज्य'; // Congo
$_country_lang["50"] = 'कुक आइलैंड्स'; // Cook Islands
$_country_lang["51"] = 'कोस्टा रिका'; // Costa Rica
$_country_lang["52"] = 'कोटे डी &#39; Ivoire'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'क्रोएशिया'; // Croatia
$_country_lang["54"] = 'क्यूबा'; // Cuba
$_country_lang["55"] = 'साइप्रस'; // Cyprus
$_country_lang["56"] = 'चेक गणराज्य'; // Czech Republic
$_country_lang["57"] = 'डेनमार्क'; // Denmark
$_country_lang["58"] = 'जिबूती'; // Djibouti
$_country_lang["59"] = 'डोमिनिका'; // Dominica
$_country_lang["60"] = 'डॉमिनिकन गणराज्य'; // Dominican Republic
$_country_lang["61"] = 'पूर्वी तिमोर'; // East Timor
$_country_lang["62"] = 'इक्वेडोर'; // Ecuador
$_country_lang["63"] = 'मिस्र'; // Egypt
$_country_lang["64"] = 'अल साल्वाडोर'; // El Salvador
$_country_lang["65"] = 'इक्वेटोरियल गिनी'; // Equatorial Guinea
$_country_lang["66"] = 'इरिट्रिया'; // Eritrea
$_country_lang["67"] = 'एस्टोनिया'; // Estonia
$_country_lang["68"] = 'इथियोपिया'; // Ethiopia
$_country_lang["69"] = 'फ़ॉकलैंड द्वीप (माल्विनास)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'फ़ैरो आइलैंड्स'; // Faroe Islands
$_country_lang["71"] = 'फिजी'; // Fiji
$_country_lang["72"] = 'फ़िनलैंड'; // Finland
$_country_lang["73"] = 'फ़्रांस'; // France
$_country_lang["74"] = 'फ़्रांस, मेट्रोपोलिटन'; // France, Metropolitan
$_country_lang["75"] = 'फ्रेंच गयाना'; // French Guiana
$_country_lang["76"] = 'फ़्रेंच पोलिनेशिया'; // French Polynesia
$_country_lang["77"] = 'फ़्रांसीसी दक्षिणी क्षेत्र'; // French Southern Territories
$_country_lang["78"] = 'गैबॉन'; // Gabon
$_country_lang["79"] = 'गाम्बिया'; // Gambia
$_country_lang["80"] = 'जॉर्जिया'; // Georgia
$_country_lang["81"] = 'जर्मनी'; // Germany
$_country_lang["82"] = 'घाना'; // Ghana
$_country_lang["83"] = 'जिब्राल्टर'; // Gibraltar
$_country_lang["84"] = 'यूनान'; // Greece
$_country_lang["85"] = 'ग्रीनलैंड'; // Greenland
$_country_lang["86"] = 'ग्रेनाडा'; // Grenada
$_country_lang["87"] = 'ग्वाडेलोप'; // Guadeloupe
$_country_lang["88"] = 'गुआम'; // Guam
$_country_lang["89"] = 'ग्वाटेमाला'; // Guatemala
$_country_lang["90"] = 'गिनी'; // Guinea
$_country_lang["91"] = 'Guinea-bissau'; // Guinea-bissau
$_country_lang["92"] = 'गुयाना'; // Guyana
$_country_lang["93"] = 'हैती'; // Haiti
$_country_lang["94"] = 'सुना और Mc डोनाल्ड द्वीप'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'होंडुरास'; // Honduras
$_country_lang["96"] = 'Hong काँग'; // Hong Kong
$_country_lang["97"] = 'हंगरी'; // Hungary
$_country_lang["98"] = 'आइसलैंड'; // Iceland
$_country_lang["99"] = 'भारत'; // India
$_country_lang["100"] = 'इंडोनेशिया'; // Indonesia
$_country_lang["101"] = 'ईरान (इस्लामिक गणराज्य)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'इराक'; // Iraq
$_country_lang["103"] = 'आयरलैंड'; // Ireland
$_country_lang["104"] = 'इज़राइल'; // Israel
$_country_lang["105"] = 'इटली'; // Italy
$_country_lang["106"] = 'जमैका'; // Jamaica
$_country_lang["107"] = 'जापान'; // Japan
$_country_lang["108"] = 'जॉर्डन'; // Jordan
$_country_lang["109"] = 'कज़ाकस्तान'; // Kazakhstan
$_country_lang["110"] = 'केन्या'; // Kenya
$_country_lang["111"] = 'किरिबाती'; // Kiribati
$_country_lang["112"] = 'कोरिया, जनतांत्रिक लोगों &#39; के एस गणराज्य'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'कोरिया, रिपब्लिक ऑफ'; // Korea, Republic of
$_country_lang["114"] = 'कुवैत'; // Kuwait
$_country_lang["115"] = 'किरगिज़स्तान'; // Kyrgyzstan
$_country_lang["116"] = 'लाओस पीपुल &#39; s लोकतांत्रिक गणराज्य'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'लाटविया'; // Latvia
$_country_lang["118"] = 'लेबनान'; // Lebanon
$_country_lang["119"] = 'लेसोथो'; // Lesotho
$_country_lang["120"] = 'लाइबेरिया'; // Liberia
$_country_lang["121"] = 'लिबियाई अरब जमहीरिया'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'लिचेंस्टीन'; // Liechtenstein
$_country_lang["123"] = 'लिथुआनिया'; // Lithuania
$_country_lang["124"] = 'लक्ज़म्बर्ग'; // Luxembourg
$_country_lang["125"] = 'मकाउ'; // Macau
$_country_lang["126"] = 'मैसेडोनिया, पूर्व यूगोस्लाव गणराज्य'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'मेडागास्कर'; // Madagascar
$_country_lang["128"] = 'मलावी'; // Malawi
$_country_lang["129"] = 'मलेशिया'; // Malaysia
$_country_lang["130"] = 'मालदीव'; // Maldives
$_country_lang["131"] = 'माली'; // Mali
$_country_lang["132"] = 'माल्टा'; // Malta
$_country_lang["133"] = 'मार्शल द्वीप'; // Marshall Islands
$_country_lang["134"] = 'मार्टिनिक'; // Martinique
$_country_lang["135"] = 'मॉरिटानिया'; // Mauritania
$_country_lang["136"] = 'मॉरीशस'; // Mauritius
$_country_lang["137"] = 'मैयट'; // Mayotte
$_country_lang["138"] = 'मेक्सिको'; // Mexico
$_country_lang["139"] = 'माइक्रोनेशिया, फेडेरेटड स्टेट्स ऑफ'; // Micronesia, Federated States of
$_country_lang["140"] = 'मोलदोवा, रिपब्लिक ऑफ'; // Moldova, Republic of
$_country_lang["141"] = 'मोनाको'; // Monaco
$_country_lang["142"] = 'मंगोलिया'; // Mongolia
$_country_lang["241"] = 'मोंटेनेग्रो'; //Montenegro
$_country_lang["143"] = 'मोंटसेराट'; // Montserrat
$_country_lang["144"] = 'मोरक्को'; // Morocco
$_country_lang["145"] = 'मोजाम्बिक'; // Mozambique
$_country_lang["146"] = 'म्यांमार'; // Myanmar
$_country_lang["147"] = 'नामीबिया'; // Namibia
$_country_lang["148"] = 'नाउरू'; // Nauru
$_country_lang["149"] = 'नेपाल'; // Nepal
$_country_lang["150"] = 'नीदरलैंड'; // Netherlands
$_country_lang["151"] = 'नीदरलैंड एंटिल्स'; // Netherlands Antilles
$_country_lang["152"] = 'न्यू कैलेडोनिया'; // New Caledonia
$_country_lang["153"] = 'न्यूज़ीलैंड'; // New Zealand
$_country_lang["154"] = 'निकारागुआ'; // Nicaragua
$_country_lang["155"] = 'नाइजर'; // Niger
$_country_lang["156"] = 'नाइजीरिया'; // Nigeria
$_country_lang["157"] = 'नियू'; // Niue
$_country_lang["158"] = 'नॉरफ़ॉक द्वीप'; // Norfolk Island
$_country_lang["159"] = 'नार्दर्न मैरियाना आइलैंड्स'; // Northern Mariana Islands
$_country_lang["160"] = 'नॉर्वे'; // Norway
$_country_lang["161"] = 'ओमान'; // Oman
$_country_lang["162"] = 'पाकिस्तान'; // Pakistan
$_country_lang["163"] = 'पलाऊ'; // Palau
$_country_lang["164"] = 'पनामा'; // Panama
$_country_lang["165"] = 'पापुआ न्यू गिनी'; // Papua New Guinea
$_country_lang["166"] = 'पैराग्वे'; // Paraguay
$_country_lang["167"] = 'पेरू'; // Peru
$_country_lang["168"] = 'फिलीपींस'; // Philippines
$_country_lang["169"] = 'पिटकेर्न'; // Pitcairn
$_country_lang["170"] = 'पोलैंड'; // Poland
$_country_lang["171"] = 'पुर्तगाल'; // Portugal
$_country_lang["172"] = 'पर्टो रिको'; // Puerto Rico
$_country_lang["173"] = 'कतर'; // Qatar
$_country_lang["174"] = 'रीयूनियन'; // Reunion
$_country_lang["175"] = 'रोमानिया'; // Romania
$_country_lang["176"] = 'रूसी संघ'; // Russian Federation
$_country_lang["177"] = 'रवांडा'; // Rwanda
$_country_lang["178"] = 'सेंट किट्स और नेविस'; // Saint Kitts and Nevis
$_country_lang["179"] = 'सेंट लूसिया'; // Saint Lucia
$_country_lang["180"] = 'संत Vincent और ग्रेनेजियन्स'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'समोआ'; // Samoa
$_country_lang["182"] = 'सैन मैरिनो'; // San Marino
$_country_lang["183"] = 'साओ टोम और प्रिंसिपे'; // Sao Tome and Principe
$_country_lang["184"] = 'सऊदी अरब'; // Saudi Arabia
$_country_lang["185"] = 'सेनेगल'; // Senegal
$_country_lang["240"] = 'सर्बिया'; //Serbia
$_country_lang["186"] = 'सेशल्स'; // Seychelles
$_country_lang["187"] = 'सिएरा लियोन'; // Sierra Leone
$_country_lang["188"] = 'सिंगापुर'; // Singapore
$_country_lang["189"] = 'स्लोवाकिया (स्लोवाक गणराज्य)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'स्लोवेनिया'; // Slovenia
$_country_lang["191"] = 'सोलोमन द्वीप समूह'; // Solomon Islands
$_country_lang["192"] = 'सोमालिया'; // Somalia
$_country_lang["193"] = 'दक्षिण अफ़्रीका'; // South Africa
$_country_lang["194"] = 'दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीप समूह'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'स्पेन'; // Spain
$_country_lang["196"] = 'श्री लंका'; // Sri Lanka
$_country_lang["197"] = 'सेंट हेलेना'; // St. Helena
$_country_lang["198"] = 'सेंट Pierre और मिकेलॉन'; // St. Pierre and Miquelon
$_country_lang["199"] = 'सूडान'; // Sudan
$_country_lang["200"] = 'सूरीनाम'; // Suriname
$_country_lang["201"] = 'स्वालबार्ड और जेन मेयन आइलैंड्स'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'स्वाज़ीलैंड'; // Swaziland
$_country_lang["203"] = 'स्वीडन'; // Sweden
$_country_lang["204"] = 'स्विट्ज़रलैंड'; // Switzerland
$_country_lang["205"] = 'सीरियाई अरब गणराज्य'; // Syrian Arab Republic
$_country_lang["206"] = 'ताइवान'; // Taiwan
$_country_lang["207"] = 'ताजिकिस्तान'; // Tajikistan
$_country_lang["208"] = 'तंज़ानिया, युनाइटेड रिपब्लिक ऑफ'; // Tanzania, United Republic of
$_country_lang["209"] = 'थाईलैंड'; // Thailand
$_country_lang["210"] = 'टोगो'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'टोंगा'; // Tonga
$_country_lang["213"] = 'त्रिनिदाद और टोबैगो'; // Trinidad and Tobago
$_country_lang["214"] = 'ट्यूनीशिया'; // Tunisia
$_country_lang["215"] = 'तुर्कस्तान'; // Turkey
$_country_lang["216"] = 'तुर्कमेनिस्तान'; // Turkmenistan
$_country_lang["217"] = 'तुर्क्स ऐंड कैकोज़ आइलैंड्स'; // Turks and Caicos Islands
$_country_lang["218"] = 'तुवालु'; // Tuvalu
$_country_lang["219"] = 'युगांडा'; // Uganda
$_country_lang["220"] = 'यूक्रेन'; // Ukraine
$_country_lang["221"] = 'संयुक्त अरब अमीरात'; // United Arab Emirates
$_country_lang["222"] = 'युनाइटेड किंगडम'; // United Kingdom
$_country_lang["223"] = 'संयुक्त राज्य'; // United States
$_country_lang["224"] = 'युनाइटेड स्टेट्स माइनर आउटलाइंग द्वीप'; // United States Minor Outlying Islands
$_country_lang["225"] = 'उरुग्वे'; // Uruguay
$_country_lang["226"] = 'उज़्बेकिस्तान'; // Uzbekistan
$_country_lang["227"] = 'वानुअतु'; // Vanuatu
$_country_lang["228"] = 'वैटिकन सिटी स्टेट (होली)'; // Vatican City State (Holy See)
$_country_lang["229"] = 'वेनेज़ुएला'; // Venezuela
$_country_lang["230"] = 'वियतनाम'; // Viet Nam
$_country_lang["231"] = 'वर्जिन द्वीप (ब्रिटिश)'; // Virgin Islands (British)
$_country_lang["232"] = 'वर्जिन द्वीप समूह (यूएस)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'वालिस और फ़्यूचूना द्वीप'; // Wallis and Futuna Islands
$_country_lang["234"] = 'पश्चिमी सहारा'; // Western Sahara
$_country_lang["235"] = 'यमन'; // Yemen
$_country_lang["236"] = 'सर्बिया और मॉन्टेंगरो'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'कांगो, लोकतांत्रिक गणराज्य'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'ज़ाम्बिया'; // Zambia
$_country_lang["239"] = 'ज़िम्बाब्वे'; // Zimbabwe
?>