<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afganisztán'; // Afghanistan
$_country_lang["2"] = 'Albánia'; // Albania
$_country_lang["3"] = 'Algéria'; // Algeria
$_country_lang["4"] = 'Amerikai Szamoa'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antarktisz'; // Antarctica
$_country_lang["9"] = 'Antigua és Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentína'; // Argentina
$_country_lang["11"] = 'Örményország'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Ausztrália'; // Australia
$_country_lang["14"] = 'Ausztria'; // Austria
$_country_lang["15"] = 'Azerbajdzsán'; // Azerbaijan
$_country_lang["16"] = 'Bahama-szigetek'; // Bahamas
$_country_lang["17"] = 'Bahrein'; // Bahrain
$_country_lang["18"] = 'Banglades'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Fehéroroszország'; // Belarus
$_country_lang["21"] = 'Belgium'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Bhután'; // Bhutan
$_country_lang["26"] = 'Bolívia'; // Bolivia
$_country_lang["27"] = 'Bosznia-Hercegovina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Bouvet-sziget'; // Bouvet Island
$_country_lang["30"] = 'Brazília'; // Brazil
$_country_lang["31"] = 'Brit Indiai-óceáni Terület'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgária'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Kambodzsa'; // Cambodia
$_country_lang["37"] = 'Kamerun'; // Cameroon
$_country_lang["38"] = 'Kanada'; // Canada
$_country_lang["39"] = 'Zöld-foki Köztársaság'; // Cape Verde
$_country_lang["40"] = 'Kajmán-szigetek'; // Cayman Islands
$_country_lang["41"] = 'Közép-afrikai Köztársaság'; // Central African Republic
$_country_lang["42"] = 'Csád'; // Chad
$_country_lang["43"] = 'Chile'; // Chile
$_country_lang["44"] = 'Kína'; // China
$_country_lang["45"] = 'Karácsony-sziget'; // Christmas Island
$_country_lang["46"] = 'Kókusz (Keeling)-szigetek'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Kolumbia'; // Colombia
$_country_lang["48"] = 'Comore-szigetek'; // Comoros
$_country_lang["49"] = 'Kongói Köztársaság'; // Congo
$_country_lang["50"] = 'Cook-szigetek'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Elefántcsontpart'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Horvátország'; // Croatia
$_country_lang["54"] = 'Kuba'; // Cuba
$_country_lang["55"] = 'Ciprus'; // Cyprus
$_country_lang["56"] = 'Csehország'; // Czech Republic
$_country_lang["57"] = 'Dánia'; // Denmark
$_country_lang["58"] = 'Dzsibuti'; // Djibouti
$_country_lang["59"] = 'Dominikai Közösség'; // Dominica
$_country_lang["60"] = 'Dominikai Köztársaság'; // Dominican Republic
$_country_lang["61"] = 'Kelet-Timor'; // East Timor
$_country_lang["62"] = 'Ecuador'; // Ecuador
$_country_lang["63"] = 'Egyiptom'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Egyenlítői-Guinea'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Észtország'; // Estonia
$_country_lang["68"] = 'Etiópia'; // Ethiopia
$_country_lang["69"] = 'Falkland-szigetek'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Feröer-szigetek'; // Faroe Islands
$_country_lang["71"] = 'Fidzsi'; // Fiji
$_country_lang["72"] = 'Finnország'; // Finland
$_country_lang["73"] = 'Franciaország'; // France
$_country_lang["74"] = 'Franciaország (Európai területek)'; // France, Metropolitan
$_country_lang["75"] = 'Francia Guyana'; // French Guiana
$_country_lang["76"] = 'Francia Polinézia'; // French Polynesia
$_country_lang["77"] = 'Francia déli és antarktiszi területek'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Grúzia'; // Georgia
$_country_lang["81"] = 'Németország'; // Germany
$_country_lang["82"] = 'Ghána'; // Ghana
$_country_lang["83"] = 'Gibraltár'; // Gibraltar
$_country_lang["84"] = 'Görögország'; // Greece
$_country_lang["85"] = 'Grönland'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Bissau-Guinea'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Heard-sziget és McDonald-szigetek'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hongkong'; // Hong Kong
$_country_lang["97"] = 'Magyarország'; // Hungary
$_country_lang["98"] = 'Izland'; // Iceland
$_country_lang["99"] = 'India'; // India
$_country_lang["100"] = 'Indonézia'; // Indonesia
$_country_lang["101"] = 'Irán'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irak'; // Iraq
$_country_lang["103"] = 'Írország'; // Ireland
$_country_lang["104"] = 'Izrael'; // Israel
$_country_lang["105"] = 'Olaszország'; // Italy
$_country_lang["106"] = 'Jamaica'; // Jamaica
$_country_lang["107"] = 'Japán'; // Japan
$_country_lang["108"] = 'Jordánia'; // Jordan
$_country_lang["109"] = 'Kazahsztán'; // Kazakhstan
$_country_lang["110"] = 'Kenya'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Koreai Népi Demokratikus Köztársaság (Észak-Korea)'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Koreai Köztársaság (Dél-Korea)'; // Korea, Republic of
$_country_lang["114"] = 'Kuvait'; // Kuwait
$_country_lang["115"] = 'Kirgizisztán'; // Kyrgyzstan
$_country_lang["116"] = 'Laoszi Népi Demokratikus Köztársaság'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Lettország'; // Latvia
$_country_lang["118"] = 'Libanon'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Libéria'; // Liberia
$_country_lang["121"] = 'Líbia'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Litvánia'; // Lithuania
$_country_lang["124"] = 'Luxemburg'; // Luxembourg
$_country_lang["125"] = 'Makaó'; // Macau
$_country_lang["126"] = 'Macedónia'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaszkár'; // Madagascar
$_country_lang["128"] = 'Malawi Köztársaság'; // Malawi
$_country_lang["129"] = 'Malajzia'; // Malaysia
$_country_lang["130"] = 'Maldív-szigetek'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Málta'; // Malta
$_country_lang["133"] = 'Marshall-szigetek'; // Marshall Islands
$_country_lang["134"] = 'Martinique'; // Martinique
$_country_lang["135"] = 'Mauritánia'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Mexikó'; // Mexico
$_country_lang["139"] = 'Mikronézia'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldova'; // Moldova, Republic of
$_country_lang["141"] = 'Monaco'; // Monaco
$_country_lang["142"] = 'Mongólia'; // Mongolia
$_country_lang["241"] = 'Montenegró'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Marokkó'; // Morocco
$_country_lang["145"] = 'Mozambik'; // Mozambique
$_country_lang["146"] = 'Mianmar'; // Myanmar
$_country_lang["147"] = 'Namíbia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepál'; // Nepal
$_country_lang["150"] = 'Hollandia'; // Netherlands
$_country_lang["151"] = 'Holland Antillák'; // Netherlands Antilles
$_country_lang["152"] = 'Új-Kaledónia'; // New Caledonia
$_country_lang["153"] = 'Új-Zéland'; // New Zealand
$_country_lang["154"] = 'Nicaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigéria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolk-sziget'; // Norfolk Island
$_country_lang["159"] = 'Északi-Mariana-szigetek'; // Northern Mariana Islands
$_country_lang["160"] = 'Norvégia'; // Norway
$_country_lang["161"] = 'Omán'; // Oman
$_country_lang["162"] = 'Pakisztán'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Pápua Új-Guinea'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Peru'; // Peru
$_country_lang["168"] = 'Fülöp-szigetek'; // Philippines
$_country_lang["169"] = 'Pitcairn-szigetek'; // Pitcairn
$_country_lang["170"] = 'Lengyelország'; // Poland
$_country_lang["171"] = 'Portugália'; // Portugal
$_country_lang["172"] = 'Puerto Rico'; // Puerto Rico
$_country_lang["173"] = 'Katar'; // Qatar
$_country_lang["174"] = 'Réunion'; // Reunion
$_country_lang["175"] = 'Románia'; // Romania
$_country_lang["176"] = 'Oroszország'; // Russian Federation
$_country_lang["177"] = 'Ruanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts és Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Saint Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent és a Grenadine-szigetek'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Szamoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'São Tomé és Príncipe'; // Sao Tome and Principe
$_country_lang["184"] = 'Szaúd-Arábia'; // Saudi Arabia
$_country_lang["185"] = 'Szenegál'; // Senegal
$_country_lang["240"] = 'Szerbia'; //Serbia
$_country_lang["186"] = 'Seychelle-szigetek'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Szingapúr'; // Singapore
$_country_lang["189"] = 'Szlovákia'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Szlovénia'; // Slovenia
$_country_lang["191"] = 'Salamon-szigetek'; // Solomon Islands
$_country_lang["192"] = 'Szomália'; // Somalia
$_country_lang["193"] = 'Dél-afrikai Köztársaság'; // South Africa
$_country_lang["194"] = 'Déli-Georgia és Déli-Sandwich-szigetek'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Spanyolország'; // Spain
$_country_lang["196"] = 'Srí Lanka'; // Sri Lanka
$_country_lang["197"] = 'Szent Ilona'; // St. Helena
$_country_lang["198"] = 'St. Pierre és Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Szudán'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Svalbard- és Jan Mayen-szigetek'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Szváziföld'; // Swaziland
$_country_lang["203"] = 'Svédország'; // Sweden
$_country_lang["204"] = 'Svájc'; // Switzerland
$_country_lang["205"] = 'Szíria'; // Syrian Arab Republic
$_country_lang["206"] = 'Tajvan'; // Taiwan
$_country_lang["207"] = 'Tádzsikisztán'; // Tajikistan
$_country_lang["208"] = 'Tanzánia'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thaiföld'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau-szigetek'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad és Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunézia'; // Tunisia
$_country_lang["215"] = 'Törökország'; // Turkey
$_country_lang["216"] = 'Türkmenisztán'; // Turkmenistan
$_country_lang["217"] = 'Turks- és Caicos-szigetek'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukrajna'; // Ukraine
$_country_lang["221"] = 'Egyesült Arab Emírségek'; // United Arab Emirates
$_country_lang["222"] = 'Egyesült Királyság'; // United Kingdom
$_country_lang["223"] = 'Egyesült Államok'; // United States
$_country_lang["224"] = 'USA Csendes-óceáni szigetek'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Üzbegisztán'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vatikán'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Vietnam'; // Viet Nam
$_country_lang["231"] = 'Virgin-szigetek (Brit)'; // Virgin Islands (British)
$_country_lang["232"] = 'Virgin-szigetek (Amerikai)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis-és Futuna-szigetek'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Nyugat-Szahara'; // Western Sahara
$_country_lang["235"] = 'Jemen'; // Yemen
$_country_lang["236"] = 'Szerbia és Montenegró'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Kongói Demokratikus Köztársaság'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>