<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afganistan'; // Afghanistan
$_country_lang["2"] = 'Albania'; // Albania
$_country_lang["3"] = 'Algeria'; // Algeria
$_country_lang["4"] = 'Samoa Amerika'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antartika'; // Antarctica
$_country_lang["9"] = 'Antigua dan Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentina'; // Argentina
$_country_lang["11"] = 'Armenia'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Australia'; // Australia
$_country_lang["14"] = 'Austria'; // Austria
$_country_lang["15"] = 'Azerbaijan'; // Azerbaijan
$_country_lang["16"] = 'Bahama'; // Bahamas
$_country_lang["17"] = 'Bahrain'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Belarus'; // Belarus
$_country_lang["21"] = 'Belgia'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Bhutan'; // Bhutan
$_country_lang["26"] = 'Bolivia'; // Bolivia
$_country_lang["27"] = 'Bosnia dan Herzegowina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Pulau Bouvet'; // Bouvet Island
$_country_lang["30"] = 'Brazil'; // Brazil
$_country_lang["31"] = 'Teritori Laut India Inggris'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei Darussalam'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgaria'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Kamboja'; // Cambodia
$_country_lang["37"] = 'Kamerun'; // Cameroon
$_country_lang["38"] = 'Kanada'; // Canada
$_country_lang["39"] = 'Tanjung Verde'; // Cape Verde
$_country_lang["40"] = 'Kayman, Kepulauan'; // Cayman Islands
$_country_lang["41"] = 'Afrika Tengah, Republik'; // Central African Republic
$_country_lang["42"] = 'Chad'; // Chad
$_country_lang["43"] = 'Chili'; // Chile
$_country_lang["44"] = 'Cina'; // China
$_country_lang["45"] = 'Krismas, Kepulauan'; // Christmas Island
$_country_lang["46"] = 'Kokos (Keeling), Kepulauan'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Kolombia'; // Colombia
$_country_lang["48"] = 'Komoro'; // Comoros
$_country_lang["49"] = 'Kongo, Republik'; // Congo
$_country_lang["50"] = 'Cook, Kepulauan'; // Cook Islands
$_country_lang["51"] = 'Kosta Rika'; // Costa Rica
$_country_lang["52"] = 'Pantai Gading'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Kroasia'; // Croatia
$_country_lang["54"] = 'Kuba'; // Cuba
$_country_lang["55"] = 'Siprus'; // Cyprus
$_country_lang["56"] = 'Ceko'; // Czech Republic
$_country_lang["57"] = 'Denmark'; // Denmark
$_country_lang["58"] = 'Djibouti'; // Djibouti
$_country_lang["59"] = 'Dominika'; // Dominica
$_country_lang["60"] = 'Dominika, Republik'; // Dominican Republic
$_country_lang["61"] = 'Timor Leste'; // East Timor
$_country_lang["62"] = 'Ekuador'; // Ecuador
$_country_lang["63"] = 'Mesir'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Guinea Khatulistiwa'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Estonia'; // Estonia
$_country_lang["68"] = 'Etiopia'; // Ethiopia
$_country_lang["69"] = 'Falkland, Kepulauan'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Faroe, Kepulauan'; // Faroe Islands
$_country_lang["71"] = 'Fiji'; // Fiji
$_country_lang["72"] = 'Finland'; // Finland
$_country_lang["73"] = 'Perancis'; // France
$_country_lang["74"] = 'Perancis Metropolitan'; // France, Metropolitan
$_country_lang["75"] = 'Guyana Perancis'; // French Guiana
$_country_lang["76"] = 'Polinesia Perancis'; // French Polynesia
$_country_lang["77"] = 'Daratan Selatan Perancis'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Georgia'; // Georgia
$_country_lang["81"] = 'Jerman'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Yunani'; // Greece
$_country_lang["85"] = 'Greenland'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Guinea-bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Heard dan Mc Donald, Kepulauan'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Hungaria'; // Hungary
$_country_lang["98"] = 'Islandia'; // Iceland
$_country_lang["99"] = 'India'; // India
$_country_lang["100"] = 'Indonesia'; // Indonesia
$_country_lang["101"] = 'Iran, Republik Islam'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irak'; // Iraq
$_country_lang["103"] = 'Irlandia'; // Ireland
$_country_lang["104"] = 'Israel'; // Israel
$_country_lang["105"] = 'Itali'; // Italy
$_country_lang["106"] = 'Jamaika'; // Jamaica
$_country_lang["107"] = 'Jepang'; // Japan
$_country_lang["108"] = 'Jordania'; // Jordan
$_country_lang["109"] = 'Kazakhstan'; // Kazakhstan
$_country_lang["110"] = 'Kenya'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Korea, Republik Rakyat Demokrasi'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Korea, Republik'; // Korea, Republic of
$_country_lang["114"] = 'Kuwait'; // Kuwait
$_country_lang["115"] = 'Kirgistan'; // Kyrgyzstan
$_country_lang["116"] = 'Lao, Republik Demokratis Rakyat'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Latvia'; // Latvia
$_country_lang["118"] = 'Libanon'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Liberia'; // Liberia
$_country_lang["121"] = 'Libya'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Lituania'; // Lithuania
$_country_lang["124"] = 'Luksemburg'; // Luxembourg
$_country_lang["125"] = 'Makao'; // Macau
$_country_lang["126"] = 'Macedonia, bekas Republik Yugoslavia'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaskar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malaysia'; // Malaysia
$_country_lang["130"] = 'Maladewa'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Kepulauan Marshall'; // Marshall Islands
$_country_lang["134"] = 'Martinik'; // Martinique
$_country_lang["135"] = 'Mauritania'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Meksiko'; // Mexico
$_country_lang["139"] = 'Mikronesia, negara Federasi'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldova, Republik'; // Moldova, Republic of
$_country_lang["141"] = 'Monako'; // Monaco
$_country_lang["142"] = 'Mongolia'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Maroko'; // Morocco
$_country_lang["145"] = 'Mozambik'; // Mozambique
$_country_lang["146"] = 'Myanmar'; // Myanmar
$_country_lang["147"] = 'Namibia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Belanda'; // Netherlands
$_country_lang["151"] = 'Belanda, Antillen'; // Netherlands Antilles
$_country_lang["152"] = 'Kaledonia Baru'; // New Caledonia
$_country_lang["153"] = 'Selandia Baru'; // New Zealand
$_country_lang["154"] = 'Nikaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolk, Pulau'; // Norfolk Island
$_country_lang["159"] = 'Mariana Utara, Kepulauan'; // Northern Mariana Islands
$_country_lang["160"] = 'Norwegia'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papua Nugini'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Peru'; // Peru
$_country_lang["168"] = 'Filipina'; // Philippines
$_country_lang["169"] = 'Pitcairn, Kepulauan'; // Pitcairn
$_country_lang["170"] = 'Polandia'; // Poland
$_country_lang["171"] = 'Portugal'; // Portugal
$_country_lang["172"] = 'Puerto Riko'; // Puerto Rico
$_country_lang["173"] = 'Qatar'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Rumania'; // Romania
$_country_lang["176"] = 'Rusia'; // Russian Federation
$_country_lang["177"] = 'Rwanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts and Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Saint Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent and the Grenadines'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'Sao Tome dan Principe, Republik'; // Sao Tome and Principe
$_country_lang["184"] = 'Arab Saudi'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'Serbia'; //Serbia
$_country_lang["186"] = 'Seychelles, Republik'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapura'; // Singapore
$_country_lang["189"] = 'Slowakia'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Slovenia'; // Slovenia
$_country_lang["191"] = 'Solomon, Kepulauan'; // Solomon Islands
$_country_lang["192"] = 'Somalia'; // Somalia
$_country_lang["193"] = 'Afrika Selatan'; // South Africa
$_country_lang["194"] = 'Georgia Selatan dan Kepulauan Sandwich Selatan'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Spanyol'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'St. Helena'; // St. Helena
$_country_lang["198"] = 'St. Pierre dan Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sudan'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Svalbard dan Kepulauan Jan Mayen'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Swazilandia'; // Swaziland
$_country_lang["203"] = 'Swedia'; // Sweden
$_country_lang["204"] = 'Swiss'; // Switzerland
$_country_lang["205"] = 'Syria'; // Syrian Arab Republic
$_country_lang["206"] = 'Taiwan'; // Taiwan
$_country_lang["207"] = 'Tajikistan'; // Tajikistan
$_country_lang["208"] = 'Tanzania, Persatuan Republik'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thailand'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad dan Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunisia'; // Tunisia
$_country_lang["215"] = 'Turki'; // Turkey
$_country_lang["216"] = 'Turkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Turks dan Caicos, Kepulauan'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukraina'; // Ukraine
$_country_lang["221"] = 'Uni Emirat Arab'; // United Arab Emirates
$_country_lang["222"] = 'Britania Raya'; // United Kingdom
$_country_lang["223"] = 'Amerika Serikat'; // United States
$_country_lang["224"] = 'Amerika Serikat, Kepulauan Terluar Kecil'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Uzbekistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vatikan'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Viet Nam'; // Viet Nam
$_country_lang["231"] = 'Virgin Britania Raya, Kepulauan'; // Virgin Islands (British)
$_country_lang["232"] = 'Virgin Amerika Serikat, Kepulauan'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis dan Futuna, Kepulauan'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Sahara Barat'; // Western Sahara
$_country_lang["235"] = 'Yemen'; // Yemen
$_country_lang["236"] = 'Serbia dan Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Kongo, Republik Demokratik'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>