<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
* Translation: Diego Meozzi
*/

$_country_lang["1"] = 'Afganistan'; // Afghanistan
$_country_lang["2"] = 'Albania'; // Albania
$_country_lang["3"] = 'Algeria'; // Algeria
$_country_lang["4"] = 'Samoa Americana'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antartide'; // Antarctica
$_country_lang["9"] = 'Antigua e Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentina'; // Argentina
$_country_lang["11"] = 'Armenia'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Australia'; // Australia
$_country_lang["14"] = 'Austria'; // Austria
$_country_lang["15"] = 'Azerbaigian'; // Azerbaijan
$_country_lang["16"] = 'Bahamas'; // Bahamas
$_country_lang["17"] = 'Bahrain'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Bielorussia'; // Belarus
$_country_lang["21"] = 'Belgio'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Bhutan'; // Bhutan
$_country_lang["26"] = 'Bolivia'; // Bolivia
$_country_lang["27"] = 'Bosnia e Erzegovina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Isola Bouvet'; // Bouvet Island
$_country_lang["30"] = 'Brasile'; // Brazil
$_country_lang["31"] = 'Territorio Britannico dell\'Oceano Indiano'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei Darussalam'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgaria'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Cambogia'; // Cambodia
$_country_lang["37"] = 'Camerun'; // Cameroon
$_country_lang["38"] = 'Canada'; // Canada
$_country_lang["39"] = 'Capo Verde'; // Cape Verde
$_country_lang["40"] = 'Isole Cayman'; // Cayman Islands
$_country_lang["41"] = 'Repubblica Centrafricana'; // Central African Republic
$_country_lang["42"] = 'Ciad'; // Chad
$_country_lang["43"] = 'Cile'; // Chile
$_country_lang["44"] = 'Cina'; // China
$_country_lang["45"] = 'Isola di Pasqua'; // Christmas Island
$_country_lang["46"] = 'Isole Cocos (Keeling)'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Colombia'; // Colombia
$_country_lang["48"] = 'Comore'; // Comoros
$_country_lang["49"] = 'Congo, Repubblica del'; // Congo
$_country_lang["50"] = 'Isole Cook'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Costa d\'Avorio'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Croazia'; // Croatia
$_country_lang["54"] = 'Cuba'; // Cuba
$_country_lang["55"] = 'Cipro'; // Cyprus
$_country_lang["56"] = 'Repubblica Ceca'; // Czech Republic
$_country_lang["57"] = 'Danimarca'; // Denmark
$_country_lang["58"] = 'Gibuti'; // Djibouti
$_country_lang["59"] = 'Dominica'; // Dominica
$_country_lang["60"] = 'Repubblica Dominicana'; // Dominican Republic
$_country_lang["61"] = 'Timor Est'; // East Timor
$_country_lang["62"] = 'Ecuador'; // Ecuador
$_country_lang["63"] = 'Egitto'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Guinea Equatoriale'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Estonia'; // Estonia
$_country_lang["68"] = 'Etiopia'; // Ethiopia
$_country_lang["69"] = 'Isole Falkland (Malvinas)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Isole Faroe'; // Faroe Islands
$_country_lang["71"] = 'Figi'; // Fiji
$_country_lang["72"] = 'Finlandia'; // Finland
$_country_lang["73"] = 'Francia'; // France
$_country_lang["74"] = 'Francia, Metropolitana'; // France, Metropolitan
$_country_lang["75"] = 'Guiana Francese'; // French Guiana
$_country_lang["76"] = 'Polynesia Francese'; // French Polynesia
$_country_lang["77"] = 'Territori Francesi del Sud'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Georgia'; // Georgia
$_country_lang["81"] = 'Germania'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibilterra'; // Gibraltar
$_country_lang["84"] = 'Grecia'; // Greece
$_country_lang["85"] = 'Groenlandia'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Guadalupa'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Guinea-bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Isole Heard e Mc Donald'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Ungheria'; // Hungary
$_country_lang["98"] = 'Islanda'; // Iceland
$_country_lang["99"] = 'India'; // India
$_country_lang["100"] = 'Indonesia'; // Indonesia
$_country_lang["101"] = 'Iran (Repubblica Islamica dell\')'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Iraq'; // Iraq
$_country_lang["103"] = 'Irlanda'; // Ireland
$_country_lang["104"] = 'Israele'; // Israel
$_country_lang["105"] = 'Italia'; // Italy
$_country_lang["106"] = 'Giamaica'; // Jamaica
$_country_lang["107"] = 'Giappone'; // Japan
$_country_lang["108"] = 'Giordania'; // Jordan
$_country_lang["109"] = 'Kazakistan'; // Kazakhstan
$_country_lang["110"] = 'Kenia'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Corea, Repubblica Democratica del Popolo di'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Corea, Repubblica di'; // Korea, Republic of
$_country_lang["114"] = 'Kuwait'; // Kuwait
$_country_lang["115"] = 'Kyrgyzstan'; // Kyrgyzstan
$_country_lang["116"] = 'Laos, Repubblica Democratica del Popolo del'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Lituania'; // Latvia
$_country_lang["118"] = 'Libano'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Liberia'; // Liberia
$_country_lang["121"] = 'Libyan Arab Jamahiriya'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Lituania'; // Lithuania
$_country_lang["124"] = 'Lussemburgo'; // Luxembourg
$_country_lang["125"] = 'Macau'; // Macau
$_country_lang["126"] = 'Macedonia'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagascar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malesia'; // Malaysia
$_country_lang["130"] = 'Maldive'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Isole Marshall'; // Marshall Islands
$_country_lang["134"] = 'Martinica'; // Martinique
$_country_lang["135"] = 'Mauritania'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Messico'; // Mexico
$_country_lang["139"] = 'Micronesia, Stati Federati della'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldavia, Repubblica di'; // Moldova, Republic of
$_country_lang["141"] = 'Monaco'; // Monaco
$_country_lang["142"] = 'Mongolia'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Marocco'; // Morocco
$_country_lang["145"] = 'Mozambico'; // Mozambique
$_country_lang["146"] = 'Myanmar'; // Myanmar
$_country_lang["147"] = 'Namibia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Olanda'; // Netherlands
$_country_lang["151"] = 'Antille Olandesi'; // Netherlands Antilles
$_country_lang["152"] = 'Nuova Caledonia'; // New Caledonia
$_country_lang["153"] = 'Nuova Zealand'; // New Zealand
$_country_lang["154"] = 'Nicaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Isola Norfolk Island'; // Norfolk Island
$_country_lang["159"] = 'Isole Marianne del Nord'; // Northern Mariana Islands
$_country_lang["160"] = 'Norvegia'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papua Nuova Guinea'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Per'; // Peru
$_country_lang["168"] = 'Filippine'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Polonia'; // Poland
$_country_lang["171"] = 'Portogallo'; // Portugal
$_country_lang["172"] = 'Portorico'; // Puerto Rico
$_country_lang["173"] = 'Qatar'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Romania'; // Romania
$_country_lang["176"] = 'Federazione Russa'; // Russian Federation
$_country_lang["177"] = 'Ruanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts e Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Santa Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent e Grenadines'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'Sao Tome e Principe'; // Sao Tome and Principe
$_country_lang["184"] = 'Arabia Saudita'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'Serbia'; //Serbia
$_country_lang["186"] = 'Seychelles'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapore'; // Singapore
$_country_lang["189"] = 'Slovacchia (Repubblica Slovacca)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Slovenia'; // Slovenia
$_country_lang["191"] = 'Isole Solomon'; // Solomon Islands
$_country_lang["192"] = 'Somalia'; // Somalia
$_country_lang["193"] = 'Sudafrica'; // South Africa
$_country_lang["194"] = 'Isole South Georgia e South Sandwich'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Spagna'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'St. Helena'; // St. Helena
$_country_lang["198"] = 'St. Pierre e Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sudan'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Isole Svalbard e Jan Mayen'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Swaziland'; // Swaziland
$_country_lang["203"] = 'Svezia'; // Sweden
$_country_lang["204"] = 'Svizzera'; // Switzerland
$_country_lang["205"] = 'Siria'; // Syrian Arab Republic
$_country_lang["206"] = 'Taiwan'; // Taiwan
$_country_lang["207"] = 'Tagikistan'; // Tajikistan
$_country_lang["208"] = 'Tanzania, Repubblica Unita della'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thailandia'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad and Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunisia'; // Tunisia
$_country_lang["215"] = 'Turchia'; // Turkey
$_country_lang["216"] = 'Turkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Isole Turks e Caicos'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ucraina'; // Ukraine
$_country_lang["221"] = 'Emorati Arabi Uniti'; // United Arab Emirates
$_country_lang["222"] = 'Regno Unito'; // United Kingdom
$_country_lang["223"] = 'Stati Uniti'; // United States
$_country_lang["224"] = 'United States Minor Outlying Islands'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Uzbekistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Cittˆ del Vaticano (Santa Sede)'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Viet Nam'; // Viet Nam
$_country_lang["231"] = 'Isole Vergini (Britanniche)'; // Virgin Islands (British)
$_country_lang["232"] = 'Isole Vergini (USA)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Isole Wallis e Futuna'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Sahara Occidentale'; // Western Sahara
$_country_lang["235"] = 'Yemen'; // Yemen
$_country_lang["236"] = 'Serbia e Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Congo, Repubblica Democratica del'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>