<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
* Translated: 8/12/2006
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'アフガニスタン'; // Afghanistan
$_country_lang["2"] = 'アルバニア'; // Albania
$_country_lang["3"] = 'アルジェリア'; // Algeria
$_country_lang["4"] = '米領サモア'; // American Samoa
$_country_lang["5"] = 'アンドラ'; // Andorra
$_country_lang["6"] = 'アンゴラ'; // Angola
$_country_lang["7"] = 'アンギラ'; // Anguilla
$_country_lang["8"] = '南極'; // Antarctica
$_country_lang["9"] = 'アンティグア・バーブーダ'; // Antigua and Barbuda
$_country_lang["10"] = 'アルゼンチン'; // Argentina
$_country_lang["11"] = 'アルメニア'; // Armenia
$_country_lang["12"] = 'アルバ'; // Aruba
$_country_lang["13"] = 'オーストラリア'; // Australia
$_country_lang["14"] = 'オーストリア'; // Austria
$_country_lang["15"] = 'アゼルバイジャン'; // Azerbaijan
$_country_lang["16"] = 'バハマ'; // Bahamas
$_country_lang["17"] = 'バーレーン'; // Bahrain
$_country_lang["18"] = 'バングラディッシュ'; // Bangladesh
$_country_lang["19"] = 'バルバドス'; // Barbados
$_country_lang["20"] = '白ロシア'; // Belarus
$_country_lang["21"] = 'ベルギー'; // Belgium
$_country_lang["22"] = 'ベリーズ'; // Belize
$_country_lang["23"] = 'ベニン'; // Benin
$_country_lang["24"] = 'バミューダ'; // Bermuda
$_country_lang["25"] = 'ブータン'; // Bhutan
$_country_lang["26"] = 'ボリビア'; // Bolivia
$_country_lang["27"] = 'ボスニア・ヘルツェコビナ'; // Bosnia and Herzegowina
$_country_lang["28"] = 'ボツワナ'; // Botswana
$_country_lang["29"] = 'ブーベ島'; // Bouvet Island
$_country_lang["30"] = 'ブラジル'; // Brazil
$_country_lang["31"] = '英領インド洋地域'; // British Indian Ocean Territory
$_country_lang["32"] = 'ブルネイ・ダルサラーム'; // Brunei Darussalam
$_country_lang["33"] = 'ブルガリア'; // Bulgaria
$_country_lang["34"] = 'ブルキナ・ファッソ'; // Burkina Faso
$_country_lang["35"] = 'ブルンジ'; // Burundi
$_country_lang["36"] = 'カンボジア'; // Cambodia
$_country_lang["37"] = 'カメルーン'; // Cameroon
$_country_lang["38"] = 'カナダ'; // Canada
$_country_lang["39"] = 'カーボベルデ'; // Cape Verde
$_country_lang["40"] = 'ケイマン諸島'; // Cayman Islands
$_country_lang["41"] = '中央アフリカ共和国'; // Central African Republic
$_country_lang["42"] = 'チャド'; // Chad
$_country_lang["43"] = 'チリ'; // Chile
$_country_lang["44"] = '中国'; // China
$_country_lang["45"] = 'クリスマス島'; // Christmas Island
$_country_lang["46"] = 'ココス諸島'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'コロンビア'; // Colombia
$_country_lang["48"] = 'コモロ'; // Comoros
$_country_lang["49"] = 'コンゴ共和国'; // Congo
$_country_lang["50"] = 'クック諸島'; // Cook Islands
$_country_lang["51"] = 'コスタリカ'; // Costa Rica
$_country_lang["52"] = 'コートジボワール'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'クロアチア'; // Croatia
$_country_lang["54"] = 'キューバ'; // Cuba
$_country_lang["55"] = 'キプロス'; // Cyprus
$_country_lang["56"] = 'チェコ'; // Czech Republic
$_country_lang["57"] = 'デンマーク'; // Denmark
$_country_lang["58"] = 'ジブチ'; // Djibouti
$_country_lang["59"] = 'ドミニカ国'; // Dominica
$_country_lang["60"] = 'ドミニカ共和国'; // Dominican Republic
$_country_lang["61"] = '東チモール'; // East Timor
$_country_lang["62"] = 'エクアドル'; // Ecuador
$_country_lang["63"] = 'エジプト'; // Egypt
$_country_lang["64"] = 'エルサルバドル'; // El Salvador
$_country_lang["65"] = '赤道ギニア'; // Equatorial Guinea
$_country_lang["66"] = 'エリトリア'; // Eritrea
$_country_lang["67"] = 'エストニア'; // Estonia
$_country_lang["68"] = 'エチオピア'; // Ethiopia
$_country_lang["69"] = 'フォークランド諸島'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'フェロー諸島'; // Faroe Islands
$_country_lang["71"] = 'フィジー'; // Fiji
$_country_lang["72"] = 'フィンランド'; // Finland
$_country_lang["73"] = 'フランス'; // France
$_country_lang["74"] = 'フランス(本国)'; // France, Metropolitan
$_country_lang["75"] = '仏領ギニア'; // French Guiana
$_country_lang["76"] = '仏領ポリネシア'; // French Polynesia
$_country_lang["77"] = '仏領南方地域'; // French Southern Territories
$_country_lang["78"] = 'ガボン'; // Gabon
$_country_lang["79"] = 'ガンビア'; // Gambia
$_country_lang["80"] = 'グルジア'; // Georgia
$_country_lang["81"] = 'ドイツ'; // Germany
$_country_lang["82"] = 'ガーナ'; // Ghana
$_country_lang["83"] = 'ジブラルタル'; // Gibraltar
$_country_lang["84"] = 'ギリシア'; // Greece
$_country_lang["85"] = 'グリーンランド'; // Greenland
$_country_lang["86"] = 'グレナダ'; // Grenada
$_country_lang["87"] = 'グアドループ'; // Guadeloupe
$_country_lang["88"] = 'グアム'; // Guam
$_country_lang["89"] = 'グァテマラ'; // Guatemala
$_country_lang["90"] = 'ギニア'; // Guinea
$_country_lang["91"] = 'ギニアビサウ'; // Guinea-bissau
$_country_lang["92"] = 'ギヤナ'; // Guyana
$_country_lang["93"] = 'ハイチ'; // Haiti
$_country_lang["94"] = 'ハード島とマクドナルド諸島'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'ホンジュラス'; // Honduras
$_country_lang["96"] = '香港'; // Hong Kong
$_country_lang["97"] = 'ハンガリ'; // Hungary
$_country_lang["98"] = 'アイスランド'; // Iceland
$_country_lang["99"] = 'インド'; // India
$_country_lang["100"] = 'インドネシア'; // Indonesia
$_country_lang["101"] = 'イラン・イスラム共和国'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'イラク'; // Iraq
$_country_lang["103"] = 'アイルランド'; // Ireland
$_country_lang["104"] = 'イスラエル'; // Israel
$_country_lang["105"] = 'イタリア'; // Italy
$_country_lang["106"] = 'ジャマイカ'; // Jamaica
$_country_lang["107"] = '日本'; // Japan
$_country_lang["108"] = 'ヨルダン'; // Jordan
$_country_lang["109"] = 'カザフスタン'; // Kazakhstan
$_country_lang["110"] = 'ケニア'; // Kenya
$_country_lang["111"] = 'キリバス'; // Kiribati
$_country_lang["112"] = '北朝鮮'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = '韓国'; // Korea, Republic of
$_country_lang["114"] = 'クェート'; // Kuwait
$_country_lang["115"] = 'キルギスタン'; // Kyrgyzstan
$_country_lang["116"] = 'ラオス'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'ラトビア'; // Latvia
$_country_lang["118"] = 'レバノン'; // Lebanon
$_country_lang["119"] = 'レソト'; // Lesotho
$_country_lang["120"] = 'リベリア'; // Liberia
$_country_lang["121"] = 'リビア'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'リヒテンシュタイン'; // Liechtenstein
$_country_lang["123"] = 'リトアニア'; // Lithuania
$_country_lang["124"] = 'ルクセンブルグ'; // Luxembourg
$_country_lang["125"] = 'マカオ'; // Macau
$_country_lang["126"] = 'マケドニア'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'マダガスカル'; // Madagascar
$_country_lang["128"] = 'マラウイ'; // Malawi
$_country_lang["129"] = 'マレーシア'; // Malaysia
$_country_lang["130"] = 'モルディブ'; // Maldives
$_country_lang["131"] = 'マリ'; // Mali
$_country_lang["132"] = 'マルタ'; // Malta
$_country_lang["133"] = 'マーシャル諸島'; // Marshall Islands
$_country_lang["134"] = 'マルティニーク'; // Martinique
$_country_lang["135"] = 'モーリタニア'; // Mauritania
$_country_lang["136"] = 'モーリシャス'; // Mauritius
$_country_lang["137"] = 'マヨット'; // Mayotte
$_country_lang["138"] = 'メキシコ'; // Mexico
$_country_lang["139"] = 'ミクロネシア連邦'; // Micronesia, Federated States of
$_country_lang["140"] = 'モルドバ共和国'; // Moldova, Republic of
$_country_lang["141"] = 'モナコ'; // Monaco
$_country_lang["142"] = 'モンゴル'; // Mongolia
$_country_lang["241"] = 'モンテネグロ'; //Montenegro
$_country_lang["143"] = 'モントセラト'; // Montserrat
$_country_lang["144"] = 'モロッコ'; // Morocco
$_country_lang["145"] = 'モザンビーク'; // Mozambique
$_country_lang["146"] = 'ミャンマー'; // Myanmar
$_country_lang["147"] = 'ナミビア'; // Namibia
$_country_lang["148"] = 'ナウル'; // Nauru
$_country_lang["149"] = 'ネパール'; // Nepal
$_country_lang["150"] = 'オランダ'; // Netherlands
$_country_lang["151"] = '蘭領アンティル'; // Netherlands Antilles
$_country_lang["152"] = 'ニューカレドニア'; // New Caledonia
$_country_lang["153"] = 'ニュージーランド'; // New Zealand
$_country_lang["154"] = 'ニカラグア'; // Nicaragua
$_country_lang["155"] = 'ニジェール'; // Niger
$_country_lang["156"] = 'ナイジェリア'; // Nigeria
$_country_lang["157"] = 'ニウエ'; // Niue
$_country_lang["158"] = 'ノーフォーク島'; // Norfolk Island
$_country_lang["159"] = '北マリアナ諸島'; // Northern Mariana Islands
$_country_lang["160"] = 'ノルウェー'; // Norway
$_country_lang["161"] = 'オマーン'; // Oman
$_country_lang["162"] = 'パキスタン'; // Pakistan
$_country_lang["163"] = 'パラオ'; // Palau
$_country_lang["164"] = 'パナマ'; // Panama
$_country_lang["165"] = 'パプア・ニューギニア'; // Papua New Guinea
$_country_lang["166"] = 'パラグアイ'; // Paraguay
$_country_lang["167"] = 'ペルー'; // Peru
$_country_lang["168"] = 'フィリピン'; // Philippines
$_country_lang["169"] = 'ピトケアン諸島'; // Pitcairn
$_country_lang["170"] = 'ポーランド'; // Poland
$_country_lang["171"] = 'ポルトガル'; // Portugal
$_country_lang["172"] = 'プエルトリコ'; // Puerto Rico
$_country_lang["173"] = 'カタール'; // Qatar
$_country_lang["174"] = 'レユニオン'; // Reunion
$_country_lang["175"] = 'ルーマニア'; // Romania
$_country_lang["176"] = 'ロシア連邦'; // Russian Federation
$_country_lang["177"] = 'ルワンダ'; // Rwanda
$_country_lang["178"] = 'セントキッツ・ネイビス'; // Saint Kitts and Nevis
$_country_lang["179"] = 'セントルシア'; // Saint Lucia
$_country_lang["180"] = 'セントビンセントおよびグレナディーン諸島'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'サモア'; // Samoa
$_country_lang["182"] = 'サンマリノ'; // San Marino
$_country_lang["183"] = 'サントメ・プリンシペ'; // Sao Tome and Principe
$_country_lang["184"] = 'サウジアラビア'; // Saudi Arabia
$_country_lang["185"] = 'セネガル'; // Senegal
$_country_lang["240"] = 'セルビア'; //Serbia
$_country_lang["186"] = 'セイシェル'; // Seychelles
$_country_lang["187"] = 'シエラレオネ'; // Sierra Leone
$_country_lang["188"] = 'シンガポール'; // Singapore
$_country_lang["189"] = 'スロバキア'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'スロベニア'; // Slovenia
$_country_lang["191"] = 'ソロモン諸島'; // Solomon Islands
$_country_lang["192"] = 'ソマリア'; // Somalia
$_country_lang["193"] = '南アフリカ'; // South Africa
$_country_lang["194"] = 'サウスジョージア・サウスサンドウィッチ諸島'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'スペイン'; // Spain
$_country_lang["196"] = 'スリランカ'; // Sri Lanka
$_country_lang["197"] = 'セントヘレナ'; // St. Helena
$_country_lang["198"] = 'サンピエール・ミクロン'; // St. Pierre and Miquelon
$_country_lang["199"] = 'スーダン'; // Sudan
$_country_lang["200"] = 'スリナム'; // Suriname
$_country_lang["201"] = 'スヴァールバル・ヤンマイエン諸島'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'スワジランド'; // Swaziland
$_country_lang["203"] = 'スェーデン'; // Sweden
$_country_lang["204"] = 'スイス'; // Switzerland
$_country_lang["205"] = 'シリア'; // Syrian Arab Republic
$_country_lang["206"] = '台湾'; // Taiwan
$_country_lang["207"] = 'タジキスタン'; // Tajikistan
$_country_lang["208"] = 'タンザニア'; // Tanzania, United Republic of
$_country_lang["209"] = 'タイ'; // Thailand
$_country_lang["210"] = 'トーゴ'; // Togo
$_country_lang["211"] = 'トケラウ'; // Tokelau
$_country_lang["212"] = 'トンガ'; // Tonga
$_country_lang["213"] = 'トリニダード・トバゴ'; // Trinidad and Tobago
$_country_lang["214"] = 'チュニジア'; // Tunisia
$_country_lang["215"] = 'トルコ'; // Turkey
$_country_lang["216"] = 'トルクメニスタン'; // Turkmenistan
$_country_lang["217"] = 'タークス・ケイコス諸島'; // Turks and Caicos Islands
$_country_lang["218"] = 'ツバル'; // Tuvalu
$_country_lang["219"] = 'ウガンダ'; // Uganda
$_country_lang["220"] = 'ウクライナ'; // Ukraine
$_country_lang["221"] = 'アラブ首長国連邦'; // United Arab Emirates
$_country_lang["222"] = 'イギリス'; // United Kingdom
$_country_lang["223"] = 'アメリカ'; // United States
$_country_lang["224"] = '米領太平洋諸島'; // United States Minor Outlying Islands
$_country_lang["225"] = 'ウルグアイ'; // Uruguay
$_country_lang["226"] = 'ウズベキスタン'; // Uzbekistan
$_country_lang["227"] = 'バヌアツ'; // Vanuatu
$_country_lang["228"] = 'ヴァチカン'; // Vatican City State (Holy See)
$_country_lang["229"] = 'ベネズエラ'; // Venezuela
$_country_lang["230"] = 'ベトナム'; // Viet Nam
$_country_lang["231"] = '英領バージン諸島'; // Virgin Islands (British)
$_country_lang["232"] = '米領バージン諸島'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'ウォリス・フツナ諸島'; // Wallis and Futuna Islands
$_country_lang["234"] = '西サハラ'; // Western Sahara
$_country_lang["235"] = 'イエメン'; // Yemen
$_country_lang["236"] = 'セルビア・モンテネグロ'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'コンゴ民主共和国'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'ザンビア'; // Zambia
$_country_lang["239"] = 'ジンバブエ'; // Zimbabwe
?>