<?php
/**
* Country List Dutch Language File
* Encoding: utf-8
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afghanistan'; // Afghanistan
$_country_lang["2"] = 'Albani&#235;'; // Albania
$_country_lang["3"] = 'Algerije'; // Algeria
$_country_lang["4"] = 'Americaans Samoa'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antarctica'; // Antarctica
$_country_lang["9"] = 'Antigua en Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentini&#235;'; // Argentina
$_country_lang["11"] = 'Armeni&#235;'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Australi&#235;'; // Australia
$_country_lang["14"] = 'Oostenrijk'; // Austria
$_country_lang["15"] = 'Azerbeijan'; // Azerbaijan
$_country_lang["16"] = 'Bahama\'s'; // Bahamas
$_country_lang["17"] = 'Bahrein'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Belarus'; // Belarus
$_country_lang["21"] = 'Belgi&#235;'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermuda'; // Bermuda
$_country_lang["25"] = 'Bhutan'; // Bhutan
$_country_lang["26"] = 'Bolivi&#235;'; // Bolivia
$_country_lang["27"] = 'Bosni&#235; en Herzegowina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Bouvet Eiland'; // Bouvet Island
$_country_lang["30"] = 'Brazili&#235;'; // Brazil
$_country_lang["31"] = 'Brits Indische Oceaan Territorium'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei Darussalam'; // Brunei Darussalam
$_country_lang["33"] = 'Bulgarije'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Cambodja'; // Cambodia
$_country_lang["37"] = 'Kameroen'; // Cameroon
$_country_lang["38"] = 'Canada'; // Canada
$_country_lang["39"] = 'Cape Verde'; // Cape Verde
$_country_lang["40"] = 'Cayman Eilanden'; // Cayman Islands
$_country_lang["41"] = 'Centraal Afrikaanse Republiek'; // Central African Republic
$_country_lang["42"] = 'Chad'; // Chad
$_country_lang["43"] = 'Chili'; // Chile
$_country_lang["44"] = 'China'; // China
$_country_lang["45"] = 'Kersteiland'; // Christmas Island
$_country_lang["46"] = 'Cocos (Keeling) Eilanden'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Colombi&#235;'; // Colombia
$_country_lang["48"] = 'Comoros'; // Comoros
$_country_lang["49"] = 'Congo'; // Congo
$_country_lang["50"] = 'Cook Eilanden'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Ivoorkust'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Kroati&#235;'; // Croatia
$_country_lang["54"] = 'Cuba'; // Cuba
$_country_lang["55"] = 'Cyprus'; // Cyprus
$_country_lang["56"] = 'Tsjechische Republiek'; // Czech Republic
$_country_lang["57"] = 'Denemarken'; // Denmark
$_country_lang["58"] = 'Djibouti'; // Djibouti
$_country_lang["59"] = 'Dominica'; // Dominica
$_country_lang["60"] = 'Dominicaanse Republiek'; // Dominican Republic
$_country_lang["61"] = 'Oost Timor'; // East Timor
$_country_lang["62"] = 'Ecuador'; // Ecuador
$_country_lang["63"] = 'Egypte'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Equatoriaal Guinea'; // Equatorial Guinea
$_country_lang["66"] = 'Eritrea'; // Eritrea
$_country_lang["67"] = 'Estoni&#235;'; // Estonia
$_country_lang["68"] = 'Ethiopi&#235;'; // Ethiopia
$_country_lang["69"] = 'Falkland Eilanden (Malvinas)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Farao Eilanden'; // Faroe Islands
$_country_lang["71"] = 'Fiji'; // Fiji
$_country_lang["72"] = 'Finland'; // Finland
$_country_lang["73"] = 'Frankrijk'; // France
$_country_lang["74"] = 'Frankrijk, Metropool'; // France, Metropolitan
$_country_lang["75"] = 'Frans Guinea'; // French Guiana
$_country_lang["76"] = 'Frans Polinesi&#235;'; // French Polynesia
$_country_lang["77"] = 'Frans Zuidelijke Territoria'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Georgi&#235;'; // Georgia
$_country_lang["81"] = 'Duitsland'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Griekenland'; // Greece
$_country_lang["85"] = 'Groenland'; // Greenland
$_country_lang["86"] = 'Granada'; // Grenada
$_country_lang["87"] = 'Guadeloupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guinea'; // Guinea
$_country_lang["91"] = 'Guinee-bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guyana'; // Guyana
$_country_lang["93"] = 'Ha&#239;ti'; // Haiti
$_country_lang["94"] = 'Heard en Mc Donald Eilanden'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Hongarije'; // Hungary
$_country_lang["98"] = 'Ijsland'; // Iceland
$_country_lang["99"] = 'India'; // India
$_country_lang["100"] = 'Indonesi&#235;'; // Indonesia
$_country_lang["101"] = 'Iran (Islamitische Republiek)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irak'; // Iraq
$_country_lang["103"] = 'Ierland'; // Ireland
$_country_lang["104"] = 'Isra&#235;l'; // Israel
$_country_lang["105"] = 'Itali&#235;'; // Italy
$_country_lang["106"] = 'Jamaica'; // Jamaica
$_country_lang["107"] = 'Japan'; // Japan
$_country_lang["108"] = 'Jordani&#235;'; // Jordan
$_country_lang["109"] = 'Kazachstan'; // Kazakhstan
$_country_lang["110"] = 'Kenia'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Korea, Noord'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Korea, Zuid'; // Korea, Republic of
$_country_lang["114"] = 'Kuweit'; // Kuwait
$_country_lang["115"] = 'Kyrgyzstan'; // Kyrgyzstan
$_country_lang["116"] = 'Laos'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Latvia'; // Latvia
$_country_lang["118"] = 'Libanon'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Liberi&#235;'; // Liberia
$_country_lang["121"] = 'Libi&#235;'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Litouwen'; // Lithuania
$_country_lang["124"] = 'Luxemburg'; // Luxembourg
$_country_lang["125"] = 'Macau'; // Macau
$_country_lang["126"] = 'Macedoni&#235;'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagascar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Maleisi&#235;'; // Malaysia
$_country_lang["130"] = 'Maldiven'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Marshall Eilanden'; // Marshall Islands
$_country_lang["134"] = 'Martinique'; // Martinique
$_country_lang["135"] = 'Mauritani&#235;'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'Mexico'; // Mexico
$_country_lang["139"] = 'Micronesia'; // Micronesia, Federated States of
$_country_lang["140"] = 'Moldavi&#235;'; // Moldova, Republic of
$_country_lang["141"] = 'Monaco'; // Monaco
$_country_lang["142"] = 'Mongoli&#235;'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Marocco'; // Morocco
$_country_lang["145"] = 'Mozambique'; // Mozambique
$_country_lang["146"] = 'Myanmar'; // Myanmar
$_country_lang["147"] = 'Namibi&#235;'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Nederland'; // Netherlands
$_country_lang["151"] = 'Nederlandse Antillen'; // Netherlands Antilles
$_country_lang["152"] = 'Nieuw Caledoni&#235;'; // New Caledonia
$_country_lang["153"] = 'Nieuw Zeeland'; // New Zealand
$_country_lang["154"] = 'Nicaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Norfolk Eiland'; // Norfolk Island
$_country_lang["159"] = 'Noord Mariana Eilanden'; // Northern Mariana Islands
$_country_lang["160"] = 'Noorwegen'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papua Nieuw Guinea'; // Papua New Guinea
$_country_lang["166"] = 'Paraguay'; // Paraguay
$_country_lang["167"] = 'Peru'; // Peru
$_country_lang["168"] = 'Philippijnen'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Polen'; // Poland
$_country_lang["171"] = 'Portugal'; // Portugal
$_country_lang["172"] = 'Puerto Rico'; // Puerto Rico
$_country_lang["173"] = 'Quatar'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Roemeni&#235;'; // Romania
$_country_lang["176"] = 'Russische Federatie'; // Russian Federation
$_country_lang["177"] = 'Rwanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts en Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Saint Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent en de Grenadines'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'Sao Tom&#235; en Principe'; // Sao Tome and Principe
$_country_lang["184"] = 'Saudi Arabi&#235;'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'Servi&#235;'; //Serbia
$_country_lang["186"] = 'Seychellen'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapore'; // Singapore
$_country_lang["189"] = 'Slowakije'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Sloveni&#235;'; // Slovenia
$_country_lang["191"] = 'Solomon Eilanden'; // Solomon Islands
$_country_lang["192"] = 'Somali&#235;'; // Somalia
$_country_lang["193"] = 'Zuid Afrika'; // South Africa
$_country_lang["194"] = 'Zuid Georgi&#235; en de Zuidelijke Sandwich Eilanden'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Spanje'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'St. Helena'; // St. Helena
$_country_lang["198"] = 'St. Pierre en Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Soedan'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Svalbard en Jan Mayen Eilanden'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Swaziland'; // Swaziland
$_country_lang["203"] = 'Zweden'; // Sweden
$_country_lang["204"] = 'Zwitzerland'; // Switzerland
$_country_lang["205"] = 'Syri&#235;'; // Syrian Arab Republic
$_country_lang["206"] = 'Taiwan'; // Taiwan
$_country_lang["207"] = 'Tajikistan'; // Tajikistan
$_country_lang["208"] = 'Tanzania'; // Tanzania, United Republic of
$_country_lang["209"] = 'Thailand'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad en Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunesi&#235;'; // Tunisia
$_country_lang["215"] = 'Turkije'; // Turkey
$_country_lang["216"] = 'Turkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Turksse en Caicos Eilanden'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Oekra&#239;ne'; // Ukraine
$_country_lang["221"] = 'Verenigde Arabische Emiraten'; // United Arab Emirates
$_country_lang["222"] = 'Verenigd Koninkrijk'; // United Kingdom
$_country_lang["223"] = 'Verenigde Staten'; // United States
$_country_lang["224"] = 'VS Minor Outlying Islands'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguay'; // Uruguay
$_country_lang["226"] = 'Uzbekistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vaticaan Stad'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Vietnam'; // Viet Nam
$_country_lang["231"] = 'Maagden Eilanden (GB)'; // Virgin Islands (British)
$_country_lang["232"] = 'Maagden Eilanden (VS)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wallis en Futuna Eilanden'; // Wallis and Futuna Islands
$_country_lang["234"] = 'West Sahara'; // Western Sahara
$_country_lang["235"] = 'Yemen'; // Yemen
$_country_lang["236"] = 'Servi&#235; en Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Congo, Democratische Republiek'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe

?>