<?php
/**
* Country List Polish Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afganistan'; // Afghanistan
$_country_lang["2"] = 'Albania'; // Albania
$_country_lang["3"] = 'Algieria'; // Algeria
$_country_lang["4"] = 'Samoa Amerykańskie'; // American Samoa
$_country_lang["5"] = 'Andora'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antarktyda'; // Antarctica
$_country_lang["9"] = 'Antigua i Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentyna'; // Argentina
$_country_lang["11"] = 'Armenia'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Australia'; // Australia
$_country_lang["14"] = 'Austria'; // Austria
$_country_lang["15"] = 'Azerbejdżan'; // Azerbaijan
$_country_lang["16"] = 'Bahamy'; // Bahamas
$_country_lang["17"] = 'Bahrajn'; // Bahrain
$_country_lang["18"] = 'Bangladesz'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Białoruś'; // Belarus
$_country_lang["21"] = 'Belgia'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benin'; // Benin
$_country_lang["24"] = 'Bermudy'; // Bermuda
$_country_lang["25"] = 'Bhutan'; // Bhutan
$_country_lang["26"] = 'Boliwia'; // Bolivia
$_country_lang["27"] = 'Bośnia i Hercegowina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Wyspa Bouveta'; // Bouvet Island
$_country_lang["30"] = 'Brazylia'; // Brazil
$_country_lang["31"] = 'Brytyjskie Terytorium Oceanu Indyjskiego'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei Darussalam'; // Brunei Darussalam
$_country_lang["33"] = 'Bułgaria'; // Bulgaria
$_country_lang["34"] = 'Burkina Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Kambodża'; // Cambodia
$_country_lang["37"] = 'Kamerun'; // Cameroon
$_country_lang["38"] = 'Kanada'; // Canada
$_country_lang["39"] = 'Wyspy Zielonego Przylądka'; // Cape Verde
$_country_lang["40"] = 'Kajmany'; // Cayman Islands
$_country_lang["41"] = 'Republika Środkowej Afryki'; // Central African Republic
$_country_lang["42"] = 'Czad'; // Chad
$_country_lang["43"] = 'Chile'; // Chile
$_country_lang["44"] = 'Chiny'; // China
$_country_lang["45"] = 'Wyspa Bożego Narodzenia'; // Christmas Island
$_country_lang["46"] = 'Cocos (Keeling)'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Kolumbia'; // Colombia
$_country_lang["48"] = 'Komory'; // Comoros
$_country_lang["49"] = 'Republika Konga'; // Congo
$_country_lang["50"] = 'Wyspy Cooka'; // Cook Islands
$_country_lang["51"] = 'Kostaryka'; // Costa Rica
$_country_lang["52"] = 'Wybrzeże Kości Słoniowej'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Chorwacja'; // Croatia
$_country_lang["54"] = 'Kuba'; // Cuba
$_country_lang["55"] = 'Cypr'; // Cyprus
$_country_lang["56"] = 'Czechy'; // Czech Republic
$_country_lang["57"] = 'Dania'; // Denmark
$_country_lang["58"] = 'Dżibuti'; // Djibouti
$_country_lang["59"] = 'Dominika'; // Dominica
$_country_lang["60"] = 'Dominikana'; // Dominican Republic
$_country_lang["61"] = 'Timor Wschodni'; // East Timor
$_country_lang["62"] = 'Ekwador'; // Ecuador
$_country_lang["63"] = 'Egipt'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Gwinea Równikowa'; // Equatorial Guinea
$_country_lang["66"] = 'Erytrea'; // Eritrea
$_country_lang["67"] = 'Estonia'; // Estonia
$_country_lang["68"] = 'Etiopia'; // Ethiopia
$_country_lang["69"] = 'Falklandy (Malwiny)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Wyspy Owcze'; // Faroe Islands
$_country_lang["71"] = 'Fidżi'; // Fiji
$_country_lang["72"] = 'Finlandia'; // Finland
$_country_lang["73"] = 'Francja'; // France
$_country_lang["74"] = 'Francja metropolitarna'; // France, Metropolitan
$_country_lang["75"] = 'Gujana Francuska'; // French Guiana
$_country_lang["76"] = 'Polinezja Francuska'; // French Polynesia
$_country_lang["77"] = 'Francuskie Terytoria Południowe'; // French Southern Territories
$_country_lang["78"] = 'Gabon'; // Gabon
$_country_lang["79"] = 'Gambia'; // Gambia
$_country_lang["80"] = 'Gruzja'; // Georgia
$_country_lang["81"] = 'Niemcy'; // Germany
$_country_lang["82"] = 'Ghana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Grecja'; // Greece
$_country_lang["85"] = 'Grenlandia'; // Greenland
$_country_lang["86"] = 'Grenada'; // Grenada
$_country_lang["87"] = 'Gwadelupa'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Gwatemala'; // Guatemala
$_country_lang["90"] = 'Gwinea'; // Guinea
$_country_lang["91"] = 'Gwinea Bissau'; // Guinea-bissau
$_country_lang["92"] = 'Gujana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Wyspy Heard i Mc Donald'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Węgry'; // Hungary
$_country_lang["98"] = 'Islandia'; // Iceland
$_country_lang["99"] = 'Indie'; // India
$_country_lang["100"] = 'Indonezja'; // Indonesia
$_country_lang["101"] = 'Iran (Islamska Republika)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Irak'; // Iraq
$_country_lang["103"] = 'Irlandia'; // Ireland
$_country_lang["104"] = 'Izrael'; // Israel
$_country_lang["105"] = 'Włochy'; // Italy
$_country_lang["106"] = 'Jamajka'; // Jamaica
$_country_lang["107"] = 'Japonia'; // Japan
$_country_lang["108"] = 'Jordania'; // Jordan
$_country_lang["109"] = 'Kazachstan'; // Kazakhstan
$_country_lang["110"] = 'Kenia'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Koreańska Republika Ludowo-Demokratyczna'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Republika Korei'; // Korea, Republic of
$_country_lang["114"] = 'Kuwejt'; // Kuwait
$_country_lang["115"] = 'Kirgistan'; // Kyrgyzstan
$_country_lang["116"] = 'Ludowo-Demokratyczna Republika Laosu'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Łotwa'; // Latvia
$_country_lang["118"] = 'Liban'; // Lebanon
$_country_lang["119"] = 'Lesotho'; // Lesotho
$_country_lang["120"] = 'Liberia'; // Liberia
$_country_lang["121"] = 'Libia'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Litwa'; // Lithuania
$_country_lang["124"] = 'Luksemburg'; // Luxembourg
$_country_lang["125"] = 'Makau'; // Macau
$_country_lang["126"] = 'Macedonia, była Republika Jugosłowiańska'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madagaskar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Malezja'; // Malaysia
$_country_lang["130"] = 'Malediwy'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Wyspy Marshalla'; // Marshall Islands
$_country_lang["134"] = 'Martynika'; // Martinique
$_country_lang["135"] = 'Mauretania'; // Mauritania
$_country_lang["136"] = 'Mauritius'; // Mauritius
$_country_lang["137"] = 'Majotta'; // Mayotte
$_country_lang["138"] = 'Meksyk'; // Mexico
$_country_lang["139"] = 'Mikronezja'; // Micronesia, Federated States of
$_country_lang["140"] = 'Republika Mołdowy'; // Moldova, Republic of
$_country_lang["141"] = 'Monako'; // Monaco
$_country_lang["142"] = 'Mongolia'; // Mongolia
$_country_lang["241"] = 'Czarnogóra'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Maroko'; // Morocco
$_country_lang["145"] = 'Mozambik'; // Mozambique
$_country_lang["146"] = 'Myanmar'; // Myanmar
$_country_lang["147"] = 'Namibia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Holandia'; // Netherlands
$_country_lang["151"] = 'Antyle Holenderskie'; // Netherlands Antilles
$_country_lang["152"] = 'Nowa Kaledonia'; // New Caledonia
$_country_lang["153"] = 'Nowa Zelandia'; // New Zealand
$_country_lang["154"] = 'Nikaragua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nigeria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Wyspa Norfolk'; // Norfolk Island
$_country_lang["159"] = 'Mariany Północne'; // Northern Mariana Islands
$_country_lang["160"] = 'Norwegia'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Pakistan'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panama'; // Panama
$_country_lang["165"] = 'Papua-Nowa Gwinea'; // Papua New Guinea
$_country_lang["166"] = 'Paragwaj'; // Paraguay
$_country_lang["167"] = 'Peru'; // Peru
$_country_lang["168"] = 'Filipiny'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Polska'; // Poland
$_country_lang["171"] = 'Portugalia'; // Portugal
$_country_lang["172"] = 'Puerto Rico'; // Puerto Rico
$_country_lang["173"] = 'Katar'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Rumunia'; // Romania
$_country_lang["176"] = 'Federacja Rosyjska'; // Russian Federation
$_country_lang["177"] = 'Rwanda'; // Rwanda
$_country_lang["178"] = 'Saint Kitts i Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Saint Lucia'; // Saint Lucia
$_country_lang["180"] = 'Saint Vincent i Grenadyny'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'San Marino'; // San Marino
$_country_lang["183"] = 'Wyspy Świętego Tomasza i Książęca'; // Sao Tome and Principe
$_country_lang["184"] = 'Arabia Saudyjska'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'Serbia'; //Serbia
$_country_lang["186"] = 'Seszele'; // Seychelles
$_country_lang["187"] = 'Sierra Leone'; // Sierra Leone
$_country_lang["188"] = 'Singapur'; // Singapore
$_country_lang["189"] = 'Słowacja (Republika Słowacka)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Słowenia'; // Slovenia
$_country_lang["191"] = 'Wyspy Salomona'; // Solomon Islands
$_country_lang["192"] = 'Somalia'; // Somalia
$_country_lang["193"] = 'Republika Południowej Afryki'; // South Africa
$_country_lang["194"] = 'Georgia Południowa i Sandwich Południowy'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Hiszpania'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'Święta Helena'; // St. Helena
$_country_lang["198"] = 'Saint-Pierre i Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sudan'; // Sudan
$_country_lang["200"] = 'Surinam'; // Suriname
$_country_lang["201"] = 'Svalbard i Jan Mayen'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Suazi'; // Swaziland
$_country_lang["203"] = 'Szwecja'; // Sweden
$_country_lang["204"] = 'Szwajcaria'; // Switzerland
$_country_lang["205"] = 'Syryjska Republika Arabska'; // Syrian Arab Republic
$_country_lang["206"] = 'Tajwan'; // Taiwan
$_country_lang["207"] = 'Tadżykistan'; // Tajikistan
$_country_lang["208"] = 'Tanzania, Zjednoczona Republika'; // Tanzania, United Republic of
$_country_lang["209"] = 'Tajlandia'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trynidad i Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tunezja'; // Tunisia
$_country_lang["215"] = 'Turcja'; // Turkey
$_country_lang["216"] = 'Turkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Wyspy Turks i Caicos'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ukraina'; // Ukraine
$_country_lang["221"] = 'Zjednoczone Emiraty Arabskie'; // United Arab Emirates
$_country_lang["222"] = 'Wielka Brytania'; // United Kingdom
$_country_lang["223"] = 'Stany Zjednoczone'; // United States
$_country_lang["224"] = 'Stany Zjednoczone Dalekie Wyspy Mniejsze'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Urugwaj'; // Uruguay
$_country_lang["226"] = 'Uzbekistan'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Watykan (Stolica Apostolska)'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Wenezuela'; // Venezuela
$_country_lang["230"] = 'Wietnam'; // Viet Nam
$_country_lang["231"] = 'Wyspy Dziewicze (Wielka Brytania)'; // Virgin Islands (British)
$_country_lang["232"] = 'Wyspy Dziewicze (USA)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Wyspy Wallis i Futuna'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Sahara Zachodnia'; // Western Sahara
$_country_lang["235"] = 'Jemen'; // Yemen
$_country_lang["236"] = 'Serbia i Czarnogóra'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Demokratyczna Republika Konga'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Zambia'; // Zambia
$_country_lang["239"] = 'Zimbabwe'; // Zimbabwe
?>

