<?php
/**
* Country List Language File
* Version: 1.0
* Date: 19/12/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Afeganist�o'; // Afghanistan
$_country_lang["2"] = 'Alb�nia'; // Albania
$_country_lang["3"] = 'Arg�lia'; // Algeria
$_country_lang["4"] = 'Samoa Americana'; // American Samoa
$_country_lang["5"] = 'Andorra'; // Andorra
$_country_lang["6"] = 'Angola'; // Angola
$_country_lang["7"] = 'Anguilla'; // Anguilla
$_country_lang["8"] = 'Antarctica'; // Antarctica
$_country_lang["9"] = 'Ant�gua e Barbuda'; // Antigua and Barbuda
$_country_lang["10"] = 'Argentina'; // Argentina
$_country_lang["11"] = 'Arm�nia'; // Armenia
$_country_lang["12"] = 'Aruba'; // Aruba
$_country_lang["13"] = 'Austr�lia'; // Australia
$_country_lang["14"] = '�ustria'; // Austria
$_country_lang["15"] = 'Azerbeij�o'; // Azerbaijan
$_country_lang["16"] = 'Bahamas'; // Bahamas
$_country_lang["17"] = 'Bahrein'; // Bahrain
$_country_lang["18"] = 'Bangladesh'; // Bangladesh
$_country_lang["19"] = 'Barbados'; // Barbados
$_country_lang["20"] = 'Bielorr�ssia'; // Belarus
$_country_lang["21"] = 'B�lgica'; // Belgium
$_country_lang["22"] = 'Belize'; // Belize
$_country_lang["23"] = 'Benim'; // Benin
$_country_lang["24"] = 'Bermudas'; // Bermuda
$_country_lang["25"] = 'But�o'; // Bhutan
$_country_lang["26"] = 'Bol�via'; // Bolivia
$_country_lang["27"] = 'B�snia-Herzegovina'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Botswana'; // Botswana
$_country_lang["29"] = 'Ilha Bouvet'; // Bouvet Island
$_country_lang["30"] = 'Brasil'; // Brazil
$_country_lang["31"] = 'Territ�rios Brit�nicos do �ndico'; // British Indian Ocean Territory
$_country_lang["32"] = 'Brunei'; // Brunei Darussalam
$_country_lang["33"] = 'Bulg�ria'; // Bulgaria
$_country_lang["34"] = 'Burkina-Faso'; // Burkina Faso
$_country_lang["35"] = 'Burundi'; // Burundi
$_country_lang["36"] = 'Cambodja'; // Cambodia
$_country_lang["37"] = 'Camar�es'; // Cameroon
$_country_lang["38"] = 'Canada'; // Canada
$_country_lang["39"] = 'Cabo Verde'; // Cape Verde
$_country_lang["40"] = 'Ilhas Caim�o'; // Cayman Islands
$_country_lang["41"] = 'Rep�blica Centro-Africana'; // Central African Republic
$_country_lang["42"] = 'Chade'; // Chad
$_country_lang["43"] = 'Chile'; // Chile
$_country_lang["44"] = 'China'; // China
$_country_lang["45"] = 'Ilha do Natal'; // Christmas Island
$_country_lang["46"] = 'Ilhas Cocos (Keeling)'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Col�mbia'; // Colombia
$_country_lang["48"] = 'Comores'; // Comoros
$_country_lang["49"] = 'Rep�blica Democr�tica do Congo'; // Congo
$_country_lang["50"] = 'Ilhas Cook'; // Cook Islands
$_country_lang["51"] = 'Costa Rica'; // Costa Rica
$_country_lang["52"] = 'Costa do Marfim'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Cro�cia'; // Croatia
$_country_lang["54"] = 'Cuba'; // Cuba
$_country_lang["55"] = 'Chipre'; // Cyprus
$_country_lang["56"] = 'Rep�blica Checa'; // Czech Republic
$_country_lang["57"] = 'Dinamarca'; // Denmark
$_country_lang["58"] = 'Djibuti'; // Djibouti
$_country_lang["59"] = 'Dominica'; // Dominica
$_country_lang["60"] = 'Rep�blica Dominicana'; // Dominican Republic
$_country_lang["61"] = 'Timor-Leste'; // East Timor
$_country_lang["62"] = 'Equador'; // Ecuador
$_country_lang["63"] = 'Egipto'; // Egypt
$_country_lang["64"] = 'El Salvador'; // El Salvador
$_country_lang["65"] = 'Guin� Equatorial'; // Equatorial Guinea
$_country_lang["66"] = 'Eritreia'; // Eritrea
$_country_lang["67"] = 'Est�nia'; // Estonia
$_country_lang["68"] = 'Eti�pia'; // Ethiopia
$_country_lang["69"] = 'Ilhas Malvinas (Falkland)'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Ilhas Faro�'; // Faroe Islands
$_country_lang["71"] = 'Fiji'; // Fiji
$_country_lang["72"] = 'Finl�ndia'; // Finland
$_country_lang["73"] = 'Fran�a'; // France
$_country_lang["74"] = 'Fran�a Metropolitana'; // France, Metropolitan
$_country_lang["75"] = 'Guiana Francesa'; // French Guiana
$_country_lang["76"] = 'Polin�sia Francesa'; // French Polynesia
$_country_lang["77"] = 'Territ�rios Franceses do Sul'; // French Southern Territories
$_country_lang["78"] = 'Gab�o'; // Gabon
$_country_lang["79"] = 'G�mbia'; // Gambia
$_country_lang["80"] = 'Ge�rgia'; // Georgia
$_country_lang["81"] = 'Alemanha'; // Germany
$_country_lang["82"] = 'Gana'; // Ghana
$_country_lang["83"] = 'Gibraltar'; // Gibraltar
$_country_lang["84"] = 'Gr�cia'; // Greece
$_country_lang["85"] = 'Gronel�ndia'; // Greenland
$_country_lang["86"] = 'Granada'; // Grenada
$_country_lang["87"] = 'Guadalupe'; // Guadeloupe
$_country_lang["88"] = 'Guam'; // Guam
$_country_lang["89"] = 'Guatemala'; // Guatemala
$_country_lang["90"] = 'Guin�-Conakry'; // Guinea
$_country_lang["91"] = 'Guin�-Bissau'; // Guinea-bissau
$_country_lang["92"] = 'Guiana'; // Guyana
$_country_lang["93"] = 'Haiti'; // Haiti
$_country_lang["94"] = 'Ilhas Heard e Mc Donald'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Honduras'; // Honduras
$_country_lang["96"] = 'Hong Kong'; // Hong Kong
$_country_lang["97"] = 'Hungria'; // Hungary
$_country_lang["98"] = 'Isl�ndia'; // Iceland
$_country_lang["99"] = '�ndia'; // India
$_country_lang["100"] = 'Indon�sia'; // Indonesia
$_country_lang["101"] = 'Ir�o'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Iraque'; // Iraq
$_country_lang["103"] = 'Irlanda'; // Ireland
$_country_lang["104"] = 'Israel'; // Israel
$_country_lang["105"] = 'It�lia'; // Italy
$_country_lang["106"] = 'Jamaica'; // Jamaica
$_country_lang["107"] = 'Jap�o'; // Japan
$_country_lang["108"] = 'Jord�nia'; // Jordan
$_country_lang["109"] = 'Cazaquist�o'; // Kazakhstan
$_country_lang["110"] = 'Qu�nia'; // Kenya
$_country_lang["111"] = 'Kiribati'; // Kiribati
$_country_lang["112"] = 'Coreia do Norte'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Coreia do Sul'; // Korea, Republic of
$_country_lang["114"] = 'Koweit'; // Kuwait
$_country_lang["115"] = 'Quirziguist�o'; // Kyrgyzstan
$_country_lang["116"] = 'Laos'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Let�nia'; // Latvia
$_country_lang["118"] = 'L�bano'; // Lebanon
$_country_lang["119"] = 'Lesoto'; // Lesotho
$_country_lang["120"] = 'Lib�ria'; // Liberia
$_country_lang["121"] = 'L�bia'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Liechtenstein'; // Liechtenstein
$_country_lang["123"] = 'Lithuania'; // Lithuania
$_country_lang["124"] = 'Luxemburgo'; // Luxembourg
$_country_lang["125"] = 'Macau'; // Macau
$_country_lang["126"] = 'Maced�nia'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Madag�scar'; // Madagascar
$_country_lang["128"] = 'Malawi'; // Malawi
$_country_lang["129"] = 'Mal�sia'; // Malaysia
$_country_lang["130"] = 'Maldivas'; // Maldives
$_country_lang["131"] = 'Mali'; // Mali
$_country_lang["132"] = 'Malta'; // Malta
$_country_lang["133"] = 'Ilhas Marshall'; // Marshall Islands
$_country_lang["134"] = 'Martinica'; // Martinique
$_country_lang["135"] = 'Maurit�nia'; // Mauritania
$_country_lang["136"] = 'Ilhas Maur�cias'; // Mauritius
$_country_lang["137"] = 'Mayotte'; // Mayotte
$_country_lang["138"] = 'M�xico'; // Mexico
$_country_lang["139"] = 'Estados Federados da Micron�sia'; // Micronesia, Federated States of
$_country_lang["140"] = 'Mold�via'; // Moldova, Republic of
$_country_lang["141"] = 'M�naco'; // Monaco
$_country_lang["142"] = 'Mong�lia'; // Mongolia
$_country_lang["241"] = 'Montenegro'; //Montenegro
$_country_lang["143"] = 'Montserrat'; // Montserrat
$_country_lang["144"] = 'Marrocos'; // Morocco
$_country_lang["145"] = 'Mo�ambique'; // Mozambique
$_country_lang["146"] = 'Myanmar (Birm�nia)'; // Myanmar
$_country_lang["147"] = 'Nam�bia'; // Namibia
$_country_lang["148"] = 'Nauru'; // Nauru
$_country_lang["149"] = 'Nepal'; // Nepal
$_country_lang["150"] = 'Pa�ses-Baixos'; // Netherlands
$_country_lang["151"] = 'Antilhas Holandesas'; // Netherlands Antilles
$_country_lang["152"] = 'Nova Caled�nia'; // New Caledonia
$_country_lang["153"] = 'Nova Zel�ndia'; // New Zealand
$_country_lang["154"] = 'Nicar�gua'; // Nicaragua
$_country_lang["155"] = 'Niger'; // Niger
$_country_lang["156"] = 'Nig�ria'; // Nigeria
$_country_lang["157"] = 'Niue'; // Niue
$_country_lang["158"] = 'Ilhas Norfolk'; // Norfolk Island
$_country_lang["159"] = 'Ilhas Marianas do Norte'; // Northern Mariana Islands
$_country_lang["160"] = 'Noruega'; // Norway
$_country_lang["161"] = 'Oman'; // Oman
$_country_lang["162"] = 'Paquist�o'; // Pakistan
$_country_lang["163"] = 'Palau'; // Palau
$_country_lang["164"] = 'Panam�'; // Panama
$_country_lang["165"] = 'Papua Nova Guin�'; // Papua New Guinea
$_country_lang["166"] = 'Paraguai'; // Paraguay
$_country_lang["167"] = 'Per�'; // Peru
$_country_lang["168"] = 'Filipinas'; // Philippines
$_country_lang["169"] = 'Pitcairn'; // Pitcairn
$_country_lang["170"] = 'Poland'; // Poland
$_country_lang["171"] = 'Portugal'; // Portugal
$_country_lang["172"] = 'Porto-Rico'; // Puerto Rico
$_country_lang["173"] = 'Qatar'; // Qatar
$_country_lang["174"] = 'Reunion'; // Reunion
$_country_lang["175"] = 'Rom�nia'; // Romania
$_country_lang["176"] = 'Federa��o R�ssa'; // Russian Federation
$_country_lang["177"] = 'Ruanda'; // Rwanda
$_country_lang["178"] = 'St. Kitts e Nevis'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Santa Luzia'; // Saint Lucia
$_country_lang["180"] = 'S�o Vincente e Grenadinas'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Samoa'; // Samoa
$_country_lang["182"] = 'S�o Marino'; // San Marino
$_country_lang["183"] = 'S�o Tom� e Pr�ncipe'; // Sao Tome and Principe
$_country_lang["184"] = 'Ar�bia Saudita'; // Saudi Arabia
$_country_lang["185"] = 'Senegal'; // Senegal
$_country_lang["240"] = 'S�rvia'; //Serbia
$_country_lang["186"] = 'Seicheles'; // Seychelles
$_country_lang["187"] = 'Serra Leoa'; // Sierra Leone
$_country_lang["188"] = 'Singapura'; // Singapore
$_country_lang["189"] = 'Eslov�quia'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Eslov�nia'; // Slovenia
$_country_lang["191"] = 'Ilhas Salom�o'; // Solomon Islands
$_country_lang["192"] = 'Som�lia'; // Somalia
$_country_lang["193"] = '�frica do Sul'; // South Africa
$_country_lang["194"] = 'Ge�rgia do Sul e Ilhas Sandwich do Sul'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Espanha'; // Spain
$_country_lang["196"] = 'Sri Lanka'; // Sri Lanka
$_country_lang["197"] = 'St. Helena'; // St. Helena
$_country_lang["198"] = 'St. Pierre e Miquelon'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Sud�o'; // Sudan
$_country_lang["200"] = 'Suriname'; // Suriname
$_country_lang["201"] = 'Ilhas Svalbard e Jan Mayen'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Swuzil�ndia'; // Swaziland
$_country_lang["203"] = 'Su�cia'; // Sweden
$_country_lang["204"] = 'Switzerland'; // Switzerland
$_country_lang["205"] = 'S�ria'; // Syrian Arab Republic
$_country_lang["206"] = 'Taiwan'; // Taiwan
$_country_lang["207"] = 'Tajiquist�o'; // Tajikistan
$_country_lang["208"] = 'Tanz�nia'; // Tanzania, United Republic of
$_country_lang["209"] = 'Tail�ndia'; // Thailand
$_country_lang["210"] = 'Togo'; // Togo
$_country_lang["211"] = 'Tokelau'; // Tokelau
$_country_lang["212"] = 'Tonga'; // Tonga
$_country_lang["213"] = 'Trinidad e Tobago'; // Trinidad and Tobago
$_country_lang["214"] = 'Tun�sia'; // Tunisia
$_country_lang["215"] = 'Turquia'; // Turkey
$_country_lang["216"] = 'Turkmenistan'; // Turkmenistan
$_country_lang["217"] = 'Ilhas Turks e Caicos'; // Turks and Caicos Islands
$_country_lang["218"] = 'Tuvalu'; // Tuvalu
$_country_lang["219"] = 'Uganda'; // Uganda
$_country_lang["220"] = 'Ucr�nia'; // Ukraine
$_country_lang["221"] = 'Emiratos �rabes Unidos'; // United Arab Emirates
$_country_lang["222"] = 'Reino Unido'; // United Kingdom
$_country_lang["223"] = 'Estados Unidos da Am�rica'; // United States
$_country_lang["224"] = 'Ilhas menores Circundantes dos Estados Unidos da Am�rica'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Uruguai'; // Uruguay
$_country_lang["226"] = 'Uzbequist�o'; // Uzbekistan
$_country_lang["227"] = 'Vanuatu'; // Vanuatu
$_country_lang["228"] = 'Vaticano'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Venezuela'; // Venezuela
$_country_lang["230"] = 'Vietname'; // Viet Nam
$_country_lang["231"] = 'Ilhas Virgens Brit�nicas'; // Virgin Islands (British)
$_country_lang["232"] = 'Virgin Islands (EUA)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Ilhas Wallis e Futuna'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Saara Ocidental'; // Western Sahara
$_country_lang["235"] = 'I�men'; // Yemen
$_country_lang["236"] = 'S�rvia e Montenegro'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Rep�blica Democr�tica do Congo'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Z�mbia'; // Zambia
$_country_lang["239"] = 'Zimbabu�'; // Zimbabwe
?>