<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Афганистан'; // Afghanistan
$_country_lang["2"] = 'Албания'; // Albania
$_country_lang["3"] = 'Алжир'; // Algeria
$_country_lang["4"] = 'Американские Самоа'; // American Samoa
$_country_lang["5"] = 'Андорра'; // Andorra
$_country_lang["6"] = 'Ангола'; // Angola
$_country_lang["7"] = 'Ангилла'; // Anguilla
$_country_lang["8"] = 'Антарктика'; // Antarctica
$_country_lang["9"] = 'Антигуа и Барбуда'; // Antigua and Barbuda
$_country_lang["10"] = 'Аргентина'; // Argentina
$_country_lang["11"] = 'Армения'; // Armenia
$_country_lang["12"] = 'Аруба'; // Aruba
$_country_lang["13"] = 'Австралия'; // Australia
$_country_lang["14"] = 'Австрия'; // Austria
$_country_lang["15"] = 'Азербайджан'; // Azerbaijan
$_country_lang["16"] = 'Багамские Острова'; // Bahamas
$_country_lang["17"] = 'Бахрейн'; // Bahrain
$_country_lang["18"] = 'Бангладеш'; // Bangladesh
$_country_lang["19"] = 'Барбадос'; // Barbados
$_country_lang["20"] = 'Беларусь'; // Belarus
$_country_lang["21"] = 'Бельгия'; // Belgium
$_country_lang["22"] = 'Белиз'; // Belize
$_country_lang["23"] = 'Бенин'; // Benin
$_country_lang["24"] = 'Бермудские острова'; // Bermuda
$_country_lang["25"] = 'Бутан'; // Bhutan
$_country_lang["26"] = 'Боливия'; // Bolivia
$_country_lang["27"] = 'Босния и Герцеговина'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Ботсвана'; // Botswana
$_country_lang["29"] = 'Буве, Остров'; // Bouvet Island
$_country_lang["30"] = 'Бразилия'; // Brazil
$_country_lang["31"] = 'Британская территория в Индийском океане'; // British Indian Ocean Territory
$_country_lang["32"] = 'Бруней'; // Brunei Darussalam
$_country_lang["33"] = 'Болгария'; // Bulgaria
$_country_lang["34"] = 'Буркина-Фасо'; // Burkina Faso
$_country_lang["35"] = 'Бурунди'; // Burundi
$_country_lang["36"] = 'Камбоджа'; // Cambodia
$_country_lang["37"] = 'Камерун'; // Cameroon
$_country_lang["38"] = 'Канада'; // Canada
$_country_lang["39"] = 'Кабо-Верде'; // Cape Verde
$_country_lang["40"] = 'Каймановы Острова'; // Cayman Islands
$_country_lang["41"] = 'Центрально-Африканская Республика'; // Central African Republic
$_country_lang["42"] = 'Чад'; // Chad
$_country_lang["43"] = 'Чили'; // Chile
$_country_lang["44"] = 'Китай'; // China
$_country_lang["45"] = 'Остров Рождества'; // Christmas Island
$_country_lang["46"] = 'Кокосовые Острова (Килинг)'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Колумбия'; // Colombia
$_country_lang["48"] = 'Коморские Острова'; // Comoros
$_country_lang["49"] = 'Конго, Республика'; // Congo
$_country_lang["50"] = 'Острова Кука'; // Cook Islands
$_country_lang["51"] = 'Коста-Рика'; // Costa Rica
$_country_lang["52"] = 'Кот-Д&#39;Ивуар'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Хорватия'; // Croatia
$_country_lang["54"] = 'Куба'; // Cuba
$_country_lang["55"] = 'Кипр'; // Cyprus
$_country_lang["56"] = 'Чехия'; // Czech Republic
$_country_lang["57"] = 'Дания'; // Denmark
$_country_lang["58"] = 'Джибути'; // Djibouti
$_country_lang["59"] = 'Доминика'; // Dominica
$_country_lang["60"] = 'Доминиканская Республика'; // Dominican Republic
$_country_lang["61"] = 'Восточный Тимор'; // East Timor
$_country_lang["62"] = 'Эквадор'; // Ecuador
$_country_lang["63"] = 'Египет'; // Egypt
$_country_lang["64"] = 'Сальвадор'; // El Salvador
$_country_lang["65"] = 'Экваториальная Гвинея'; // Equatorial Guinea
$_country_lang["66"] = 'Эритрея'; // Eritrea
$_country_lang["67"] = 'Эстония'; // Estonia
$_country_lang["68"] = 'Эфиопия'; // Ethiopia
$_country_lang["69"] = 'Фолклендские (Мальвинские) Острова'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Фарерские острова'; // Faroe Islands
$_country_lang["71"] = 'Фиджи'; // Fiji
$_country_lang["72"] = 'Финляндия'; // Finland
$_country_lang["73"] = 'Франция'; // France
$_country_lang["74"] = 'Франция'; // France, Metropolitan
$_country_lang["75"] = 'Французская Гвиана'; // French Guiana
$_country_lang["76"] = 'Французская Полинезия'; // French Polynesia
$_country_lang["77"] = 'Французские Южные Территории'; // French Southern Territories
$_country_lang["78"] = 'Габон'; // Gabon
$_country_lang["79"] = 'Гамбия'; // Gambia
$_country_lang["80"] = 'Грузия'; // Georgia
$_country_lang["81"] = 'Германия'; // Germany
$_country_lang["82"] = 'Гана'; // Ghana
$_country_lang["83"] = 'Гибралтар'; // Gibraltar
$_country_lang["84"] = 'Греция'; // Greece
$_country_lang["85"] = 'Гренландия'; // Greenland
$_country_lang["86"] = 'Гренада'; // Grenada
$_country_lang["87"] = 'Гваделупа'; // Guadeloupe
$_country_lang["88"] = 'Гуам'; // Guam
$_country_lang["89"] = 'Гватемала'; // Guatemala
$_country_lang["90"] = 'Гвинея'; // Guinea
$_country_lang["91"] = 'Гвинея-Биссау'; // Guinea-bissau
$_country_lang["92"] = 'Гайана'; // Guyana
$_country_lang["93"] = 'Гаити'; // Haiti
$_country_lang["94"] = 'Остров Херд и острова Макдональд'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Гондурас'; // Honduras
$_country_lang["96"] = 'Гонконг'; // Hong Kong
$_country_lang["97"] = 'Венгрия'; // Hungary
$_country_lang["98"] = 'Исландия'; // Iceland
$_country_lang["99"] = 'Индия'; // India
$_country_lang["100"] = 'Индонезия'; // Indonesia
$_country_lang["101"] = 'Иран, Исламская Республика'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Ирак'; // Iraq
$_country_lang["103"] = 'Ирландия'; // Ireland
$_country_lang["104"] = 'Израиль'; // Israel
$_country_lang["105"] = 'Италия'; // Italy
$_country_lang["106"] = 'Ямайка'; // Jamaica
$_country_lang["107"] = 'Япония'; // Japan
$_country_lang["108"] = 'Иордания'; // Jordan
$_country_lang["109"] = 'Казахстан'; // Kazakhstan
$_country_lang["110"] = 'Кения'; // Kenya
$_country_lang["111"] = 'Кирибати'; // Kiribati
$_country_lang["112"] = 'КНДР'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Южная Корея'; // Korea, Republic of
$_country_lang["114"] = 'Кувейт'; // Kuwait
$_country_lang["115"] = 'Киргизия'; // Kyrgyzstan
$_country_lang["116"] = 'Лаос'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Латвия'; // Latvia
$_country_lang["118"] = 'Ливан'; // Lebanon
$_country_lang["119"] = 'Лесото'; // Lesotho
$_country_lang["120"] = 'Либерия'; // Liberia
$_country_lang["121"] = 'Ливия'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Лихтенштейн'; // Liechtenstein
$_country_lang["123"] = 'Литва'; // Lithuania
$_country_lang["124"] = 'Люксембург'; // Luxembourg
$_country_lang["125"] = 'Макау'; // Macau
$_country_lang["126"] = 'Македония'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Мадагаскар'; // Madagascar
$_country_lang["128"] = 'Малави'; // Malawi
$_country_lang["129"] = 'Малайзия'; // Malaysia
$_country_lang["130"] = 'Мальдивы'; // Maldives
$_country_lang["131"] = 'Мали'; // Mali
$_country_lang["132"] = 'Мальта'; // Malta
$_country_lang["133"] = 'Маршалловы Острова'; // Marshall Islands
$_country_lang["134"] = 'Мартиника'; // Martinique
$_country_lang["135"] = 'Мавритания'; // Mauritania
$_country_lang["136"] = 'Маврикий'; // Mauritius
$_country_lang["137"] = 'Майотта'; // Mayotte
$_country_lang["138"] = 'Мексика'; // Mexico
$_country_lang["139"] = 'Федеративные Штаты Микронезии'; // Micronesia, Federated States of
$_country_lang["140"] = 'Молдавия'; // Moldova, Republic of
$_country_lang["141"] = 'Монако'; // Monaco
$_country_lang["142"] = 'Монголия'; // Mongolia
$_country_lang["241"] = 'Черногория'; //Montenegro
$_country_lang["143"] = 'Монтсеррат'; // Montserrat
$_country_lang["144"] = 'Марокко'; // Morocco
$_country_lang["145"] = 'Мозамбик'; // Mozambique
$_country_lang["146"] = 'Мьянма'; // Myanmar
$_country_lang["147"] = 'Намибия'; // Namibia
$_country_lang["148"] = 'Науру'; // Nauru
$_country_lang["149"] = 'Непал'; // Nepal
$_country_lang["150"] = 'Нидерланды'; // Netherlands
$_country_lang["151"] = 'Нидерландские Антиллы'; // Netherlands Antilles
$_country_lang["152"] = 'Новая Каледония'; // New Caledonia
$_country_lang["153"] = 'Новая Зеландия'; // New Zealand
$_country_lang["154"] = 'Никарагуа'; // Nicaragua
$_country_lang["155"] = 'Нигер'; // Niger
$_country_lang["156"] = 'Нигерия'; // Nigeria
$_country_lang["157"] = 'Ниуэ'; // Niue
$_country_lang["158"] = 'Остров Норфолк'; // Norfolk Island
$_country_lang["159"] = 'Северные Марианские Острова'; // Northern Mariana Islands
$_country_lang["160"] = 'Норвегия'; // Norway
$_country_lang["161"] = 'Оман'; // Oman
$_country_lang["162"] = 'Пакистан'; // Pakistan
$_country_lang["163"] = 'Палау'; // Palau
$_country_lang["164"] = 'Панама'; // Panama
$_country_lang["165"] = 'Папуа-Новая Гвинея'; // Papua New Guinea
$_country_lang["166"] = 'Парагвай'; // Paraguay
$_country_lang["167"] = 'Перу'; // Peru
$_country_lang["168"] = 'Филиппины'; // Philippines
$_country_lang["169"] = 'Острова Питкэрн'; // Pitcairn
$_country_lang["170"] = 'Польша'; // Poland
$_country_lang["171"] = 'Португалия'; // Portugal
$_country_lang["172"] = 'Пуэрто-Рико'; // Puerto Rico
$_country_lang["173"] = 'Катар'; // Qatar
$_country_lang["174"] = 'Реюньон'; // Reunion
$_country_lang["175"] = 'Румыния'; // Romania
$_country_lang["176"] = 'Российская Федерация'; // Russian Federation
$_country_lang["177"] = 'Руанда'; // Rwanda
$_country_lang["178"] = 'Сент-Китс и Невис'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Сент-Люсия'; // Saint Lucia
$_country_lang["180"] = 'Сент-Винсент и Гренадины'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Самоа'; // Samoa
$_country_lang["182"] = 'Сан-Марино'; // San Marino
$_country_lang["183"] = 'Сан-Томе и Принсипи'; // Sao Tome and Principe
$_country_lang["184"] = 'Саудовская Аравия'; // Saudi Arabia
$_country_lang["185"] = 'Сенегал'; // Senegal
$_country_lang["240"] = 'Сербия'; //Serbia
$_country_lang["186"] = 'Сейшельские Острова'; // Seychelles
$_country_lang["187"] = 'Сьерра-Леоне'; // Sierra Leone
$_country_lang["188"] = 'Сингапур'; // Singapore
$_country_lang["189"] = 'Словакия (Словацкая Республика)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Словения'; // Slovenia
$_country_lang["191"] = 'Соломоновы Острова'; // Solomon Islands
$_country_lang["192"] = 'Сомали'; // Somalia
$_country_lang["193"] = 'Южно-Африканская Республика'; // South Africa
$_country_lang["194"] = 'Южная Георгия и Южные Сандвичевы Острова'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Испания'; // Spain
$_country_lang["196"] = 'Шри Ланка'; // Sri Lanka
$_country_lang["197"] = 'Остров Святой Елены'; // St. Helena
$_country_lang["198"] = 'Сен-Пьер и Микелон'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Судан'; // Sudan
$_country_lang["200"] = 'Суринам'; // Suriname
$_country_lang["201"] = 'Шпицберген и Ян-Майен'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Свазиленд'; // Swaziland
$_country_lang["203"] = 'Швеция'; // Sweden
$_country_lang["204"] = 'Швейцария'; // Switzerland
$_country_lang["205"] = 'Сирийская Арабская Республика'; // Syrian Arab Republic
$_country_lang["206"] = 'Тайвань'; // Taiwan
$_country_lang["207"] = 'Таджикистан'; // Tajikistan
$_country_lang["208"] = 'Танзания'; // Tanzania, United Republic of
$_country_lang["209"] = 'Тайланд'; // Thailand
$_country_lang["210"] = 'Того'; // Togo
$_country_lang["211"] = 'Токелау'; // Tokelau
$_country_lang["212"] = 'Тонга'; // Tonga
$_country_lang["213"] = 'Тринидад и Тобаго'; // Trinidad and Tobago
$_country_lang["214"] = 'Тунис'; // Tunisia
$_country_lang["215"] = 'Турция'; // Turkey
$_country_lang["216"] = 'Туркменистан'; // Turkmenistan
$_country_lang["217"] = 'Теркс и Кайкос'; // Turks and Caicos Islands
$_country_lang["218"] = 'Тувалу'; // Tuvalu
$_country_lang["219"] = 'Уганда'; // Uganda
$_country_lang["220"] = 'Украина'; // Ukraine
$_country_lang["221"] = 'Объединенные Арабские Эмираты'; // United Arab Emirates
$_country_lang["222"] = 'Великобритания'; // United Kingdom
$_country_lang["223"] = 'Соединенные Штаты Америки (США)'; // United States
$_country_lang["224"] = 'Внешние малые острова США'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Уругвай'; // Uruguay
$_country_lang["226"] = 'Узбекистан'; // Uzbekistan
$_country_lang["227"] = 'Вануату'; // Vanuatu
$_country_lang["228"] = 'Ватикан'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Венесуэла'; // Venezuela
$_country_lang["230"] = 'Вьетнам'; // Viet Nam
$_country_lang["231"] = 'Британские Виргинские Острова'; // Virgin Islands (British)
$_country_lang["232"] = 'Американские Виргинские Острова'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Уоллис и Футуна'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Западная Сахара'; // Western Sahara
$_country_lang["235"] = 'Йемен'; // Yemen
$_country_lang["236"] = 'Сербия и Черногория'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Конго, Демократическая Республика'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Замбия'; // Zambia
$_country_lang["239"] = 'Зимбабве'; // Zimbabwe
?>