<?php
/**
 * Country List Language File(Thai)
 *
 * Array keys refer to the ID number that is saved in the database
 * by Mr.Kittipong Intaboot COE#18,KKU (@kittipongint)
 * updated 30/01/2012
 */

$_country_lang["1"] = 'สาธารณรัฐอิสลามอัฟกานิสถาน'; // Afghanistan
$_country_lang["2"] = 'สาธารณรัฐแอลเบเนีย'; // Albania
$_country_lang["3"] = 'สาธารณรัฐประชาธิปไตยประชาชนแอลจีเรีย'; // Algeria
$_country_lang["4"] = 'อเมริกันซามัว'; // American Samoa
$_country_lang["5"] = 'ราชรัฐอันดอร์รา'; // Andorra
$_country_lang["6"] = 'สาธารณรัฐแองโกลา'; // Angola
$_country_lang["7"] = 'แองกวิลลา'; // Anguilla
$_country_lang["8"] = 'แอนตาร์กติกา'; // Antarctica
$_country_lang["9"] = 'แอนติกาและบาร์บูดา'; // Antigua and Barbuda
$_country_lang["10"] = 'สาธารณรัฐอาร์เจนตินา'; // Argentina
$_country_lang["11"] = 'สาธารณรัฐอาร์เมเนีย'; // Armenia
$_country_lang["12"] = 'อารูบา'; // Aruba
$_country_lang["13"] = 'เครือรัฐออสเตรเลีย'; // Australia
$_country_lang["14"] = 'สาธารณรัฐออสเตรีย'; // Austria
$_country_lang["15"] = 'สาธารณรัฐอาเซอร์ไบจาน'; // Azerbaijan
$_country_lang["16"] = 'เครือรัฐบาฮามาส'; // Bahamas
$_country_lang["17"] = 'ราชอาณาจักรบาห์เรน'; // Bahrain
$_country_lang["18"] = 'สาธารณรัฐประชาชนบังกลาเทศ'; // Bangladesh
$_country_lang["19"] = 'บาร์เบโดส'; // Barbados
$_country_lang["20"] = 'สาธารณรัฐเบลารุส'; // Belarus
$_country_lang["21"] = 'ราชอาณาจักรเบลเยียม'; // Belgium
$_country_lang["22"] = 'เบลีซ'; // Belize
$_country_lang["23"] = 'สาธารณรัฐเบนิน'; // Benin
$_country_lang["24"] = 'เบอร์มิวดา'; // Bermuda
$_country_lang["25"] = 'ราชอาณาจักรภูฏาน'; // Bhutan
$_country_lang["26"] = 'สาธารณรัฐโบลิเวีย'; // Bolivia
$_country_lang["27"] = 'บอสเนียและเฮอร์เซโกวีนา'; // Bosnia and Herzegowina
$_country_lang["28"] = 'สาธารณรัฐบอตสวานา'; // Botswana
$_country_lang["29"] = 'เกาะบูเวต'; // Bouvet Island
$_country_lang["30"] = 'สหพันธ์สาธารณรัฐบราซิล'; // Brazil
$_country_lang["31"] = 'บริติชอินเดียนโอเชียนเทร์ริทอรี'; // British Indian Ocean Territory
$_country_lang["32"] = 'เนการาบรูไนดารุสซาลาม'; // Brunei Darussalam
$_country_lang["33"] = 'สาธารณรัฐบัลแกเรีย'; // Bulgaria
$_country_lang["34"] = 'บูร์กินาฟาโซ'; // Burkina Faso
$_country_lang["35"] = 'สาธารณรัฐบุรุนดี'; // Burundi
$_country_lang["36"] = 'ราชอาณาจักรกัมพูชา'; // Cambodia
$_country_lang["37"] = 'สาธารณรัฐแคเมอรูน'; // Cameroon
$_country_lang["38"] = 'แคนาดา'; // Canada
$_country_lang["39"] = 'สาธารณรัฐเคปเวิร์ด'; // Cape Verde
$_country_lang["40"] = 'หมู่เกาะเคย์แมน'; // Cayman Islands
$_country_lang["41"] = 'สาธารณรัฐแอฟริกากลาง'; // Central African Republic
$_country_lang["42"] = 'สาธารณรัฐชาด'; // Chad
$_country_lang["43"] = 'สาธารณรัฐชิลี'; // Chile
$_country_lang["44"] = 'สาธารณรัฐประชาชนจีน'; // China
$_country_lang["45"] = 'เกาะคริสต์มาส'; // Christmas Island
$_country_lang["46"] = 'หมู่เกาะโคโคส'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'สาธารณรัฐโคลอมเบีย'; // Colombia
$_country_lang["48"] = 'สหภาพคอโมโรส'; // Comoros
$_country_lang["49"] = 'สาธารณรัฐคองโก'; // Congo
$_country_lang["50"] = 'หมู่เกาะคุก'; // Cook Islands
$_country_lang["51"] = 'สาธารณรัฐคอสตาริกา'; // Costa Rica
$_country_lang["52"] = 'สาธารณรัฐโกตดิวัวร์ (ไอวอรี่โคสต์)'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'สาธารณรัฐโครเอเชีย'; // Croatia
$_country_lang["54"] = 'สาธารณรัฐคิวบา'; // Cuba
$_country_lang["55"] = 'สาธารณรัฐไซปรัส'; // Cyprus
$_country_lang["56"] = 'สาธารณรัฐเช็ก'; // Czech Republic
$_country_lang["57"] = 'ราชอาณาจักรเดนมาร์ก'; // Denmark
$_country_lang["58"] = 'สาธารณรัฐจิบูตี'; // Djibouti
$_country_lang["59"] = 'เครือรัฐโดมินิกา'; // Dominica
$_country_lang["60"] = 'สาธารณรัฐโดมินิกัน'; // Dominican Republic
$_country_lang["61"] = 'สาธารณรัฐประชาธิปไตยติมอร์-เลสเต'; // East Timor
$_country_lang["62"] = 'สาธารณรัฐเอกวาดอร์'; // Ecuador
$_country_lang["63"] = 'สาธารณรัฐอาหรับอียิปต์'; // Egypt
$_country_lang["64"] = 'สาธารณรัฐเอลซัลวาดอร์'; // El Salvador
$_country_lang["65"] = 'สาธารณรัฐอิเควทอเรียลกินี'; // Equatorial Guinea
$_country_lang["66"] = 'รัฐเอริเทรีย'; // Eritrea
$_country_lang["67"] = 'สาธารณรัฐเอสโตเนีย'; // Estonia
$_country_lang["68"] = 'สหพันธ์สาธารณรัฐประชาธิปไตยเอธิโอเปีย'; // Ethiopia
$_country_lang["69"] = 'หมู่เกาะฟอล์กแลนด์'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'หมู่เกาะแฟโร'; // Faroe Islands
$_country_lang["71"] = 'สาธารณรัฐหมู่เกาะฟิจิ'; // Fiji
$_country_lang["72"] = 'สาธารณรัฐฟินแลนด์'; // Finland
$_country_lang["73"] = 'สาธารณรัฐฝรั่งเศส'; // France
$_country_lang["74"] = 'ประเทศฝรั่งเศสแผ่นดินใหญ่'; // France, Metropolitan
$_country_lang["75"] = 'เฟรนช์เกียนา'; // French Guiana
$_country_lang["76"] = 'เฟรนช์โปลินีเซีย'; // French Polynesia
$_country_lang["77"] = 'เฟรนช์เซาเทิร์นเทอริทอรี่ '; // French Southern Territories
$_country_lang["78"] = 'สาธารณรัฐกาบอง'; // Gabon
$_country_lang["79"] = 'สาธารณรัฐแกมเบีย'; // Gambia
$_country_lang["80"] = 'สาธารณรัฐจอร์เจีย'; // Georgia
$_country_lang["81"] = 'สหพันธ์สาธารณรัฐเยอรมนี'; // Germany
$_country_lang["82"] = 'สาธารณรัฐกานา'; // Ghana
$_country_lang["83"] = 'ยิบรอลตาร์'; // Gibraltar
$_country_lang["84"] = 'กรีซ'; // Greece
$_country_lang["85"] = 'กรีนแลนด์'; // Greenland
$_country_lang["86"] = 'เกรเนดา'; // Grenada
$_country_lang["87"] = 'กวาเดอลูป'; // Guadeloupe
$_country_lang["88"] = 'กวม'; // Guam
$_country_lang["89"] = 'สาธารณรัฐกัวเตมาลา'; // Guatemala
$_country_lang["90"] = 'สาธารณรัฐกินี'; // Guinea
$_country_lang["91"] = 'สาธารณรัฐกินี-บิสเซา'; // Guinea-bissau
$_country_lang["92"] = 'สาธารณรัฐสหกรณ์กายอานา'; // Guyana
$_country_lang["93"] = 'สาธารณรัฐเฮติ'; // Haiti
$_country_lang["94"] = 'หมู่เกาะเฮิร์ดและแมกดอนัลด์ '; // Heard and Mc Donald Islands
$_country_lang["95"] = 'สาธารณรัฐฮอนดูรัส'; // Honduras
$_country_lang["96"] = 'ฮ่องกง'; // Hong Kong
$_country_lang["97"] = 'สาธารณรัฐฮังการี'; // Hungary
$_country_lang["98"] = 'สาธารณรัฐไอซ์แลนด์'; // Iceland
$_country_lang["99"] = 'สาธารณรัฐอินเดีย'; // India
$_country_lang["100"] = 'สาธารณรัฐอินโดนีเซีย'; // Indonesia
$_country_lang["101"] = 'สาธารณรัฐอิสลามอิหร่าน'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'สาธารณรัฐอิรัก'; // Iraq
$_country_lang["103"] = 'ไอร์แลนด์'; // Ireland
$_country_lang["104"] = 'รัฐอิสราเอล'; // Israel
$_country_lang["105"] = 'สาธารณรัฐอิตาลี'; // Italy
$_country_lang["106"] = 'จาเมกา'; // Jamaica
$_country_lang["107"] = 'ญี่ปุ่น'; // Japan
$_country_lang["108"] = 'ราชอาณาจักรฮัชไมต์จอร์แดน'; // Jordan
$_country_lang["109"] = 'สาธารณรัฐคาซัคสถาน'; // Kazakhstan
$_country_lang["110"] = 'สาธารณรัฐเคนยา'; // Kenya
$_country_lang["111"] = 'สาธารณรัฐคิริบาส'; // Kiribati
$_country_lang["112"] = 'สาธารณรัฐประชาธิปไตยประชาชนเกาหลี(เหนือ)'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'สาธารณรัฐเกาหลี(ใต้)'; // Korea, Republic of
$_country_lang["114"] = 'รัฐคูเวต'; // Kuwait
$_country_lang["115"] = 'สาธารณรัฐคีร์กีซ'; // Kyrgyzstan
$_country_lang["116"] = 'สาธารณรัฐประชาธิปไตยประชาชนลาว'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'สาธารณรัฐลัตเวีย'; // Latvia
$_country_lang["118"] = 'สาธารณรัฐเลบานอน'; // Lebanon
$_country_lang["119"] = 'ราชอาณาจักรเลโซโท'; // Lesotho
$_country_lang["120"] = 'สาธารณรัฐไลบีเรีย'; // Liberia
$_country_lang["121"] = 'สาธารณรัฐสังคมนิยมประชาชนอาหรับลิเบีย'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'ราชรัฐลิกเตนสไตน์'; // Liechtenstein
$_country_lang["123"] = 'สาธารณรัฐลิทัวเนีย'; // Lithuania
$_country_lang["124"] = 'ราชรัฐลักเซมเบิร์ก'; // Luxembourg
$_country_lang["125"] = 'มาเก๊า'; // Macau
$_country_lang["126"] = 'สาธารณรัฐมาซิโดเนีย'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'สาธารณรัฐสังคมนิยมประชาชนอาหรับลิเบีย'; // Madagascar
$_country_lang["128"] = 'สาธารณรัฐมาลาวี'; // Malawi
$_country_lang["129"] = 'มาเลเซีย'; // Malaysia
$_country_lang["130"] = 'สาธารณรัฐมัลดีฟส์'; // Maldives
$_country_lang["131"] = 'สาธารณรัฐมาลี'; // Mali
$_country_lang["132"] = 'สาธารณรัฐมอลตา'; // Malta
$_country_lang["133"] = 'สาธารณรัฐหมู่เกาะมาร์แชลล์'; // Marshall Islands
$_country_lang["134"] = 'มาร์ตินีค'; // Martinique
$_country_lang["135"] = 'สาธารณรัฐอิสลามมอริเตเนีย'; // Mauritania
$_country_lang["136"] = 'สาธารณรัฐมอริเชียส'; // Mauritius
$_country_lang["137"] = 'มายอต'; // Mayotte
$_country_lang["138"] = 'สหรัฐเม็กซิโก'; // Mexico
$_country_lang["139"] = 'สหพันธรัฐไมโครนีเซีย'; // Micronesia, Federated States of
$_country_lang["140"] = 'สาธารณรัฐมอลโดวา'; // Moldova, Republic of
$_country_lang["141"] = 'ราชรัฐโมนาโก'; // Monaco
$_country_lang["142"] = 'มองโกเลีย'; // Mongolia
$_country_lang["241"] = 'สาธารณรัฐมอนเตเนโกร'; //Montenegro
$_country_lang["143"] = 'มอนต์เซอร์รัต'; // Montserrat
$_country_lang["144"] = 'ราชอาณาจักรโมร็อกโก'; // Morocco
$_country_lang["145"] = 'สาธารณรัฐโมซัมบิก'; // Mozambique
$_country_lang["146"] = 'สหภาพพม่า'; // Myanmar
$_country_lang["147"] = 'สาธารณรัฐนามิเบีย'; // Namibia
$_country_lang["148"] = 'สาธารณรัฐนาอูรู'; // Nauru
$_country_lang["149"] = 'ราชอาณาจักรเนปาล'; // Nepal
$_country_lang["150"] = 'ราชอาณาจักรเนเธอร์แลนด์'; // Netherlands
$_country_lang["151"] = 'เนเธอร์แลนด์แอนทิลลิส'; // Netherlands Antilles
$_country_lang["152"] = 'นิวแคลิโดเนีย'; // New Caledonia
$_country_lang["153"] = 'นิวซีแลนด์'; // New Zealand
$_country_lang["154"] = 'สาธารณรัฐนิการากัว'; // Nicaragua
$_country_lang["155"] = 'สาธารณรัฐไนเจอร์'; // Niger
$_country_lang["156"] = 'สหพันธ์สาธารณรัฐไนจีเรีย'; // Nigeria
$_country_lang["157"] = 'นีอูเอ'; // Niue
$_country_lang["158"] = 'เกาะนอร์ฟอล์'; // Norfolk Island
$_country_lang["159"] = 'หมู่เกาะนอร์เทิร์นมาเรียนา'; // Northern Mariana Islands
$_country_lang["160"] = 'ราชอาณาจักรนอร์เวย์'; // Norway
$_country_lang["161"] = 'รัฐสุลต่านโอมาน'; // Oman
$_country_lang["162"] = 'สาธารณรัฐอิสลามปากีสถาน'; // Pakistan
$_country_lang["163"] = 'สาธารณรัฐปาเลา'; // Palau
$_country_lang["164"] = 'สาธารณรัฐปานามา'; // Panama
$_country_lang["165"] = 'ปาปัวนิวกินี'; // Papua New Guinea
$_country_lang["166"] = 'สาธารณรัฐปารากวัย'; // Paraguay
$_country_lang["167"] = 'สาธารณรัฐเปรู'; // Peru
$_country_lang["168"] = 'สาธารณรัฐฟิลิปปินส์'; // Philippines
$_country_lang["169"] = 'หมู่เกาะพิตแคร์น'; // Pitcairn
$_country_lang["170"] = 'สาธารณรัฐโปแลนด์'; // Poland
$_country_lang["171"] = 'สาธารณรัฐโปรตุเกส'; // Portugal
$_country_lang["172"] = 'เปอร์โตริโก'; // Puerto Rico
$_country_lang["173"] = 'รัฐกาตาร์'; // Qatar
$_country_lang["174"] = 'เรอูนียง'; // Reunion
$_country_lang["175"] = 'โรมาเนีย'; // Romania
$_country_lang["176"] = 'สหพันธรัฐรัสเซีย'; // Russian Federation
$_country_lang["177"] = 'สาธารณรัฐรวันดา'; // Rwanda
$_country_lang["178"] = 'สหพันธรัฐเซนต์คิตส์และเนวิส'; // Saint Kitts and Nevis
$_country_lang["179"] = 'เซนต์ลูเซีย'; // Saint Lucia
$_country_lang["180"] = 'เซนต์วินเซนต์และเกรนาดีนส์'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'รัฐเอกราชซามัว'; // Samoa
$_country_lang["182"] = 'สาธารณรัฐซานมารีโน'; // San Marino
$_country_lang["183"] = 'สาธารณรัฐประชาธิปไตยเซาตูเมและปรินซิปี'; // Sao Tome and Principe
$_country_lang["184"] = 'ราชอาณาจักรซาอุดีอาระเบีย'; // Saudi Arabia
$_country_lang["185"] = 'สาธารณรัฐเซเนกัล'; // Senegal
$_country_lang["240"] = 'สาธารณรัฐเซอร์เบีย'; //Serbia
$_country_lang["186"] = 'สาธารณรัฐเซเชลส์'; // Seychelles
$_country_lang["187"] = 'สาธารณรัฐเซียร์ราลีโอน'; // Sierra Leone
$_country_lang["188"] = 'สาธารณรัฐสิงคโปร์'; // Singapore
$_country_lang["189"] = 'สาธารณรัฐสโลวัก (สโลวะเกีย)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'สาธารณรัฐสโลวีเนีย'; // Slovenia
$_country_lang["191"] = 'หมู่เกาะโซโลมอน'; // Solomon Islands
$_country_lang["192"] = 'สาธารณรัฐประชาธิปไตยโซมาลี (โซมาเลีย)'; // Somalia
$_country_lang["193"] = 'สาธารณรัฐแอฟริกาใต้'; // South Africa
$_country_lang["194"] = 'หมู่เกาะเซาท์จอร์เจียและเซาท์แซนด์วิช'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'ราชอาณาจักรสเปน'; // Spain
$_country_lang["196"] = 'สาธารณรัฐสังคมนิยมประชาธิปไตยศรีลังกา'; // Sri Lanka
$_country_lang["197"] = 'เซนต์เฮเลนา'; // St. Helena
$_country_lang["198"] = 'เซนต์ปิแอร์และมิคิวลอน'; // St. Pierre and Miquelon
$_country_lang["199"] = 'สาธารณรัฐซูดาน'; // Sudan
$_country_lang["200"] = 'สาธารณรัฐซูรินาเม'; // Suriname
$_country_lang["201"] = 'หมู่เกาะสวอลบอร์ดและแจนมาเยน'; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'ราชอาณาจักรสวาซิแลนด์'; // Swaziland
$_country_lang["203"] = 'ราชอาณาจักรสวีเดน'; // Sweden
$_country_lang["204"] = 'สมาพันธรัฐสวิส (สวิตเซอร์แลนด์)'; // Switzerland
$_country_lang["205"] = 'สาธารณรัฐอาหรับซีเรีย'; // Syrian Arab Republic
$_country_lang["206"] = 'ไต้หวัน'; // Taiwan
$_country_lang["207"] = 'สาธารณรัฐทาจิกิสถาน'; // Tajikistan
$_country_lang["208"] = 'สหสาธารณรัฐแทนซาเนีย'; // Tanzania, United Republic of
$_country_lang["209"] = 'ราชอาณาจักรไทย'; // Thailand
$_country_lang["210"] = 'สาธารณรัฐโตโก'; // Togo
$_country_lang["211"] = 'โตเกเลา'; // Tokelau
$_country_lang["212"] = 'ราชอาณาจักรตองกา'; // Tonga
$_country_lang["213"] = 'สาธารณรัฐตรินิแดดและโตเบโก'; // Trinidad and Tobago
$_country_lang["214"] = 'สาธารณรัฐตูนิเซีย'; // Tunisia
$_country_lang["215"] = 'สาธารณรัฐตุรกี'; // Turkey
$_country_lang["216"] = 'เติร์กเมนิสถาน'; // Turkmenistan
$_country_lang["217"] = 'หมู่เกาะเติกส์และหมู่เกาะเคคอส'; // Turks and Caicos Islands
$_country_lang["218"] = 'ตูวาลู'; // Tuvalu
$_country_lang["219"] = 'สาธารณรัฐยูกันดา'; // Uganda
$_country_lang["220"] = 'ยูเครน'; // Ukraine
$_country_lang["221"] = 'สหรัฐอาหรับเอมิเรตส์'; // United Arab Emirates
$_country_lang["222"] = 'สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์เหนือ'; // United Kingdom
$_country_lang["223"] = 'สหรัฐอเมริกา'; // United States
$_country_lang["224"] = 'หมู่เกาะเล็กๆรอบๆสหรัฐอเมริกา'; // United States Minor Outlying Islands
$_country_lang["225"] = 'สาธารณรัฐบูรพาอุรุกวัย'; // Uruguay
$_country_lang["226"] = 'สาธารณรัฐอุซเบกิสถาน'; // Uzbekistan
$_country_lang["227"] = 'สาธารณรัฐวานูอาตู'; // Vanuatu
$_country_lang["228"] = 'นครรัฐวาติกัน'; // Vatican City State (Holy See)
$_country_lang["229"] = 'สาธารณรัฐโบลีวาร์แห่งเวเนซุเอลา'; // Venezuela
$_country_lang["230"] = 'สาธารณรัฐสังคมนิยมเวียดนาม'; // Viet Nam
$_country_lang["231"] = 'หมู่เกาะบริติชเวอร์จิน'; // Virgin Islands (British)
$_country_lang["232"] = 'หมู่เกาะเวอร์จินของสหรัฐอเมริกา'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'หมู่เกาะวาลลิสและหมู่เกาะฟุตูนา'; // Wallis and Futuna Islands
$_country_lang["234"] = 'เวสเทิร์นสะฮารา'; // Western Sahara
$_country_lang["235"] = 'สาธารณรัฐเยเมน'; // Yemen
$_country_lang["236"] = 'เซอร์เบียและมอนเตเนโกร'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'สาธารณรัฐประชาธิปไตยคองโก'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'สาธารณรัฐแซมเบีย'; // Zambia
$_country_lang["239"] = 'สาธารณรัฐซิมบับเว'; // Zimbabwe
?>