<?php
/**
* Country List Language File
* Version: 1.0
* Date: 31/10/2006
*
* Array keys refer to the ID number that is saved in the database
*
*/

$_country_lang["1"] = 'Афганістан'; // Afghanistan
$_country_lang["2"] = 'Албанія'; // Albania
$_country_lang["3"] = 'Алжир'; // Algeria
$_country_lang["4"] = 'Американське Самоа'; // American Samoa
$_country_lang["5"] = 'Андорра'; // Andorra
$_country_lang["6"] = 'Ангола'; // Angola
$_country_lang["7"] = 'Ангілья'; // Anguilla
$_country_lang["8"] = 'Антарктика'; // Antarctica
$_country_lang["9"] = 'Антигуа і Барбуда'; // Antigua and Barbuda
$_country_lang["10"] = 'Аргентина'; // Argentina
$_country_lang["11"] = 'Вірменія'; // Armenia
$_country_lang["12"] = 'Аруба'; // Aruba
$_country_lang["13"] = 'Австралія'; // Australia
$_country_lang["14"] = 'Австрія'; // Austria
$_country_lang["15"] = 'Азербайжан'; // Azerbaijan
$_country_lang["16"] = 'Багамські острови'; // Bahamas
$_country_lang["17"] = 'Бахрейн'; // Bahrain
$_country_lang["18"] = 'Бангладеш'; // Bangladesh
$_country_lang["19"] = 'Барбадос'; // Barbados
$_country_lang["20"] = 'Білорусь'; // Belarus
$_country_lang["21"] = 'Бельгія'; // Belgium
$_country_lang["22"] = 'Беліз'; // Belize
$_country_lang["23"] = 'Бенін'; // Benin
$_country_lang["24"] = 'Бермудські острови'; // Bermuda
$_country_lang["25"] = 'Бутан'; // Bhutan
$_country_lang["26"] = 'Болівія'; // Bolivia
$_country_lang["27"] = 'Боснія і Герцеговина'; // Bosnia and Herzegowina
$_country_lang["28"] = 'Ботсвана'; // Botswana
$_country_lang["29"] = 'Острів Буве'; // Bouvet Island
$_country_lang["30"] = 'Бразилія'; // Brazil
$_country_lang["31"] = 'Британська територія в Індійському океані'; // British Indian Ocean Territory
$_country_lang["32"] = 'Бруней'; // Brunei Darussalam
$_country_lang["33"] = 'Болгарія'; // Bulgaria
$_country_lang["34"] = 'Буркіна-Фасо'; // Burkina Faso
$_country_lang["35"] = 'Бурунді'; // Burundi
$_country_lang["36"] = 'Камбоджа'; // Cambodia
$_country_lang["37"] = 'Камерун'; // Cameroon
$_country_lang["38"] = 'Канада'; // Canada
$_country_lang["39"] = 'Кабо-Верде'; // Cape Verde
$_country_lang["40"] = 'Кайманові острови'; // Cayman Islands
$_country_lang["41"] = 'Центральноафриканська Республіка'; // Central African Republic
$_country_lang["42"] = 'Чад'; // Chad
$_country_lang["43"] = 'Чилі'; // Chile
$_country_lang["44"] = 'Китай'; // China
$_country_lang["45"] = 'Острів Різдва'; // Christmas Island
$_country_lang["46"] = 'Кокосові острови (Кілінг)'; // Cocos (Keeling) Islands
$_country_lang["47"] = 'Колумбія'; // Colombia
$_country_lang["48"] = 'Коморські острови'; // Comoros
$_country_lang["49"] = 'Республіка Конго'; // Congo
$_country_lang["50"] = 'Острови Кука'; // Cook Islands
$_country_lang["51"] = 'Коста-Рика'; // Costa Rica
$_country_lang["52"] = 'Кот д&#39;Івуар'; // Cote D&#39;Ivoire
$_country_lang["53"] = 'Хорватія'; // Croatia
$_country_lang["54"] = 'Куба'; // Cuba
$_country_lang["55"] = 'Кіпр'; // Cyprus
$_country_lang["56"] = 'Чеська Республіка'; // Czech Republic
$_country_lang["57"] = 'Данія'; // Denmark
$_country_lang["58"] = 'Республіка Джибуті'; // Djibouti
$_country_lang["59"] = 'Домініка'; // Dominica
$_country_lang["60"] = 'Домініканська республіка'; // Dominican Republic
$_country_lang["61"] = 'Східний Тимор'; // East Timor
$_country_lang["62"] = 'Еквадор'; // Ecuador
$_country_lang["63"] = 'Єгипет'; // Egypt
$_country_lang["64"] = 'Сальвадор'; // El Salvador
$_country_lang["65"] = 'Екваторіальна Гвінея'; // Equatorial Guinea
$_country_lang["66"] = 'Еритрея'; // Eritrea
$_country_lang["67"] = 'Естонія'; // Estonia
$_country_lang["68"] = 'Ефіопія'; // Ethiopia
$_country_lang["69"] = 'Фолклендські острови'; // Falkland Islands (Malvinas)
$_country_lang["70"] = 'Фарерські острови'; // Faroe Islands
$_country_lang["71"] = 'Фіджі'; // Fiji
$_country_lang["72"] = 'Фінляндія'; // Finland
$_country_lang["73"] = 'Франція'; // France
$_country_lang["74"] = 'Франція, метрополія'; // France, Metropolitan
$_country_lang["75"] = 'Французька Гвіана'; // French Guiana
$_country_lang["76"] = 'Французька Полінезія'; // French Polynesia
$_country_lang["77"] = 'Французькі південні території'; // French Southern Territories
$_country_lang["78"] = 'Габон'; // Gabon
$_country_lang["79"] = 'Гамбія'; // Gambia
$_country_lang["80"] = 'Грузія'; // Georgia
$_country_lang["81"] = 'Німеччина'; // Germany
$_country_lang["82"] = 'Гана'; // Ghana
$_country_lang["83"] = 'Гібралтар'; // Gibraltar
$_country_lang["84"] = 'Греція'; // Greece
$_country_lang["85"] = 'Ґренландія'; // Greenland
$_country_lang["86"] = 'Гренада'; // Grenada
$_country_lang["87"] = 'Гваделупа'; // Guadeloupe
$_country_lang["88"] = 'Гуам'; // Guam
$_country_lang["89"] = 'Гватемала'; // Guatemala
$_country_lang["90"] = 'Гвінея'; // Guinea
$_country_lang["91"] = 'Гвінея-Бісау'; // Guinea-bissau
$_country_lang["92"] = 'Ґаяна'; // Guyana
$_country_lang["93"] = 'Гаїті'; // Haiti
$_country_lang["94"] = 'Острів Херд і острови Макдональд'; // Heard and Mc Donald Islands
$_country_lang["95"] = 'Гондурас'; // Honduras
$_country_lang["96"] = 'Гонконг'; // Hong Kong
$_country_lang["97"] = 'Угорщина'; // Hungary
$_country_lang["98"] = 'Ісландія'; // Iceland
$_country_lang["99"] = 'Індія'; // India
$_country_lang["100"] = 'Індонезія'; // Indonesia
$_country_lang["101"] = 'Іран (Ісламська Республіка)'; // Iran (Islamic Republic of)
$_country_lang["102"] = 'Ірак'; // Iraq
$_country_lang["103"] = 'Ірландія'; // Ireland
$_country_lang["104"] = 'Ізраїль'; // Israel
$_country_lang["105"] = 'Італія'; // Italy
$_country_lang["106"] = 'Ямайка'; // Jamaica
$_country_lang["107"] = 'Японія'; // Japan
$_country_lang["108"] = 'Йорданія'; // Jordan
$_country_lang["109"] = 'Казахстан'; // Kazakhstan
$_country_lang["110"] = 'Кенія'; // Kenya
$_country_lang["111"] = 'Кірибаті'; // Kiribati
$_country_lang["112"] = 'Корейська народно-демократична республіка'; // Korea, Democratic People&#39;s Republic of
$_country_lang["113"] = 'Південна Корея'; // Korea, Republic of
$_country_lang["114"] = 'Кувейт'; // Kuwait
$_country_lang["115"] = 'Киргизстан'; // Kyrgyzstan
$_country_lang["116"] = 'Лаоська народна Демократична Республіка'; // Lao People&#39;s Democratic Republic
$_country_lang["117"] = 'Латвія'; // Latvia
$_country_lang["118"] = 'Ліван'; // Lebanon
$_country_lang["119"] = 'Лесото'; // Lesotho
$_country_lang["120"] = 'Ліберія'; // Liberia
$_country_lang["121"] = 'Лівійська Арабська Джамахірія'; // Libyan Arab Jamahiriya
$_country_lang["122"] = 'Ліхтенштейн'; // Liechtenstein
$_country_lang["123"] = 'Литва'; // Lithuania
$_country_lang["124"] = 'Люксембург'; // Luxembourg
$_country_lang["125"] = 'Макао'; // Macau
$_country_lang["126"] = 'Македонія Колишня Югославська Республіка'; // Macedonia, The Former Yugoslav Republic of
$_country_lang["127"] = 'Мадагаскар'; // Madagascar
$_country_lang["128"] = 'Малаві'; // Malawi
$_country_lang["129"] = 'Малайзія'; // Malaysia
$_country_lang["130"] = 'Мальдіви'; // Maldives
$_country_lang["131"] = 'Малі'; // Mali
$_country_lang["132"] = 'Мальта'; // Malta
$_country_lang["133"] = 'Маршалові острови'; // Marshall Islands
$_country_lang["134"] = 'Мартініка'; // Martinique
$_country_lang["135"] = 'Мавританія'; // Mauritania
$_country_lang["136"] = 'Маврикій'; // Mauritius
$_country_lang["137"] = 'Майотта'; // Mayotte
$_country_lang["138"] = 'Мексика'; // Mexico
$_country_lang["139"] = 'Федеративні Штати Мікронезії'; // Micronesia, Federated States of
$_country_lang["140"] = 'Республіка Молдова'; // Moldova, Republic of
$_country_lang["141"] = 'Монако'; // Monaco
$_country_lang["142"] = 'Монголія'; // Mongolia
$_country_lang["241"] = 'Чорногорія'; //Montenegro
$_country_lang["143"] = 'Монтсеррат'; // Montserrat
$_country_lang["144"] = 'Марокко'; // Morocco
$_country_lang["145"] = 'Мозамбік'; // Mozambique
$_country_lang["146"] = 'М\'янма'; // Myanmar
$_country_lang["147"] = 'Намібія'; // Namibia
$_country_lang["148"] = 'Науру'; // Nauru
$_country_lang["149"] = 'Непал'; // Nepal
$_country_lang["150"] = 'Нідерланди'; // Netherlands
$_country_lang["151"] = 'Нідерландські Антильські острови'; // Netherlands Antilles
$_country_lang["152"] = 'Нова Каледонія'; // New Caledonia
$_country_lang["153"] = 'Нова Зеландія'; // New Zealand
$_country_lang["154"] = 'Нікарагуа'; // Nicaragua
$_country_lang["155"] = 'Нігер'; // Niger
$_country_lang["156"] = 'Ніґерія'; // Nigeria
$_country_lang["157"] = 'Ніуе'; // Niue
$_country_lang["158"] = 'Острів Норфолк'; // Norfolk Island
$_country_lang["159"] = 'Північні Маріанські острови'; // Northern Mariana Islands
$_country_lang["160"] = 'Норвегія'; // Norway
$_country_lang["161"] = 'Оман'; // Oman
$_country_lang["162"] = 'Пакістан'; // Pakistan
$_country_lang["163"] = 'Палау'; // Palau
$_country_lang["164"] = 'Панама'; // Panama
$_country_lang["165"] = 'Папуа Нова Гвінея'; // Papua New Guinea
$_country_lang["166"] = 'Парагвай'; // Paraguay
$_country_lang["167"] = 'Перу'; // Peru
$_country_lang["168"] = 'Філіпіни'; // Philippines
$_country_lang["169"] = 'Острови Піткерн'; // Pitcairn
$_country_lang["170"] = 'Польща'; // Poland
$_country_lang["171"] = 'Португалія'; // Portugal
$_country_lang["172"] = 'Пуерто-Рико'; // Puerto Rico
$_country_lang["173"] = 'Катар'; // Qatar
$_country_lang["174"] = 'Реюньйон'; // Reunion
$_country_lang["175"] = 'Румунія'; // Romania
$_country_lang["176"] = 'Російська Федерація'; // Russian Federation
$_country_lang["177"] = 'Руанда'; // Rwanda
$_country_lang["178"] = 'Сени-Кіттс і Невіс'; // Saint Kitts and Nevis
$_country_lang["179"] = 'Сент-Люсія'; // Saint Lucia
$_country_lang["180"] = 'Сент-Вінсент і Гренадини'; // Saint Vincent and the Grenadines
$_country_lang["181"] = 'Самоа'; // Samoa
$_country_lang["182"] = 'Сан-Маріно'; // San Marino
$_country_lang["183"] = 'Сан-Томе і Прінсіпі'; // Sao Tome and Principe
$_country_lang["184"] = 'Саудівська Аравія'; // Saudi Arabia
$_country_lang["185"] = 'Сенеґал'; // Senegal
$_country_lang["240"] = 'Сербія'; //Serbia
$_country_lang["186"] = 'Сейшельські острови'; // Seychelles
$_country_lang["187"] = 'Сьєрра-Леоне'; // Sierra Leone
$_country_lang["188"] = 'Сінґапур'; // Singapore
$_country_lang["189"] = 'Словаччина (Словацька Республіка)'; // Slovakia (Slovak Republic)
$_country_lang["190"] = 'Словенія'; // Slovenia
$_country_lang["191"] = 'Соломонові острови'; // Solomon Islands
$_country_lang["192"] = 'Сомалі'; // Somalia
$_country_lang["193"] = 'Південна Африка'; // South Africa
$_country_lang["194"] = 'Південна Джорджія та Південні Сандвічеві острови'; // South Georgia and the South Sandwich Islands
$_country_lang["195"] = 'Іспанія'; // Spain
$_country_lang["196"] = 'Шрі-Ланка'; // Sri Lanka
$_country_lang["197"] = 'Святої Єлени'; // St. Helena
$_country_lang["198"] = 'Сен-П\'єр і Мікелон'; // St. Pierre and Miquelon
$_country_lang["199"] = 'Судан'; // Sudan
$_country_lang["200"] = 'Суринам'; // Suriname
$_country_lang["201"] = 'острови Шпіцберген та Ян-Маєн '; // Svalbard and Jan Mayen Islands
$_country_lang["202"] = 'Свазіленд'; // Swaziland
$_country_lang["203"] = 'Швеція'; // Sweden
$_country_lang["204"] = 'Швейцарія'; // Switzerland
$_country_lang["205"] = 'Сирія'; // Syrian Arab Republic
$_country_lang["206"] = 'Тайвань'; // Taiwan
$_country_lang["207"] = 'Таджикістан'; // Tajikistan
$_country_lang["208"] = 'Танзанія'; // Tanzania, United Republic of
$_country_lang["209"] = 'Таїланд'; // Thailand
$_country_lang["210"] = 'Того'; // Togo
$_country_lang["211"] = 'Токелау'; // Tokelau
$_country_lang["212"] = 'Тонга'; // Tonga
$_country_lang["213"] = 'Тринідад і Тобаго'; // Trinidad and Tobago
$_country_lang["214"] = 'Туніс'; // Tunisia
$_country_lang["215"] = 'Туреччина'; // Turkey
$_country_lang["216"] = 'Туркменістан'; // Turkmenistan
$_country_lang["217"] = 'Острови Теркс і Кайкос'; // Turks and Caicos Islands
$_country_lang["218"] = 'Тувалу'; // Tuvalu
$_country_lang["219"] = 'Уганда'; // Uganda
$_country_lang["220"] = 'Україна'; // Ukraine
$_country_lang["221"] = 'Об\'єднані Арабські Емірати'; // United Arab Emirates
$_country_lang["222"] = 'Англія'; // United Kingdom
$_country_lang["223"] = 'Сполучені Штати'; // United States
$_country_lang["224"] = 'Зовнішні малі острови США'; // United States Minor Outlying Islands
$_country_lang["225"] = 'Уругвай'; // Uruguay
$_country_lang["226"] = 'Узбекістан'; // Uzbekistan
$_country_lang["227"] = 'Вануату'; // Vanuatu
$_country_lang["228"] = 'Держава-місто Ватикан (Святий Престол)'; // Vatican City State (Holy See)
$_country_lang["229"] = 'Венесуела'; // Venezuela
$_country_lang["230"] = 'В\'єтнам'; // Viet Nam
$_country_lang["231"] = 'Віргінські о-ви (Британські)'; // Virgin Islands (British)
$_country_lang["232"] = 'Віргінські острови (США)'; // Virgin Islands (U.S.)
$_country_lang["233"] = 'Уолліс і Футуна'; // Wallis and Futuna Islands
$_country_lang["234"] = 'Західна Сахара'; // Western Sahara
$_country_lang["235"] = 'Ємен'; // Yemen
$_country_lang["236"] = 'Сербія і Чорногорія'; // DEPRECATED: kept for backwards compatibility, Serbia and Montenegro
$_country_lang["237"] = 'Конго, Демократична Республіка'; // Congo, Democratic Republic of the
$_country_lang["238"] = 'Замбія'; // Zambia
$_country_lang["239"] = 'Зімбабве'; // Zimbabwe
?>