<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'スニペット';
$_lang['snippets_available'] = 'スニペットはページ中にコールを記述して呼び出すことができます。';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'このスニペットを削除しますか？';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'このスニペットを複製しますか？';
$_lang['snippet_duplicate_error'] = 'スニペットの複製中にエラーが発生しました。';
$_lang['snippet_err_create'] = 'スニペットの作成中にエラーが発生しました。';
$_lang['snippet_err_delete'] = 'スニペットの削除中にエラーが発生しました。';
$_lang['snippet_err_duplicate'] = 'スニペットの複製中にエラーが発生しました。';
$_lang['snippet_err_ae'] = '[[+name]]という名前のスニペットがすでに存在します。';
$_lang['snippet_err_invalid_name'] = '無効なスニペット名です。';
$_lang['snippet_err_locked'] = 'このスニペットは編集中のためロックされています。';
$_lang['snippet_err_nf'] = 'スニペットが見つかりません。';
$_lang['snippet_err_ns'] = 'スニペットが指定されていません。';
$_lang['snippet_err_ns_name'] = 'スニペットの名前を指定してください。';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'スニペットの保存中にエラーが発生しました。';
$_lang['snippet_execonsave'] = '保存後にスニペットを実行';
$_lang['snippet_lock'] = '編集のためスニペットをロックする';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = '<h3 style="font-weight:bold;">スニペットの管理</h3><p>編集したいスニペットを選択してください。</p>';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = '既定のプロパティ';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'スニペット';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
