<?php
/**
 * Chunk English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */

// Entry out of alpha order because it must come before the entry it's used in below
$_lang['example_tag_chunk_name'] = 'NameOfChunk';

$_lang['chunk'] = 'टुकड़ा';
$_lang['chunk_category_desc'] = 'Use to group Chunks within the Elements tree.';
$_lang['chunk_code'] = 'Chunk Code (HTML)';
$_lang['chunk_description_desc'] = 'Usage information for this Chunk shown in search results and as a tooltip in the Elements tree.';
$_lang['chunk_delete_confirm'] = 'क्या आप वाकई यह chunk हटाना चाहते हैं?';
$_lang['chunk_duplicate_confirm'] = 'आप सुनिश्चित करें कि आप इस chunk नकल करना चाहते हैं';
$_lang['chunk_err_create'] = 'चौंक बनाने का प्रयास करते समय एक त्रुटि हुईं ।';
$_lang['chunk_err_duplicate'] = 'त्रुटि duplicating chunk।';
$_lang['chunk_err_ae'] = '"[[+name]]" नाम के साथ एक chunk पहले से ही है।';
$_lang['chunk_err_invalid_name'] = 'chunk का नाम अमान्य है।';
$_lang['chunk_err_locked'] = 'chunk अवरोधित है।';
$_lang['chunk_err_remove'] = 'Chunk ko हटाने का प्रयास समय एक त्रुटि हुईं ।';
$_lang['chunk_err_save'] = 'Chunk को सहेजते समय कोई त्रुटि उत्पन्न हुई।';
$_lang['chunk_err_nf'] = 'Chunk नहीं मिला!';
$_lang['chunk_err_nfs'] = 'Chunk के साथ id नहीं मिला: [[+id]]';
$_lang['chunk_err_ns'] = 'Chunk नहीं निर्दिष्ट किया।';
$_lang['chunk_err_ns_name'] = 'कृपया कोई नाम निर्दिष्ट करें।';
$_lang['chunk_lock'] = 'संपादन के लिए लॉक chunk.';
$_lang['chunk_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Chunk.';
$_lang['chunk_name_desc'] = 'Place the content generated by this Chunk in a Resource, Template, or other Chunk using the following MODX tag: [[+tag]]';
$_lang['chunk_new'] = 'मेनू बनाए';
$_lang['chunk_properties'] = 'डिफ़ॉल्ट गुण';
$_lang['chunk_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Chunk</em> as well as its content. The content must be HTML, either placed in the <em>Chunk Code</em> field below or in a static external file, and may include MODX tags. Note, however, that PHP code will not run in this element.';
$_lang['chunk_tag_copied'] = 'Chunk tag copied!';
$_lang['chunks'] = 'टुकड़े';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['chunk_desc_category'] = $_lang['chunk_category_desc'];
$_lang['chunk_desc_description'] = $_lang['chunk_description_desc'];
$_lang['chunk_desc_name'] = $_lang['chunk_name_desc'];
$_lang['chunk_lock_msg'] = $_lang['chunk_lock_desc'];

// --tabs
$_lang['chunk_msg'] = $_lang['chunk_tab_general_desc'];
