<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'स्नीपेट';
$_lang['snippets_available'] = 'आप के लिए उपलब्ध Snippets अपने पेज में शामिल करने के लिए';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'आप सुनिश्चित करें कि आप इस Snippet हटाना चाहते हैं?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'आप इस snippet नकल करना चाहते हैं आप यकीन कर रहे हैं?';
$_lang['snippet_duplicate_error'] = 'Snippet duplicating करते समय एक त्रुटि उत्पन्न हुई।';
$_lang['snippet_err_create'] = 'Snippet बनाते समय कोई त्रुटि उत्पन्न हुई।';
$_lang['snippet_err_delete'] = 'Snippet को नष्ट करने का प्रयास करते समय एक त्रुटि उत्पन्न हुई।';
$_lang['snippet_err_duplicate'] = 'Snippet duplicate करने का प्रयास करते समय एक त्रुटि उत्पन्न हुई।';
$_lang['snippet_err_ae'] = 'एक snippet "[[+name]]" नाम के साथ पहले से ही मौजूद है।';
$_lang['snippet_err_invalid_name'] = 'Snippet नाम अमान्य है।';
$_lang['snippet_err_locked'] = 'यह snippet संपादन के लिए अवरोधित है।';
$_lang['snippet_err_nf'] = 'Snippet नहीं पाया!';
$_lang['snippet_err_ns'] = 'Snippet निर्दिष्ट नहीं किया गया।';
$_lang['snippet_err_ns_name'] = 'कृपया Snippet के लिए एक नाम निर्दिष्ट करें।';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'Snippet सहेजते समय एक त्रुटि उत्पन्न हुई।';
$_lang['snippet_execonsave'] = 'Snippet सहेजने के बाद निष्पादित।';
$_lang['snippet_lock'] = 'संपादन के लिए लॉक snippet';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'यहाँ आप कौन सा snippet आप संपादित करना चाहते हैं चुन सकते हैं।';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Snippet बनाएँ';
$_lang['snippet_properties'] = 'डिफ़ॉल्ट गुण';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'स्निपेट्स';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
