<?php
/**
 * TV English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_tv_name'] = 'NameOfTV';
$_lang['has_access'] = 'तक पहुँच गया है?';
$_lang['filter_by_category'] = 'Category द्वारा फ़िल्टर करें...';
$_lang['rank'] = 'पद';
$_lang['rendering_options'] = 'प्रतिपादन विकल्प';
$_lang['tv'] = 'टीवी ';
$_lang['tvs'] = 'पोस्टर चर';
$_lang['tv_binding_msg'] = 'इस फ़ील्ड का उपयोग कर डेटा स्रोत बाइंडिंग का समर्थन करता है @ आदेशों';
$_lang['tv_caption'] = 'कैप्शन';
$_lang['tv_caption_desc'] = 'The label shown for this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_category_desc'] = 'Use to group TVs in Resource editing pages and within the Elements tree.';
$_lang['tv_change_template_msg'] = 'Changing this template will cause the page to reload the TVs, losing any unsaved changes.<br /><br /> Are you sure you want to change this template?';
$_lang['tv_delete_confirm'] = 'क्या आप बकाई इस टीवी को हटाना चाहते हैं';
$_lang['tv_description'] = 'Description:';
$_lang['tv_description_desc'] = 'Usage information for this TV shown next to its caption in Resource editing pages, as a tooltip in the Elements tree, and within search results.';
$_lang['tv_err_delete'] = 'An error occurred while trying to delete the TV.';
$_lang['tv_err_duplicate'] = 'An error occurred while trying to duplicate the TV.';
$_lang['tv_err_duplicate_templates'] = 'टीवी टेम्पलेट्स duplicating करते समय एक त्रुटि उत्पन्न हुई।';
$_lang['tv_err_duplicate_documents'] = 'टीवी documents duplicating करते समय एक त्रुटि उत्पन्न हुई।';
$_lang['tv_err_duplicate_documentgroups'] = 'टीवी document समूहों duplicating करते समय एक त्रुटि उत्पन्न हुई।';
$_lang['tv_err_ae'] = 'A TV already exists with the name "[[+name]]".';
$_lang['tv_err_invalid_name'] = 'TV name is invalid.';
$_lang['tv_err_invalid_id_attr'] = 'HTML ids must not begin with a number or contain any white space.';
$_lang['tv_err_locked'] = 'TV बंद!';
$_lang['tv_err_nf'] = 'TV नहीं मिला.';
$_lang['tv_err_nfs'] = 'कुंजी के साथ TV नहीं मिला: [[+id]]';
$_lang['tv_err_ns'] = 'TV निर्दिष्ट नहीं.';
$_lang['tv_err_reserved_name'] = 'A TV cannot have the same name as a Resource field.';
$_lang['tv_err_save_access_permissions'] = 'TV एक्सेस अनुमतियों को सहेजने का प्रयास करते समय एक त्रुटि हुई';
$_lang['tv_err_save'] = 'An error occurred while saving the TV.';
$_lang['tv_inuse'] = 'The following document(s) are currently using this TV. To continue with the delete operation click the Delete button otherwise click the Cancel button.';
$_lang['tv_inuse_template'] = 'निम्न टेम्पलेट वर्तमान मे इस TV का उपयोग कर रहे हैं: [[+टेम्पलेट्स]].<br /><br />कृपया इसे हटाने से पहले TV को टेम्प्लेट(s) से अलग करें.';
$_lang['is_static_tv_desc'] = 'Use an external file to store the default value for this TV. This may be useful if the default value’s content is particularly lengthy.';
$_lang['tv_lock'] = 'संपादन प्रतिबंधित है';
$_lang['tv_lock_desc'] = 'Only users with “edit_locked” permissions can edit this TV.';
$_lang['tv_management_msg'] = 'Manage additional custom TVs for your documents.';
$_lang['tv_name_desc'] = 'Place the content generated by this TV in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['tv_new'] = 'TV बनायें';
$_lang['tv_novars'] = 'कोई Tvs नहीं मिला';
$_lang['tv_properties'] = 'डिफ़ॉल्ट गुण';
$_lang['tv_rank'] = 'सॉर्ट क्रम';
$_lang['tv_rank_desc'] = 'Use to control the positioning of this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_reset_params'] = 'पैरामीटर्स को रीसेट';
$_lang['tv_tab_access_desc'] = 'Select the Resource Groups that this TV belongs to. Only users with access to the Groups selected will be able to modify this TV. If no Groups are selected, all users with access to the Manager will be able to modify the TV.';
$_lang['tv_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Template Variable</em> (TV). Note that TVs must be assigned to templates in order to access them from snippets and documents.';
$_lang['tv_tab_input_options'] = 'इनपुट विकल्प';
$_lang['tv_tab_input_options_desc'] = '<p>Here you can edit the input options for the TV, specific to the type of input render that you select.</p>';
$_lang['tv_tab_output_options'] = 'आउटपुट विकल्प';
$_lang['tv_tab_output_options_desc'] = '<p>Here you can edit the output options for the TV, specific to the type of output render that you select.</p>';
$_lang['tv_tab_sources_desc'] = 'यहाँ आप मीडिया स्रोतों कि प्रत्येक निर्दिष्ट Context में इस टीवी के लिए इस्तेमाल किया जा करने के लिए कर रहे हैं असाइन कर सकते हैं। इसे परिवर्तित करने के लिए ग्रिड में स्रोत के नाम पर डबल क्लिक करें।';
$_lang['tv_tab_tmpl_access'] = 'टेम्पलेट का उपयोग';
$_lang['tv_tab_tmpl_access_desc'] = 'इस टेम्पलेट वेरिएबल का उपयोग करने के लिए अनुमति दी जाती है कि टेम्पलेट का चयन करें.';
$_lang['tv_tag_copied'] = 'TV टैग कॉपी किया गया';
$_lang['tv_widget'] = 'विजेट';
$_lang['tv_widget_prop'] = 'विजेट गुण';
$_lang['tvd_err_remove'] = 'An error occurred while trying to delete the TV from the document.';
$_lang['tvdg_err_remove'] = 'An error occurred while trying to delete the TV from the document group.';
$_lang['tvdg_err_save'] = 'An error occurred while trying to attach the TV to the document group.';
$_lang['tvt_err_nf'] = 'TV does not have access to the specified template.';
$_lang['tvt_err_remove'] = 'An error occurred while trying to delete the TV from the template.';
$_lang['tvt_err_save'] = 'An error occurred while trying to attach the TV to the template.';

// Temporarily match old keys to new ones to ensure compatibility
// -- fields
$_lang['tv_desc_caption'] = $_lang['tv_caption_desc'];
$_lang['tv_desc_category'] = $_lang['tv_category_desc'];
$_lang['tv_desc_description'] = $_lang['tv_description_desc'];
$_lang['tv_desc_name'] = $_lang['tv_name_desc'];
$_lang['tv_lock_msg'] = $_lang['tv_lock_desc'];
$_lang['tv_rank_msg'] = $_lang['tv_rank_desc'];

// -- tabs
$_lang['tv_access_msg'] = $_lang['tv_tab_access_desc'];
$_lang['tv_input_options'] = $_lang['tv_tab_input_options'];
$_lang['tv_input_options_msg'] = $_lang['tv_tab_input_options_desc'];
$_lang['tv_msg'] = $_lang['tv_tab_general_desc'];
$_lang['tv_output_options'] = $_lang['tv_tab_output_options'];
$_lang['tv_output_options_msg'] = $_lang['tv_tab_output_options_desc'];
$_lang['tv_sources.intro_msg'] = $_lang['tv_tab_sources_desc'];
$_lang['tv_tmpl_access'] = $_lang['tv_tab_tmpl_access'];
$_lang['tv_tmpl_access_msg'] = $_lang['tv_tab_tmpl_access_desc'];

/*
    Refer to default.inc.php for the keys below.
    (Placement in this default file necessary to allow
    quick create/edit panels access to them when opened
    outside the context of their respective element types)

    tv_caption_desc
    tv_category_desc
    tv_description_desc

*/
