<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Potongan';
$_lang['snippets_available'] = 'Potongan tersedia bagi Anda untuk disertakan dalam halaman Anda';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Apakah Anda yakin Anda ingin menghapus potongan ini?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Apakah Anda yakin Anda ingin menduplikasi potongan ini?';
$_lang['snippet_duplicate_error'] = 'Terjadi kesalahan saat duplikasi potongan.';
$_lang['snippet_err_create'] = 'Terjadi kesalahan saat membuat potongan.';
$_lang['snippet_err_delete'] = 'Terjadi kesalahan saat mencoba untuk menghapus cuplikan.';
$_lang['snippet_err_duplicate'] = 'Galat terjadi saat mencoba menduplikasi potongan.';
$_lang['snippet_err_ae'] = 'Potongan sudah ada dengan nama "[[+name]]".';
$_lang['snippet_err_invalid_name'] = 'Potongan name tidak valid.';
$_lang['snippet_err_locked'] = 'Potongan ini terkunci untuk mengedit.';
$_lang['snippet_err_nf'] = 'Potongan tidak ditemukan!';
$_lang['snippet_err_ns'] = 'Potongan tidak ditentukan.';
$_lang['snippet_err_ns_name'] = 'Silakan tentukan nama untuk potongan.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'Terjadi kesalahan saat menyimpan cuplikan.';
$_lang['snippet_execonsave'] = 'Mengeksekusi potongan setelah menyimpan.';
$_lang['snippet_lock'] = 'Kunci potongan untuk mengedit';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Di sini Anda dapat memilih potongan yang akan diedit.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'Properti bawaan';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'Potongan';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
