<?php
/**
 * Chunk English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */

// Entry out of alpha order because it must come before the entry it's used in below
$_lang['example_tag_chunk_name'] = 'NameOfChunk';

$_lang['chunk'] = 'Чанк';
$_lang['chunk_category_desc'] = 'Use to group Chunks within the Elements tree.';
$_lang['chunk_code'] = 'Chunk Code (HTML)';
$_lang['chunk_description_desc'] = 'Usage information for this Chunk shown in search results and as a tooltip in the Elements tree.';
$_lang['chunk_delete_confirm'] = 'Вы уверены, что хотите удалить этот чанк?';
$_lang['chunk_duplicate_confirm'] = 'Вы уверены, что хотите сделать копию этого чанка?';
$_lang['chunk_err_create'] = 'Произошла ошибка при попытке создать чанк.';
$_lang['chunk_err_duplicate'] = 'Ошибка при дублировании чанка.';
$_lang['chunk_err_ae'] = 'Уже существует чанк с названием «[[+name]]».';
$_lang['chunk_err_invalid_name'] = 'Название чанка недопустимо.';
$_lang['chunk_err_locked'] = 'Чанк заблокирован.';
$_lang['chunk_err_remove'] = 'Произошла ошибка при попытке удалить чанк.';
$_lang['chunk_err_save'] = 'Произошла ошибка при сохранении чанка.';
$_lang['chunk_err_nf'] = 'Чанк не найден!';
$_lang['chunk_err_nfs'] = 'Не найден чанк с ID: [[+id]]';
$_lang['chunk_err_ns'] = 'Чанк не указан.';
$_lang['chunk_err_ns_name'] = 'Пожалуйста, укажите название.';
$_lang['chunk_lock'] = 'Заблокировать чанк для редактирования';
$_lang['chunk_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Chunk.';
$_lang['chunk_name_desc'] = 'Place the content generated by this Chunk in a Resource, Template, or other Chunk using the following MODX tag: [[+tag]]';
$_lang['chunk_new'] = 'Создать чанк';
$_lang['chunk_properties'] = 'Параметры по умолчанию';
$_lang['chunk_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Chunk</em> as well as its content. The content must be HTML, either placed in the <em>Chunk Code</em> field below or in a static external file, and may include MODX tags. Note, however, that PHP code will not run in this element.';
$_lang['chunk_tag_copied'] = 'Chunk tag copied!';
$_lang['chunk_title'] = 'Создать/редактировать чанк';
$_lang['chunk_untitled'] = 'Безымянный чанк';
$_lang['chunks'] = 'Чанки';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['chunk_desc_category'] = $_lang['chunk_category_desc'];
$_lang['chunk_desc_description'] = $_lang['chunk_description_desc'];
$_lang['chunk_desc_name'] = $_lang['chunk_name_desc'];
$_lang['chunk_lock_msg'] = $_lang['chunk_lock_desc'];

// --tabs
$_lang['chunk_msg'] = $_lang['chunk_tab_general_desc'];
