<?php
/**
 * English language strings for Dashboards
 *
 * @package modx
 * @subpackage lexicon
 * @language en
 */
$_lang['dashboard'] = 'Панель управления';
$_lang['dashboard_add'] = 'Создать панель';
$_lang['dashboard_create'] = 'Создать панель';
$_lang['dashboard_desc_name'] = 'Название панели.';
$_lang['dashboard_desc_description'] = 'Краткое описание панели.';
$_lang['dashboard_desc_hide_trees'] = 'Если отмечено, древовидные меню будут скрыты при генерации панели.';
$_lang['dashboard_hide_trees'] = 'Скрыть древовидные меню';
$_lang['dashboard_desc_customizable'] = 'Allow users to customize this dashboard for their accounts: create, delete and change position or size of widgets.';
$_lang['dashboard_customizable'] = 'Настраиваемая';
$_lang['dashboard_duplicate'] = 'Копировать панель';
$_lang['dashboard_remove'] = 'Удалить панель';
$_lang['dashboard_remove_confirm'] = 'Are you sure you want to delete this Dashboard?';
$_lang['dashboard_remove_multiple'] = 'Delete Dashboards';
$_lang['dashboard_remove_multiple_confirm'] = 'Are you sure you want to delete the selected Dashboards?';
$_lang['dashboard_update'] = 'Edit Dashboard';
$_lang['dashboard_err_ae_name'] = 'Панель с названием «[[+name]]» уже существует! Пожалуйста, укажите другое название.';
$_lang['dashboard_err_duplicate'] = 'Произошла ошибка при попытке копировать панель.';
$_lang['dashboard_err_nf'] = 'Панель не найдена.';
$_lang['dashboard_err_ns'] = 'Панель не указана.';
$_lang['dashboard_err_ns_name'] = 'Укажите название панели.';
$_lang['dashboard_err_remove'] = 'An error occurred while trying to delete the Dashboard.';
$_lang['dashboard_err_remove_default'] = 'You cannot delete the default Dashboard!';
$_lang['dashboard_err_save'] = 'Произошла ошибка при попытке сохранить панель.';
$_lang['dashboard_usergroup_add'] = 'Назначить панель группе пользователей';
$_lang['dashboard_usergroup_remove'] = 'Delete Dashboard from User Group';
$_lang['dashboard_usergroup_remove_confirm'] = 'Вы уверены, что хотите восстановить панель по умолчанию для этой группы пользователей?';
$_lang['dashboard_usergroups.intro_msg'] = 'Список групп пользователей, использующих эту панель.';
$_lang['dashboard_widget_err_placed'] = 'Этот виджет уже есть в этой панели!';
$_lang['dashboard_widgets.intro_msg'] = 'Manage widgets in this dashboard. You can also drag and drop rows in the grid to rearrange them.<br><br>Please note: if a dashboard is "customizable", this settings will be applied only for the first load for every user. From here they will be able to create, delete and change the position or size of their widgets. User access to widgets can be limited by applying permissions.';
$_lang['dashboards'] = 'Панели управления';
$_lang['dashboards.intro_msg'] = 'Здесь вы можете управлять всеми доступными панелями.';
$_lang['rank'] = 'Сортировка';
$_lang['user_group_filter'] = 'По группе пользователей';
$_lang['widget'] = 'Виджет';
$_lang['widget_content'] = 'Содержимое виджета';
$_lang['widget_create'] = 'Create Widget';
$_lang['widget_err_ae_name'] = 'Виджет с названием «[[+name]]» уже существует! Укажите другое название.';
$_lang['widget_err_nf'] = 'Виджет не найден!';
$_lang['widget_err_ns'] = 'Виджет не указан!';
$_lang['widget_err_ns_name'] = 'Укажите название виджета.';
$_lang['widget_err_remove'] = 'An error occurred while trying to delete the Widget.';
$_lang['widget_err_save'] = 'Произошла ошибка при попытке сохранить виджет.';
$_lang['widget_file'] = 'Файл';
$_lang['widget_dashboards.intro_msg'] = 'Ниже приведен список всех панелей, на которых этот виджет размещён.';
$_lang['widget_dashboard_remove'] = 'Delete Widget From Dashboard';
$_lang['widget_description_desc'] = 'Описание виджета или ключ записи словаря с описанием виджета и того, что он делает.';
$_lang['widget_html'] = 'HTML';
$_lang['widget_lexicon_desc'] = 'Тема словаря, которая загружается вместе с виджетом. Используется для перевода имени и описания, или любого другого текста в виджете.';
$_lang['widget_permission_desc'] = 'Наличие этого разрешения будет требоваться, чтобы пользователь мог добавить виджет на свою панель.';
$_lang['widget_permission'] = 'Привилегии';
$_lang['widget_name_desc'] = 'Название виджета или ключ записи словаря с названием виджета.';
$_lang['widget_new'] = 'Create Widget';
$_lang['widget_add'] = 'Добавить виджет';
$_lang['widget_add_desc'] = 'Выберите виджет, который нужно добавить на панель.';
$_lang['widget_add_success'] = 'Виджет был успешно добавлен на вашу панель. Он будет загружен после закрытия этого окна.';
$_lang['widget_remove'] = 'Удалить виджет';
$_lang['widget_remove_confirm'] = 'Are you sure you want to delete this Dashboard Widget? This is permanent, and will delete the Widget from all Dashboards.';
$_lang['widget_remove_multiple'] = 'Удалить несколько виджетов';
$_lang['widget_remove_multiple_confirm'] = 'Are you sure you want to delete these Dashboard Widgets? This is permanent, and will delete the Widgets from all their assigned Dashboards.';
$_lang['widget_namespace'] = 'Пространство имён';
$_lang['widget_namespace_desc'] = 'Пространство имён, которое будет использовать виджет. Полезно при использовании собственных путей.';
$_lang['widget_php'] = 'Встроенный PHP-виджет';
$_lang['widget_place'] = 'Добавить виджет';
$_lang['widget_size'] = 'Размер';
$_lang['widget_size_desc'] = 'Размер виджета. Размеры варьируются от «Одной четвёртой» до «Двойного размера».';
$_lang['widget_size_double'] = 'Двойной размер';
$_lang['widget_size_full'] = 'На всю ширину';
$_lang['widget_size_three_quarters'] = 'Три четверти';
$_lang['widget_size_two_third'] = 'Две третьих';
$_lang['widget_size_half'] = 'Половина';
$_lang['widget_size_one_third'] = 'Одна третья';
$_lang['widget_size_quarter'] = 'Одна четвёртая';
$_lang['widget_snippet'] = 'Сниппет';
$_lang['widget_type'] = 'Тип виджета';
$_lang['widget_type_desc'] = 'Виджет типа «Сниппет» — это обычный сниппет, результаты его работы будут выведены в виджете. Виджет типа «HTML» просто выведет HTML. Виджет типа «Файл» загружается из php-файла, путь к которому указан в содержимом виджета, в файле надо использовать return для вывода содержимого или return \'имяКласса\', наследующего класс modDashboardWidgetClass. Виджет типа «Встроенный PHP-виджет» выводит результаты выполнения PHP-кода из содержимого виджета. <a href="http://rtfm.modx.com/display/revolution20/Dashboard+Widget+Types">Документация по типам виджетов</a>. ';
$_lang['widget_unplace'] = 'Delete Widget from Dashboard';
$_lang['widget_update'] = 'Edit Widget';
$_lang['widgets'] = 'Виджеты';
$_lang['widgets.intro_msg'] = 'Список доступных виджетов.';

$_lang['action_new_resource'] = 'Новый ресурс';
$_lang['action_new_resource_desc'] = 'Создать новый ресурс.';
$_lang['action_view_website'] = 'Перейти на сайт';
$_lang['action_view_website_desc'] = 'Открыть сайт в новой вкладке.';
$_lang['action_advanced_search'] = 'Расширенный поиск';
$_lang['action_advanced_search_desc'] = 'Расширенный поиск вашего сайта.';
$_lang['action_manage_users'] = 'Управление пользователями';
$_lang['action_manage_users_desc'] = 'Добавление, обновление, и назначение прав пользователям.';

$_lang['w_buttons'] = 'Кнопки';
$_lang['w_buttons_desc'] = 'Отображение набора кнопок из массива, указанного в свойствах виджета.';
$_lang['w_updates'] = 'Обновления';
$_lang['w_updates_desc'] = 'Проверка наличия обновлений для ядра и приложений.';
$_lang['w_configcheck'] = 'Проверка конфигурации';
$_lang['w_configcheck_desc'] = 'Показывает результат проверки конфигурации, чтобы убедиться в том, что текущая установка MODX безопасна.';
$_lang['w_newsfeed'] = 'Новости MODX';
$_lang['w_newsfeed_desc'] = 'Выводит ленту новостей MODX';
$_lang['w_recentlyeditedresources'] = 'Недавно редактированные ресурсы';
$_lang['w_recentlyeditedresources_desc'] = 'Показывает список недавно отредактированных ресурсов.';
$_lang['w_securityfeed'] = 'Уведомления безопасности MODX';
$_lang['w_securityfeed_desc'] = 'Показывает ленту уведомлений безопасности MODX';
$_lang['w_whosonline'] = 'Пользователи онлайн';
$_lang['w_whosonline_desc'] = 'Показывает список пользователей, которые сейчас онлайн.';
$_lang['w_view_all'] = 'Показать все';
$_lang['w_no_data'] = 'Нет данных для отображения';