<?php
/**
 * Russian language strings for Dashboards
 *
 * @package modx
 * @subpackage lexicon
 * @language ru
 */
$_lang['dashboard'] = 'Панель управления';
$_lang['dashboard_add'] = 'Добавить панель';
$_lang['dashboard_create'] = 'Создать панель';
$_lang['dashboard_desc_name'] = 'Название панели.';
$_lang['dashboard_desc_description'] = 'Краткое описание панели.';
$_lang['dashboard_desc_hide_trees'] = 'Если отмечено, древовидные меню будут скрыты при показе этой панели на странице приветствия.';
$_lang['dashboard_hide_trees'] = 'Скрыть древовидные меню';
$_lang['dashboard_desc_customizable'] = 'Позволяет пользователянастраивать их Панели управления для их учетных записей: добавление, удаление и изменение позиции или размера виджетов.';
$_lang['dashboard_customizable'] = 'Настраиваемый';
$_lang['dashboard_duplicate'] = 'Копировать панель';
$_lang['dashboard_remove'] = 'Удалить панель';
$_lang['dashboard_remove_confirm'] = 'Вы уверены, что хотите удалить панель?';
$_lang['dashboard_remove_multiple'] = 'Удалить панели';
$_lang['dashboard_remove_multiple_confirm'] = 'Вы уверены, что хотите удалить выбранные панели?';
$_lang['dashboard_update'] = 'Редактировать панель';
$_lang['dashboard_err_ae_name'] = 'Панель с названием «[[+name]]» уже существует! Пожалуйста, выберите другое название.';
$_lang['dashboard_err_duplicate'] = 'Произошла ошибка при попытке копирования панели.';
$_lang['dashboard_err_nf'] = 'Панель не найдена.';
$_lang['dashboard_err_ns'] = 'Панель не указана.';
$_lang['dashboard_err_ns_name'] = 'Укажите имя виджета.';
$_lang['dashboard_err_remove'] = 'Произошла ошибка при попытке удалить панель.';
$_lang['dashboard_err_remove_default'] = 'Вы не можете удалить панель, используемую по умолчанию!';
$_lang['dashboard_err_save'] = 'Произошла ошибка при попытке сохранить панель.';
$_lang['dashboard_usergroup_add'] = 'Назначить панель группе пользователей';
$_lang['dashboard_usergroup_remove'] = 'Удалить панель для группы пользователей';
$_lang['dashboard_usergroup_remove_confirm'] = 'Вы уверены, что хотите восстановить панель по умолчанию для этой группы пользователей?';
$_lang['dashboard_usergroups.intro_msg'] = 'Это список групп пользователей, использующих эту панель.';
$_lang['dashboard_widget_err_placed'] = 'Этот виджет уже есть в этой панели!';
$_lang['dashboard_widgets.intro_msg'] = 'Здесь вы можете добавлять, удалять, а также управлять виджетами для этой панели. Вы можете перетаскивать виджеты в таблице для изменения порядка их сортировки.';
$_lang['dashboards'] = 'Панели';
$_lang['dashboards.intro_msg'] = 'Здесь вы можете управлять всеми доступными панелями.';
$_lang['rank'] = 'Сортировка';
$_lang['user_group_filter'] = 'По группе пользователей';
$_lang['widget'] = 'Виджет';
$_lang['widget_content'] = 'Содержимое виджета';
$_lang['widget_create'] = 'Создать виджет';
$_lang['widget_err_ae_name'] = 'Виджет с именем «[[+name]]» уже существует! Выберите другое имя.';
$_lang['widget_err_nf'] = 'Виджет не найден!';
$_lang['widget_err_ns'] = 'Виджет не указан!';
$_lang['widget_err_ns_name'] = 'Укажите имя виджета.';
$_lang['widget_err_remove'] = 'Произошла ошибка при попытке удалить виджет.';
$_lang['widget_err_save'] = 'Произошла ошибка при попытке сохранить виджет.';
$_lang['widget_file'] = 'Файл';
$_lang['widget_dashboards.intro_msg'] = 'Ниже приведен список всех панелей, на которых этот виджет размещён.';
$_lang['widget_dashboard_remove'] = 'Убрать виджет с панели';
$_lang['widget_description_desc'] = 'Описание виджета или ключ записи словаря с описанием виджета и того, что он делает.';
$_lang['widget_html'] = 'HTML';
$_lang['widget_lexicon_desc'] = 'Тема словаря, которая загружается вместе с виджетом. Используется для перевода имени и описания, или любого другого текста в виджете.';
$_lang['widget_permission_desc'] = 'Это разрешение будет необходимо для добавления виджета на Панель управления пользователя.';
$_lang['widget_permission'] = 'Разрешение';
$_lang['widget_name_desc'] = 'Название виджета или ключ записи словаря с названием виджета.';
$_lang['widget_new'] = 'Новый виджет';
$_lang['widget_add'] = 'Добавить виджет';
$_lang['widget_add_desc'] = 'Пожалуйста, выберите Виджет для добавления на Панель управления.';
$_lang['widget_add_success'] = 'Виджет был успешно добавлен на Вашу Панель управления. Он будет автоматически загружен после закрытия этого окна.';
$_lang['widget_remove'] = 'Удалить';
$_lang['widget_remove_confirm'] = 'Вы действительно хотите удалить этот виджет? Это необратимо, и удалит виджет из всех панелей.';
$_lang['widget_remove_multiple'] = 'Удалить несколько виджетов';
$_lang['widget_remove_multiple_confirm'] = 'Вы уверены в том, что хотите удалить эти виджеты? Это необратимо и удалит эти виджеты из всех панелей.';
$_lang['widget_namespace'] = 'Пространство имён';
$_lang['widget_namespace_desc'] = 'Пространство имён, которое будет использовать виджет. Полезно при использовании собственных путей.';
$_lang['widget_php'] = 'Встроенный PHP-виджет';
$_lang['widget_place'] = 'Добавить виджет';
$_lang['widget_size'] = 'Размер';
$_lang['widget_size_desc'] = 'Размер виджета. «Половина» — пол-экрана в ширину, «Полный» — во всю ширину, «Двойной» — во всю ширину и в два ряда по высоте.';
$_lang['widget_size_double'] = 'Двойной';
$_lang['widget_size_full'] = 'Полный';
$_lang['widget_size_three_quarters'] = 'Три четвертых';
$_lang['widget_size_two_third'] = 'Две третьих';
$_lang['widget_size_half'] = 'Половина';
$_lang['widget_size_one_third'] = 'Одна третья';
$_lang['widget_size_quarter'] = 'Четверть';
$_lang['widget_snippet'] = 'Сниппет';
$_lang['widget_type'] = 'Тип виджета';
$_lang['widget_type_desc'] = 'Виджет типа «Сниппет» — это обычный сниппет, результаты его работы будут выведены в виджете. Виджет типа «HTML» просто выведет HTML. Виджет типа «Файл» загружается из php-файла, путь к которому указан в содержимом виджета, в файле надо использовать return для вывода содержимого или return \'имяКласса\', наследующего класс modDashboardWidgetClass. Виджет типа «Встроенный PHP-виджет» выводит результаты выполнения PHP кода из содержимого виджета. <a href="http://rtfm.modx.com/display/revolution20/Dashboard+Widget+Types">Документация по типам виджетов</a>. ';
$_lang['widget_unplace'] = 'Удалить виджет из панели';
$_lang['widget_update'] = 'Редактировать';
$_lang['widgets'] = 'Виджеты';
$_lang['widgets.intro_msg'] = 'Список доступных виджетов.';

$_lang['action_new_resource'] = 'Новая страница';
$_lang['action_new_resource_desc'] = 'Создайте новую страницу на сайте';
$_lang['action_view_website'] = 'Просмотр сайта';
$_lang['action_view_website_desc'] = 'Открыть сайт в новом окне';
$_lang['action_advanced_search'] = 'Расширенный поиск';
$_lang['action_advanced_search_desc'] = 'Расширенный поиск по сайту';
$_lang['action_manage_users'] = 'Управление пользователями';
$_lang['action_manage_users_desc'] = 'Управление всеми пользователями сайта';

$_lang['w_configcheck'] = 'Проверка конфигурации';
$_lang['w_configcheck_desc'] = 'Показывает результат проверки конфигурации, чтобы убедиться в том, что текущая установка MODX безопасна.';
$_lang['w_newsfeed'] = 'Канал новостей MODX';
$_lang['w_newsfeed_desc'] = 'Выводит ленту новостей MODX';
$_lang['w_recentlyeditedresources'] = 'Недавно редактированные ресурсы.';
$_lang['w_recentlyeditedresources_desc'] = 'Показывает список недавно отредактированных ресурсов.';
$_lang['w_securityfeed'] = 'Канал безопасности MODX';
$_lang['w_securityfeed_desc'] = 'Показывает ленту уведомлений безопасности MODX';
$_lang['w_whosonline'] = 'Пользователи онлайн';
$_lang['w_whosonline_desc'] = 'Показывает список пользователей, которые сейчас онлайн.';
$_lang['w_buttons'] = 'Кнопки';
$_lang['w_buttons_desc'] = 'Показывает набор кнопок, указанных в настройках.';
$_lang['w_updates'] = 'Обновления';
$_lang['w_updates_desc'] = 'Проверяет достцпные обновления для ядра и приложений.';
$_lang['w_view_all'] = 'Смотреть все';
$_lang['w_no_data'] = 'Нет данных для отображения';