<?php
$_lang['login_activation_key_err'] = 'Неверный код активации! Пожалуйста, проверьте письмо с кодом активации и убедитесь, что вы загрузили правильный URL.';
$_lang['login_blocked_admin'] = 'Ваш доступ к системе управления заблокирован администратором.';
$_lang['login_blocked_error'] = 'Вы временно заблокированы и не можете войти в систему управления сайтом. Попробуйте позже.';
$_lang['login_blocked_ip'] = 'Вам запрещено входить в систему управления сайтом этого IP-адреса.';
$_lang['login_blocked_time'] = 'В это время вам запрещено входить в систему управления сайтом. Пожалуйста попытайтесь позже.';
$_lang['login_blocked_too_many_attempts'] = 'Вы были заблокированы из-за слишком большого количества неудачных попыток входа.';
$_lang['login_button'] = 'Войти';
$_lang['login_cannot_locate_account'] = 'Учётная запись не найдена. Проверьте имя пользователя и введите пароль заново для новой попытки.';
$_lang['login_copyright'] = '&copy; 2005-2010  <a href="http://modxcms.com/" target="_blank" style="text-decoration: none;">MODx Team</a>. <strong>MODx</strong>&trade; распространяется по лицензии GPLv2 или любой более поздней.';
$_lang['login_email_label'] = 'E-mail аккаунта:';
$_lang['login_err_unknown'] = 'При попытке авторизации произошла неизвестная ошибка.';
$_lang['login_forget_your_login'] = 'Забыли свой логин?';
$_lang['login_hostname_error'] = 'Ваше имя хоста не указывает на ваш IP-адрес.';
$_lang['login_message'] = 'Для входа в панель управления введите имя пользователя и пароль. Будьте внимательны, они чувствительны к регистру! ';
$_lang['login_modx_support'] = '<p>При поддержке:</p><p><a href="http://www.modxcms.com/forums/" target="_blank" ><strong>Сообщество MODx </strong></a></p>';
$_lang['login_password'] = 'Пароль: ';
$_lang['login_password_reset_act_sent'] = 'Отправлено письмо для сброса пароля. Проверьте почтовый ящик.';
$_lang['login_remember'] = 'Запомнить меня';
$_lang['login_send_activation_email'] = 'Выслать письмо для активации';
$_lang['login_title'] = 'Вход в систему управления MODx ';
$_lang['login_user_err_nf_email'] = 'Пользователь с таким адресом электронной почты не найден. Попробуйте ещё раз.';
$_lang['login_username'] = 'Имя пользователя: ';
$_lang['login_username_password_incorrect'] = 'Неправильное имя пользователя или пароль. Проверьте введённые данные и попытайтесь снова.';
$_lang['login_user_inactive'] = 'Ваша учётная запись заблокирована. Свяжитесь с системным администратором для отмены блокировки.';
