<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Сниппет';
$_lang['snippets_available'] = 'Сниппеты доступные вам для включения в вашу страницу';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Вы уверены, что хотите удалить этот сниппет?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Вы уверены, что хотите сделать копию этого сниппета?';
$_lang['snippet_duplicate_error'] = 'Произошла ошибка в процессе копирования сниппета.';
$_lang['snippet_err_create'] = 'Произошла ошибка в процессе создания сниппета.';
$_lang['snippet_err_delete'] = 'Произошла ошибка при попытке удалить сниппет.';
$_lang['snippet_err_duplicate'] = 'Произошла ошибка при попытке копировать сниппет.';
$_lang['snippet_err_ae'] = 'Сниппет с названием «[[+name]]» уже существует.';
$_lang['snippet_err_invalid_name'] = 'Название сниппета недопустимо.';
$_lang['snippet_err_locked'] = 'Этот сниппет заблокирован для редактирования.';
$_lang['snippet_err_nf'] = 'Сниппет не найден!';
$_lang['snippet_err_ns'] = 'Сниппет не указан.';
$_lang['snippet_err_ns_name'] = 'Пожалуйста, укажите название сниппета.';
$_lang['snippet_err_remove'] = 'Произошла ошибка при попытке удалить сниппет.';
$_lang['snippet_err_save'] = 'Произошла ошибка в процессе сохранения сниппета.';
$_lang['snippet_execonsave'] = 'Запустить сниппет после сохранения.';
$_lang['snippet_lock'] = 'Заблокировать сниппет для редактирования';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Здесь вы можете выбрать сниппет для редактирования.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Создать сниппет';
$_lang['snippet_properties'] = 'Параметры по умолчанию';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippet_title'] = 'Create/Edit Snippet';
$_lang['snippet_untitled'] = 'Безымянный сниппет';
$_lang['snippets'] = 'Сниппеты';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
