<?php
/**
 * TV English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_tvname'] = 'SablonváltozóNeve';
$_lang['has_access'] = 'Hozzáférhet?';
$_lang['filter_by_category'] = 'Szűrés kategória alapján...';
$_lang['rank'] = 'Rangsor';
$_lang['rendering_options'] = 'Megjelenítési beállítások';
$_lang['tv'] = 'Sablonváltozó';
$_lang['tvs'] = 'Sablonváltozók';
$_lang['tv_binding_msg'] = 'Ez a mező a @ parancsokkal támogatja az adatforrások kapcsolását';
$_lang['tv_caption'] = 'Felirat';
$_lang['tv_caption_desc'] = 'The label shown for this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_category_desc'] = 'Use to group TVs in Resource editing pages and within the Elements tree.';
$_lang['tv_change_template_msg'] = 'A sablon cseréje miatt az oldal újratöltődik, így elvesznek a mentetlen módosítások.<br /><br /> Biztosan cseréli a sablont?';
$_lang['tv_delete_confirm'] = 'Biztosan törli ezt a sablonváltozót?';
$_lang['tv_description'] = 'Leírás';
$_lang['tv_description_desc'] = 'Usage information for this TV shown next its caption in Resource editing pages and as a tooltip in the Elements tree.';
$_lang['tv_err_delete'] = 'Hiba történt a sablonváltozó törlése közben.';
$_lang['tv_err_duplicate'] = 'Hiba történt a sablonváltozó kettőzésekor.';
$_lang['tv_err_duplicate_templates'] = 'Hiba történt a sablonváltozó másolatának létrehozásakor.';
$_lang['tv_err_duplicate_documents'] = 'Hiba történt a sablonváltozó dokumentumok másolatának létrehozásakor.';
$_lang['tv_err_duplicate_documentgroups'] = 'Hiba történt a sablonváltozó dokumentumcsoportok másolatának létrehozásakor.';
$_lang['tv_err_ae'] = 'Már létezik sablonváltozó "[[+name]]" néven.';
$_lang['tv_err_invalid_name'] = 'Érvénytelen sablonváltozó.';
$_lang['tv_err_invalid_id_attr'] = 'HTML ids must not begin with a number or contain any white space.';
$_lang['tv_err_locked'] = 'Sablonváltozó zárolva!';
$_lang['tv_err_nf'] = 'Sablonváltozó nem található.';
$_lang['tv_err_nfs'] = 'Sablonváltozó nem található [[+id]] azonosítóval';
$_lang['tv_err_ns'] = 'Sablonváltozó nincs megadva.';
$_lang['tv_err_reserved_name'] = 'A sablonváltozó neve nem lehet azonos egy erőforrásmezőével.';
$_lang['tv_err_save_access_permissions'] = 'Hiba történt a sablonváltozó hozzáférési engedélyeinek mentésekor.';
$_lang['tv_err_save'] = 'Hiba történt a sablonváltozó mentésekor.';
$_lang['tv_inuse'] = 'A következő dokumentum(ok) jelenleg használják ezt a sablonváltozót. A törlési művelet folytatásához kattintson a Törlés gombra, egyébként kattintson a Mégsem gombra.';
$_lang['tv_inuse_template'] = 'A következő sablon(ok) használják jelenleg ezt a sablonváltozót: [[+templates]].<br /><br />Kérjük, válassza le a sablonváltozót a sablon(ok)ról, mielőtt törölné.';
$_lang['tv_lock'] = 'Szerkesztés korlátozása';
$_lang['tv_lock_desc'] = 'Only users with “edit_locked” permissions can edit this TV.';
$_lang['tv_management_msg'] = 'További egyéni sablonváltozók kezelése a dokumentumaihoz.';
$_lang['tv_name'] = 'Sablonváltozó neve';
$_lang['tv_name_desc'] = 'Place the content generated by this TV in a Resource, Template, or Chunk using the following MODX tag: <span class="copy-this">[[*<span class="example-replace-name">'.$_lang['example_tag_tvname'].'</span>]]</span>';
$_lang['tv_new'] = 'Sablonváltozó létrehozása';
$_lang['tv_novars'] = 'Nem található sablonváltozó';
$_lang['tv_properties'] = 'Alaptulajdonságok';
$_lang['tv_rank'] = 'Sorrend';
$_lang['tv_rank_desc'] = 'Use to control the positioning of this TV in Resource editing pages (can be overridden per template or other criteria using <a href="?a=security/forms" target="_blank">Form Customization</a>).';
$_lang['tv_reset_params'] = 'Jellemzők alaphelyzetbe állítása';
$_lang['tv_tab_access_desc'] = 'Select the Resource Groups that this TV belongs to. Only users with access to the Groups selected will be able to modify this TV. If no Groups are selected, all users with access to the Manager will be able to modify the TV.';
$_lang['tv_tab_general_desc'] = 'Here you can create/edit a <dfn>Template Variable</dfn> (TV). TVs must be assigned to templates in order to access them from snippets and documents.';
$_lang['tv_tab_input_options'] = 'Beviteli beállítások';
$_lang['tv_tab_input_options_desc'] = '<p>Here you can edit the input options for the TV, specific to the type of input render that you select.</p>';
$_lang['tv_tab_output_options'] = 'Kimenetei beállítások';
$_lang['tv_tab_output_options_desc'] = '<p>Here you can edit the output options for the TV, specific to the type of output render that you select.</p>';
$_lang['tv_tab_sources_desc'] = 'Itt rendelheti hozzá ehhez a sablonváltozóhoz az egyes környezetekben általa használható médiaforrásokat. A forrás neve kettős kattintással válik módosíthatóvá.';
$_lang['tv_tab_tmpl_access'] = 'Sablon hozzáférése';
$_lang['tv_tab_tmpl_access_desc'] = 'Select the templates that are allowed to access this TV.';
$_lang['tv_tag_copied'] = 'Sablonváltozó címkéje másolva!';
$_lang['tv_widget'] = 'Vezérlőelem';
$_lang['tv_widget_prop'] = 'Sablonváltozó tulajdonságai';
$_lang['tvd_err_remove'] = 'Hiba történt a sablonváltozó dokumentumból való törlése közben.';
$_lang['tvdg_err_remove'] = 'Hiba történt a sablonváltozó dokumentum csoportból való törlése közben.';
$_lang['tvdg_err_save'] = 'Hiba történt a sablonváltozó dokumentum csoporthoz való csatolása közben.';
$_lang['tvt_err_nf'] = 'Sablonváltozó nem fér hozzá a megadott sablonhoz.';
$_lang['tvt_err_remove'] = 'Hiba történt a sablonváltozó sablonból való törlése közben.';
$_lang['tvt_err_save'] = 'Hiba történt a sablonváltozó sablonhoz való csatolása közben.';

// Temporarily match old keys to new ones to ensure compatibility
// -- fields
$_lang['tv_desc_caption'] = $_lang['tv_caption_desc'];
$_lang['tv_desc_category'] = $_lang['tv_category_desc'];
$_lang['tv_desc_description'] = $_lang['tv_description_desc'];
$_lang['tv_desc_name'] = $_lang['tv_name_desc'];
$_lang['tv_lock_msg'] = $_lang['tv_lock_desc'];
$_lang['tv_rank_msg'] = $_lang['tv_rank_desc'];

// -- tabs
$_lang['tv_access_msg'] = $_lang['tv_tab_access_desc'];
$_lang['tv_input_options'] = $_lang['tv_tab_input_options'];
$_lang['tv_input_options_msg'] = $_lang['tv_tab_input_options_desc'];
$_lang['tv_msg'] = $_lang['tv_tab_general_desc'];
$_lang['tv_output_options'] = $_lang['tv_tab_output_options'];
$_lang['tv_output_options_msg'] = $_lang['tv_tab_output_options_desc'];
$_lang['tv_sources.intro_msg'] = $_lang['tv_tab_sources_desc'];
$_lang['tv_tmpl_access'] = $_lang['tv_tab_tmpl_access'];
$_lang['tv_tmpl_access_msg'] = $_lang['tv_tab_tmpl_access_desc'];
