<?php
/**
 * TV English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_tv_name'] = 'NameOfTV';
$_lang['has_access'] = 'Hozzáférhet?';
$_lang['filter_by_category'] = 'Szűrés kategória alapján...';
$_lang['rank'] = 'Rangsor';
$_lang['rendering_options'] = 'Megjelenítési beállítások';
$_lang['tv'] = 'Sablonváltozó';
$_lang['tvs'] = 'Sablonváltozók';
$_lang['tv_binding_msg'] = 'Ez a mező a @ parancsokkal támogatja az adatforrások kapcsolását';
$_lang['tv_caption'] = 'Felirat';
$_lang['tv_caption_desc'] = 'Ehhez a sablonváltozóhoz tartozó megnevezés az erőforrás-szerkesztő oldalakon (felülírható sablonszinten, vagy más feltételek alapján az <a href="?a=security/forms" target="_blank">Űrlap testreszabása</a> használatával).';
$_lang['tv_category_desc'] = 'Használja a sablonváltozók csoportosítására az erőforrás-szerkesztő oldalakon és az összetevők fájában.';
$_lang['tv_change_template_msg'] = 'A sablon cseréje miatt az oldal újratöltődik, így elvesznek a mentetlen módosítások.<br /><br /> Biztosan cseréli a sablont?';
$_lang['tv_delete_confirm'] = 'Biztosan törli ezt a sablonváltozót?';
$_lang['tv_description'] = 'Leírás';
$_lang['tv_description_desc'] = 'Usage information for this TV shown next to its caption in Resource editing pages, as a tooltip in the Elements tree, and within search results.';
$_lang['tv_err_delete'] = 'Hiba történt a sablonváltozó törlése közben.';
$_lang['tv_err_duplicate'] = 'Hiba történt a sablonváltozó kettőzésekor.';
$_lang['tv_err_duplicate_templates'] = 'Hiba történt a sablonváltozó másolatának létrehozásakor.';
$_lang['tv_err_duplicate_documents'] = 'Hiba történt a sablonváltozó dokumentumok másolatának létrehozásakor.';
$_lang['tv_err_duplicate_documentgroups'] = 'Hiba történt a sablonváltozó dokumentumcsoportok másolatának létrehozásakor.';
$_lang['tv_err_ae'] = 'Már létezik sablonváltozó "[[+name]]" néven.';
$_lang['tv_err_invalid_name'] = 'Érvénytelen sablonváltozó.';
$_lang['tv_err_invalid_id_attr'] = 'HTML azonosítók nem kezdődhetnek számmal, és nem tartalmazhatnak szóközöket.';
$_lang['tv_err_locked'] = 'Sablonváltozó zárolva!';
$_lang['tv_err_nf'] = 'Sablonváltozó nem található.';
$_lang['tv_err_nfs'] = 'Sablonváltozó nem található [[+id]] azonosítóval';
$_lang['tv_err_ns'] = 'Sablonváltozó nincs megadva.';
$_lang['tv_err_reserved_name'] = 'A sablonváltozó neve nem lehet azonos egy erőforrásmezőével.';
$_lang['tv_err_save_access_permissions'] = 'Hiba történt a sablonváltozó hozzáférési engedélyeinek mentésekor.';
$_lang['tv_err_save'] = 'Hiba történt a sablonváltozó mentésekor.';
$_lang['tv_inuse'] = 'A következő dokumentum(ok) jelenleg használják ezt a sablonváltozót. A törlési művelet folytatásához kattintson a Törlés gombra, egyébként kattintson a Mégsem gombra.';
$_lang['tv_inuse_template'] = 'A következő sablon(ok) használják jelenleg ezt a sablonváltozót: [[+templates]].<br /><br />Kérjük, válassza le a sablonváltozót a sablon(ok)ról, mielőtt törölné.';
$_lang['is_static_tv_desc'] = 'Use an external file to store the default value for this TV. This may be useful if the default value’s content is particularly lengthy.';
$_lang['tv_lock'] = 'Szerkesztés korlátozása';
$_lang['tv_lock_desc'] = 'A sablonváltozó szerkesztéséhez szükség van az “edit_locked“ felhasználói engedélyre.';
$_lang['tv_management_msg'] = 'További egyéni sablonváltozók kezelése a dokumentumaihoz.';
$_lang['tv_name_desc'] = 'Place the content generated by this TV in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['tv_new'] = 'Sablonváltozó létrehozása';
$_lang['tv_novars'] = 'Nem található sablonváltozó';
$_lang['tv_properties'] = 'Alaptulajdonságok';
$_lang['tv_rank'] = 'Sorrend';
$_lang['tv_rank_desc'] = 'Használja a sablonváltozó elhelyezkedésének beállításához az erőforrás-szerkesztő oldalakon (felülírható sablonszinten, vagy más feltételek alapján az <a href="?a=security/forms" target="_blank">Űrlap testreszabása</a> használatával).';
$_lang['tv_reset_params'] = 'Jellemzők alaphelyzetbe állítása';
$_lang['tv_tab_access_desc'] = 'Válassza ki az erőforráscsoportokat, amelyekhez ez a sablonváltozó tartozik. Csak az ezekhez a csoportokhoz hozzáféréssel rendelkező felhasználók módosíthatják ezt a sablonváltozót. Ha nem választ csoportot, a kezelőhöz hozzáféréssel rendelkező minden felhasználó módosíthatja.';
$_lang['tv_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Template Variable</em> (TV). Note that TVs must be assigned to templates in order to access them from snippets and documents.';
$_lang['tv_tab_input_options'] = 'Beviteli beállítások';
$_lang['tv_tab_input_options_desc'] = '<p>Itt módosíthatja a sablonváltozó beviteli beállításait a választott beviteli megjelenítéstől függően.</p>';
$_lang['tv_tab_output_options'] = 'Kimenetei beállítások';
$_lang['tv_tab_output_options_desc'] = '<p>Itt módosíthatja a sablonváltozó kiviteli beállításait a választott kiviteli megjelenítéstől függően.</p>';
$_lang['tv_tab_sources_desc'] = 'Itt rendelheti hozzá ehhez a sablonváltozóhoz az egyes környezetekben általa használható médiaforrásokat. A forrás neve kettős kattintással válik módosíthatóvá.';
$_lang['tv_tab_tmpl_access'] = 'Sablon hozzáférése';
$_lang['tv_tab_tmpl_access_desc'] = 'Válassza ki a sablonokat, amelyek hozzáférhetnek ezen sablonváltozóhoz.';
$_lang['tv_tag_copied'] = 'Sablonváltozó címkéje másolva!';
$_lang['tv_widget'] = 'Vezérlőelem';
$_lang['tv_widget_prop'] = 'Sablonváltozó tulajdonságai';
$_lang['tvd_err_remove'] = 'Hiba történt a sablonváltozó dokumentumból való törlése közben.';
$_lang['tvdg_err_remove'] = 'Hiba történt a sablonváltozó dokumentum csoportból való törlése közben.';
$_lang['tvdg_err_save'] = 'Hiba történt a sablonváltozó dokumentum csoporthoz való csatolása közben.';
$_lang['tvt_err_nf'] = 'Sablonváltozó nem fér hozzá a megadott sablonhoz.';
$_lang['tvt_err_remove'] = 'Hiba történt a sablonváltozó sablonból való törlése közben.';
$_lang['tvt_err_save'] = 'Hiba történt a sablonváltozó sablonhoz való csatolása közben.';

// Temporarily match old keys to new ones to ensure compatibility
// -- fields
$_lang['tv_desc_caption'] = $_lang['tv_caption_desc'];
$_lang['tv_desc_category'] = $_lang['tv_category_desc'];
$_lang['tv_desc_description'] = $_lang['tv_description_desc'];
$_lang['tv_desc_name'] = $_lang['tv_name_desc'];
$_lang['tv_lock_msg'] = $_lang['tv_lock_desc'];
$_lang['tv_rank_msg'] = $_lang['tv_rank_desc'];

// -- tabs
$_lang['tv_access_msg'] = $_lang['tv_tab_access_desc'];
$_lang['tv_input_options'] = $_lang['tv_tab_input_options'];
$_lang['tv_input_options_msg'] = $_lang['tv_tab_input_options_desc'];
$_lang['tv_msg'] = $_lang['tv_tab_general_desc'];
$_lang['tv_output_options'] = $_lang['tv_tab_output_options'];
$_lang['tv_output_options_msg'] = $_lang['tv_tab_output_options_desc'];
$_lang['tv_sources.intro_msg'] = $_lang['tv_tab_sources_desc'];
$_lang['tv_tmpl_access'] = $_lang['tv_tab_tmpl_access'];
$_lang['tv_tmpl_access_msg'] = $_lang['tv_tab_tmpl_access_desc'];

/*
    Refer to default.inc.php for the keys below.
    (Placement in this default file necessary to allow
    quick create/edit panels access to them when opened
    outside the context of their respective element types)

    tv_caption_desc
    tv_category_desc
    tv_description_desc

*/
