<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'สนิปเพต';
$_lang['snippets_available'] = 'สนิปเพตที่สามารถใช้งานได้เพื่อรวมไว้ในหน้าเว็บของคุณ';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'คุณแน่ใจว่าต้องการลบสนิปเพตนี้หรือไม่?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'คุณแน่ใจว่าต้องการทำสำเนาสนิปเพตนี้หรือไม่?';
$_lang['snippet_duplicate_error'] = 'เกิดข้อผิดพลาดขณะกำลังทำสำเนาสนิปเพต';
$_lang['snippet_err_create'] = 'เกิดข้อผิดพลาดขณะกำลังสร้างสนิปเพต';
$_lang['snippet_err_delete'] = 'เกิดข้อผิดพลาดขณะที่พยายามลบสนิปเพต';
$_lang['snippet_err_duplicate'] = 'เกิดข้อผิดพลาดขณะที่พยายามทำสำเนาสนิปเพต';
$_lang['snippet_err_ae'] = 'มีสนิปเพตชื่อ "[[+name]]" อยู่แล้ว';
$_lang['snippet_err_invalid_name'] = 'ชื่อสนิปเพตนี้ไม่ถูกต้อง';
$_lang['snippet_err_locked'] = 'สนิปเพตนี้ถูกป้องกันการแก้ไข';
$_lang['snippet_err_nf'] = 'ไม่พบสนิปเพต!';
$_lang['snippet_err_ns'] = 'ไม่มีการระบุสนิปเพต';
$_lang['snippet_err_ns_name'] = 'กรุณาระบุชื่อสำหรับสนิปเพต';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'เกิดข้อผิดพลาดขณะกำลังบันทึกสนิปเพต';
$_lang['snippet_execonsave'] = 'ดำเนินการสนิปเพตหลังการบันทึก';
$_lang['snippet_lock'] = 'ป้องกันการแก้ไขสนิปเพต';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'คุณสามารถเลือกสนิปเพตที่คุณต้องการแก้ไข';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'คุณสมบัติปริยาย';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'สนิปเพต';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
