<?php

/*
 * This file is part of MODX Revolution.
 *
 * Copyright (c) MODX, LLC. All Rights Reserved.
 *
 * For complete copyright and license information, see the COPYRIGHT and LICENSE
 * files found in the top-level directory of this distribution.
 */

namespace MODX\Revolution\Processors\Resource;

trait UrlElementsTrait
{
    /**
     * Checks validity of generated URI character length, depending on associated system settings.
     *
     * @param string $aliasPath The full relative uri to evaluate
     * @return void Issues a message payload on failure, but does not return a value
     *
     * Note that the URI field is not visible and contains a derived value when not overridden (via Freeze URI).
     * Thus a general error is emitted when the URI value is invalid instead of a field error. This simplifies
     * the process and avoids creating confusion in the UI.
     */
    private function validateUriLength(string $aliasPath): void
    {
        $useCacheAliasMap = $this->workingContext->getOption('cache_alias_map', false);
        $uriMaxLength = $useCacheAliasMap ? $this->workingContext->getOption('uri_max_length') : 191 ;
        $pathLength = strlen($aliasPath);

        if ($pathLength > $uriMaxLength) {
            $lengthDifference = $pathLength - $uriMaxLength;
            $msgKey = $useCacheAliasMap ? 'uri_max_length_err_exceeded' : 'uri_max_length_err_exceeded__cache_map_off' ;
            $settingsBaseUrl = MODX_MANAGER_URL . '?a=system/settings&tab=0';
            $msg = $this->modx->lexicon(
                $msgKey,
                [
                    'uri-max' => $uriMaxLength,
                    'diff' => $lengthDifference,
                    'uml-link' => $settingsBaseUrl . '&query=uri_max_length',
                    'cam-link' => $settingsBaseUrl . '&query=cache_alias_map'
                ]
            );
            $this->failure(json_encode($msg, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES));
        }
    }

    /**
     * Generates auto alias when applicable and performs basic validation checks
     * in the context of the full relative alias path (uri)
     * @return string The generated or given alias
     */
    public function prepareResourceAlias(): string
    {
        $useFriendlyUrls = $this->workingContext->getOption('friendly_urls', false);
        $isReload = $this->getProperty('reloadOnly', false);

        $pageTitle = $this->getProperty('pagetitle');

        $alias = $this->getProperty('alias');
        $aliasPath = $this->object->getAliasPath($alias, $this->getProperties());
        $autoAlias = $this->workingContext->getOption('automatic_alias', false);
        $autoGenerated = false;

        if (empty($alias) && $autoAlias) {
            $alias = $this->object->cleanAlias($pageTitle);
            $autoGenerated = true;
        }

        // Check for duplicates
        $handleDuplicates = $useFriendlyUrls && (!$isReload || !empty($pageTitle));
        $duplicateContext = $this->workingContext->getOption('global_duplicate_uri_check', false)
            ? ''
            : $this->getProperty('context_key')
            ;
        $duplicateId = $this->object->isDuplicateAlias($aliasPath, $duplicateContext);

        if ($duplicateId) {
            if ($handleDuplicates) {
                $err = $this->modx->lexicon('duplicate_uri_found', [
                    'id' => $duplicateId,
                    'uri' => $aliasPath,
                ]);
                $this->addFieldError('uri', $err);
                if ($this->getProperty('uri_override', 0) !== 1) {
                    $this->addFieldError('alias', $err);
                }
            } elseif ($autoGenerated) {
                $alias = '';
            }
        }

        if ($useFriendlyUrls) {
            if (empty($alias) && !$isReload) {
                $this->addFieldError('alias', $this->modx->lexicon('field_required'));
            }
            $this->validateUriLength($aliasPath);
        }

        $this->setProperty('alias', $alias);
        return $alias;
    }
}
