<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Snippet';
$_lang['snippets_available'] = 'Skrawki dostępne do dodania na stronę';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Czy na pewno chcesz usunąć ten Skrawek?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Na pewno chcesz zduplikować ten skrawek?';
$_lang['snippet_duplicate_error'] = 'Wystąpił błąd podczas powielania Skrawka.';
$_lang['snippet_err_create'] = 'An error occurred while creating the snippet.';
$_lang['snippet_err_delete'] = 'An error occured while trying to delete the snippet.';
$_lang['snippet_err_duplicate'] = 'An error occured while trying to duplicate the snippet.';
$_lang['snippet_err_ae'] = 'A snippet already exists with the name "[[+name]]".';
$_lang['snippet_err_invalid_name'] = 'Nazwa Skrawka jest nieprawidłowa.';
$_lang['snippet_err_locked'] = 'Ten Skrawek jest zablokowany do edycji.';
$_lang['snippet_err_nf'] = 'Skrawek nie znaleziony!';
$_lang['snippet_err_ns'] = 'Skrawek nie określony.';
$_lang['snippet_err_ns_name'] = 'Proszę podać nazwę Skrawka.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'An error occurred while saving the snippet.';
$_lang['snippet_execonsave'] = 'Execute snippet after saving.';
$_lang['snippet_lock'] = 'Zablokuj Skrawek do edycji';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Tutaj możesz wybrać który Skrawek chcesz edytować.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'Domyślne property';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'Fragmenty kodu';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
