<?php
/**
* Top Menu Polish lexicon topic
*
* @language pl
* @package modx
* @subpackage lexicon
*/
$_lang['about'] = 'O MODX';
$_lang['about_desc'] = 'Wyświetl informacje o MODX Revolution.';
$_lang['access_permissions'] = 'Uprawnienia';
$_lang['access_permissions_desc'] = 'Manage user group access to resources and contexts.';
$_lang['api_docs'] = 'Dokumentacja API';
$_lang['api_docs_desc'] = 'Wyświetl dokumentację API MODX.';
$_lang['components'] = 'Rozszerzenia';
$_lang['content_types'] = 'Formaty zawartości';
$_lang['content_types_desc'] = 'Zarządzaj <var title="Content Types">formatami zawartości</var> dla zasobów.';
$_lang['contexts'] = 'Konteksty';
$_lang['contexts_desc'] = 'Zarządzaj kontekstami i ich ustawieniami.';
$_lang['dashboard'] = 'Dashboard';
$_lang['dashboards'] = 'Dashboards';
$_lang['dashboards_desc'] = 'Manage all dashboard configurations.';
$_lang['edit_menu'] = 'Akcje i Menu';
$_lang['edit_menu_desc'] = 'Zarządzaj <var title="Actions">akcjami</var> i strukturą głównego menu.';
$_lang['eventlog_viewer'] = 'Dziennik Błędów';
$_lang['eventlog_viewer_desc'] = 'Wyświetl dziennik błędów MODX.';
$_lang['export_site'] = 'Export Static HTML';
$_lang['export_site_desc'] = 'Export the current site into static HTML pages.';
$_lang['flush_access'] = 'Twoja sesja';
$_lang['flush_access_confirm'] = 'Twoja sesja w panelu administracyjnym MODX zostanie zresetowana, aby odświeżyć uprawnienia. Nie dotyczy to sesji pozostałych użytkowników. Czy na pewno chcesz to zrobić?';
$_lang['flush_access_desc'] = 'Zresetuj sesję i odśwież Twoje uprawnienia w panelu administracyjnym.';
$_lang['flush_sessions'] = 'Wszystkie sesje';
$_lang['flush_sessions_confirm'] = 'Wszystkie bieżące i poprzednie sesje wszystkich użytkowników, także Twoja, zostaną zresetowane. Każdy użytkownik będzie musiał zalogować się ponownie. Czy na pewno chcesz to zrobić?';
$_lang['flush_sessions_desc'] = 'Zresetuj wszystkie sesje i wyloguj wszystkich użytkowników.';
$_lang['flush_sessions_err'] = 'Podczas resetowania sesji wystąpił błąd.';
$_lang['flush_sessions_not_supported'] = 'Resetowanie sesji nie jest dostępne w Twojej konfiguracji.';
$_lang['form_customization'] = 'Formatki Zasobów';
$_lang['form_customization_desc'] = 'Dostosuj formatki zasobów, nadając uprawnienia grupom użytkowników.';
$_lang['forums'] = 'Forum MODX';
$_lang['forums_desc'] = 'Przejdź do oficjalnego forum użytkowników MODX.';
$_lang['import_resources'] = 'Importowanie Zasobów';
$_lang['import_resources_desc'] = 'Zaimportuj pliki z serwera i utwórz z nich dokumenty lub załączniki.';
$_lang['import_site'] = 'Importowanie Dokumentów';
$_lang['import_site_desc'] = 'Zaimportuj pliki HTML i utwórz z nich dokumenty w serwisie.';
$_lang['jira'] = 'Błędy MODX';
$_lang['jira_desc'] = 'Wyświetl stronę systemu zgłaszania i śledzenia błędów MODX.';
$_lang['lexicon_management'] = 'Leksykon';
$_lang['lexicon_management_desc'] = 'Zmodyfikuj dowolny fragment opisu panelu administracyjnego MODX.';
$_lang['logout_desc'] = 'Wyloguj się z panelu administracyjnego MODX.';
$_lang['manage_workspaces'] = 'Rozszerzenia';
$_lang['manage_workspaces_desc'] = 'Zarządzaj <var title="3rd Party Components">rozszerzeniami</var>, <var title="Providers">dostawcami</var> i pakietami.';
$_lang['messages'] = 'Wiadomości';
$_lang['messages_desc'] = 'Przeglądaj i wysyłaj wiadomości do innych użytkowników.';
$_lang['namespaces'] = 'Przestrzenie Nazw';
$_lang['namespaces_desc'] = 'Zarządzaj <var title="Namespaces">przestrzeniami nazw</var>, które zapewniają rozróżnienie pomiędzy rozszerzeniami.';
$_lang['new_document'] = 'Nowy Dokument';
$_lang['new_document_desc'] = 'Utwórz nowy dokument';
$_lang['new_resource'] = 'New Resource';
$_lang['new_resource_desc'] = 'Create a new resource.';
$_lang['new_static_resource'] = 'Nowy Załącznik';
$_lang['new_static_resource_desc'] = 'Utwórz nowy załącznik, który zawiera plik znajdujący się na dysku serwera.';
$_lang['new_symlink'] = 'Nowe Dowiązanie';
$_lang['new_symlink_desc'] = 'Utwórz nowe dowiązanie, które wyświetla zdalną zawartość bez przekierowywania.';
$_lang['new_weblink'] = 'Nowy Odnośnik';
$_lang['new_weblink_desc'] = 'Utwórz nowy odnośnik, który przekierowuje do zdalnej zawartości.';
$_lang['policy_management'] = 'Access Policies';
$_lang['policy_management_desc'] = 'Create and edit site-wide policies to secure processes.';
$_lang['preview'] = 'Podgląd';
$_lang['preview_desc'] = 'Wyświetl stronę główną w nowym oknie lub zakładce.';
$_lang['profile'] = 'Profil użytkownika';
$_lang['profile_desc'] = 'Zarządzaj Twoim kontem użytkownika.';
$_lang['propertysets'] = 'Zestawy Właściwości';
$_lang['propertysets_desc'] = 'Zarządzaj <var title="Property Sets">zestawami właściwości</var> i <var>element</var>ami, do których są przypisane.';
$_lang['refresh_site'] = 'Pamięć podręczna';
$_lang['refresh_site_desc'] = 'Usuń pamięć podręczną serwisu.';
$_lang['remove_locks'] = 'Blokady';
$_lang['remove_locks_desc'] = 'Usuń wszystkie blokady stron w panelu zarządzania, które powstały podczas pracy innych użytkowników.';
$_lang['remove_locks_error'] = 'Podczas usuwania blokad wystąpiły błedy.';
$_lang['reports'] = 'Raporty';
$_lang['resource_groups'] = 'Grupy Zasobów';
$_lang['resource_groups_desc'] = 'Zarządzaj przynależnością zasobów do grup.';
$_lang['search'] = 'Wyszukiwanie';
$_lang['search_desc'] = 'Wyszukaj zasoby.';
$_lang['security'] = 'Bezpieczeństwo';
$_lang['site'] = 'Serwis';
$_lang['sources'] = 'Media Sources';
$_lang['sources_desc'] = 'Manage your media sources here.';
$_lang['support'] = 'Wsparcie';
$_lang['support_desc'] = '';
$_lang['site_schedule'] = 'Kalendarz Publikacji';
$_lang['site_schedule_desc'] = 'Wyświetl zasoby z przyszłymi datami rozpoczęcia lub zakończenia publikacji.';
$_lang['system'] = 'System';
$_lang['system_settings'] = 'Ustawienia Systemowe';
$_lang['system_settings_desc'] = 'Zarządzaj ustawieniami systemowymi dla całego serwisu.';
$_lang['tools'] = 'Narzędzia';
$_lang['user'] = 'Użytkownik';
$_lang['user_management'] = 'Użytkownicy';
$_lang['user_management_desc'] = 'Zarządzaj użytkownikami serwisu.';
$_lang['user_group_management'] = 'Uprawnienia';
$_lang['user_group_management_desc'] = 'Zarządzaj grupami, rolami i uprawnieniami użytkowników.';
$_lang['view_logging'] = 'Aktywność Użytkowników';
$_lang['view_logging_desc'] = 'Wyświetl zestawienie aktywności użytkowników w panelu administracyjnym Twojego serwisu.';
$_lang['view_sysinfo'] = 'Informacje Systemowe';
$_lang['view_sysinfo_desc'] = 'Wyświetl informacje o systemie takie jak <code>phpinfo</code>, baza danych i inne.';
$_lang['wiki'] = 'Dokumentacja MODX';
$_lang['wiki_desc'] = 'Wyświetl dokumentację MODX.';