<?php
/**
 * Access Spanish lexicon topic
 *
 * @language es_MX
 * @package modx
 * @subpackage lexicon
 */
$_lang['access_category_management_msg'] = 'Administra el acceso de miembros de un Grupo de Usuarios a Elementos vía Categorías y opcionalmente aplica políticas de acceso.';
$_lang['access_category_err_ae'] = 'Un ACL para esa Categoría ya existe!';
$_lang['access_category_err_nf'] = 'ACL de Categoría no encontrado.';
$_lang['access_category_err_ns'] = 'ACL de Categoría no especificado.';
$_lang['access_category_err_remove'] = 'Un error ocurrió mientras se trataba de remover el ACL de la Categoría.';
$_lang['access_category_remove'] = 'Remover Acceso a Categoría';
$_lang['access_category_update'] = 'Actualizar Acceso a Categoría';
$_lang['access_confirm_remove'] = '¿Estás seguro de que quieres remover este registro de seguridad de control de acceso?';
$_lang['access_context_management_msg'] = 'Administra el acceso de miembros de un Grupo de Usuarios a Contextos y opcionalmente aplica políticas de acceso.';
$_lang['access_context_err_ae'] = 'Un ACL para ese Contexto ya existe!';
$_lang['access_context_err_nf'] = 'ACL de Contexto no encontrado.';
$_lang['access_context_err_ns'] = 'ACL de Contexto no especificado.';
$_lang['access_context_err_remove'] = 'Un error occurrió mientras se trataba de remover el ACL de Contexto.';
$_lang['access_context_remove'] = 'Remover Acceso a Contexto';
$_lang['access_context_update'] = 'Actualizar Acceso a Contexto';
$_lang['access_err_ae'] = 'ACL ya existe!';
$_lang['access_err_create_md'] = 'No se puede crear ACL; faltan datos!';
$_lang['access_err_nf'] = 'No se pudo encontrar el ACL especificado!';
$_lang['access_err_remove'] = '¡Error removiendo ACL!';
$_lang['access_err_save'] = '¡Error guardando ACL!';
$_lang['access_grid_empty'] = 'No ACLs para mostrar';
$_lang['access_grid_paginate'] = 'Mostrando ACLs {0} - {1} de {2}';
$_lang['access_permissions'] = 'Permisos de Acceso';
$_lang['access_permissions_add_document_group'] = 'Crear un nuevo grupo de documentos';
$_lang['access_permissions_add_user_group'] = 'Crear un nuevo grupo de usuarios';
$_lang['access_permissions_documents_in_group'] = '<strong>Documentos en el grupo:</strong> ';
$_lang['access_permissions_documents_tab'] = 'Aquí puedes ver que grupos de documentos han sido configurados.  También puedes crear grupos nuevos, renombrar grupos, borrar grupos y ver que documentos existen en los diferentes grupos (sostén el mouse sobre el ID del documento para ver su nombre).  Para añadir un documento a un grupo o borrar un remover un documento de un grupo, edita el documento directamente.';
$_lang['access_permissions_document_groups'] = 'Grupos de documentos';
$_lang['access_permissions_introtext'] = 'Aquí puedes administrar los grupos de usuarios y los grupos de documentos usados para los permisos de acceso.  Para añadir grupos de usuarios o usuarios a grupos de usuarios, usa el árbol de la izquierda y has clic con el botón derecho.  Para enlazar Grupos de Usuarios a Grupos de Documentos, simplemente arrastra grupos de usuarios desde el árbol de la izquierda dentro de los grupos de documentos en el árbol derecho.';
$_lang['access_permissions_links'] = 'Enlaces de grupos de Usuarios/Documentos';
$_lang['access_permissions_links_tab'] = 'Esto es donde especificamos que grupos de usuarios tienen acceso (p.ej. se pueden editar o crear hijos) para los grupos de documentos.  Para enlazar un grupo de documentos a un grupo de usuarios, selecciona el grupo del menú desplegable y has clin en \'Enlace\'.  Para remover el enlace para un cierto grupo, has clic en \'Remover ->\'.  Esto removerá inmediatamente el enlace.';
$_lang['access_permissions_no_documents_in_group'] = 'Ninguno.';
$_lang['access_permissions_no_users_in_group'] = 'Ninguno.';
$_lang['access_permissions_off'] = '<span class="warning">Permisos de Acceso no están activados.</span> Esto significa que cualquier cambio hecho aquí no tendrá ningún efecto hasta que los Permisos de Acceso estén activados.';
$_lang['access_permissions_users_in_group'] = '<strong>Usuarios en el grupo:</strong> ';
$_lang['access_permissions_users_tab'] = 'Aquí puedes ver que grupos de usuarios han sido configurados.  También puedes crear grupos nuevos, renombrar grupos, borrar grupos y ver que usuarios son miembros de diferentes grupos.  Para añadir un usuario nuevo a un grupo o para remover un usuario de un grupo, edita al usuario directamente.';
$_lang['access_permissions_user_group'] = 'Grupo de Usuario:';
$_lang['access_permissions_user_groups'] = 'Grupos de Usuario';
$_lang['access_permissions_user_group_access'] = 'Grupos de documentos a los que este grupo de usuarios tiene acceso:';
$_lang['access_permissions_user_message'] = 'Aquí puedes seleccionar a que grupos de usuarios pertenece este usuario:';
$_lang['access_permission_denied'] = 'No tienes los permisos correctos para este documento.';
$_lang['access_permission_parent_denied'] = 'No tienes permiso para crear o mover un documento aquí.  Favor de elegir otro lugar.';
$_lang['access_policy_err_nf'] = 'Política de Acceso no encontrada.';
$_lang['access_policy_err_ns'] = 'Política de Acceso no especificada.';
$_lang['access_policy_grid_empty'] = 'No hay políticas que mostrar';
$_lang['access_policy_grid_paginate'] = 'Mostrando políticas {0} - {1} de {2}';
$_lang['access_resourcegroup_management_msg'] = 'Administrar acceso de miembros del Grupo de Usuarios a Grupos de Recursos y opcionalmente aplicar las políticas de acceso.';
$_lang['access_rgroup_err_ae'] = 'Un ACL para ese Grupo de Recursos ya existe!';
$_lang['access_rgroup_err_nf'] = 'ACL de Grupo de Recursos no encontrado.';
$_lang['access_rgroup_err_ns'] = 'ACL de Grupo de Recursos no especificado.';
$_lang['access_rgroup_err_remove'] = 'Un error ocurrió mientras se trataba de remover el ACL de Grupo de Recursos.';
$_lang['access_rgroup_remove'] = 'Remover Acceso al Grupo de Recursos';
$_lang['access_rgroup_update'] = 'Update Resource Group Access';
$_lang['access_to_contexts'] = 'Acceso a Contextos';
$_lang['access_to_resource_groups'] = 'Acceso a Grupos de Recursos';
$_lang['access_type_err_ns'] = 'Tipo de Objetivo o ID no especificada!';
$_lang['acl_add'] = 'Añadir Control de Acceso';
$_lang['authority'] = 'Autoridad';
$_lang['authority_err_ns'] = 'Por favor especifica un Rol Mínimo.';
$_lang['category'] = 'Categoría';
$_lang['category_add'] = 'Añadir Categoría';
$_lang['filter_by_context'] = 'Filtrar por Contexto...';
$_lang['filter_by_policy'] = 'Filtrar por Política...';
$_lang['filter_by_resource_group'] = 'Filtrar por Grupo de Recursos...';
$_lang['filter_by_category'] = 'Filtrar por Categoría...';
$_lang['no_policy_option'] = ' (no hay política) ';
$_lang['resource_group'] = 'Grupo de Recursos';
$_lang['resource_group_add'] = 'Añadir Grupo de Recursos';

$_lang['resource_group_access_remove_confirm'] = '¡Estás segura de que quieres remover este recurso del grupo de recursos?';
$_lang['resource_group_create'] = 'Crear Grupo de Recursos';
$_lang['resource_group_err_ae'] = 'Un grupo de recursos con ese nombre ya existe.';
$_lang['resource_group_err_create'] = 'Un error ocurrió mietras se trataba de crear el grupo de recursos.';
$_lang['resource_group_err_nf'] = 'Grupo de recursos no encontrado.';
$_lang['resource_group_err_ns'] = 'Grupo de recursos no especificado.';
$_lang['resource_group_err_remove'] = 'Un error ocurrió mientras se trataba de remover el grupo de recursos.';
$_lang['resource_group_remove'] = 'Remover Grupo de Recursos';
$_lang['resource_group_remove_confirm'] = '¡Estás seguro de que quieres remover este grupo de recursos?';
$_lang['resource_group_resource_err_ae'] = 'El recurso ya es parte de ese  grupo de recursos.';
$_lang['resource_group_resource_err_create'] = 'Un error ocurrió mietras se trataba de poner el recurso en el grupo de recursos.';
$_lang['resource_group_resource_err_nf'] = 'El recurso no es parte de ese grupo de recursos.';
$_lang['resource_group_resource_err_remove'] = 'Un error ocurrió mientras se trataba de remover el recurso del grupo de recursos.';
$_lang['resource_group_untitled'] = 'Grupo de Recursos sin Título';
$_lang['roles_msg'] = 'Un rol es, por definición, una posición o estatus que alguien tiene dentro de cierta situación.  Pueden ser usados para agrupar Usuarios en una posición o estatus dentro de un Grupo de Usuarios.  Los roles en MODX también tienen lo que se llama "Autoridad". Esto es un valor numérico que puede ser cualquier número entero válido.  Los niveles de Autoridad son "heredados hacia abajo", en el mismo sentido en el que un Rol con Autoridad 1 heredará cualquier y todas las Políticas de Grupo asignadas a él mismo, y a cualquier Rol con un nivel de Autoridad mayor a 1.';
$_lang['user_group_category_access'] = 'Acceso de Categorías por Elemento';
$_lang['user_group_category_access_msg'] = 'Aquí puedes configurar cuales Elementos este Grupo de Usuarios puede acceder por las Categorías en las que están los Elementos.';
$_lang['user_group_category_err_ae'] = 'Grupo de Usuarios ya tiene acceso a esa Categoría.';
$_lang['user_group_category_remove_confirm'] = '¡Estás seguro de que quieres remover esta Categoría del Grupo de Usuarios?';
$_lang['user_group_context_access'] = 'Acceso a Contextos';
$_lang['user_group_context_access_msg'] = 'Aquí puedes determinar a que Contextos puede accesar este Grupo de Usuarios.';
$_lang['user_group_context_err_ae'] = 'El Grupo de Usuarios ya tiene acceso a ese contexto.';
$_lang['user_group_context_remove_confirm'] = '¡Estás segura de que quieres remover este Contexto de este Grupo de Usuarios?';
$_lang['user_group_resourcegroup_access'] = 'Acceso a Grupos de Recursos';
$_lang['user_group_resourcegroup_access_msg'] = 'Aquí puedes determinar a que Grupos de Recursos tiene acceso este Grupo de Usuarios.';
$_lang['user_group_resourcegroup_err_ae'] = 'El Grupo de Usuarios ya tiene acceso a ese Grupo de Recursos.';
$_lang['user_group_resourcegroup_remove_confirm'] = '¡Estás seguro de que quieres remover este Grupo de Recursos de este Grupo de Usuarios?';
$_lang['user_group_user_access_msg'] = 'Selecciona que usuarios quieres en este Grupo de Usuarios.';