<?php
/**
 * Chunk English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */

// Entry out of alpha order because it must come before the entry it's used in below
$_lang['example_tag_chunk_name'] = 'NameOfChunk';

$_lang['chunk'] = 'Чанк';
$_lang['chunk_category_desc'] = 'Use to group Chunks within the Elements tree.';
$_lang['chunk_code'] = 'Chunk Code (HTML)';
$_lang['chunk_description_desc'] = 'Usage information for this Chunk shown in search results and as a tooltip in the Elements tree.';
$_lang['chunk_delete_confirm'] = 'Ви впевнені, що хочете видалити цей чанк?';
$_lang['chunk_duplicate_confirm'] = 'Ви впевнені, що хочете дублювати цей чанк?';
$_lang['chunk_err_create'] = 'Сталася помилка при спробі створення чанку.';
$_lang['chunk_err_duplicate'] = 'Помилка при дублюванні чанку.';
$_lang['chunk_err_ae'] = 'Вже існує чанк з іменем "[[+name]]".';
$_lang['chunk_err_invalid_name'] = 'Некоректне ім\'я чанку.';
$_lang['chunk_err_locked'] = 'Чанк заблоковано.';
$_lang['chunk_err_remove'] = 'Сталася помилка при спробі видалення чанку.';
$_lang['chunk_err_save'] = 'Сталася помилка при спробі збереження чанку.';
$_lang['chunk_err_nf'] = 'Чанк не знайдено!';
$_lang['chunk_err_nfs'] = 'Не знайдено чанк з id: [[+id]]';
$_lang['chunk_err_ns'] = 'Чанк не вказаний.';
$_lang['chunk_err_ns_name'] = 'Будь ласка, вкажіть ім\'я.';
$_lang['chunk_lock'] = 'Заблокувати чанк для редагування';
$_lang['chunk_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Chunk.';
$_lang['chunk_name_desc'] = 'Place the content generated by this Chunk in a Resource, Template, or other Chunk using the following MODX tag: [[+tag]]';
$_lang['chunk_new'] = 'Створити чанк';
$_lang['chunk_properties'] = 'Параметри за замовчуванням';
$_lang['chunk_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Chunk</em> as well as its content. The content must be HTML, either placed in the <em>Chunk Code</em> field below or in a static external file, and may include MODX tags. Note, however, that PHP code will not run in this element.';
$_lang['chunk_tag_copied'] = 'Chunk tag copied!';
$_lang['chunk_title'] = 'Створити/редагувати чанк';
$_lang['chunk_untitled'] = 'Безіменний чанк';
$_lang['chunks'] = 'Чанки';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['chunk_desc_category'] = $_lang['chunk_category_desc'];
$_lang['chunk_desc_description'] = $_lang['chunk_description_desc'];
$_lang['chunk_desc_name'] = $_lang['chunk_name_desc'];
$_lang['chunk_lock_msg'] = $_lang['chunk_lock_desc'];

// --tabs
$_lang['chunk_msg'] = $_lang['chunk_tab_general_desc'];
