<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Сніпет';
$_lang['snippets_available'] = 'Сніпети, доступні Вам для включення до Вашої сторінки';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Ви впевнені, що хочете видалити цей сніпет?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Ви впевнені, що бажаєте дублювати сніпет?';
$_lang['snippet_duplicate_error'] = 'Сталася помила під час дублювання сніпета.';
$_lang['snippet_err_create'] = 'Сталася помилка під час створення сніпета.';
$_lang['snippet_err_delete'] = 'Сталася помилка при спробі видалення сніпета.';
$_lang['snippet_err_duplicate'] = 'Сталася помилка при спробі дублювання сніпета.';
$_lang['snippet_err_ae'] = 'Сніпет з ім\'ям "[[+name]]" вже існує.';
$_lang['snippet_err_invalid_name'] = 'Ім\'я сніпета некоректне.';
$_lang['snippet_err_locked'] = 'Цей сніпет заблокований для редагування.';
$_lang['snippet_err_nf'] = 'Сніпет не знайдено!';
$_lang['snippet_err_ns'] = 'Сніпет не вказаний.';
$_lang['snippet_err_ns_name'] = 'Будь ласка, вкажіть ім\'я сніпета.';
$_lang['snippet_err_remove'] = 'Сталася помилка при спробі видалення сніпета.';
$_lang['snippet_err_save'] = 'Сталася помилка під час збереження сніпета.';
$_lang['snippet_execonsave'] = 'Запустити сніпет після збереження.';
$_lang['snippet_lock'] = 'Заблокувати сніпет для редагування';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Тут Ви можете обрати, який сніпет Ви хочете редагувати.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Створити сніпет';
$_lang['snippet_properties'] = 'Параметри за замовчуванням';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'Сніпети';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
