<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Frammento';
$_lang['snippets_available'] = 'Snippets disponibili per essere inclusi nella tua pagina';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Sei sicuro di voler eliminare questo snippet?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Sei sicuro di voler duplicare questo snippet?';
$_lang['snippet_duplicate_error'] = 'Si è verificato un errore durante la duplicazione dello snippet.';
$_lang['snippet_err_create'] = 'Si è verificato un errore durante la creazione dello snippet.';
$_lang['snippet_err_delete'] = 'Si è verificato un errore durante il tentativo di eliminare lo snippet.';
$_lang['snippet_err_duplicate'] = 'Si è verificato un errore durante il tentativo di duplicare lo snippet.';
$_lang['snippet_err_ae'] = 'Esiste già uno snippet con il nome "[[+name]]".';
$_lang['snippet_err_invalid_name'] = 'Il nome dello Snippet non è valido.';
$_lang['snippet_err_locked'] = 'Questo snippet è bloccato per la modifica e non può essere editato.';
$_lang['snippet_err_nf'] = 'Snippet non trovato!';
$_lang['snippet_err_ns'] = 'Snippet non specificato.';
$_lang['snippet_err_ns_name'] = 'Specificare un nome per lo snippet.';
$_lang['snippet_err_remove'] = 'Si è verificato un errore provando a eliminare il frammento.';
$_lang['snippet_err_save'] = 'Si è verificato un errore durante il salvataggio dello snippet.';
$_lang['snippet_execonsave'] = 'Esegui lo snippet dopo il salvataggio.';
$_lang['snippet_lock'] = 'Blocca Modifiche Snippet';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Qui puoi scegliere quale snippet vorresti modificare.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Crea Frammento';
$_lang['snippet_properties'] = 'Proprietà di default';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'Frammenti';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
