<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Parça';
$_lang['snippets_available'] = 'Pasajlar sayfanıza dahil etmeniz için kullanılabilir halde';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Bu pasajı silmek istediğinizden emin misiniz?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Bu pasajı çoğaltmak istediğinize emin misiniz?';
$_lang['snippet_duplicate_error'] = 'Pasaj çoğaltılırken bir hata meydana geldi.';
$_lang['snippet_err_create'] = 'Pasaj yaratılırken bir hata meydana geldi.';
$_lang['snippet_err_delete'] = 'Pasaj silinmeye çalışılırken bir hata meydana geldi.';
$_lang['snippet_err_duplicate'] = 'Pasaj çoğaltılmaya çalışılırken bir hata meydana geldi.';
$_lang['snippet_err_ae'] = '"[[+name]]" isminde bir pasaj zaten mevcut.';
$_lang['snippet_err_invalid_name'] = 'Pasaj ismi geçersiz.';
$_lang['snippet_err_locked'] = 'Bu pasaj düzenlemeye karşı kilitli.';
$_lang['snippet_err_nf'] = 'Pasaj bulunamadı!';
$_lang['snippet_err_ns'] = 'Pasaj Belirtilmedi.';
$_lang['snippet_err_ns_name'] = 'Lütfen pasaj için bir isim belirtin.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'Pasaj kaydedilirken bir hata meydana geldi.';
$_lang['snippet_execonsave'] = 'Pasajı kaydettikten sonra çalıştır.';
$_lang['snippet_lock'] = 'Pasajı düzenlemeye kilitle';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Burada düzenlemek istediğiniz pasajı seçebilirsiniz.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'Varsayılan Özellikler';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'Parçacıklar';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
