<?php
/**
 * Chunk English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */

// Entry out of alpha order because it must come before the entry it's used in below
$_lang['example_tag_chunk_name'] = 'NameOfChunk';

$_lang['chunk'] = 'HTML -palanen';
$_lang['chunk_category_desc'] = 'Use to group Chunks within the Elements tree.';
$_lang['chunk_code'] = 'Chunk Code (HTML)';
$_lang['chunk_description_desc'] = 'Usage information for this Chunk shown in search results and as a tooltip in the Elements tree.';
$_lang['chunk_delete_confirm'] = 'Oletko varma että haluat poistaa palasen?';
$_lang['chunk_duplicate_confirm'] = 'Oletko varma että haluat kopioida palasen?';
$_lang['chunk_err_create'] = 'An error occurred while trying to create the chunk.';
$_lang['chunk_err_duplicate'] = 'Virhe kopioidessa palasta.';
$_lang['chunk_err_ae'] = 'Palanen on jo olemassa samalla nimellä "[[+name]]".';
$_lang['chunk_err_invalid_name'] = 'Epäkelvollinen palasen nimi.';
$_lang['chunk_err_locked'] = 'Palanen on lukittu.';
$_lang['chunk_err_remove'] = 'An error occurred while trying to delete the chunk.';
$_lang['chunk_err_save'] = 'Virhe tallentaessa palasta.';
$_lang['chunk_err_nf'] = 'Palasta ei löydy!';
$_lang['chunk_err_nfs'] = 'Palasta ei löydy id:llä: [[+id]]';
$_lang['chunk_err_ns'] = 'Palasta ei ole määritetty.';
$_lang['chunk_err_ns_name'] = 'Määritä nimi.';
$_lang['chunk_lock'] = 'Merkitse palanen lukituksi muokkaukselta';
$_lang['chunk_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Chunk.';
$_lang['chunk_name_desc'] = 'Place the content generated by this Chunk in a Resource, Template, or other Chunk using the following MODX tag: [[+tag]]';
$_lang['chunk_new'] = 'Create Chunk';
$_lang['chunk_properties'] = 'Oletusominaisuudet';
$_lang['chunk_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Chunk</em> as well as its content. The content must be HTML, either placed in the <em>Chunk Code</em> field below or in a static external file, and may include MODX tags. Note, however, that PHP code will not run in this element.';
$_lang['chunk_tag_copied'] = 'Chunk tag copied!';
$_lang['chunks'] = 'Palaset';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['chunk_desc_category'] = $_lang['chunk_category_desc'];
$_lang['chunk_desc_description'] = $_lang['chunk_description_desc'];
$_lang['chunk_desc_name'] = $_lang['chunk_name_desc'];
$_lang['chunk_lock_msg'] = $_lang['chunk_lock_desc'];

// --tabs
$_lang['chunk_msg'] = $_lang['chunk_tab_general_desc'];
