<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Snippet';
$_lang['snippets_available'] = 'Snippets disponíveis para você incluir na sua página ';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Tem certeza de que deseja excluir este snippet?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Tem certeza que quer duplicar esse trecho?';
$_lang['snippet_duplicate_error'] = 'Ocorreu um erro durante a duplicação do snippet.';
$_lang['snippet_err_create'] = 'Ocorreu um erro ao criar o snippet.';
$_lang['snippet_err_delete'] = 'Ocorreu um erro ao tentar excluir o snippet.';
$_lang['snippet_err_duplicate'] = 'Ocorreu um erro durante a tentativa de duplicar o snippet.';
$_lang['snippet_err_ae'] = 'Um snippet já existe com o nome de "[[+name]]".';
$_lang['snippet_err_invalid_name'] = 'O nome do Snippet é inválido.';
$_lang['snippet_err_locked'] = 'Este trecho está bloqueado para edição.';
$_lang['snippet_err_nf'] = 'Snippet não encontrado!';
$_lang['snippet_err_ns'] = 'Snippet não especificado.';
$_lang['snippet_err_ns_name'] = 'Por favor, indique um nome para o trecho de código.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'Ocorreu um erro ao salvar o trecho.';
$_lang['snippet_execonsave'] = 'Executar snippet depois de salvar.';
$_lang['snippet_lock'] = 'Travar snippet para edição';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Aqui você pode escolher qual o trecho que você deseja editar.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'Propriedades Padrão';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippets'] = 'Snippets';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
