<?php
/**
 * Snippet English lexicon topic
 *
 * @language en
 * @package modx
 * @subpackage lexicon
 */
$_lang['example_tag_snippet_name'] = 'NameOfSnippet';
$_lang['snippet'] = 'Snippet';
$_lang['snippets_available'] = 'Snippets beschikbaar voor jou om te includen in jouw pagina';
$_lang['snippet_category_desc'] = 'Use to group Snippets within the Elements tree.';
$_lang['snippet_code'] = 'Snippet Code (PHP)';
$_lang['snippet_delete_confirm'] = 'Weet je zeker dat je deze snippet wilt verwijderen?';
$_lang['snippet_description_desc'] = 'Usage information for this Snippet shown in search results and as a tooltip in the Elements tree.';
$_lang['snippet_duplicate_confirm'] = 'Weet je zeker dat je deze snippet wilt dupliceren?';
$_lang['snippet_duplicate_error'] = 'Er is een fout opgetreden tijdens het dupliceren van de snippet.';
$_lang['snippet_err_create'] = 'Er is een fout opgetreden tijdens het maken van de snippet.';
$_lang['snippet_err_delete'] = 'Er is een fout opgetreden tijdens het proberen te verwijderen van de snippet.';
$_lang['snippet_err_duplicate'] = 'Er is een fout opgetreden tijdens het proberen te dupliceren van de snippet.';
$_lang['snippet_err_ae'] = 'Een snippet met deze naam "[[+name]]" bestaat reeds.';
$_lang['snippet_err_invalid_name'] = 'Snippetnaam is ongeldig.';
$_lang['snippet_err_locked'] = 'Deze snippet is vergrendeld voor bewerken.';
$_lang['snippet_err_nf'] = 'Snippet niet gevonden!';
$_lang['snippet_err_ns'] = 'Snippet niet gespecificeerd.';
$_lang['snippet_err_ns_name'] = 'Vul een naam in voor de snippet.';
$_lang['snippet_err_remove'] = 'An error occurred while trying to delete the snippet.';
$_lang['snippet_err_save'] = 'Er is een fout opgetreden tijdens het opslaan van de snippet.';
$_lang['snippet_execonsave'] = 'Snippet uitvoeren na opslaan.';
$_lang['snippet_lock'] = 'Vergrendel snippet voor bewerken';
$_lang['snippet_lock_desc'] = 'Only users with “edit_locked” permissions can edit this Snippet.';
$_lang['snippet_management_msg'] = 'Hier kun je kiezen welke snippet je wilt bewerken.';
$_lang['snippet_name_desc'] = 'Place the content generated by this Snippet in a Resource, Template, or Chunk using the following MODX tag: [[+tag]]';
$_lang['snippet_new'] = 'Create Snippet';
$_lang['snippet_properties'] = 'Standaard eigenschappen';
$_lang['snippet_tab_general_desc'] = 'Here you can enter the basic attributes for this <em>Snippet</em> as well as its content. The content must be PHP, either placed in the <em>Snippet Code</em> field below or in a static external file. To receive output from your Snippet at the point where it is called (within a Template or Chunk), a value must be returned from within the code.';
$_lang['snippet_tag_copied'] = 'Snippet tag copied!';
$_lang['snippet_title'] = 'Create/Edit Snippet';
$_lang['snippet_untitled'] = 'Naamloze snippet';
$_lang['snippets'] = 'Snippets';

// Temporarily match old keys to new ones to ensure compatibility
// --fields
$_lang['snippet_desc_category'] = $_lang['snippet_category_desc'];
$_lang['snippet_desc_description'] = $_lang['snippet_description_desc'];
$_lang['snippet_desc_name'] = $_lang['snippet_name_desc'];
$_lang['snippet_lock_msg'] = $_lang['snippet_lock_desc'];

// --tabs
$_lang['snippet_msg'] = $_lang['snippet_tab_general_desc'];
