name: CI

on:
  push:
      branches-ignore:
          - 'l10n_**'
      paths-ignore:
          - "_build/templates/**"
  pull_request:
      branches-ignore:
          - 'l10n_**'
      paths-ignore:
          - "_build/templates/**"

          # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  mysql-check:
    name: MySQL Check
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: "mysql:5.6"

        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=revo_test
        ports:
          - 3306:3306

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo, pdo_mysql, zip, mysqli, gd

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup MODX
        run: cd _build/test && ./generateConfigs.sh auto

      - name: Run PHPUnit
        run: XDEBUG_MODE=coverage core/vendor/bin/phpunit --enforce-time-limit -c ./_build/test/phpunit.xml --coverage-clover coverage.xml

      - name: Upload CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
